// frontend/src/pages/Users.tsx
import { Card, Table, Tag, Space, Button, Modal, Form, Input, Select, message, Popconfirm } from 'antd'
import { PlusOutlined, EditOutlined } from '@ant-design/icons'
import { useState, useEffect } from 'react'
import { get, post, put, del } from '../api'
import type { User, PaginatedResponse } from '../types'
import type { User as AuthUser } from '../store/auth'

const { Option } = Select

const roleTexts: Record<string, string> = {
  admin: '系统管理员',
  manager: '运营经理',
  cleaner: '保洁员',
  maintenance: '维修工',
}

const roleColors: Record<string, string> = {
  admin: 'red',
  manager: 'blue',
  cleaner: 'green',
  maintenance: 'orange',
}

const Users: React.FC = () => {
  const [users, setUsers] = useState<AuthUser[]>([])
  const [total, setTotal] = useState(0)
  const [loading, setLoading] = useState(false)
  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(20)
  const [roleFilter, setRoleFilter] = useState<string | undefined>()
  const [modalVisible, setModalVisible] = useState(false)
  const [selectedUser, setSelectedUser] = useState<AuthUser | null>(null)
  const [form] = Form.useForm()

  const fetchUsers = async () => {
    setLoading(true)
    try {
      const data = await get<PaginatedResponse<AuthUser>>('/users', {
        params: { page, page_size: pageSize },
      })
      setUsers(data.data)
      setTotal(data.total)
    } catch (e) {
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchUsers()
  }, [page, pageSize, roleFilter])

  const handleCreate = () => {
    setSelectedUser(null)
    form.resetFields()
    setModalVisible(true)
  }

  const handleEdit = (record: AuthUser) => {
    setSelectedUser(record)
    form.setFieldsValue(record)
    setModalVisible(true)
  }

  const handleSubmit = async (values: any) => {
    try {
      if (selectedUser) {
        await put(`/users/${selectedUser.id}`, values)
        message.success('更新成功')
      } else {
        await post('/users', values)
        message.success('创建成功')
      }
      setModalVisible(false)
      fetchUsers()
    } catch (e) {}
  }

  const handleDelete = async (record: AuthUser) => {
    try {
      await del(`/users/${record.id}`)
      message.success('已禁用')
      fetchUsers()
    } catch (e) {}
  }

  const columns = [
    { title: '用户名', dataIndex: 'username', key: 'username', width: 120 },
    { title: '姓名', dataIndex: 'full_name', key: 'full_name', width: 120 },
    { title: '角色', dataIndex: 'role', key: 'role', width: 100,
      render: (r: string) => <Tag color={roleColors[r]}>{roleTexts[r]}</Tag> },
    { title: '邮箱', dataIndex: 'email', key: 'email', width: 180 },
    { title: '电话', dataIndex: 'phone', key: 'phone', width: 130 },
    { title: '状态', dataIndex: 'is_active', key: 'is_active', width: 80,
      render: (v: boolean) => v ? <Tag color="green">正常</Tag> : <Tag color="red">禁用</Tag> },
    {
      title: '操作',
      key: 'actions',
      width: 180,
      fixed: 'right' as const,
      render: (_: any, record: AuthUser) => (
        <Space size="small">
          <Button type="link" size="small" icon={<EditOutlined />} onClick={() => handleEdit(record)}>编辑</Button>
          {record.role !== 'admin' && (
            <Popconfirm title="确定禁用该用户吗？" onConfirm={() => handleDelete(record)}>
              <Button type="link" size="small" danger>禁用</Button>
            </Popconfirm>
          )}
        </Space>
      ),
    },
  ]

  return (
    <div>
      <Card>
        <Space style={{ marginBottom: 16 }}>
          <Select
            placeholder="角色筛选"
            style={{ width: 150 }}
            allowClear
            value={roleFilter}
            onChange={setRoleFilter}
          >
            {Object.entries(roleTexts).map(([key, text]) => (
              <Option key={key} value={key}>{text}</Option>
            ))}
          </Select>
          <Button type="primary" icon={<PlusOutlined />} onClick={handleCreate}>
            添加用户
          </Button>
        </Space>

        <Table
          columns={columns}
          dataSource={users}
          rowKey="id"
          loading={loading}
          scroll={{ x: 900 }}
          pagination={{
            current: page,
            pageSize,
            total,
            onChange: (p, ps) => { setPage(p); setPageSize(ps) },
          }}
        />
      </Card>

      <Modal
        title={selectedUser ? '编辑用户' : '添加用户'}
        open={modalVisible}
        onCancel={() => setModalVisible(false)}
        footer={null}
        width={500}
      >
        <Form form={form} layout="vertical" onFinish={handleSubmit}>
          {!selectedUser && (
            <>
              <Form.Item name="username" label="用户名" rules={[{ required: true }]}>
                <Input placeholder="请输入用户名" />
              </Form.Item>
              <Form.Item name="password" label="初始密码" rules={[{ required: true, min: 6 }]}>
                <Input.Password placeholder="请输入初始密码" />
              </Form.Item>
            </>
          )}
          <Form.Item name="full_name" label="姓名" rules={[{ required: true }]}>
            <Input placeholder="请输入真实姓名" />
          </Form.Item>
          <Form.Item name="role" label="角色" rules={[{ required: true }]}>
            <Select>
              {Object.entries(roleTexts).map(([k, v]) => (
                <Option key={k} value={k}>{v}</Option>
              ))}
            </Select>
          </Form.Item>
          <Form.Item name="email" label="邮箱">
            <Input placeholder="请输入邮箱" />
          </Form.Item>
          <Form.Item name="phone" label="电话">
            <Input placeholder="请输入电话" />
          </Form.Item>
          {selectedUser && (
            <Form.Item name="is_active" label="状态" initialValue={true}>
              <Select>
                <Option value={true}>正常</Option>
                <Option value={false}>禁用</Option>
              </Select>
            </Form.Item>
          )}
          {selectedUser && (
            <Form.Item name="password" label="重置密码(留空则不修改)">
              <Input.Password placeholder="输入新密码" />
            </Form.Item>
          )}
          <Form.Item>
            <Space>
              <Button type="primary" htmlType="submit">保存</Button>
              <Button onClick={() => setModalVisible(false)}>取消</Button>
            </Space>
          </Form.Item>
        </Form>
      </Modal>
    </div>
  )
}

export default Users

// frontend/src/views/admin/Users.vue
<template>
  <div class="admin-users">
    <el-card>
      <template #header>
        <div class="card-header">
          <span>用户管理</span>
          <el-button type="primary" icon="Plus" @click="openDialog()">新增用户</el-button>
        </div>
      </template>

      <el-table :data="users" v-loading="loading" stripe border>
        <el-table-column prop="username" label="用户名" width="150" />
        <el-table-column label="姓名" width="120">
          <template #default="{ row }">{{ row.first_name }}{{ row.last_name }}</template>
        </el-table-column>
        <el-table-column prop="email" label="邮箱" width="180" />
        <el-table-column label="角色" width="120" align="center">
          <template #default="{ row }">
            <el-tag :type="roleTagType(row.role)">{{ row.role_display }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="phone" label="手机号" width="130" />
        <el-table-column label="状态" width="80" align="center">
          <template #default="{ row }">
            <el-tag :type="row.is_active ? 'success' : 'danger'" size="small">
              {{ row.is_active ? '正常' : '禁用' }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="created_at" label="创建时间" width="180" />
        <el-table-column label="操作" width="200" fixed="right">
          <template #default="{ row }">
            <el-button type="primary" link size="small" @click="openDialog(row)">编辑</el-button>
            <el-button type="warning" link size="small" @click="resetPassword(row)">重置密码</el-button>
            <el-button :type="row.is_active ? 'danger' : 'success'" link size="small" @click="toggleStatus(row)">
              {{ row.is_active ? '禁用' : '启用' }}
            </el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <el-dialog v-model="dialogVisible" :title="form.id ? '编辑用户' : '新增用户'" width="500px">
      <el-form :model="form" :rules="rules" ref="formRef" label-width="100px">
        <el-form-item label="用户名" prop="username">
          <el-input v-model="form.username" :disabled="!!form.id" />
        </el-form-item>
        <el-form-item label="姓名" prop="first_name">
          <el-input v-model="form.first_name" placeholder="名" />
        </el-form-item>
        <el-form-item label="角色" prop="role">
          <el-select v-model="form.role" style="width: 100%;">
            <el-option label="系统管理员" value="admin" />
            <el-option label="店长" value="manager" />
            <el-option label="普通员工" value="staff" />
          </el-select>
        </el-form-item>
        <el-form-item label="邮箱">
          <el-input v-model="form.email" />
        </el-form-item>
        <el-form-item label="手机号">
          <el-input v-model="form.phone" />
        </el-form-item>
        <el-form-item v-if="!form.id" label="初始密码" prop="password">
          <el-input v-model="form.password" type="password" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialogVisible = false">取消</el-button>
        <el-button type="primary" @click="saveUser">确定</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api } from '@/utils/request'

const loading = ref(false)
const users = ref([])
const dialogVisible = ref(false)
const formRef = ref(null)

const form = reactive({
  id: null, username: '', first_name: '', role: 'staff', email: '', phone: '', password: ''
})

const rules = {
  username: [{ required: true, message: '请输入用户名', trigger: 'blur' }],
  first_name: [{ required: true, message: '请输入姓名', trigger: 'blur' }],
  role: [{ required: true, message: '请选择角色', trigger: 'change' }],
  password: [{ required: true, message: '请输入初始密码', trigger: 'blur' }],
}

const roleTagType = (role) => {
  const types = { admin: 'danger', manager: 'warning', staff: 'primary' }
  return types[role] || 'info'
}

const loadUsers = async () => {
  loading.value = true
  try {
    const { data } = await api.get('/auth/users/', { params: { page_size: 100 } })
    users.value = data.results
  } finally {
    loading.value = false
  }
}

const openDialog = (row = null) => {
  if (row) {
    Object.assign(form, { ...row, password: '' })
  } else {
    Object.assign(form, { id: null, username: '', first_name: '', role: 'staff', email: '', phone: '', password: '' })
  }
  dialogVisible.value = true
}

const saveUser = async () => {
  await formRef.value.validate()
  try {
    if (form.id) {
      await api.patch(`/auth/users/${form.id}/`, form)
      ElMessage.success('更新成功')
    } else {
      await api.post('/auth/users/', form)
      ElMessage.success('创建成功')
    }
    dialogVisible.value = false
    loadUsers()
  } catch (e) {
    ElMessage.error('保存失败')
  }
}

const resetPassword = async (row) => {
  try {
    const { value: password } = await ElMessageBox.prompt('请输入新密码', '重置密码', {
      inputPattern: /.{6,}/,
      inputErrorMessage: '密码至少6位'
    })
    await api.post(`/auth/users/${row.id}/set_password/`, { password })
    ElMessage.success('密码重置成功')
  } catch (e) {
    if (e !== 'cancel') ElMessage.error('操作失败')
  }
}

const toggleStatus = async (row) => {
  try {
    const newStatus = !row.is_active
    await api.patch(`/auth/users/${row.id}/`, { is_active: newStatus })
    ElMessage.success('操作成功')
    loadUsers()
  } catch (e) {
    ElMessage.error('操作失败')
  }
}

onMounted(loadUsers)
</script>

<style lang="scss" scoped>
.admin-users {
  .card-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    width: 100%;
  }
}
</style>
