// src/components/charts/StatCard.vue
<script setup lang="ts">
import { computed } from 'vue';
import { TrendingUp, TrendingDown } from 'lucide-vue-next';

const props = defineProps<{
  title: string;
  value: number | string;
  unit?: string;
  isPercentage?: boolean;
  trend?: number;
  icon?: any;
  color?: string;
}>();

const displayValue = computed(() => {
  if (typeof props.value === 'string') return props.value;
  if (props.isPercentage) return `${(props.value * 100).toFixed(1)}%`;
  return props.value.toLocaleString();
});

const trendColor = computed(() => {
  if (!props.trend) return 'text-slate-500';
  return props.trend > 0 ? 'text-green-600' : 'text-red-600';
});
</script>

<template>
  <div class="bg-white rounded-xl p-5 shadow-sm border border-slate-100 hover:shadow-md transition-shadow duration-300">
    <div class="flex items-start justify-between">
      <div>
        <p class="text-sm text-slate-500 font-medium">{{ title }}</p>
        <p class="text-3xl font-bold mt-2" :class="color || 'text-slate-800'">
          {{ displayValue }}
          <span v-if="unit" class="text-lg font-normal text-slate-500">{{ unit }}</span>
        </p>
        <div v-if="trend !== undefined" class="flex items-center gap-1 mt-2" :class="trendColor">
          <component :is="trend >= 0 ? TrendingUp : TrendingDown" class="w-4 h-4" />
          <span class="text-sm font-medium">{{ Math.abs(trend).toFixed(1) }}%</span>
          <span class="text-slate-500 text-xs">较上周</span>
        </div>
      </div>
      <div 
        v-if="icon" 
        class="w-12 h-12 rounded-xl flex items-center justify-center"
        :class="[color ? color.replace('text-', 'bg-').replace('800', '100') : 'bg-blue-100', color ? color.replace('text-', 'text-').replace('800', '600') : 'text-blue-600']"
      >
        <component :is="icon" class="w-6 h-6" />
      </div>
    </div>
  </div>
</template>

// frontend/src/components/StatCard.tsx
import React from 'react';
import { LucideIcon } from 'lucide-react';

interface StatCardProps {
  title: string;
  value: number | string;
  icon: LucideIcon;
  trend?: { value: number; isPositive: boolean };
  color?: 'teal' | 'blue' | 'amber' | 'red' | 'slate';
}

const colorClasses: Record<string, string> = {
  teal: 'bg-teal-50 text-teal-600',
  blue: 'bg-blue-50 text-blue-600',
  amber: 'bg-amber-50 text-amber-600',
  red: 'bg-red-50 text-red-600',
  slate: 'bg-slate-50 text-slate-600',
};

export const StatCard: React.FC<StatCardProps> = ({ title, value, icon: Icon, trend, color = 'teal', formatValue }) => {
  const displayValue = formatValue ? formatValue(value) : value;
  
  return (
    <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-5 hover:shadow-md transition-shadow">
      <div className="flex items-start justify-between">
        <div>
          <p className="text-sm text-slate-500 mb-1">{title}</p>
          <p className="text-2xl font-bold text-slate-800">{displayValue}</p>
          {trend && (
            <p className={`text-xs mt-1 ${trend.isPositive ? 'text-green-600' : 'text-red-600'}`}>
              {trend.isPositive ? '↑' : '↓'} {Math.abs(trend.value)}% 较上月
            </p>
          )}
        </div>
        <div className={`p-3 rounded-xl ${colorClasses[color]}`}>
          <Icon size={24} />
        </div>
      </div>
    </div>
  );
};
