// frontend/src/views/station/Notifications.vue
<script setup>
import { ref, onMounted } from 'vue'
import { getNotifications, retryPendingNotifications } from '../../api'

const notifications = ref([])
const loading = ref(false)

async function loadData() {
  loading.value = true
  try {
    notifications.value = await getNotifications({})
  } catch (e) {
    console.error(e)
  } finally {
    loading.value = false
  }
}

onMounted(loadData)

async function handleRetry(item) {
  try {
    await retryPendingNotifications()
    await loadData()
  } catch (e) {
    alert('重试失败: ' + e.message)
  }
}
</script>

<template>
  <div class="page-card">
    <h2 class="card-title">通知管理</h2>
    <div v-if="loading" class="empty-state">加载中...</div>
    <div v-else-if="!notifications.length" class="empty-state">暂无通知</div>
    <table v-else class="data-table">
      <thead>
        <tr>
          <th>通知类型</th>
          <th>接收人</th>
          <th>发送时间</th>
          <th>状态</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="n in notifications" :key="n.id">
          <td>{{ n.type }}</td>
          <td>{{ n.recipient }}</td>
          <td>{{ n.sent_at }}</td>
          <td><span :class="['status-tag', n.status]">{{ n.status_label }}</span></td>
          <td>
            <button v-if="n.status === 'failed'" class="action-btn" @click="handleRetry(n)">重试</button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<style scoped>
.page-card {
  background: #fff;
  border-radius: 8px;
  padding: 24px;
}
.card-title {
  font-size: 16px;
  font-weight: 600;
  color: #1a3a5c;
  margin-bottom: 16px;
}
.empty-state {
  text-align: center;
  padding: 40px 0;
  color: #999;
  font-size: 14px;
}
.data-table {
  width: 100%;
  border-collapse: collapse;
}
.data-table th,
.data-table td {
  padding: 10px 12px;
  text-align: left;
  border-bottom: 1px solid #f0f0f0;
  font-size: 14px;
}
.data-table th {
  background: #fafafa;
  color: #666;
  font-weight: 500;
}
.status-tag {
  display: inline-block;
  padding: 2px 8px;
  border-radius: 4px;
  font-size: 12px;
}
.status-tag.sent { background: #f6ffed; color: #389e0d; }
.status-tag.pending { background: #fff7e6; color: #d48806; }
.status-tag.failed { background: #fff2f0; color: #cf1322; }
.action-btn {
  padding: 4px 12px;
  border: 1px solid #e8912d;
  border-radius: 4px;
  background: #fff;
  color: #e8912d;
  font-size: 13px;
  cursor: pointer;
}
.action-btn:hover { background: #e8912d; color: #fff; }
</style>

// frontend/src/routes/notifications/+page.svelte
<script>
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { api } from '$lib/api';

	let loading = true;
	let notifications = [];

	onMount(async () => {
		await loadData();
	});

	async function loadData() {
		loading = true;
		try {
			const res = await api.getNotifications();
			notifications = res.list;
		} catch (e) {
			console.error(e);
		} finally {
			loading = false;
		}
	}

	async function markRead(id) {
		try {
			await api.markNotificationRead(id);
			const n = notifications.find(x => x.id === id);
			if (n) n.is_read = true;
		} catch (e) {
			console.error(e);
		}
	}

	function getIcon(type) {
		const icons = {
			system: '🔔',
			application: '📋',
			violation: '⚠️',
			review: '✅'
		};
		return icons[type] || '🔔';
	}
</script>

<div class="page">
	<div class="page-header">
		<h2>通知中心</h2>
	</div>

	<div class="card">
		{#if loading}
			<div class="loading">加载中...</div>
		{:else}
			<div class="notification-list">
				{#each notifications as n}
					<div class="notification-item {n.is_read ? 'read' : 'unread'}" on:click={() => markRead(n.id)}>
						<div class="icon">{getIcon(n.type)}</div>
						<div class="content">
							<div class="title">{n.title}</div>
							<div class="desc">{n.content}</div>
							<div class="time">{new Date(n.created_at).toLocaleString('zh-CN')}</div>
						</div>
						{#if !n.is_read}
							<div class="dot"></div>
						{/if}
					</div>
				{/each}
				{#if notifications.length === 0}
					<div class="empty">暂无通知</div>
				{/if}
			</div>
		{/if}
	</div>
</div>

<style>
	.page { padding: 0; }
	.page-header h2 { font-size: 22px; margin-bottom: 20px; color: #1f2937; }
	.card {
		background: white;
		border-radius: 10px;
		box-shadow: 0 1px 3px rgba(0,0,0,0.1);
		overflow: hidden;
	}
	.loading { text-align: center; padding: 60px 0; color: #9ca3af; }
	.notification-list { max-height: 600px; overflow-y: auto; }
	.notification-item {
		display: flex;
		gap: 14px;
		padding: 16px 20px;
		border-bottom: 1px solid #f3f4f6;
		cursor: pointer;
		transition: background 0.2s;
		position: relative;
	}
	.notification-item:hover { background: #f9fafb; }
	.notification-item.read { opacity: 0.6; }
	.notification-item .icon {
		font-size: 24px;
		flex-shrink: 0;
	}
	.notification-item .content { flex: 1; }
	.notification-item .title {
		font-size: 14px;
		font-weight: 500;
		color: #1f2937;
		margin-bottom: 4px;
	}
	.notification-item .desc {
		font-size: 13px;
		color: #6b7280;
		line-height: 1.5;
	}
	.notification-item .time {
		font-size: 12px;
		color: #9ca3af;
		margin-top: 6px;
	}
	.notification-item .dot {
		width: 8px;
		height: 8px;
		background: #ef4444;
		border-radius: 50%;
		flex-shrink: 0;
		margin-top: 6px;
	}
	.empty { text-align: center; color: #9ca3af; padding: 60px 0; }
</style>
