// src/lib/components/filters/FilterBar.svelte
<script lang="ts">
	import { filterStore, activeFilterCount } from '@/lib/stores/filterStore';
	import { getDistinctValues } from '@/lib/utils/queryService';
	import { getLevelLabel, getChannelLabel } from '@/lib/utils/format';
	import { Calendar, Filter, X } from 'lucide-svelte';

	const { intents, channels, versions, customerLevels } = getDistinctValues();

	let filters = $state($filterStore);
	let showFilters = $state(false);

	$effect(() => {
		filters = $filterStore;
	});

	function handleDateChange(type: 'start' | 'end', value: string) {
		if (type === 'start') {
			filterStore.setDateRange(value, filters.endDate);
		} else {
			filterStore.setDateRange(filters.startDate, value);
		}
	}

	function handleMultiSelectChange(
		field: 'channels' | 'versions' | 'customerLevels' | 'intentTags',
		value: string
	) {
		const current = filters[field];
		const updated = current.includes(value)
			? current.filter((v) => v !== value)
			: [...current, value];

		switch (field) {
			case 'channels':
				filterStore.setChannels(updated);
				break;
			case 'versions':
				filterStore.setVersions(updated);
				break;
			case 'customerLevels':
				filterStore.setCustomerLevels(updated);
				break;
			case 'intentTags':
				filterStore.setIntentTags(updated);
				break;
		}
	}

	function resetFilters() {
		filterStore.reset();
	}
</script>

<div class="bg-white rounded-xl shadow-card border border-slate-100 p-4 mb-6">
	<div class="flex items-center justify-between mb-4">
		<div class="flex items-center gap-4">
			<div class="flex items-center gap-2">
				<Calendar class="w-5 h-5 text-slate-400" />
				<input
					type="date"
					class="input max-w-[160px]"
					value={filters.startDate}
					oninput={(e) => handleDateChange('start', e.target.value)}
				/>
				<span class="text-slate-400">至</span>
				<input
					type="date"
					class="input max-w-[160px]"
					value={filters.endDate}
					oninput={(e) => handleDateChange('end', e.target.value)}
				/>
			</div>
		</div>

		<div class="flex items-center gap-2">
			<button
				class="btn btn-outline flex items-center gap-2"
				onclick={() => (showFilters = !showFilters)}
			>
				<Filter class="w-4 h-4" />
				高级筛选
				{#if $activeFilterCount > 0}
					<span class="badge badge-info">{$activeFilterCount}</span>
				{/if}
			</button>
			{#if $activeFilterCount > 0}
				<button class="btn btn-secondary" onclick={resetFilters}>
					<X class="w-4 h-4 inline mr-1" />
					重置
				</button>
			{/if}
		</div>
	</div>

	{#if showFilters}
		<div class="grid grid-cols-4 gap-4 pt-4 border-t border-slate-100 animate-fade-in">
			<div>
				<label class="block text-sm font-medium text-slate-600 mb-2">渠道</label>
				<div class="space-y-1">
					{#each channels as channel}
						<label class="flex items-center gap-2 cursor-pointer">
							<input
								type="checkbox"
								checked={filters.channels.includes(channel)}
								onchange={() => handleMultiSelectChange('channels', channel)}
								class="rounded text-primary-500 focus:ring-primary-500"
							/>
							<span class="text-sm text-slate-700">{getChannelLabel(channel)}</span>
						</label>
					{/each}
				</div>
			</div>

			<div>
				<label class="block text-sm font-medium text-slate-600 mb-2">版本</label>
				<div class="space-y-1">
					{#each versions as version}
						<label class="flex items-center gap-2 cursor-pointer">
							<input
								type="checkbox"
								checked={filters.versions.includes(version)}
								onchange={() => handleMultiSelectChange('versions', version)}
								class="rounded text-primary-500 focus:ring-primary-500"
							/>
							<span class="text-sm text-slate-700">{version}</span>
						</label>
					{/each}
				</div>
			</div>

			<div>
				<label class="block text-sm font-medium text-slate-600 mb-2">客户等级</label>
				<div class="space-y-1">
					{#each customerLevels as level}
						<label class="flex items-center gap-2 cursor-pointer">
							<input
								type="checkbox"
								checked={filters.customerLevels.includes(level)}
								onchange={() => handleMultiSelectChange('customerLevels', level)}
								class="rounded text-primary-500 focus:ring-primary-500"
							/>
							<span class="text-sm text-slate-700">{getLevelLabel(level)}</span>
						</label>
					{/each}
				</div>
			</div>

			<div>
				<label class="block text-sm font-medium text-slate-600 mb-2">意图标签</label>
				<div class="space-y-1 max-h-[200px] overflow-y-auto scrollbar-thin pr-2">
					{#each intents as intent}
						<label class="flex items-center gap-2 cursor-pointer">
							<input
								type="checkbox"
								checked={filters.intentTags.includes(intent)}
								onchange={() => handleMultiSelectChange('intentTags', intent)}
								class="rounded text-primary-500 focus:ring-primary-500"
							/>
							<span class="text-sm text-slate-700 truncate">{intent}</span>
						</label>
					{/each}
				</div>
			</div>
		</div>
	{/if}
</div>

// app/components/FilterBar.tsx
import { useState, useEffect } from 'react';
import { Filter, X, ChevronDown } from 'lucide-react';
import { useFilters } from '~/contexts/FilterContext';
import { api } from '~/utils/api';
import type { FilterOption } from '@shared/types';

export default function FilterBar() {
  const { filters, updateFilters, resetFilters } = useFilters();
  const [options, setOptions] = useState<{
    stores: FilterOption[];
    categories: FilterOption[];
    suppliers: FilterOption[];
  }>({ stores: [], categories: [], suppliers: [] });
  const [openDropdown, setOpenDropdown] = useState<string | null>(null);

  useEffect(() => {
    api.getFilterOptions().then(setOptions);
  }, []);

  const activeFilterCount = 
    (filters.storeIds?.length || 0) +
    (filters.categoryIds?.length || 0) +
    (filters.supplierIds?.length || 0);

  const toggleDropdown = (name: string) => {
    setOpenDropdown(openDropdown === name ? null : name);
  };

  const toggleOption = (field: 'storeIds' | 'categoryIds' | 'supplierIds', id: string) => {
    const current = filters[field] || [];
    const updated = current.includes(id)
      ? current.filter((i) => i !== id)
      : [...current, id];
    updateFilters({ [field]: updated.length > 0 ? updated : undefined });
  };

  const renderDropdown = (
    name: string,
    field: 'storeIds' | 'categoryIds' | 'supplierIds',
    items: FilterOption[]
  ) => (
    <div className="relative">
      <button
        onClick={() => toggleDropdown(name)}
        className="flex items-center gap-2 px-4 py-2 rounded-lg bg-slate-800/50 border border-slate-700 hover:border-slate-600 text-sm transition-all"
      >
        <span className="text-slate-400">{name}</span>
        {(filters[field]?.length || 0) > 0 && (
          <span className="px-1.5 py-0.5 text-xs bg-fresh-green/20 text-fresh-green rounded-full">
            {filters[field]!.length}
          </span>
        )}
        <ChevronDown className={`w-4 h-4 text-slate-400 transition-transform ${openDropdown === name ? 'rotate-180' : ''}`} />
      </button>
      
      {openDropdown === name && (
        <div className="absolute top-full left-0 mt-2 w-56 max-h-64 overflow-y-auto bg-slate-800 border border-slate-700 rounded-xl shadow-2xl z-50 animate-fade-in">
          {items.map((item) => (
            <label
              key={item.id}
              className="flex items-center gap-3 px-4 py-2.5 hover:bg-slate-700/50 cursor-pointer text-sm"
            >
              <input
                type="checkbox"
                checked={(filters[field] || []).includes(item.id)}
                onChange={() => toggleOption(field, item.id)}
                className="w-4 h-4 rounded border-slate-600 bg-slate-700 text-fresh-green focus:ring-fresh-green"
              />
              <span className="text-slate-200">{item.name}</span>
            </label>
          ))}
        </div>
      )}
    </div>
  );

  return (
    <div className="border-b border-slate-700/50 bg-slate-900/30">
      <div className="max-w-[1600px] mx-auto px-6 py-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="flex items-center gap-2 text-slate-400">
              <Filter className="w-4 h-4" />
              <span className="text-sm font-medium">筛选：</span>
            </div>
            
            {renderDropdown('门店', 'storeIds', options.stores)}
            {renderDropdown('品类', 'categoryIds', options.categories)}
            {renderDropdown('供应商', 'supplierIds', options.suppliers)}

            <div className="flex items-center gap-2 px-3 py-2 rounded-lg bg-slate-800/50 border border-slate-700">
              <input
                type="date"
                value={filters.startDate}
                onChange={(e) => updateFilters({ startDate: e.target.value })}
                className="bg-transparent text-sm text-slate-300 outline-none"
              />
              <span className="text-slate-500">至</span>
              <input
                type="date"
                value={filters.endDate}
                onChange={(e) => updateFilters({ endDate: e.target.value })}
                className="bg-transparent text-sm text-slate-300 outline-none"
              />
            </div>
          </div>

          {activeFilterCount > 0 && (
            <button
              onClick={resetFilters}
              className="flex items-center gap-1.5 text-sm text-slate-400 hover:text-white transition-colors"
            >
              <X className="w-4 h-4" />
              清除筛选 ({activeFilterCount})
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
