// badminton-court/pages/login.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-primary-600 via-primary-700 to-primary-900 p-4">
    <div class="w-full max-w-md">
      <div class="bg-white rounded-2xl shadow-2xl p-8">
        <div class="text-center mb-8">
          <div class="w-16 h-16 mx-auto bg-primary-100 rounded-2xl flex items-center justify-center text-3xl mb-3">🏸</div>
          <h1 class="text-2xl font-bold text-gray-800">羽毛球馆管理系统</h1>
          <p class="text-gray-500 mt-1 text-sm">Badminton Court Management System</p>
        </div>

        <form @submit.prevent="handleLogin" class="space-y-4">
          <div>
            <label class="label">用户名 / 手机号</label>
            <input v-model="form.username" class="input" placeholder="请输入用户名或手机号" autocomplete="username" />
          </div>
          <div>
            <label class="label">密码</label>
            <input v-model="form.password" type="password" class="input" placeholder="请输入密码" autocomplete="current-password" />
          </div>
          <div v-if="errorMsg" class="text-red-600 text-sm bg-red-50 p-3 rounded-lg">{{ errorMsg }}</div>
          <button :disabled="loading" class="btn-primary w-full py-3">
            {{ loading ? '登录中...' : '登 录' }}
          </button>
        </form>

        <div class="mt-6 pt-6 border-t border-gray-100">
          <p class="text-xs text-gray-400 mb-2 text-center">演示账号</p>
          <div class="grid grid-cols-2 gap-2 text-xs">
            <button v-for="a in demoAccounts" :key="a[0]" class="bg-gray-50 hover:bg-gray-100 rounded-lg p-2 text-left transition"
              @click="form = { username: a[0], password: a[1] }">
              <div class="font-medium text-gray-700">{{ a[2] }}</div>
              <div class="text-gray-400">{{ a[0] }} / {{ a[1] }}</div>
            </button>
          </div>
        </div>
      </div>
      <p class="text-center text-white/60 text-xs mt-4">© 2024 Badminton Court Management System</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { reactive, ref } from 'vue'
import { useAuthStore } from '~/stores/auth'

const auth = useAuthStore()
const router = useRouter()

const form = reactive({ username: 'superadmin', password: 'admin123' })
const loading = ref(false)
const errorMsg = ref('')

const demoAccounts = [
  ['superadmin', 'admin123', '超级管理员'],
  ['admin', 'admin123', '管理员'],
  ['manager', 'admin123', '运营经理'],
  ['coach01', 'admin123', '教练'],
  ['staff01', 'admin123', '前台'],
  ['user001', 'user123', '客户']
]

async function handleLogin() {
  if (!form.username || !form.password) {
    errorMsg.value = '请输入用户名和密码'
    return
  }
  loading.value = true
  errorMsg.value = ''
  try {
    await auth.login(form.username, form.password)
    router.push('/dashboard')
  } catch (e: any) {
    errorMsg.value = e.message || '登录失败'
  } finally {
    loading.value = false
  }
}
</script>

// apps/frontend/src/pages/Login.tsx
import { useState } from 'react';
import { useNavigate } from '@tanstack/react-router';
import { useAuthStore } from '../store/auth';

export function LoginPage() {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const { login } = useAuthStore();
  const navigate = useNavigate();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      await login(username, password);
      navigate({ to: '/' });
    } catch (err: any) {
      setError(err.response?.data?.error || '登录失败，请检查用户名和密码');
    } finally {
      setLoading(false);
    }
  };

  const quickLogin = async (role: string) => {
    const accounts: Record<string, { username: string; password: string }> = {
      admin: { username: 'admin', password: '123456' },
      staff: { username: 'staff', password: '123456' },
      coach: { username: 'coach', password: '123456' },
      manager: { username: 'manager', password: '123456' },
    };

    const acc = accounts[role];
    if (acc) {
      setUsername(acc.username);
      setPassword(acc.password);
      setLoading(true);
      try {
        await login(acc.username, acc.password);
        navigate({ to: '/' });
      } catch (err: any) {
        setError(err.response?.data?.error || '登录失败');
      } finally {
        setLoading(false);
      }
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-primary-500 to-primary-800">
      <div className="bg-white rounded-2xl shadow-2xl p-8 w-full max-w-md">
        <div className="text-center mb-8">
          <div className="text-5xl mb-4">🏊</div>
          <h1 className="text-2xl font-bold text-gray-800">游泳馆设备巡检管理系统</h1>
          <p className="text-gray-500 mt-2">请登录您的账户</p>
        </div>

        <form onSubmit={handleSubmit} className="space-y-5">
          {error && (
            <div className="bg-red-50 border border-red-200 text-red-600 px-4 py-3 rounded-lg text-sm">
              {error}
            </div>
          )}

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">用户名</label>
            <input
              type="text"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none transition-all"
              placeholder="请输入用户名"
              required
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">密码</label>
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none transition-all"
              placeholder="请输入密码"
              required
            />
          </div>

          <button
            type="submit"
            disabled={loading}
            className="w-full py-3 bg-primary-500 text-white rounded-lg font-medium hover:bg-primary-600 disabled:bg-primary-300 transition-colors"
          >
            {loading ? '登录中...' : '登录'}
          </button>
        </form>

        <div className="mt-6 pt-6 border-t border-gray-200">
          <p className="text-xs text-gray-500 text-center mb-3">快捷登录（演示账户）</p>
          <div className="grid grid-cols-4 gap-2">
            <button
              onClick={() => quickLogin('admin')}
              className="text-xs py-2 px-2 bg-gray-100 hover:bg-gray-200 rounded transition-colors"
            >
              管理员
            </button>
            <button
              onClick={() => quickLogin('staff')}
              className="text-xs py-2 px-2 bg-gray-100 hover:bg-gray-200 rounded transition-colors"
            >
              前台
            </button>
            <button
              onClick={() => quickLogin('coach')}
              className="text-xs py-2 px-2 bg-gray-100 hover:bg-gray-200 rounded transition-colors"
            >
              教练主管
            </button>
            <button
              onClick={() => quickLogin('manager')}
              className="text-xs py-2 px-2 bg-gray-100 hover:bg-gray-200 rounded transition-colors"
            >
              负责人
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
