// src/components/AppLayout.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import {
  Bell,
  ClipboardList,
  PlusCircle,
  LayoutDashboard,
  BellRing,
  Settings,
  ScrollText,
  LogOut,
  ChevronRight,
} from 'lucide-vue-next'

const route = useRoute()
const router = useRouter()
const authStore = useAuthStore()

const navItems = computed(() => {
  const items = [
    { label: '需求列表', icon: ClipboardList, to: '/requirements' },
    { label: '新建需求', icon: PlusCircle, to: '/requirements/new' },
    { label: '值班看板', icon: LayoutDashboard, to: '/dashboard' },
  ]
  if (authStore.canManageReminders) {
    items.push({ label: '提醒管理', icon: BellRing, to: '/reminders' })
  }
  if (authStore.canManageAdmin) {
    items.push({ label: '后台管理', icon: Settings, to: '/admin' })
  }
  if (authStore.canManageReminders) {
    items.push({ label: '操作日志', icon: ScrollText, to: '/logs' })
  }
  return items
})

const breadcrumbs = computed(() => {
  const map: Record<string, string> = {
    requirements: '需求列表',
    'requirement-new': '新建需求',
    'requirement-detail': '需求详情',
    reminders: '提醒管理',
    dashboard: '值班看板',
    admin: '后台管理',
    logs: '操作日志',
  }
  return map[route.name as string] ?? ''
})

const userInitials = computed(() => {
  const name = authStore.user?.name ?? ''
  return name.slice(0, 2).toUpperCase()
})

function handleLogout() {
  authStore.logout()
  router.push('/login')
}
</script>

<template>
  <div class="min-h-screen bg-slate-50">
    <aside class="fixed left-0 top-0 bottom-0 w-60 bg-slate-800 text-white flex flex-col z-30">
      <div class="h-14 flex items-center gap-2.5 px-5 border-b border-slate-700">
        <Bell class="w-6 h-6 text-amber-500" />
        <span class="text-lg font-semibold tracking-wide">提醒中心</span>
      </div>

      <nav class="flex-1 py-3 overflow-y-auto">
        <router-link
          v-for="item in navItems"
          :key="item.to"
          :to="item.to"
          class="flex items-center gap-3 px-5 py-2.5 text-sm transition-all duration-200 border-l-[3px] border-transparent"
          :class="
            route.path === item.to || (item.to !== '/' && route.path.startsWith(item.to + '/'))
              ? 'bg-slate-700 text-white border-amber-500'
              : 'text-slate-300 hover:bg-slate-700/50 hover:text-white border-transparent'
          "
        >
          <component :is="item.icon" class="w-[18px] h-[18px] shrink-0" />
          <span>{{ item.label }}</span>
        </router-link>
      </nav>

      <div class="border-t border-slate-700 p-4">
        <div class="flex items-center gap-3 mb-3">
          <div class="w-8 h-8 rounded-full bg-amber-500 flex items-center justify-center text-xs font-bold text-white shrink-0">
            {{ userInitials }}
          </div>
          <div class="min-w-0">
            <p class="text-sm font-medium truncate">{{ authStore.user?.name }}</p>
            <p class="text-xs text-slate-400 truncate">{{ authStore.user?.email }}</p>
          </div>
        </div>
        <button
          class="flex items-center gap-2 text-sm text-slate-400 hover:text-white transition-colors w-full cursor-pointer"
          @click="handleLogout"
        >
          <LogOut class="w-4 h-4" />
          <span>退出登录</span>
        </button>
      </div>
    </aside>

    <div class="pl-60 min-h-screen flex flex-col">
      <header class="h-14 bg-white border-b border-slate-200 flex items-center justify-between px-6 sticky top-0 z-20">
        <div class="flex items-center gap-1.5 text-sm text-slate-500">
          <span class="text-slate-400">首页</span>
          <ChevronRight v-if="breadcrumbs" class="w-4 h-4 text-slate-300" />
          <span v-if="breadcrumbs" class="text-slate-700 font-medium">{{ breadcrumbs }}</span>
        </div>
        <div class="flex items-center gap-4">
          <button class="relative text-slate-400 hover:text-slate-600 transition-colors cursor-pointer">
            <Bell class="w-5 h-5" />
            <span class="absolute -top-1 -right-1 w-2 h-2 bg-red-500 rounded-full"></span>
          </button>
          <div class="w-8 h-8 rounded-full bg-amber-500 flex items-center justify-center text-xs font-bold text-white">
            {{ userInitials }}
          </div>
        </div>
      </header>

      <main class="flex-1 p-6">
        <router-view />
      </main>
    </div>
  </div>
</template>

// components/layout/AppLayout.tsx
'use client';

import { usePathname, useRouter } from 'next/navigation';
import Link from 'next/link';
import {
  LayoutDashboard,
  Map,
  LineChart,
  Database,
  FileDown,
  Droplets,
  LogOut,
  Shield,
  Building2,
} from 'lucide-react';
import { useAuthStore } from '@/lib/store/useAuthStore';
import { useEffect } from 'react';

const navItems = [
  { path: '/dashboard', label: '总览仪表盘', icon: LayoutDashboard },
  { path: '/map', label: '地图监测', icon: Map },
  { path: '/trends', label: '趋势分析', icon: LineChart },
  { path: '/data-management', label: '数据管理', icon: Database, adminOnly: true },
  { path: '/export', label: '报告导出', icon: FileDown },
];

export default function AppLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const router = useRouter();
  const { user, logout, checkAuth, isAuthenticated } = useAuthStore();

  useEffect(() => {
    checkAuth();
  }, [checkAuth]);

  useEffect(() => {
    if (!isAuthenticated && pathname !== '/login') {
      router.push('/login');
    }
  }, [isAuthenticated, pathname, router]);

  const handleLogout = async () => {
    logout();
    router.push('/login');
  };

  if (!isAuthenticated) {
    return <>{children}</>;
  }

  return (
    <div className="flex min-h-screen">
      <div className="w-60 bg-slate-900 text-white min-h-screen flex flex-col flex-shrink-0">
        <div className="p-5 border-b border-slate-700">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-gradient-to-br from-cyan-500 to-blue-600 flex items-center justify-center">
              <Droplets className="w-6 h-6 text-white" />
            </div>
            <div>
              <h1 className="font-bold text-lg">水质监测系统</h1>
              <p className="text-xs text-slate-400">River Water Quality</p>
            </div>
          </div>
        </div>

        <nav className="flex-1 p-3">
          <ul className="space-y-1">
            {navItems.map((item) => {
              if (item.adminOnly && user?.role !== 'admin') return null;
              const isActive = pathname === item.path;
              const Icon = item.icon;

              return (
                <li key={item.path}>
                  <Link
                    href={item.path}
                    className={`flex items-center gap-3 px-4 py-2.5 rounded-lg text-sm font-medium transition-all duration-200 ${
                      isActive
                        ? 'bg-cyan-600 text-white shadow-lg shadow-cyan-600/30'
                        : 'text-slate-300 hover:bg-slate-800 hover:text-white'
                    }`}
                  >
                    <Icon className="w-5 h-5" />
                    {item.label}
                  </Link>
                </li>
              );
            })}
          </ul>
        </nav>

        <div className="p-4 border-t border-slate-700">
          <div className="flex items-center gap-3 px-2 mb-3">
            <div className="w-10 h-10 rounded-full bg-gradient-to-br from-cyan-400 to-blue-500 flex items-center justify-center text-sm font-bold shadow-lg">
              {user?.username?.charAt(0).toUpperCase()}
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-sm font-medium truncate">{user?.username}</p>
              <p className="text-xs text-slate-400 truncate flex items-center gap-1">
                <Building2 className="w-3 h-3" />
                {user?.organization}
              </p>
            </div>
          </div>
          <div className="flex items-center justify-between">
            <span className={`inline-flex items-center gap-1 text-xs px-2 py-1 rounded-full ${
              user?.role === 'admin'
                ? 'bg-amber-500/20 text-amber-300'
                : 'bg-cyan-500/20 text-cyan-300'
            }`}>
              <Shield className="w-3 h-3" />
              {user?.role === 'admin' ? '管理员' : '研究员'}
            </span>
            <button
              onClick={handleLogout}
              className="flex items-center gap-1.5 text-xs text-slate-400 hover:text-white px-2 py-1 rounded hover:bg-slate-700 transition-colors"
              title="退出登录"
            >
              <LogOut className="w-3.5 h-3.5" />
              退出
            </button>
          </div>
        </div>
      </div>

      <div className="flex-1 flex flex-col overflow-hidden">
        <main className="flex-1 overflow-auto p-6 bg-slate-50">
          {children}
        </main>
      </div>
    </div>
  );
}
