// src/components/ChartCard.vue
<script setup lang="ts">
import { Download, Loader2, AlertCircle, Database } from 'lucide-vue-next';

interface Props {
  title: string;
  sampleSize?: number;
  loading?: boolean;
  error?: string | null;
  showExport?: boolean;
  large?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  showExport: false,
  large: false
});

const emit = defineEmits<{
  (e: 'export'): void;
}>();
</script>

<template>
  <div
    :class="[
      'bg-white rounded-xl border border-slate-200 shadow-sm flex flex-col overflow-hidden',
      large ? 'col-span-2 row-span-2' : ''
    ]"
  >
    <div class="flex items-center justify-between px-5 py-4 border-b border-slate-100">
      <div class="flex items-center gap-3">
        <h3 class="font-semibold text-slate-800">{{ title }}</h3>
        <div v-if="sampleSize !== undefined" class="flex items-center gap-1 text-xs text-slate-400">
          <Database class="w-3 h-3" />
          <span>样本量: {{ sampleSize.toLocaleString() }}</span>
        </div>
      </div>
      <div class="flex items-center gap-2">
        <div v-if="loading" class="flex items-center gap-2 text-sm text-slate-400">
          <Loader2 class="w-4 h-4 animate-spin" />
          <span>加载中</span>
        </div>
        <div v-else-if="error" class="flex items-center gap-1 text-sm text-rose-500">
          <AlertCircle class="w-4 h-4" />
          <span>数据异常</span>
        </div>
        <button
          v-if="showExport && !loading"
          class="p-2 text-slate-400 hover:text-slate-600 hover:bg-slate-100 rounded-lg transition-colors"
          @click="emit('export')"
          title="导出数据"
        >
          <Download class="w-4 h-4" />
        </button>
      </div>
    </div>
    <div class="flex-1 p-4 min-h-0 relative">
      <slot />
      <div v-if="loading" class="absolute inset-0 bg-white/60 flex items-center justify-center z-10">
        <Loader2 class="w-8 h-8 animate-spin text-teal-600" />
      </div>
    </div>
  </div>
</template>

// src/components/charts/ChartCard.tsx
import { ReactNode } from 'react';
import { Info, MoreHorizontal, Loader2 } from 'lucide-react';

interface ChartCardProps {
  title: string;
  subtitle?: string;
  children: ReactNode;
  loading?: boolean;
  error?: string | null;
  sampleSize?: number;
  onDrillDown?: () => void;
  action?: ReactNode;
}

export function ChartCard({
  title,
  subtitle,
  children,
  loading = false,
  error = null,
  sampleSize,
  onDrillDown,
  action,
}: ChartCardProps) {
  return (
    <div className="bg-white rounded-xl border border-gray-200 shadow-sm card-hover overflow-hidden">
      <div className="px-5 py-4 border-b border-gray-100 flex items-start justify-between">
        <div>
          <h3 className="font-semibold text-gray-800 text-base">{title}</h3>
          {subtitle && <p className="text-sm text-gray-500 mt-0.5">{subtitle}</p>}
        </div>
        <div className="flex items-center gap-2">
          {sampleSize !== undefined && (
            <span className="text-xs text-gray-400 bg-gray-50 px-2 py-1 rounded">
              样本: {sampleSize.toLocaleString()}
            </span>
          )}
          {action}
          <button className="p-1 text-gray-400 hover:text-gray-600 rounded hover:bg-gray-100">
            <MoreHorizontal className="w-4 h-4" />
          </button>
        </div>
      </div>

      <div className="p-5 relative min-h-[280px]">
        {loading && (
          <div className="absolute inset-0 bg-white/80 flex items-center justify-center z-10">
            <div className="flex items-center gap-2 text-gray-500">
              <Loader2 className="w-5 h-5 animate-spin" />
              <span className="text-sm">加载中...</span>
            </div>
          </div>
        )}

        {error && (
          <div className="absolute inset-0 flex items-center justify-center bg-white">
            <div className="text-center">
              <div className="w-12 h-12 rounded-full bg-danger-50 flex items-center justify-center mx-auto mb-3">
                <Info className="w-6 h-6 text-danger-500" />
              </div>
              <p className="text-sm text-gray-600 mb-2">数据加载失败</p>
              <p className="text-xs text-gray-400">{error}</p>
            </div>
          </div>
        )}

        {!loading && !error && children}
      </div>
    </div>
  );
}
