// src/components/FunnelChart.vue
<template>
  <div class="funnel-chart card-shadow">
    <div class="chart-header">
      <h3>报名转化漏斗</h3>
      <div class="cancel-summary">
        <span class="cancel-label">取消率：</span>
        <span class="cancel-value">{{ cancelRate }}%</span>
        <span class="cancel-count">（共 {{ totalCancelled }} 人取消）</span>
      </div>
    </div>

    <div class="chart-content">
      <div ref="funnelRef" class="funnel-container"></div>
      
      <div class="cancel-reasons">
        <h4>取消原因分布</h4>
        <div class="reason-list">
          <div
            v-for="reason in cancelByReason"
            :key="reason.reasonId"
            class="reason-item"
          >
            <span class="reason-name">{{ reason.reason }}</span>
            <div class="reason-bar">
              <div
                class="reason-fill"
                :style="{ width: getReasonBarWidth(reason.count) + '%' }"
              ></div>
            </div>
            <span class="reason-count">{{ reason.count }}</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, watch, nextTick, computed } from 'vue'
import * as d3 from 'd3'

const props = defineProps({
  funnelData: {
    type: Array,
    default: () => []
  },
  cancelByReason: {
    type: Array,
    default: () => []
  },
  totalCancelled: {
    type: Number,
    default: 0
  },
  cancelRate: {
    type: String,
    default: '0'
  }
})

const funnelRef = ref(null)
const maxCancelCount = computed(() => {
  if (props.cancelByReason.length === 0) return 1
  return Math.max(...props.cancelByReason.map(r => r.count))
})

const getReasonBarWidth = (count) => {
  return (count / maxCancelCount.value) * 100
}

const drawFunnel = () => {
  if (!funnelRef.value || !props.funnelData || props.funnelData.length === 0) return

  const container = funnelRef.value
  container.innerHTML = ''

  const width = container.clientWidth
  const height = container.clientHeight
  const margin = { top: 20, right: 40, bottom: 20, left: 40 }
  const innerWidth = width - margin.left - margin.right
  const innerHeight = height - margin.top - margin.bottom

  const svg = d3.select(container)
    .append('svg')
    .attr('width', width)
    .attr('height', height)

  const g = svg.append('g')
    .attr('transform', `translate(${margin.left},${margin.top})`)

  const maxCount = d3.max(props.funnelData, d => d.count)
  const stageHeight = innerHeight / props.funnelData.length

  const colorScale = d3.scaleLinear()
    .domain([0, props.funnelData.length - 1])
    .range(['#1890ff', '#69c0ff'])

  props.funnelData.forEach((d, i) => {
    const nextCount = i < props.funnelData.length - 1 ? props.funnelData[i + 1].count : 0
    const topWidth = (d.count / maxCount) * innerWidth
    const bottomWidth = (nextCount / maxCount) * innerWidth
    const y = i * stageHeight

    const pathData = [
      [innerWidth / 2 - topWidth / 2, y],
      [innerWidth / 2 + topWidth / 2, y],
      [innerWidth / 2 + bottomWidth / 2, y + stageHeight],
      [innerWidth / 2 - bottomWidth / 2, y + stageHeight]
    ]

    g.append('path')
      .attr('d', `M${pathData.map(p => p.join(',')).join('L')}Z`)
      .attr('fill', colorScale(i))
      .attr('stroke', '#fff')
      .attr('stroke-width', 2)
      .style('cursor', 'pointer')
      .on('mouseenter', function() {
        d3.select(this).attr('fill', d3.color(colorScale(i)).brighter(0.2))
      })
      .on('mouseleave', function() {
        d3.select(this).attr('fill', colorScale(i))
      })

    g.append('text')
      .attr('x', innerWidth / 2)
      .attr('y', y + stageHeight / 2 - 10)
      .attr('text-anchor', 'middle')
      .attr('fill', '#fff')
      .attr('font-size', '14px')
      .attr('font-weight', 'bold')
      .text(d.stage)

    g.append('text')
      .attr('x', innerWidth / 2)
      .attr('y', y + stageHeight / 2 + 12)
      .attr('text-anchor', 'middle')
      .attr('fill', '#fff')
      .attr('font-size', '16px')
      .attr('font-weight', 'bold')
      .text(d.count.toLocaleString())

    if (i < props.funnelData.length - 1) {
      const rate = ((nextCount / d.count) * 100).toFixed(1)
      g.append('text')
        .attr('x', innerWidth / 2)
        .attr('y', y + stageHeight + 5)
        .attr('text-anchor', 'middle')
        .attr('fill', '#52c41a')
        .attr('font-size', '12px')
        .text(`转化率 ${rate}%`)
    }
  })
}

onMounted(() => {
  nextTick(() => {
    drawFunnel()
  })
})

watch(
  () => props.funnelData,
  () => {
    nextTick(() => {
      drawFunnel()
    })
  },
  { deep: true }
)
</script>

<style scoped lang="scss">
.funnel-chart {
  padding: 20px;
  height: 100%;
  display: flex;
  flex-direction: column;
}

.chart-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 16px;

  h3 {
    margin: 0;
    font-size: 16px;
    color: #303133;
  }
}

.cancel-summary {
  display: flex;
  align-items: center;
  gap: 4px;
  font-size: 13px;

  .cancel-label {
    color: #606266;
  }

  .cancel-value {
    color: #f5222d;
    font-weight: 600;
    font-size: 16px;
  }

  .cancel-count {
    color: #909399;
  }
}

.chart-content {
  flex: 1;
  display: flex;
  gap: 20px;
  min-height: 0;
}

.funnel-container {
  flex: 2;
  min-height: 300px;
}

.cancel-reasons {
  flex: 1;
  display: flex;
  flex-direction: column;

  h4 {
    margin: 0 0 12px 0;
    font-size: 14px;
    color: #303133;
  }
}

.reason-list {
  flex: 1;
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.reason-item {
  display: flex;
  align-items: center;
  gap: 10px;

  .reason-name {
    width: 70px;
    font-size: 12px;
    color: #606266;
    flex-shrink: 0;
  }

  .reason-bar {
    flex: 1;
    height: 16px;
    background: #f0f0f0;
    border-radius: 8px;
    overflow: hidden;
  }

  .reason-fill {
    height: 100%;
    background: linear-gradient(90deg, #faad14, #f5222d);
    border-radius: 8px;
    transition: width 0.3s ease;
  }

  .reason-count {
    width: 30px;
    text-align: right;
    font-size: 12px;
    color: #303133;
    font-weight: 500;
    flex-shrink: 0;
  }
}
</style>

// src/components/charts/FunnelChart.tsx
import React, { useEffect, useRef } from 'react';
import * as d3 from 'd3';
import { FunnelData } from '../../types';
import { TrendingDown, ArrowRight } from 'lucide-react';

interface FunnelChartProps {
  data: FunnelData;
  onStepClick?: (stepId: string) => void;
}

const FunnelChart: React.FC<FunnelChartProps> = ({ data, onStepClick }) => {
  const svgRef = useRef<SVGSVGElement>(null);

  useEffect(() => {
    if (!svgRef.current || !data) return;

    const svg = d3.select(svgRef.current);
    svg.selectAll('*').remove();

    const container = svgRef.current.parentElement;
    if (!container) return;

    const width = container.clientWidth;
    const height = 500;
    const margin = { top: 40, right: 180, bottom: 40, left: 40 };

    svg.attr('width', width).attr('height', height);

    const innerWidth = width - margin.left - margin.right;
    const innerHeight = height - margin.top - margin.bottom;

    const g = svg.append('g').attr('transform', `translate(${margin.left},${margin.top})`);

    const maxCount = data.steps[0].count;
    const stepHeight = innerHeight / data.steps.length;
    const minWidth = innerWidth * 0.2;

    const colorScale = d3
      .scaleLinear<string>()
      .domain([0, data.steps.length - 1])
      .range(['#0ea5e9', '#0369a1']);

    const steps = g
      .selectAll('.funnel-step')
      .data(data.steps)
      .enter()
      .append('g')
      .attr('class', 'funnel-step')
      .attr('transform', (_, i) => `translate(0,${i * stepHeight})`)
      .style('cursor', 'pointer')
      .on('click', (_event, d) => {
        onStepClick?.(d.id);
      });

    steps.each(function (d, i) {
      const stepGroup = d3.select(this);
      const nextCount = i < data.steps.length - 1 ? data.steps[i + 1].count : 0;
      const currentWidth = ((d.count / maxCount) * (innerWidth - minWidth)) + minWidth;
      const nextWidth = ((nextCount / maxCount) * (innerWidth - minWidth)) + minWidth;
      const x1 = (innerWidth - currentWidth) / 2;
      const x2 = (innerWidth - nextWidth) / 2;

      const pathData = `
        M ${x1} 5
        L ${x1 + currentWidth} 5
        L ${x2 + nextWidth} ${stepHeight - 5}
        L ${x2} ${stepHeight - 5}
        Z
      `;

      stepGroup
        .append('path')
        .attr('d', pathData)
        .attr('fill', colorScale(i))
        .attr('opacity', 0.85)
        .attr('rx', 8)
        .style('transition', 'opacity 0.2s')
        .on('mouseenter', function () {
          d3.select(this).attr('opacity', 1);
        })
        .on('mouseleave', function () {
          d3.select(this).attr('opacity', 0.85);
        });

      stepGroup
        .append('text')
        .attr('x', innerWidth / 2)
        .attr('y', stepHeight / 2 - 8)
        .attr('text-anchor', 'middle')
        .attr('fill', 'white')
        .attr('font-size', '14px')
        .attr('font-weight', '600')
        .text(d.name);

      stepGroup
        .append('text')
        .attr('x', innerWidth / 2)
        .attr('y', stepHeight / 2 + 14)
        .attr('text-anchor', 'middle')
        .attr('fill', 'rgba(255,255,255,0.9)')
        .attr('font-size', '12px')
        .text(`${d.count.toLocaleString()} 用户 (${d.conversionRate}%)`);
    });

    const annotations = g
      .selectAll('.funnel-annotation')
      .data(data.steps.slice(1))
      .enter()
      .append('g')
      .attr('class', 'funnel-annotation')
      .attr('transform', (_, i) => `translate(${innerWidth + 20},${(i + 0.5) * stepHeight})`);

    annotations
      .append('rect')
      .attr('x', 0)
      .attr('y', -20)
      .attr('width', 150)
      .attr('height', 40)
      .attr('fill', '#f8fafc')
      .attr('stroke', '#e2e8f0')
      .attr('rx', 6);

    annotations
      .append('text')
      .attr('x', 10)
      .attr('y', -2)
      .attr('fill', '#64748b')
      .attr('font-size', '11px')
      .text((d) => `流失率 ${d.dropOffRate}%`);

    annotations
      .append('text')
      .attr('x', 10)
      .attr('y', 14)
      .attr('fill', '#ef4444')
      .attr('font-size', '12px')
      .attr('font-weight', '600')
      .text(function (d, i) {
        const prevCount = data.steps[i].count;
        const lost = prevCount - d.count;
        return `-${lost.toLocaleString()} 人`;
      });
  }, [data, onStepClick]);

  return (
    <div className="bg-white rounded-xl border border-gray-200 p-6">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h3 className="text-lg font-semibold text-gray-800">转化漏斗分析</h3>
          <p className="text-sm text-gray-500 mt-1">
            总转化: <span className="font-semibold text-primary-600">{data.overallConversion}%</span>
            <span className="mx-2">·</span>
            起始用户: <span className="font-semibold text-gray-700">{data.totalUsers.toLocaleString()}</span>
          </p>
        </div>
        <div className="flex items-center gap-2 px-3 py-1.5 bg-primary-50 rounded-lg">
          <TrendingDown className="w-4 h-4 text-primary-600" />
          <span className="text-sm font-medium text-primary-700">漏斗视图</span>
        </div>
      </div>
      <svg ref={svgRef} className="w-full" />
      <div className="mt-6 grid grid-cols-3 gap-4">
        {data.steps.slice(0, 3).map((step, idx) => (
          <div key={step.id} className="bg-gray-50 rounded-lg p-4">
            <div className="flex items-center gap-2 text-sm text-gray-500 mb-1">
              {idx > 0 && <ArrowRight className="w-3 h-3" />}
              {step.name}
            </div>
            <div className="text-xl font-bold text-gray-800">{step.count.toLocaleString()}</div>
            <div className="text-xs text-gray-500 mt-1">
              转化率 {step.conversionRate}% · 上一步流失 {step.dropOffRate}%
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default FunnelChart;
