// apps/frontend/src/components/common/StatCard.tsx
import React from 'react';

interface StatCardProps {
  title: string;
  value: string | number;
  icon?: string;
  trend?: number;
  color?: 'blue' | 'green' | 'yellow' | 'red';
  onClick?: () => void;
}

const colorMap = {
  blue: 'bg-blue-50 text-blue-600',
  green: 'bg-green-50 text-green-600',
  yellow: 'bg-yellow-50 text-yellow-600',
  red: 'bg-red-50 text-red-600',
};

export function StatCard({ title, value, icon, trend, color = 'blue', onClick }: StatCardProps) {
  return (
    <div
      onClick={onClick}
      className={`bg-white rounded-lg shadow-sm p-5 ${onClick ? 'cursor-pointer hover:shadow-md transition-shadow' : ''}`}
    >
      <div className="flex items-start justify-between">
        <div>
          <p className="text-sm text-gray-500 mb-1">{title}</p>
          <p className="text-2xl font-bold text-gray-800">{value}</p>
          {trend !== undefined && (
            <p className={`text-sm mt-1 ${trend >= 0 ? 'text-green-500' : 'text-red-500'}`}>
              {trend >= 0 ? '↑' : '↓'} {Math.abs(trend)}%
            </p>
          )}
        </div>
        {icon && (
          <div className={`w-12 h-12 rounded-lg flex items-center justify-center text-2xl ${colorMap[color]}`}>
            {icon}
          </div>
        )}
      </div>
    </div>
  );
}

// src/components/charts/StatCard.vue
<script setup lang="ts">
import { computed } from 'vue';
import { TrendingUp, TrendingDown } from 'lucide-vue-next';

const props = defineProps<{
  title: string;
  value: number | string;
  unit?: string;
  isPercentage?: boolean;
  trend?: number;
  icon?: any;
  color?: string;
}>();

const displayValue = computed(() => {
  if (typeof props.value === 'string') return props.value;
  if (props.isPercentage) return `${(props.value * 100).toFixed(1)}%`;
  return props.value.toLocaleString();
});

const trendColor = computed(() => {
  if (!props.trend) return 'text-slate-500';
  return props.trend > 0 ? 'text-green-600' : 'text-red-600';
});
</script>

<template>
  <div class="bg-white rounded-xl p-5 shadow-sm border border-slate-100 hover:shadow-md transition-shadow duration-300">
    <div class="flex items-start justify-between">
      <div>
        <p class="text-sm text-slate-500 font-medium">{{ title }}</p>
        <p class="text-3xl font-bold mt-2" :class="color || 'text-slate-800'">
          {{ displayValue }}
          <span v-if="unit" class="text-lg font-normal text-slate-500">{{ unit }}</span>
        </p>
        <div v-if="trend !== undefined" class="flex items-center gap-1 mt-2" :class="trendColor">
          <component :is="trend >= 0 ? TrendingUp : TrendingDown" class="w-4 h-4" />
          <span class="text-sm font-medium">{{ Math.abs(trend).toFixed(1) }}%</span>
          <span class="text-slate-500 text-xs">较上周</span>
        </div>
      </div>
      <div 
        v-if="icon" 
        class="w-12 h-12 rounded-xl flex items-center justify-center"
        :class="[color ? color.replace('text-', 'bg-').replace('800', '100') : 'bg-blue-100', color ? color.replace('text-', 'text-').replace('800', '600') : 'text-blue-600']"
      >
        <component :is="icon" class="w-6 h-6" />
      </div>
    </div>
  </div>
</template>
