// frontend/src/pages/login/index.tsx
import React, { useEffect } from 'react'
import { Form, Input, Button, Checkbox, Card, Typography, message } from 'antd'
import { UserOutlined, LockOutlined } from '@ant-design/icons'
import { useNavigate } from 'react-router-dom'
import { useUserStore } from '@/store'
import type { RoleCode } from '@/types'

const { Title } = Typography

interface LoginFormValues {
  username: string
  password: string
  remember: boolean
}

const Login: React.FC = () => {
  const [form] = Form.useForm<LoginFormValues>()
  const navigate = useNavigate()
  const { login, isLoading, isLoggedIn, user } = useUserStore()

  useEffect(() => {
    if (isLoggedIn && user) {
      const redirectPath = getRedirectPath(user.roles)
      navigate(redirectPath, { replace: true })
    }
  }, [isLoggedIn, user, navigate])

  const getRedirectPath = (roles: RoleCode[]): string => {
    const adminRoles: RoleCode[] = ['ADMIN', 'FINANCE_MANAGER', 'APPROVER']
    const hasAdminRole = roles.some(role => adminRoles.includes(role))
    return hasAdminRole ? '/admin/dashboard' : '/portal/apply'
  }

  const onFinish = async (values: LoginFormValues) => {
    try {
      const response = await login({
        username: values.username,
        password: values.password
      })
      message.success('登录成功')
      const redirectPath = getRedirectPath(response.user.roles)
      navigate(redirectPath, { replace: true })
    } catch (error) {
      console.error('Login failed:', error)
    }
  }

  const onFinishFailed = () => {
    message.error('请检查输入的用户名和密码')
  }

  return (
    <div style={{
      minHeight: '100vh',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      padding: 16
    }}>
      <Card
        style={{
          width: '100%',
          maxWidth: 400,
          boxShadow: '0 8px 32px rgba(0, 0, 0, 0.1)',
          borderRadius: 12
        }}
      >
        <div style={{ textAlign: 'center', marginBottom: 32 }}>
          <Title level={3} style={{ margin: 0, color: '#1890ff' }}>
            费用报销系统
          </Title>
          <p style={{ color: '#666', marginTop: 8 }}>请登录您的账户</p>
        </div>
        <Form
          form={form}
          name="login"
          initialValues={{ remember: true }}
          onFinish={onFinish}
          onFinishFailed={onFinishFailed}
          layout="vertical"
          size="large"
        >
          <Form.Item
            name="username"
            label="用户名"
            rules={[
              { required: true, message: '请输入用户名' },
              { min: 3, message: '用户名至少3个字符' }
            ]}
          >
            <Input
              prefix={<UserOutlined style={{ color: '#bfbfbf' }} />}
              placeholder="请输入用户名"
              autoComplete="username"
            />
          </Form.Item>
          <Form.Item
            name="password"
            label="密码"
            rules={[
              { required: true, message: '请输入密码' },
              { min: 6, message: '密码至少6个字符' }
            ]}
          >
            <Input.Password
              prefix={<LockOutlined style={{ color: '#bfbfbf' }} />}
              placeholder="请输入密码"
              autoComplete="current-password"
            />
          </Form.Item>
          <Form.Item name="remember" valuePropName="checked">
            <Checkbox>记住我</Checkbox>
          </Form.Item>
          <Form.Item style={{ marginBottom: 0 }}>
            <Button
              type="primary"
              htmlType="submit"
              loading={isLoading}
              block
              style={{ height: 44, fontSize: 16 }}
            >
              登录
            </Button>
          </Form.Item>
        </Form>
        <div style={{ textAlign: 'center', marginTop: 16, color: '#999', fontSize: 12 }}>
          <p>测试账号: applicant / applicant123 (申请人)</p>
          <p>测试账号: approver / approver123 (审批人)</p>
          <p>测试账号: admin / admin123 (管理员)</p>
        </div>
      </Card>
    </div>
  )
}

export default Login

// client/src/pages/Login.vue
<template>
  <div class="login-container">
    <div class="login-card">
      <div class="login-logo">
        <CarOutlined class="logo-icon" />
      </div>
      <h1 class="login-title">汽车维修管理系统</h1>
      <p class="login-subtitle">请登录您的账号</p>
      <a-form :model="form" @finish="handleLogin" layout="vertical">
        <a-form-item
          label="用户名"
          name="username"
          :rules="[{ required: true, message: '请输入用户名' }]"
        >
          <a-input
            v-model:value="form.username"
            size="large"
            placeholder="请输入用户名"
          >
            <template #prefix>
              <UserOutlined />
            </template>
          </a-input>
        </a-form-item>
        <a-form-item
          label="密码"
          name="password"
          :rules="[{ required: true, message: '请输入密码' }]"
        >
          <a-input-password
            v-model:value="form.password"
            size="large"
            placeholder="请输入密码"
          >
            <template #prefix>
              <LockOutlined />
            </template>
          </a-input-password>
        </a-form-item>
        <a-form-item>
          <a-checkbox v-model:checked="form.rememberMe">记住我</a-checkbox>
        </a-form-item>
        <a-button type="primary" html-type="submit" size="large" block :loading="loading">
          登录
        </a-button>
      </a-form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { reactive, ref, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { message } from 'ant-design-vue'
import { CarOutlined, UserOutlined, LockOutlined } from '@ant-design/icons-vue'
import { useUserStore } from '@/stores/user'

const route = useRoute()
const router = useRouter()
const userStore = useUserStore()

const form = reactive({
  username: '',
  password: '',
  rememberMe: false,
})

const loading = ref(false)

onMounted(() => {
  const savedUsername = localStorage.getItem('rememberedUsername')
  if (savedUsername) {
    form.username = savedUsername
    form.rememberMe = true
  }
})

const handleLogin = async () => {
  try {
    loading.value = true
    await userStore.login({ username: form.username, password: form.password })
    if (form.rememberMe) {
      localStorage.setItem('rememberedUsername', form.username)
    } else {
      localStorage.removeItem('rememberedUsername')
    }
    message.success('登录成功')
    const redirect = (route.query.redirect as string) || '/'
    router.push(redirect)
  } catch (error) {
    console.error('Login failed:', error)
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.login-container {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: linear-gradient(135deg, #165dff 0%, #0039cb 100%);
  padding: 24px;
}

.login-card {
  width: 100%;
  max-width: 400px;
  background: white;
  border-radius: 12px;
  padding: 48px 40px;
  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.2);
}

.login-logo {
  width: 64px;
  height: 64px;
  margin: 0 auto 16px;
  background: linear-gradient(135deg, #165dff 0%, #4080ff 100%);
  border-radius: 16px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.logo-icon {
  font-size: 32px;
  color: white;
}

.login-title {
  font-size: 28px;
  font-weight: 700;
  color: #1f1f1f;
  margin: 0 0 8px 0;
  text-align: center;
}

.login-subtitle {
  font-size: 14px;
  color: #8c8c8c;
  margin: 0 0 32px 0;
  text-align: center;
}
</style>
