// frontend/src/views/portal/MyApplications.vue
<template>
  <div>
    <div class="page-header">
      <h2 class="page-title">我的申请</h2>
      <el-button type="primary" @click="$router.push('/portal/applications/new')">
        <el-icon><Plus /></el-icon>新建申请
      </el-button>
    </div>

    <div class="card-shadow">
      <div class="filter-bar">
        <el-select v-model="filter.status" placeholder="全部状态" clearable style="width: 140px">
          <el-option
            v-for="(label, key) in ApplicationStatusLabel"
            :key="key"
            :label="label"
            :value="key"
          />
        </el-select>
        <el-date-picker
          v-model="dateRange"
          type="daterange"
          range-separator="至"
          start-placeholder="开始日期"
          end-placeholder="结束日期"
          value-format="YYYY-MM-DD"
        />
        <el-input v-model="filter.keyword" placeholder="搜索单号/用途" clearable style="width: 240px" />
        <el-button type="primary" @click="loadData">查询</el-button>
      </div>

      <el-table :data="list" v-loading="loading" stripe>
        <el-table-column prop="applicationNo" label="申请单号" width="180" />
        <el-table-column prop="applicantName" label="申请人" width="100" />
        <el-table-column prop="applicantDepartment" label="部门" width="120" />
        <el-table-column prop="purpose" label="用途" show-overflow-tooltip />
        <el-table-column label="试剂项" width="100">
          <template #default="{ row }">
            {{ row.items?.length || 0 }} 项
          </template>
        </el-table-column>
        <el-table-column label="状态" width="100">
          <template #default="{ row }">
            <el-tag :type="ApplicationStatusType[row.status] as any">
              {{ ApplicationStatusLabel[row.status] }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="createdAt" label="创建时间" width="180">
          <template #default="{ row }">{{ formatDate(row.createdAt) }}</template>
        </el-table-column>
        <el-table-column label="操作" width="200" fixed="right">
          <template #default="{ row }">
            <el-button link type="primary" @click="$router.push(`/portal/applications/${row._id}`)">详情</el-button>
            <el-button
              v-if="row.status === 'draft'"
              link
              type="primary"
              @click="handleSubmit(row)"
            >提交</el-button>
            <el-button
              v-if="['draft', 'pending'].includes(row.status)"
              link
              type="danger"
              @click="handleCancel(row)"
            >取消</el-button>
          </template>
        </el-table-column>
      </el-table>

      <el-pagination
        v-model:current-page="page"
        v-model:page-size="pageSize"
        :total="total"
        :page-sizes="[10, 20, 50, 100]"
        layout="total, sizes, prev, pager, next, jumper"
        style="margin-top: 16px; justify-content: flex-end"
        background
        @size-change="loadData"
        @current-change="loadData"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { applicationApi } from '@/api'
import { ApplicationStatusLabel, ApplicationStatusType, type Application } from '@/types'
import dayjs from 'dayjs'
import { Plus } from '@element-plus/icons-vue'

const loading = ref(false)
const list = ref<Application[]>([])
const total = ref(0)
const page = ref(1)
const pageSize = ref(20)
const dateRange = ref<string[]>([])

const filter = reactive({
  status: '',
  keyword: '',
})

function formatDate(d: string) {
  return dayjs(d).format('YYYY-MM-DD HH:mm')
}

async function loadData() {
  loading.value = true
  try {
    const params: any = {
      page: page.value,
      pageSize: pageSize.value,
    }
    if (filter.status) params.status = filter.status
    if (filter.keyword) params.keyword = filter.keyword
    if (dateRange.value?.length === 2) {
      params.startDate = dateRange.value[0]
      params.endDate = dateRange.value[1]
    }
    const res = await applicationApi.list(params)
    list.value = res.list
    total.value = res.total
  } finally {
    loading.value = false
  }
}

async function handleSubmit(row: Application) {
  try {
    await ElMessageBox.confirm(`确定提交申请 ${row.applicationNo}？`, '提示', { type: 'warning' })
    await applicationApi.submit(row._id)
    ElMessage.success('提交成功')
    loadData()
  } catch {}
}

async function handleCancel(row: Application) {
  try {
    await ElMessageBox.confirm(`确定取消申请 ${row.applicationNo}？`, '提示', { type: 'warning' })
    await applicationApi.cancel(row._id)
    ElMessage.success('已取消')
    loadData()
  } catch {}
}

onMounted(loadData)
</script>

// frontend/src/pages/portal/my-applications/index.tsx
import React, { useState, useEffect } from 'react'
import { Table, Tag, Button, Space, Card, Typography, Select, Input, Form } from 'antd'
import { EyeOutlined, PlusOutlined, SearchOutlined } from '@ant-design/icons'
import { useNavigate } from 'react-router-dom'
import { application } from '@/api'
import { formatDate, formatMoney } from '@/utils'
import type { ExpenseApplication, ApplicationStatus, PageParams } from '@/types'
import type { ColumnsType } from 'antd/es/table'

const { Title } = Typography
const { Option } = Select

const statusMap: Record<ApplicationStatus, { text: string; color: string }> = {
  DRAFT: { text: '草稿', color: 'default' },
  PENDING: { text: '审批中', color: 'processing' },
  APPROVED: { text: '已通过', color: 'success' },
  REJECTED: { text: '已拒绝', color: 'error' }
}

const MyApplications: React.FC = () => {
  const navigate = useNavigate()
  const [loading, setLoading] = useState(false)
  const [data, setData] = useState<ExpenseApplication[]>([])
  const [total, setTotal] = useState(0)
  const [pagination, setPagination] = useState<PageParams>({ page: 1, pageSize: 10 })
  const [status, setStatus] = useState<string>('')
  const [keyword, setKeyword] = useState('')

  const fetchData = async () => {
    setLoading(true)
    try {
      const params: PageParams & { status?: string; keyword?: string } = {
        ...pagination,
        ...(status ? { status } : {}),
        ...(keyword ? { keyword } : {})
      }
      const result = await application.list(params)
      setData(result.list)
      setTotal(result.total)
    } catch (error) {
      console.error('Fetch applications failed:', error)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchData()
  }, [pagination, status, keyword])

  const handleSearch = () => {
    setPagination(prev => ({ ...prev, page: 1 }))
  }

  const handleReset = () => {
    setStatus('')
    setKeyword('')
    setPagination({ page: 1, pageSize: 10 })
  }

  const handleTableChange = (page: number, pageSize: number) => {
    setPagination({ page, pageSize })
  }

  const columns: ColumnsType<ExpenseApplication> = [
    {
      title: '申请编号',
      dataIndex: 'applicationNo',
      key: 'applicationNo',
      width: 150,
      render: (text: string) => <span style={{ fontFamily: 'monospace' }}>{text}</span>
    },
    {
      title: '标题',
      dataIndex: 'title',
      key: 'title',
      ellipsis: true
    },
    {
      title: '费用类型',
      dataIndex: 'expenseType',
      key: 'expenseType',
      width: 100
    },
    {
      title: '金额',
      dataIndex: 'amount',
      key: 'amount',
      width: 120,
      render: (amount: number) => <span style={{ fontWeight: 'bold', color: '#1890ff' }}>{formatMoney(amount)}</span>
    },
    {
      title: '状态',
      dataIndex: 'status',
      key: 'status',
      width: 100,
      render: (status: ApplicationStatus) => {
        const { text, color } = statusMap[status] || { text: status, color: 'default' }
        return <Tag color={color as any}>{text}</Tag>
      }
    },
    {
      title: '当前节点',
      dataIndex: 'currentNodeName',
      key: 'currentNodeName',
      width: 120,
      render: (text?: string) => text || '-'
    },
    {
      title: '创建时间',
      dataIndex: 'createdAt',
      key: 'createdAt',
      width: 160,
      render: (date: string) => formatDate(date)
    },
    {
      title: '操作',
      key: 'action',
      width: 100,
      render: (_, record) => (
        <Space size="small">
          <Button
            type="link"
            size="small"
            icon={<EyeOutlined />}
            onClick={() => navigate(`/portal/application-detail/${record.id}`)}
          >
            详情
          </Button>
        </Space>
      )
    }
  ]

  return (
    <div>
      <Card style={{ marginBottom: 16 }}>
        <Form layout="inline">
          <Form.Item label="状态">
            <Select
              placeholder="全部状态"
              style={{ width: 150 }}
              value={status || undefined}
              onChange={value => setStatus(value || '')}
              allowClear
            >
              <Option value="DRAFT">草稿</Option>
              <Option value="PENDING">审批中</Option>
              <Option value="APPROVED">已通过</Option>
              <Option value="REJECTED">已拒绝</Option>
            </Select>
          </Form.Item>
          <Form.Item label="关键词">
            <Input
              placeholder="搜索标题/编号"
              style={{ width: 200 }}
              value={keyword}
              onChange={e => setKeyword(e.target.value)}
              onPressEnter={handleSearch}
            />
          </Form.Item>
          <Form.Item>
            <Space>
              <Button type="primary" icon={<SearchOutlined />} onClick={handleSearch}>
                搜索
              </Button>
              <Button onClick={handleReset}>重置</Button>
            </Space>
          </Form.Item>
        </Form>
      </Card>
      <Card>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
          <Title level={4} style={{ margin: 0 }}>我的申请</Title>
          <Button type="primary" icon={<PlusOutlined />} onClick={() => navigate('/portal/apply')}>
            新建申请
          </Button>
        </div>
        <Table
          rowKey="id"
          columns={columns}
          dataSource={data}
          loading={loading}
          pagination={{
            current: pagination.page,
            pageSize: pagination.pageSize,
            total,
            showSizeChanger: true,
            showQuickJumper: true,
            showTotal: (total) => `共 ${total} 条记录`,
            onChange: handleTableChange
          }}
        />
      </Card>
    </div>
  )
}

export default MyApplications
