// client/app/routes/users.tsx
import { useState, useEffect } from 'react';
import { useNavigate } from '@remix-run/react';
import AppLayout from '~/components/Layout';
import { userApi, storeApi } from '~/utils/api';
import { formatDate, getRoleName, getStatusTag } from '~/utils/format';

export default function Users() {
  const [list, setList] = useState<any[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [pageSize] = useState(10);
  const [role, setRole] = useState('');
  const [status, setStatus] = useState('');
  const [keyword, setKeyword] = useState('');
  const [storeId, setStoreId] = useState('');
  const [loading, setLoading] = useState(true);
  const [modalOpen, setModalOpen] = useState(false);
  const [permissionModalOpen, setPermissionModalOpen] = useState(false);
  const [editingItem, setEditingItem] = useState<any>(null);
  const [currentItem, setCurrentItem] = useState<any>(null);
  const [permissions, setPermissions] = useState<string[]>([]);
  const [stores, setStores] = useState<any[]>([]);
  const navigate = useNavigate();

  const [formData, setFormData] = useState({
    username: '',
    password: '',
    name: '',
    role: 'store_manager',
    store: '',
    email: '',
    phone: '',
    status: 'active',
    permissions: [] as string[]
  });

  useEffect(() => {
    const token = localStorage.getItem('token');
    if (!token) {
      navigate('/login');
      return;
    }
    loadStores();
    loadData();
  }, [navigate]);

  const loadStores = async () => {
    try {
      const res = await storeApi.getList({ pageSize: 100 });
      if (res.success) setStores(res.data?.list || []);
    } catch (err) { console.error(err); }
  };

  useEffect(() => { loadData(); }, [page, role, status, keyword, storeId]);

  const loadData = async () => {
    setLoading(true);
    try {
      const params: any = { page, pageSize };
      if (role) params.role = role;
      if (status) params.status = status;
      if (keyword) params.keyword = keyword;
      if (storeId) params.storeId = storeId;
      
      const res = await userApi.getList(params);
      if (res.success) {
        setList(res.data?.list || []);
        setTotal(res.data?.total || 0);
      }
    } catch (err) { console.error(err); }
    finally { setLoading(false); }
  };

  const handleAdd = () => {
    setEditingItem(null);
    setFormData({
      username: '',
      password: '',
      name: '',
      role: 'store_manager',
      store: '',
      email: '',
      phone: '',
      status: 'active',
      permissions: []
    });
    setModalOpen(true);
  };

  const handleEdit = (item: any) => {
    setEditingItem(item);
    setFormData({
      username: item.username,
      password: '',
      name: item.name,
      role: item.role,
      store: item.store?._id || item.store || '',
      email: item.email || '',
      phone: item.phone || '',
      status: item.status,
      permissions: item.permissions || []
    });
    setModalOpen(true);
  };

  const handlePermissions = (item: any) => {
    setCurrentItem(item);
    setPermissions(item.permissions || []);
    setPermissionModalOpen(true);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      let res;
      if (editingItem) {
        const { password, ...updateData } = formData;
        if (password) {
          (updateData as any).password = password;
        }
        res = await userApi.update(editingItem._id, updateData);
      } else {
        res = await userApi.create(formData);
      }
      
      if (res.success) {
        setModalOpen(false);
        loadData();
      } else { alert(res.message); }
    } catch (err) { alert('操作失败'); }
  };

  const handlePermissionSubmit = async () => {
    try {
      const res = await userApi.updatePermissions(currentItem._id, permissions);
      if (res.success) {
        setPermissionModalOpen(false);
        loadData();
      } else { alert(res.message); }
    } catch (err) { alert('操作失败'); }
  };

  const handleDelete = async (id: string) => {
    if (!confirm('确定删除此用户？')) return;
    try {
      const res = await userApi.delete(id);
      if (res.success) loadData();
      else alert(res.message);
    } catch (err) { alert('删除失败'); }
  };

  const togglePermission = (perm: string) => {
    if (permissions.includes(perm)) {
      setPermissions(permissions.filter(p => p !== perm));
    } else {
      setPermissions([...permissions, perm]);
    }
  };

  const totalPages = Math.ceil(total / pageSize);

  const roleOptions = [
    { value: 'admin', label: '系统管理员' },
    { value: 'manager', label: '区域经理' },
    { value: 'store_manager', label: '门店店长' },
    { value: 'staff', label: '普通员工' },
  ];

  const allPermissions = [
    { key: 'store:read', label: '门店查看' },
    { key: 'store:write', label: '门店编辑' },
    { key: 'user:read', label: '用户查看' },
    { key: 'user:write', label: '用户编辑' },
    { key: 'business:read', label: '营业数据查看' },
    { key: 'business:write', label: '营业数据编辑' },
    { key: 'anomaly:read', label: '异常查看' },
    { key: 'anomaly:write', label: '异常编辑' },
    { key: 'rectification:read', label: '整改任务查看' },
    { key: 'rectification:write', label: '整改任务编辑' },
    { key: 'inventory:read', label: '库存查看' },
    { key: 'inventory:write', label: '库存编辑' },
    { key: 'log:read', label: '日志查看' },
  ];

  return (
    <AppLayout>
      <div className="flex-between mb-20">
        <h2 className="page-title" style={{ margin: 0 }}>用户管理</h2>
        <button className="btn btn-primary" onClick={handleAdd}>+ 新增用户</button>
      </div>

      <div className="card">
        <div className="search-bar">
          <div className="form-group">
            <select className="form-select" value={role} onChange={(e) => setRole(e.target.value)}>
              <option value="">全部角色</option>
              {roleOptions.map(opt => (<option key={opt.value} value={opt.value}>{opt.label}</option>))}
            </select>
          </div>
          <div className="form-group">
            <select className="form-select" value={status} onChange={(e) => setStatus(e.target.value)}>
              <option value="">全部状态</option>
              <option value="active">启用</option>
              <option value="inactive">禁用</option>
            </select>
          </div>
          <div className="form-group">
            <select className="form-select" value={storeId} onChange={(e) => setStoreId(e.target.value)}>
              <option value="">全部门店</option>
              {stores.map(s => (<option key={s._id} value={s._id}>{s.name}</option>))}
            </select>
          </div>
          <div className="form-group">
            <input type="text" className="form-input" placeholder="搜索用户名/姓名"
              value={keyword} onChange={(e) => setKeyword(e.target.value)} />
          </div>
          <button className="btn btn-primary" onClick={() => { setPage(1); loadData(); }}>查询</button>
        </div>

        {loading ? (
          <div style={{ textAlign: 'center', padding: '40px' }}>加载中...</div>
        ) : (
          <>
            <table>
              <thead>
                <tr>
                  <th>用户名</th>
                  <th>姓名</th>
                  <th>角色</th>
                  <th>门店</th>
                  <th>手机号</th>
                  <th>状态</th>
                  <th>最后登录</th>
                  <th>操作</th>
                </tr>
              </thead>
              <tbody>
                {list.length === 0 ? (
                  <tr>
                    <td colSpan={8} style={{ textAlign: 'center', color: '#909399', padding: '40px' }}>暂无数据</td>
                  </tr>
                ) : (
                  list.map((item: any) => {
                    const statusTag = getStatusTag(item.status);
                    return (
                      <tr key={item._id}>
                        <td>{item.username}</td>
                        <td>{item.name}</td>
                        <td>{getRoleName(item.role)}</td>
                        <td>{item.store?.name || '-'}</td>
                        <td>{item.phone || '-'}</td>
                        <td><span className={`tag ${statusTag.type}`}>{statusTag.text}</span></td>
                        <td>{item.lastLoginAt ? formatDate(item.lastLoginAt) : '-'}</td>
                        <td>
                          <button className="btn btn-default btn-sm" onClick={() => handleEdit(item)}>编辑</button>
                          <button className="btn btn-warning btn-sm ml-8" onClick={() => handlePermissions(item)}>权限</button>
                          {item.role !== 'admin' && (
                            <button className="btn btn-danger btn-sm ml-8" onClick={() => handleDelete(item._id)}>删除</button>
                          )}
                        </td>
                      </tr>
                    );
                  })
                )}
              </tbody>
            </table>

            <div className="pagination">
              <button onClick={() => setPage(p => Math.max(1, p - 1))} disabled={page === 1}>上一页</button>
              {Array.from({ length: Math.min(totalPages, 5) }, (_, i) => i + 1).map(p => (
                <button key={p} className={page === p ? 'active' : ''} onClick={() => setPage(p)}>{p}</button>
              ))}
              <button onClick={() => setPage(p => Math.min(totalPages, p + 1))} disabled={page === totalPages}>下一页</button>
              <span style={{ marginLeft: '10px', color: '#909399' }}>共 {total} 条</span>
            </div>
          </>
        )}
      </div>

      {modalOpen && (
        <div className="modal-mask" onClick={() => setModalOpen(false)}>
          <div className="modal" onClick={e => e.stopPropagation()} style={{ minWidth: '550px' }}>
            <div className="modal-header">
              <span className="modal-title">{editingItem ? '编辑用户' : '新增用户'}</span>
              <span className="modal-close" onClick={() => setModalOpen(false)}>×</span>
            </div>
            <form onSubmit={handleSubmit}>
              <div className="modal-body">
                <div className="form-row">
                  <div className="form-group">
                    <label className="form-label">用户名 *</label>
                    <input type="text" className="form-input" value={formData.username}
                      onChange={(e) => setFormData({ ...formData, username: e.target.value })}
                      required disabled={!!editingItem} />
                  </div>
                  <div className="form-group">
                    <label className="form-label">{editingItem ? '新密码 (留空不修改)' : '密码 *'}</label>
                    <input type="password" className="form-input" value={formData.password}
                      onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                      required={!editingItem} />
                  </div>
                </div>
                <div className="form-row">
                  <div className="form-group">
                    <label className="form-label">姓名 *</label>
                    <input type="text" className="form-input" value={formData.name}
                      onChange={(e) => setFormData({ ...formData, name: e.target.value })} required />
                  </div>
                  <div className="form-group">
                    <label className="form-label">角色</label>
                    <select className="form-select" value={formData.role}
                      onChange={(e) => setFormData({ ...formData, role: e.target.value })}>
                      {roleOptions.map(opt => (<option key={opt.value} value={opt.value}>{opt.label}</option>))}
                    </select>
                  </div>
                </div>
                <div className="form-row">
                  <div className="form-group">
                    <label className="form-label">所属门店</label>
                    <select className="form-select" value={formData.store}
                      onChange={(e) => setFormData({ ...formData, store: e.target.value })}>
                      <option value="">请选择门店</option>
                      {stores.map(s => (<option key={s._id} value={s._id}>{s.name}</option>))}
                    </select>
                  </div>
                  <div className="form-group">
                    <label className="form-label">手机号</label>
                    <input type="text" className="form-input" value={formData.phone}
                      onChange={(e) => setFormData({ ...formData, phone: e.target.value })} />
                  </div>
                </div>
                <div className="form-group">
                  <label className="form-label">邮箱</label>
                  <input type="email" className="form-input" value={formData.email}
                    onChange={(e) => setFormData({ ...formData, email: e.target.value })} />
                </div>
                <div className="form-group">
                  <label className="form-label">状态</label>
                  <select className="form-select" value={formData.status}
                    onChange={(e) => setFormData({ ...formData, status: e.target.value })}>
                    <option value="active">启用</option>
                    <option value="inactive">禁用</option>
                  </select>
                </div>
              </div>
              <div className="modal-footer">
                <button type="button" className="btn btn-default" onClick={() => setModalOpen(false)}>取消</button>
                <button type="submit" className="btn btn-primary ml-8">确定</button>
              </div>
            </form>
          </div>
        </div>
      )}

      {permissionModalOpen && currentItem && (
        <div className="modal-mask" onClick={() => setPermissionModalOpen(false)}>
          <div className="modal" onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <span className="modal-title">用户权限 - {currentItem.name}</span>
              <span className="modal-close" onClick={() => setPermissionModalOpen(false)}>×</span>
            </div>
            <div className="modal-body">
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '10px' }}>
                {allPermissions.map(perm => (
                  <label key={perm.key} style={{ display: 'flex', alignItems: 'center', gap: '6px', cursor: 'pointer' }}>
                    <input
                      type="checkbox"
                      checked={permissions.includes(perm.key)}
                      onChange={() => togglePermission(perm.key)}
                    />
                    {perm.label}
                  </label>
                ))}
              </div>
            </div>
            <div className="modal-footer">
              <button type="button" className="btn btn-default" onClick={() => setPermissionModalOpen(false)}>取消</button>
              <button className="btn btn-primary ml-8" onClick={handlePermissionSubmit}>保存</button>
            </div>
          </div>
        </div>
      )}
    </AppLayout>
  );
}

// frontend/pages/admin/users.vue
<template>
  <MainLayout>
    <div class="admin-users-page">
      <n-card :bordered="false">
        <div class="filter-section">
          <n-form inline :model="queryForm">
            <n-form-item label="关键词">
              <n-input
                v-model:value="queryForm.keyword"
                placeholder="用户名/邮箱/姓名"
                clearable
                style="width: 200px"
              />
            </n-form-item>
            <n-form-item label="状态">
              <n-select
                v-model:value="queryForm.status"
                placeholder="请选择"
                clearable
                style="width: 130px"
                :options="[
                  { label: '启用', value: 'active' },
                  { label: '禁用', value: 'inactive' },
                ]"
              />
            </n-form-item>
            <n-form-item>
              <n-space>
                <n-button type="primary" @click="handleSearch">查询</n-button>
                <n-button @click="handleReset">重置</n-button>
              </n-space>
            </n-form-item>
          </n-form>
        </div>

        <div class="table-toolbar">
          <div class="toolbar-left">
            <n-button type="primary" @click="handleCreate">新增用户</n-button>
          </div>
          <div class="toolbar-right">
            <n-button @click="loadData">刷新</n-button>
          </div>
        </div>

        <n-spin :show="loading">
          <n-data-table
            :columns="columns"
            :data="tableData"
            :pagination="pagination"
            :bordered="false"
            @update:page="handlePageChange"
            @update:page-size="handlePageSizeChange"
          />
        </n-spin>
      </n-card>

      <n-modal
        v-model:show="showModal"
        preset="card"
        :title="isEdit ? '编辑用户' : '新增用户'"
        style="width: 500px"
      >
        <n-form ref="formRef" :model="formData" :rules="formRules" label-placement="left" label-width="100px">
          <n-form-item label="用户名" path="username">
            <n-input v-model:value="formData.username" />
          </n-form-item>
          <n-form-item v-if="!isEdit" label="密码" path="password">
            <n-input v-model:value="formData.password" type="password" />
          </n-form-item>
          <n-form-item label="邮箱" path="email">
            <n-input v-model:value="formData.email" />
          </n-form-item>
          <n-form-item label="姓名" path="full_name">
            <n-input v-model:value="formData.full_name" />
          </n-form-item>
          <n-form-item label="手机号" path="phone">
            <n-input v-model:value="formData.phone" />
          </n-form-item>
          <n-form-item label="角色" path="role_ids">
            <n-select
              v-model:value="formData.role_ids"
              multiple
              :options="roleOptions"
            />
          </n-form-item>
          <n-form-item label="状态" path="is_active">
            <n-switch v-model:value="formData.is_active" />
          </n-form-item>
        </n-form>
        <template #footer>
          <n-space justify="end">
            <n-button @click="showModal = false">取消</n-button>
            <n-button type="primary" :loading="submitting" @click="handleSubmit">确定</n-button>
          </n-space>
        </template>
      </n-modal>
    </div>
  </MainLayout>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted, h } from 'vue'
import type { FormInst, FormRules, DataTableColumns } from 'naive-ui'
import MainLayout from '~/components/layout/MainLayout.vue'
import { getUserList, createUser, updateUser, deleteUser, getRoles } from '~/api/system'
import { useMessageUtil, useDialogUtil } from '~/composables/useMessage'

const { success, error } = useMessageUtil()
const { confirm } = useDialogUtil()

const loading = ref(false)
const tableData = ref<any[]>([])
const pagination = reactive({
  page: 1,
  pageSize: 20,
  total: 0,
  showSizePicker: true,
  pageSizes: [10, 20, 50, 100],
})

const queryForm = reactive({
  keyword: '',
  status: '',
})

const showModal = ref(false)
const isEdit = ref(false)
const submitting = ref(false)
const formRef = ref<FormInst | null>(null)
const editingId = ref<number | null>(null)

const formData = reactive<any>({
  username: '',
  password: '',
  email: '',
  full_name: '',
  phone: '',
  role_ids: [],
  is_active: true,
})

const roleOptions = ref<{ label: string; value: number }[]>([])

const formRules: FormRules = {
  username: [{ required: true, message: '请输入用户名', trigger: 'blur' }],
  password: [{ required: true, message: '请输入密码', trigger: 'blur' }],
  email: [{ required: true, message: '请输入邮箱', trigger: 'blur', type: 'email' }],
}

const columns: DataTableColumns = [
  { title: 'ID', key: 'id', width: 60 },
  { title: '用户名', key: 'username', width: 120 },
  { title: '邮箱', key: 'email', width: 200 },
  { title: '姓名', key: 'full_name', width: 100 },
  { title: '手机号', key: 'phone', width: 130 },
  {
    title: '角色',
    key: 'roles',
    width: 180,
    render: (row: any) => row.roles?.map((r: any) => r.name).join(', ') || '-',
  },
  {
    title: '状态',
    key: 'is_active',
    width: 100,
    render: (row: any) => h('n-tag', { type: row.is_active ? 'success' : 'error' }, () => row.is_active ? '启用' : '禁用'),
  },
  { title: '创建时间', key: 'created_at', width: 170 },
  {
    title: '操作',
    key: 'actions',
    width: 150,
    render: (row: any) => h('n-space', null, () => [
      h('n-button', { size: 'small', onClick: () => handleEdit(row) }, () => '编辑'),
      h('n-button', { size: 'small', type: 'error', onClick: () => handleDelete(row.id) }, () => '删除'),
    ]),
  },
]

async function loadData() {
  loading.value = true
  try {
    const params: any = {
      page: pagination.page,
      page_size: pagination.pageSize,
      ...queryForm,
    }
    const res = await getUserList(params)
    if (res.code === 200) {
      tableData.value = res.data.items
      pagination.total = res.data.total
    }
  } catch (e: any) {
    error(e.message || '加载失败')
  } finally {
    loading.value = false
  }
}

async function loadRoles() {
  try {
    const res = await getRoles()
    if (res.code === 200) {
      roleOptions.value = res.data.map((r: any) => ({ label: r.name, value: r.id }))
    }
  } catch (e) {
    console.error('加载角色失败', e)
  }
}

function handleSearch() {
  pagination.page = 1
  loadData()
}

function handleReset() {
  queryForm.keyword = ''
  queryForm.status = ''
  pagination.page = 1
  loadData()
}

function handlePageChange(page: number) {
  pagination.page = page
  loadData()
}

function handlePageSizeChange(pageSize: number) {
  pagination.pageSize = pageSize
  pagination.page = 1
  loadData()
}

function handleCreate() {
  isEdit.value = false
  editingId.value = null
  Object.assign(formData, {
    username: '',
    password: '',
    email: '',
    full_name: '',
    phone: '',
    role_ids: [],
    is_active: true,
  })
  showModal.value = true
}

function handleEdit(row: any) {
  isEdit.value = true
  editingId.value = row.id
  Object.assign(formData, {
    username: row.username,
    email: row.email,
    full_name: row.full_name,
    phone: row.phone,
    role_ids: row.roles?.map((r: any) => r.id) || [],
    is_active: row.is_active,
  })
  showModal.value = true
}

async function handleSubmit() {
  if (!formRef.value) return
  if (!isEdit.value) {
    const valid = await formRef.value.validate().catch(() => false)
    if (!valid) return
  }

  submitting.value = true
  try {
    if (isEdit.value && editingId.value) {
      const data: any = { ...formData }
      delete data.password
      await updateUser(editingId.value, data)
      success('更新成功')
    } else {
      await createUser(formData)
      success('创建成功')
    }
    showModal.value = false
    loadData()
  } catch (e: any) {
    error(e.message || '操作失败')
  } finally {
    submitting.value = false
  }
}

function handleDelete(id: number) {
  confirm('确认删除', '确定要删除这个用户吗？', async () => {
    try {
      await deleteUser(id)
      success('删除成功')
      loadData()
    } catch (e: any) {
      error(e.message || '删除失败')
    }
  })
}

onMounted(() => {
  loadData()
  loadRoles()
})
</script>

<style scoped>
.admin-users-page {
  padding: 0;
}

.filter-section {
  margin-bottom: 16px;
  padding: 16px;
  background: #fafafa;
  border-radius: 8px;
}

.table-toolbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 16px;
}
</style>
