// src/lib/components/Toast.svelte
<script lang="ts">
	import { toastStore } from '$lib/stores';
	import { CheckCircle, XCircle, AlertCircle, Info, X } from 'lucide-svelte';

	const iconMap = {
		success: CheckCircle,
		error: XCircle,
		warning: AlertCircle,
		info: Info
	};

	const colorMap = {
		success: 'bg-green-50 text-green-800 border-green-200',
		error: 'bg-red-50 text-red-800 border-red-200',
		warning: 'bg-yellow-50 text-yellow-800 border-yellow-200',
		info: 'bg-blue-50 text-blue-800 border-blue-200'
	};

	const iconColorMap = {
		success: 'text-green-500',
		error: 'text-red-500',
		warning: 'text-yellow-500',
		info: 'text-blue-500'
	};
</script>

{#if $toastStore}
	<div class="fixed top-4 right-4 z-50 animate-pulse">
		<div class="flex items-center gap-3 px-4 py-3 rounded-lg border shadow-lg {colorMap[$toastStore.type]}">
			<svelte:component
				this={iconMap[$toastStore.type]}
				class="w-5 h-5 flex-shrink-0 {iconColorMap[$toastStore.type]}"
			/>
			<p class="text-sm font-medium">{$toastStore.message}</p>
			<button on:click={() => ($toastStore = null)} class="ml-2">
				<X class="w-4 h-4" />
			</button>
		</div>
	</div>
{/if}

// packages/web/src/components/Toast.tsx
import { useApp } from '../store/app';
import { CheckCircle2, XCircle, Info, X } from 'lucide-react';
import { useEffect } from 'react';

export default function Toast() {
  const toastMsg = useApp((s) => s.toastMsg);
  const clearToast = useApp((s) => s.clearToast);

  useEffect(() => {
    if (toastMsg) {
      const t = setTimeout(clearToast, 3000);
      return () => clearTimeout(t);
    }
  }, [toastMsg]);

  if (!toastMsg) return null;
  const cfg = {
    success: { icon: CheckCircle2, bg: 'bg-primary-600' },
    error: { icon: XCircle, bg: 'bg-danger-600' },
    info: { icon: Info, bg: 'bg-slate-700' },
  }[toastMsg.type];
  const Icon = cfg.icon;

  return (
    <div className="fixed right-6 top-6 z-[100] animate-[fadeIn_.2s_ease-out]">
      <div className={`flex items-center gap-3 rounded-lg ${cfg.bg} px-4 py-3 text-white shadow-xl`}>
        <Icon size={18} />
        <span className="text-sm">{toastMsg.message}</span>
        <button onClick={clearToast} className="ml-2 text-white/70 hover:text-white">
          <X size={16} />
        </button>
      </div>
    </div>
  );
}
