// src/routes/login/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { userStore, showToast } from '$lib/stores';
	import { Truck, Lock, User } from 'lucide-svelte';

	let username = 'admin';
	let password = 'admin123';
	let loading = false;

	async function handleLogin(e: Event) {
		e.preventDefault();
		loading = true;

		setTimeout(() => {
			userStore.set({
				id: 'u001',
				username: 'admin',
				role: 'admin',
				fullName: '运营管理员',
				email: 'admin@coldchain.com',
				isActive: true,
				createdAt: new Date()
			});
			showToast('登录成功，欢迎使用冷链温控追踪分析系统', 'success');
			loading = false;
			goto('/dashboard');
		}, 800);
	}
</script>

<div class="min-h-screen bg-gradient-to-br from-primary-500 via-primary-600 to-primary-800 flex items-center justify-center p-4">
	<div class="w-full max-w-md">
		<div class="bg-white rounded-2xl shadow-2xl overflow-hidden">
			<div class="bg-primary-500 px-8 py-10 text-center">
				<div class="w-16 h-16 bg-white/20 rounded-2xl flex items-center justify-center mx-auto mb-4">
					<Truck class="w-8 h-8 text-white" />
				</div>
				<h1 class="text-2xl font-bold text-white">冷链温控追踪分析系统</h1>
				<p class="text-primary-100 mt-2">Cold Chain Temperature Tracking Analytics</p>
			</div>

			<div class="p-8">
				<form on:submit={handleLogin} class="space-y-5">
					<div>
						<label class="block text-sm font-medium text-slate-700 mb-2">用户名</label>
						<div class="relative">
							<User class="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400" />
							<input
								type="text"
								class="input pl-10"
								placeholder="请输入用户名"
								bind:value={username}
								required
							/>
						</div>
					</div>

					<div>
						<label class="block text-sm font-medium text-slate-700 mb-2">密码</label>
						<div class="relative">
							<Lock class="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400" />
							<input
								type="password"
								class="input pl-10"
								placeholder="请输入密码"
								bind:value={password}
								required
							/>
						</div>
					</div>

					<button
						type="submit"
						class="w-full btn btn-primary py-3"
						disabled={loading}
					>
						{#if loading}
							<span class="inline-flex items-center gap-2">
								<svg class="animate-spin w-4 h-4" fill="none" viewBox="0 0 24 24">
									<circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" />
									<path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
								</svg>
								登录中...
							</span>
						{:else}
							登录系统
						{/if}
					</button>
				</form>

				<p class="text-center text-xs text-slate-400 mt-6">
					演示账号: admin / admin123
				</p>
			</div>
		</div>

		<p class="text-center text-primary-200 text-xs mt-6">
			Cold Chain Analytics Platform © 2024
		</p>
	</div>
</div>

// src/app/login/page.tsx
'use client';

import { useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { Package, Eye, EyeOff } from 'lucide-react';

export default function LoginPage() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const supabase = createClient();

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError(null);

    try {
      const { error } = await supabase.auth.signInWithPassword({
        email,
        password,
      });

      if (error) throw error;
      window.location.href = '/dashboard';
    } catch (err: any) {
      setError(err.message || '登录失败，请检查邮箱和密码');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-amber-50 via-orange-50 to-amber-100">
      <div className="w-full max-w-md px-8">
        <div className="bg-white rounded-2xl shadow-xl p-8">
          <div className="text-center mb-8">
            <div className="inline-flex items-center justify-center h-16 w-16 rounded-2xl bg-gradient-to-br from-amber-500 to-orange-600 mb-4">
              <Package className="h-8 w-8 text-white" />
            </div>
            <h1 className="text-2xl font-bold text-gray-900">艺术馆展品借展管理系统</h1>
            <p className="text-gray-500 mt-2">请登录您的账户</p>
          </div>

          <form onSubmit={handleLogin} className="space-y-5">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                邮箱地址
              </label>
              <input
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="admin@museum.com"
                className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-amber-500 focus:border-amber-500 transition-all"
                required
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
              密码
            </label>
            <div className="relative">
              <input
                type={showPassword ? 'text' : 'password'}
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder="请输入密码"
                className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-amber-500 focus:border-amber-500 transition-all pr-12"
                required
              />
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gray-700"
              >
                {showPassword ? <EyeOff className="h-5 w-5" /> : <Eye className="h-5 w-5" />}
              </button>
            </div>
          </div>

          {error && (
            <div className="p-3 bg-red-50 border border-red-200 rounded-lg text-red-600 text-sm">
              {error}
            </div>
          )}

          <button
            type="submit"
            disabled={loading}
            className="w-full py-3 px-4 bg-gradient-to-r from-amber-500 to-orange-600 text-white font-medium rounded-lg hover:from-amber-600 hover:to-orange-700 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {loading ? '登录中...' : '登录'}
          </button>
        </form>

        <div className="mt-6 p-4 bg-amber-50 rounded-lg border border-amber-200">
          <p className="text-xs text-amber-800 font-medium mb-2">测试账号</p>
          <div className="text-xs text-amber-700 space-y-1">
            <p>管理员: admin@museum.com / admin123</p>
            <p>策展人: curator@museum.com / curator123</p>
            <p>登记员: registrar@museum.com / registrar123</p>
          </div>
        </div>
      </div>
    </div>
    </div>
  );
}
