// frontend/src/pages/Users.jsx
import React, { useState, useEffect } from 'react'
import {
  Table,
  Button,
  Space,
  Select,
  Modal,
  Form,
  Input,
  Tag,
  App,
  Popconfirm,
  Card,
  Switch,
  Avatar,
} from 'antd'
import {
  UserOutlined,
  PlusOutlined,
  EditOutlined,
  DeleteOutlined,
  SafetyOutlined,
  LockOutlined,
} from '@ant-design/icons'
import dayjs from 'dayjs'
import { authApi } from '../services/api'

const { Option } = Select

const Users = () => {
  const [data, setData] = useState([])
  const [loading, setLoading] = useState(false)
  const [modalVisible, setModalVisible] = useState(false)
  const [editingId, setEditingId] = useState(null)
  const [form] = Form.useForm()
  const { message, modal } = App.useApp()

  useEffect(() => {
    fetchData()
  }, [])

  const fetchData = async () => {
    try {
      setLoading(true)
      const res = await authApi.getUsers()
      if (res.code === 200) setData(res.data)
    } catch (e) {
      message.error('加载数据失败')
    } finally {
      setLoading(false)
    }
  }

  const handleAdd = () => {
    setEditingId(null)
    form.resetFields()
    form.setFieldsValue({
      role: 'WORKSHOP_DIRECTOR',
      status: 'ACTIVE',
    })
    setModalVisible(true)
  }

  const handleEdit = (record) => {
    setEditingId(record.id)
    form.setFieldsValue({
      username: record.username,
      name: record.name,
      email: record.email,
      phone: record.phone,
      role: record.role,
      status: record.status,
    })
    setModalVisible(true)
  }

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields()
      let res
      if (editingId) {
        res = await authApi.updateUser(editingId, values)
      } else {
        res = await authApi.createUser(values)
      }
      if (res.code === 200) {
        message.success(editingId ? '更新成功' : '创建成功')
        setModalVisible(false)
        fetchData()
      }
    } catch (e) {
      if (e.errorFields) return
      message.error(editingId ? '更新失败' : '创建失败')
    }
  }

  const handleDelete = async (id) => {
    try {
      const res = await authApi.deleteUser(id)
      if (res.code === 200) {
        message.success('删除成功')
        fetchData()
      }
    } catch (e) {
      message.error('删除失败')
    }
  }

  const handleResetPassword = (record) => {
    modal.confirm({
      title: '重置密码',
      content: `确定要重置用户 "${record.name}" 的密码为默认密码 "123456" 吗？`,
      onOk: async () => {
        message.success('密码已重置为 123456')
      },
    })
  }

  const handleToggleStatus = async (record, checked) => {
    try {
      const res = await authApi.updateUser(record.id, {
        status: checked ? 'ACTIVE' : 'INACTIVE',
      })
      if (res.code === 200) {
        message.success(checked ? '用户已启用' : '用户已禁用')
        fetchData()
      }
    } catch (e) {
      message.error('操作失败')
      fetchData()
    }
  }

  const getRoleColor = (role) => {
    return role === 'ADMIN' ? 'red' : 'blue'
  }

  const getRoleText = (role) => {
    return role === 'ADMIN' ? '管理员' : '车间主任'
  }

  const getStatusColor = (status) => {
    return status === 'ACTIVE' ? 'success' : 'error'
  }

  const getStatusText = (status) => {
    return status === 'ACTIVE' ? '启用' : '禁用'
  }

  const columns = [
    {
      title: '用户',
      dataIndex: 'name',
      key: 'name',
      render: (_, record) => (
        <Space>
          <Avatar size="small" icon={<UserOutlined />} />
          <span>{record.name}</span>
        </Space>
      ),
    },
    {
      title: '用户名',
      dataIndex: 'username',
      key: 'username',
    },
    {
      title: '角色',
      dataIndex: 'role',
      key: 'role',
      width: 120,
      render: (r) => (
        <Tag color={getRoleColor(r)} icon={<SafetyOutlined />}>
          {getRoleText(r)}
        </Tag>
      ),
    },
    {
      title: '邮箱',
      dataIndex: 'email',
      key: 'email',
      ellipsis: true,
    },
    {
      title: '电话',
      dataIndex: 'phone',
      key: 'phone',
    },
    {
      title: '状态',
      dataIndex: 'status',
      key: 'status',
      width: 100,
      render: (s, record) => (
        <Space>
          <Tag color={getStatusColor(s)}>{getStatusText(s)}</Tag>
          <Switch
            size="small"
            checked={s === 'ACTIVE'}
            onChange={(checked) => handleToggleStatus(record, checked)}
          />
        </Space>
      ),
    },
    {
      title: '创建时间',
      dataIndex: 'createdAt',
      key: 'createdAt',
      width: 160,
      render: (d) => dayjs(d).format('YYYY-MM-DD HH:mm'),
    },
    {
      title: '操作',
      key: 'action',
      width: 200,
      render: (_, record) => (
        <Space size="small">
          <Button
            type="link"
            size="small"
            icon={<EditOutlined />}
            onClick={() => handleEdit(record)}
          >
            编辑
          </Button>
          <Button
            type="link"
            size="small"
            icon={<LockOutlined />}
            onClick={() => handleResetPassword(record)}
          >
            重置密码
          </Button>
          {record.username !== 'admin' && (
            <Popconfirm
              title="确定删除"
              description="删除后无法恢复，确定要删除此用户吗？"
              onConfirm={() => handleDelete(record.id)}
              okText="确定"
              cancelText="取消"
            >
              <Button type="link" size="small" danger icon={<DeleteOutlined />}>
                删除
              </Button>
            </Popconfirm>
          )}
        </Space>
      ),
    },
  ]

  return (
    <div>
      <div className="page-header">
        <h1 className="page-title">
          <Space>
            <UserOutlined />
            用户管理
          </Space>
        </h1>
        <Space>
          <Button type="primary" icon={<PlusOutlined />} onClick={handleAdd}>
            新增用户
          </Button>
        </Space>
      </div>

      <Card>
        <Table
          columns={columns}
          dataSource={data}
          rowKey="id"
          loading={loading}
          pagination={{ pageSize: 10 }}
        />
      </Card>

      <Modal
        title={editingId ? '编辑用户' : '新增用户'}
        open={modalVisible}
        onCancel={() => setModalVisible(false)}
        footer={[
          <Button key="cancel" onClick={() => setModalVisible(false)}>
            取消
          </Button>,
          <Button key="ok" type="primary" onClick={handleSubmit}>
            {editingId ? '保存' : '创建'}
          </Button>,
        ]}
        width={500}
      >
        <Form form={form} layout="vertical">
          <Form.Item
            name="username"
            label="用户名"
            rules={[{ required: true, message: '请输入用户名' }]}
          >
            <Input placeholder="请输入用户名" disabled={!!editingId} />
          </Form.Item>
          {!editingId && (
            <Form.Item
              name="password"
              label="密码"
              rules={[
                { required: true, message: '请输入密码' },
                { min: 6, message: '密码至少6位' },
              ]}
            >
              <Input.Password placeholder="请输入密码（至少6位）" />
            </Form.Item>
          )}
          <Form.Item
            name="name"
            label="姓名"
            rules={[{ required: true, message: '请输入姓名' }]}
          >
            <Input placeholder="请输入姓名" />
          </Form.Item>
          <Form.Item
            name="role"
            label="角色"
            rules={[{ required: true, message: '请选择角色' }]}
          >
            <Select>
              <Option value="WORKSHOP_DIRECTOR">车间主任</Option>
              <Option value="ADMIN">管理员</Option>
            </Select>
          </Form.Item>
          <Form.Item name="email" label="邮箱">
            <Input placeholder="请输入邮箱" />
          </Form.Item>
          <Form.Item name="phone" label="电话">
            <Input placeholder="请输入电话" />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  )
}

export default Users

// frontend/pages/users.vue
<template>
  <div>
    <n-page-header title="用户管理" subtitle="管理系统用户和权限">
      <template #extra>
        <n-button type="primary" @click="showCreateModal = true">
          <template #icon><PlusOutlined /></template>
          新增用户
        </n-button>
      </template>
    </n-page-header>

    <n-card class="mt-4">
      <n-space class="mb-4">
        <n-input
          v-model:value="keyword"
          placeholder="搜索用户名/姓名/邮箱"
          style="width: 240px"
          clearable
        />
        <n-select
          v-model:value="filterRole"
          placeholder="角色筛选"
          :options="roleOptions"
          style="width: 160px"
          clearable
        />
        <n-button @click="loadData">
          <template #icon><SearchOutlined /></template>
          搜索
        </n-button>
      </n-space>

      <n-data-table
        :columns="columns"
        :data="users"
        :loading="loading"
        :bordered="false"
      />
    </n-card>

    <n-modal v-model:show="showCreateModal" preset="card" :title="isEdit ? '编辑用户' : '新增用户'" style="width: 500px">
      <n-form :model="formData" label-placement="top">
        <n-form-item label="用户名" required>
          <n-input v-model:value="formData.username" placeholder="请输入用户名" :disabled="isEdit" />
        </n-form-item>
        <n-grid :cols="2" :x-gap="16">
          <n-grid-item>
            <n-form-item label="邮箱" required>
              <n-input v-model:value="formData.email" placeholder="请输入邮箱" />
            </n-form-item>
          </n-grid-item>
          <n-grid-item>
            <n-form-item label="密码" v-if="!isEdit" required>
              <n-input v-model:value="formData.password" type="password" show-password-on="click" placeholder="请输入密码" />
            </n-form-item>
          </n-grid-item>
        </n-grid>
        <n-grid :cols="2" :x-gap="16">
          <n-grid-item>
            <n-form-item label="姓名">
              <n-input v-model:value="formData.full_name" placeholder="请输入姓名" />
            </n-form-item>
          </n-grid-item>
          <n-grid-item>
            <n-form-item label="部门">
              <n-input v-model:value="formData.department" placeholder="请输入部门" />
            </n-form-item>
          </n-grid-item>
        </n-grid>
        <n-form-item label="角色" required>
          <n-select
            v-model:value="formData.role"
            :options="roleOptions"
            placeholder="请选择角色"
          />
        </n-form-item>
        <n-form-item label="状态" v-if="isEdit">
          <n-switch v-model:value="formData.is_active" />
        </n-form-item>
      </n-form>
      <template #footer>
        <n-space justify="end">
          <n-button @click="showCreateModal = false">取消</n-button>
          <n-button type="primary" :loading="submitting" @click="handleSubmit">保存</n-button>
        </n-space>
      </template>
    </n-modal>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted, computed, h } from 'vue'
import {
  NPageHeader,
  NCard,
  NSpace,
  NInput,
  NSelect,
  NButton,
  NDataTable,
  NModal,
  NForm,
  NFormItem,
  NGrid,
  NGridItem,
  NSwitch,
  NTag,
  useMessage,
  useDialog,
} from 'naive-ui'
import { PlusOutlined, SearchOutlined } from '@vicons/antd'
import { useApiClient } from '~/composables/useApiClient'
import { useAuthStore } from '~/stores/auth'

definePageMeta({
  layout: 'admin',
  requiresAuth: true,
  requiresAdmin: true,
})

const message = useMessage()
const dialog = useDialog()
const api = useApiClient()
const authStore = useAuthStore()

const loading = ref(false)
const submitting = ref(false)
const users = ref<any[]>([])
const keyword = ref('')
const filterRole = ref<string | null>(null)
const showCreateModal = ref(false)
const editingId = ref<number | null>(null)

const isEdit = computed(() => editingId.value !== null)

const roleOptions = [
  { label: '普通用户', value: 'user' },
  { label: '管理员', value: 'admin' },
  { label: '安全负责人', value: 'security_officer' },
]

const roleLabel: Record<string, string> = {
  user: '普通用户',
  admin: '管理员',
  security_officer: '安全负责人',
}

const roleTagType: Record<string, string> = {
  user: 'default',
  admin: 'info',
  security_officer: 'error',
}

const formData = reactive<any>({
  username: '',
  email: '',
  password: '',
  full_name: '',
  department: '',
  role: 'user',
  is_active: true,
})

const columns = [
  { title: 'ID', key: 'id', width: 70 },
  { title: '用户名', key: 'username', width: 120 },
  { title: '姓名', key: 'full_name', width: 120 },
  { title: '邮箱', key: 'email', width: 180 },
  { title: '部门', key: 'department', width: 120 },
  {
    title: '角色',
    key: 'role',
    width: 120,
    render: (row: any) => h(NTag, { type: roleTagType[row.role] as any, size: 'small' }, { default: () => roleLabel[row.role] }),
  },
  {
    title: '状态',
    key: 'is_active',
    width: 80,
    render: (row: any) => h(NTag, { type: row.is_active ? 'success' : 'error', size: 'small' }, { default: () => row.is_active ? '启用' : '禁用' }),
  },
  {
    title: '操作',
    key: 'actions',
    width: 150,
    render: (row: any) => h(
      NSpace,
      { size: 'small' },
      {
        default: () => [
          h(NButton, { size: 'small', onClick: () => editUser(row) }, { default: () => '编辑' }),
          h(NButton, { size: 'small', type: 'error', onClick: () => deleteUser(row) }, { default: () => '删除' }),
        ],
      }
    ),
  },
]

const loadData = async () => {
  loading.value = true
  try {
    const params: any = { limit: 100 }
    if (keyword.value) params.keyword = keyword.value
    if (filterRole.value) params.role = filterRole.value

    const data = await api.users.list(params)
    users.value = data as any[]
  } catch (error: any) {
    message.error('加载失败')
  } finally {
    loading.value = false
  }
}

const resetForm = () => {
  formData.username = ''
  formData.email = ''
  formData.password = ''
  formData.full_name = ''
  formData.department = ''
  formData.role = 'user'
  formData.is_active = true
  editingId.value = null
}

const editUser = (row: any) => {
  Object.assign(formData, row)
  editingId.value = row.id
  showCreateModal.value = true
}

const handleSubmit = async () => {
  if (!formData.username || !formData.email) {
    message.error('请填写必填项')
    return
  }

  if (!isEdit.value && !formData.password) {
    message.error('请输入密码')
    return
  }

  if (formData.role === 'security_officer' && !authStore.isSecurityOfficer) {
    message.warning('只有安全负责人可以分配安全负责人角色')
    return
  }

  submitting.value = true
  try {
    if (isEdit.value) {
      const updateData = { ...formData }
      delete updateData.username
      delete updateData.password
      await api.users.update(editingId.value!, updateData)
      message.success('更新成功')
    } else {
      await api.users.create(formData)
      message.success('创建成功')
    }
    showCreateModal.value = false
    resetForm()
    loadData()
  } catch (error: any) {
    message.error(error.message || '操作失败')
  } finally {
    submitting.value = false
  }
}

const deleteUser = (row: any) => {
  if (row.id === authStore.user?.id) {
    message.warning('不能删除自己')
    return
  }

  dialog.warning({
    title: '确认删除',
    content: `确定要删除用户「${row.username}」吗？`,
    positiveText: '删除',
    negativeText: '取消',
    onPositiveClick: async () => {
      try {
        await api.users.remove(row.id)
        message.success('删除成功')
        loadData()
      } catch (error: any) {
        message.error('删除失败')
      }
    },
  })
}

onMounted(() => {
  loadData()
})
</script>
