// src/components/Layout/Sidebar.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import {
  Home, ClipboardList, RefreshCcw, TrendingUp, Calendar,
  BarChart3, Tags, FileText, Settings, ChevronLeft, ChevronRight,
} from 'lucide-vue-next'

const route = useRoute()
const router = useRouter()
const collapsed = ref(false)

const navItems = [
  { path: '/', label: '首页', icon: Home },
  { path: '/leads', label: '线索管理', icon: ClipboardList },
  { path: '/followup-plans', label: '回访计划', icon: RefreshCcw },
  { path: '/predictions', label: '转化预测', icon: TrendingUp },
  { path: '/followup-rules', label: '回访规则', icon: Calendar },
  { path: '/churn', label: '流失分析', icon: BarChart3 },
  { path: '/tags', label: '标签管理', icon: Tags },
  { path: '/reports', label: '报表中心', icon: FileText },
  { path: '/settings/dicts', label: '系统设置', icon: Settings },
]

const activeRoute = computed(() => route.path)

function navigateTo(path: string) {
  router.push(path)
}
</script>

<template>
  <aside
    class="fixed left-0 top-0 h-screen bg-slate-800 text-slate-300 flex flex-col transition-all duration-300 z-30"
    :class="collapsed ? 'w-16' : 'w-56'"
  >
    <div class="flex items-center h-16 px-4 border-b border-slate-700">
      <div v-if="!collapsed" class="flex items-center gap-2">
        <div class="w-8 h-8 rounded bg-amber-500 flex items-center justify-center">
          <Home class="w-4 h-4 text-white" />
        </div>
        <span class="text-white font-semibold text-sm whitespace-nowrap">装修线索回访</span>
      </div>
      <div v-else class="w-8 h-8 rounded bg-amber-500 flex items-center justify-center mx-auto">
        <Home class="w-4 h-4 text-white" />
      </div>
    </div>

    <nav class="flex-1 py-4 overflow-y-auto">
      <div
        v-for="item in navItems"
        :key="item.path"
        class="flex items-center gap-3 px-4 py-2.5 mx-2 rounded-md cursor-pointer transition-colors"
        :class="
          activeRoute === item.path || (item.path !== '/' && activeRoute.startsWith(item.path))
            ? 'bg-amber-500/20 text-amber-400'
            : 'hover:bg-slate-700 text-slate-400 hover:text-slate-200'
        "
        @click="navigateTo(item.path)"
      >
        <component :is="item.icon" class="w-5 h-5 flex-shrink-0" />
        <span v-if="!collapsed" class="text-sm whitespace-nowrap">{{ item.label }}</span>
      </div>
    </nav>

    <div class="p-2 border-t border-slate-700">
      <button
        class="w-full flex items-center justify-center py-2 rounded-md hover:bg-slate-700 transition-colors text-slate-400"
        @click="collapsed = !collapsed"
      >
        <component :is="collapsed ? ChevronRight : ChevronLeft" class="w-4 h-4" />
      </button>
    </div>
  </aside>
</template>

// qc-dashboard/src/components/sidebar.tsx
"use client"

import Link from "next/link"
import { usePathname } from "next/navigation"
import {
  LayoutDashboard,
  MessageSquare,
  BookOpen,
  AlertTriangle,
  ChevronLeft,
  ChevronRight,
} from "lucide-react"
import { useState } from "react"
import { cn } from "@/lib/utils"

const navItems = [
  { href: "/dashboard", label: "质检看板", icon: LayoutDashboard },
  { href: "/sessions", label: "会话质检", icon: MessageSquare },
  { href: "/knowledge", label: "知识库", icon: BookOpen },
  { href: "/issues", label: "问题追踪", icon: AlertTriangle },
]

export default function Sidebar() {
  const pathname = usePathname()
  const [collapsed, setCollapsed] = useState(false)

  return (
    <aside
      className={cn(
        "fixed left-0 top-0 z-40 flex h-screen flex-col bg-navy text-white transition-all duration-300",
        collapsed ? "w-[68px]" : "w-[220px]"
      )}
    >
      <div className="flex h-16 items-center justify-between px-4">
        {!collapsed && (
          <div className="flex items-center gap-2">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-amber text-sm font-bold text-navy-dark">
              质检
            </div>
            <span className="text-sm font-semibold tracking-wide">售后质检台</span>
          </div>
        )}
        <button
          onClick={() => setCollapsed(!collapsed)}
          className={cn(
            "flex h-7 w-7 items-center justify-center rounded-md transition-colors hover:bg-navy-light",
            collapsed && "mx-auto"
          )}
        >
          {collapsed ? <ChevronRight size={16} /> : <ChevronLeft size={16} />}
        </button>
      </div>

      <nav className="mt-4 flex flex-1 flex-col gap-1 px-3">
        {navItems.map((item) => {
          const isActive = pathname.startsWith(item.href)
          return (
            <Link
              key={item.href}
              href={item.href}
              className={cn(
                "flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium transition-colors",
                isActive
                  ? "bg-navy-light text-white shadow-sm"
                  : "text-slate-light hover:bg-navy-light/50 hover:text-white"
              )}
            >
              <item.icon size={18} className="shrink-0" />
              {!collapsed && <span>{item.label}</span>}
            </Link>
          )
        })}
      </nav>

      <div className="border-t border-navy-light p-3">
        <div className={cn("flex items-center gap-3", collapsed && "justify-center")}>
          <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-emerald text-xs font-bold text-white">
            周
          </div>
          {!collapsed && (
            <div className="min-w-0">
              <p className="truncate text-sm font-medium">质检员周明</p>
              <p className="truncate text-xs text-slate-light">质检专员</p>
            </div>
          )}
        </div>
      </div>
    </aside>
  )
}
