// league-manager/src/app/(auth)/register/page.tsx
'use client';

import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { Trophy, Mail, Lock, AlertCircle, UserPlus } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { Select } from '@/components/ui/Select';
import { useAuthStore } from '@/stores/auth';
import type { UserRole } from '@/types';

const roleDashboard: Record<UserRole, string> = {
  admin: '/admin',
  captain: '/captain',
  referee: '/referee',
  viewer: '/standings',
};

export default function RegisterPage() {
  const router = useRouter();
  const { hydrate } = useAuthStore();
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [role, setRole] = useState<UserRole>('captain');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    hydrate();
  }, [hydrate]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);
    try {
      const res = await fetch('/api/auth/register', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name, email, password, role }),
      });
      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || '注册失败');
      }
      router.push('/login');
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : '注册失败，请重试');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-[#1B5E20] via-[#2E7D32] to-[#1B5E20] px-4">
      <div className="w-full max-w-md">
        <div className="bg-white rounded-2xl shadow-2xl p-8">
          <div className="flex flex-col items-center mb-8">
            <div className="w-16 h-16 bg-[#1B5E20] rounded-full flex items-center justify-center mb-4">
              <UserPlus size={32} className="text-[#F9A825]" />
            </div>
            <h1 className="text-2xl font-bold text-[#1B5E20]">注册账号</h1>
            <p className="text-sm text-gray-500 mt-1">加入业余联赛管理系统</p>
          </div>

          {error && (
            <div className="flex items-center gap-2 bg-red-50 border border-red-200 text-[#D32F2F] px-4 py-3 rounded-lg mb-6 text-sm">
              <AlertCircle size={16} className="shrink-0" />
              {error}
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-4">
            <Input label="姓名" placeholder="请输入姓名" value={name} onChange={(e) => setName(e.target.value)} required />
            <div className="relative">
              <Mail size={18} className="absolute left-3 top-[38px] text-gray-400" />
              <Input label="邮箱" type="email" placeholder="请输入邮箱" value={email} onChange={(e) => setEmail(e.target.value)} required className="pl-10" />
            </div>
            <div className="relative">
              <Lock size={18} className="absolute left-3 top-[38px] text-gray-400" />
              <Input label="密码" type="password" placeholder="请输入密码" value={password} onChange={(e) => setPassword(e.target.value)} required minLength={6} className="pl-10" />
            </div>
            <Select
              label="角色"
              value={role}
              onChange={(e) => setRole(e.target.value as UserRole)}
              options={[
                { value: 'captain', label: '领队' },
                { value: 'referee', label: '裁判' },
              ]}
            />
            <Button type="submit" loading={loading} className="w-full" size="lg">
              注册
            </Button>
          </form>

          <div className="mt-6 text-center">
            <p className="text-sm text-gray-500">
              已有账号？{' '}
              <Link href="/login" className="text-[#1B5E20] font-medium hover:underline">
                立即登录
              </Link>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

// frontend/src/views/auth/Register.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-purple-50 to-amber-50 p-4">
    <div class="w-full max-w-md">
      <div class="card">
        <div class="card-body">
          <div class="text-center mb-8">
            <h1 class="text-2xl font-bold text-gray-800">注册账号</h1>
            <p class="text-gray-500 mt-2">开启您的手作之旅</p>
          </div>

          <form @submit.prevent="handleRegister">
            <div class="form-group">
              <label class="form-label">姓名</label>
              <input v-model="form.name" type="text" class="form-input" placeholder="请输入您的姓名" />
            </div>

            <div class="form-group">
              <label class="form-label">手机号</label>
              <input v-model="form.phone" type="tel" class="form-input" placeholder="请输入手机号" maxlength="11" />
            </div>

            <div class="form-group">
              <label class="form-label">邮箱（选填）</label>
              <input v-model="form.email" type="email" class="form-input" placeholder="请输入邮箱" />
            </div>

            <div class="form-group">
              <label class="form-label">密码</label>
              <input v-model="form.password" type="password" class="form-input" placeholder="请设置密码（至少6位）" />
            </div>

            <div class="form-group">
              <label class="form-label">确认密码</label>
              <input v-model="form.password_confirmation" type="password" class="form-input" placeholder="请再次输入密码" />
            </div>

            <div v-if="error" class="text-red-500 text-sm mb-4">{{ error }}</div>

            <button type="submit" class="btn btn-primary btn-lg btn-block" :disabled="loading">
              <span v-if="loading" class="loading-spinner inline-block w-4 h-4 mr-2"></span>
              {{ loading ? '注册中...' : '注册' }}
            </button>
          </form>

          <div class="mt-6 text-center">
            <p class="text-gray-500 text-sm">
              已有账号？
              <router-link to="/login" class="text-purple-600 font-medium">立即登录</router-link>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../../stores/auth'
import { UserRole } from '../../types'

const router = useRouter()
const authStore = useAuthStore()

const form = reactive({
  name: '',
  phone: '',
  email: '',
  password: '',
  password_confirmation: ''
})

const loading = ref(false)
const error = ref('')

const handleRegister = async () => {
  if (!form.name || !form.phone || !form.password) {
    error.value = '请填写完整信息'
    return
  }
  if (form.password.length < 6) {
    error.value = '密码至少6位'
    return
  }
  if (form.password !== form.password_confirmation) {
    error.value = '两次密码不一致'
    return
  }

  loading.value = true
  error.value = ''

  try {
    await authStore.register(form.name, form.phone, form.password, UserRole.STUDENT)
    router.push('/courses')
  } catch (e: any) {
    error.value = e.response?.data?.error || '注册失败，请重试'
  } finally {
    loading.value = false
  }
}
</script>
