// frontend/src/pages/Maintenance.tsx
import React, { useEffect, useState } from 'react';
import axios from 'axios';
import dayjs from 'dayjs';
import { useAuthStore } from '../store/authStore';

interface MaintenanceTicket {
  id: string;
  equipment_name: string;
  title: string;
  description: string;
  priority: 'low' | 'medium' | 'high' | 'critical';
  status: 'open' | 'in_progress' | 'resolved' | 'closed';
  reporter_name: string;
  reported_at: string;
  resolved_at?: string;
}

const priorityLabels: Record<string, string> = {
  low: '低',
  medium: '中',
  high: '高',
  critical: '紧急'
};

const priorityColors: Record<string, string> = {
  low: 'bg-gray-100 text-gray-600',
  medium: 'bg-blue-100 text-blue-600',
  high: 'bg-orange-100 text-orange-600',
  critical: 'bg-red-100 text-red-600'
};

const statusLabels: Record<string, string> = {
  open: '待处理',
  in_progress: '处理中',
  resolved: '已解决',
  closed: '已关闭'
};

export default function Maintenance() {
  const user = useAuthStore(state => state.user);
  const [tickets, setTickets] = useState<MaintenanceTicket[]>([]);
  const [loading, setLoading] = useState(true);
  const [showNewModal, setShowNewModal] = useState(false);
  const [newTicket, setNewTicket] = useState({
    equipment_id: '',
    title: '',
    description: '',
    priority: 'medium'
  });
  const [equipment, setEquipment] = useState<any[]>([]);

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    try {
      const [ticketsRes, equipRes] = await Promise.all([
        axios.get('/api/maintenance'),
        axios.get('/api/equipment')
      ]);
      setTickets(ticketsRes.data);
      setEquipment(equipRes.data);
    } catch (error) {
      console.error('获取数据失败:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleCreateTicket = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      await axios.post('/api/maintenance', newTicket);
      alert('工单创建成功！');
      setShowNewModal(false);
      setNewTicket({ equipment_id: '', title: '', description: '', priority: 'medium' });
      fetchData();
    } catch (error) {
      console.error('创建工单失败:', error);
      alert('创建失败，请重试');
    }
  };

  const handleUpdateStatus = async (id: string, status: string) => {
    try {
      await axios.patch(`/api/maintenance/${id}`, { status });
      fetchData();
    } catch (error) {
      console.error('更新状态失败:', error);
      alert('操作失败，请重试');
    }
  };

  if (loading) {
    return <div className="text-gray-500">加载中...</div>;
  }

  const openTickets = tickets.filter(t => ['open', 'in_progress'].includes(t.status));
  const resolvedTickets = tickets.filter(t => ['resolved', 'closed'].includes(t.status));

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-800">维修工单</h1>
          <p className="text-gray-500 mt-1">设备故障报修和维修进度跟踪</p>
        </div>
        <button onClick={() => setShowNewModal(true)} className="btn-primary">
          + 新建工单
        </button>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div className="card text-center">
          <p className="text-3xl font-bold text-red-600">
            {tickets.filter(t => t.priority === 'critical' && t.status === 'open').length}
          </p>
          <p className="text-sm text-gray-500 mt-1">紧急待处理</p>
        </div>
        <div className="card text-center">
          <p className="text-3xl font-bold text-orange-600">
            {tickets.filter(t => t.status === 'open').length}
          </p>
          <p className="text-sm text-gray-500 mt-1">待处理</p>
        </div>
        <div className="card text-center">
          <p className="text-3xl font-bold text-blue-600">
            {tickets.filter(t => t.status === 'in_progress').length}
          </p>
          <p className="text-sm text-gray-500 mt-1">处理中</p>
        </div>
        <div className="card text-center">
          <p className="text-3xl font-bold text-green-600">
            {tickets.filter(t => t.status === 'resolved').length}
          </p>
          <p className="text-sm text-gray-500 mt-1">本月已解决</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="space-y-4">
          <h2 className="font-semibold text-lg flex items-center gap-2">
            <span className="w-2 h-2 bg-red-500 rounded-full" />
            待处理工单 ({openTickets.length})
          </h2>
          <div className="space-y-3">
            {openTickets.map(ticket => (
              <div key={ticket.id} className="card">
                <div className="flex items-start justify-between mb-3">
                  <div>
                    <div className="flex items-center gap-2">
                      <h3 className="font-semibold">{ticket.title}</h3>
                      <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${priorityColors[ticket.priority]}`}>
                        {priorityLabels[ticket.priority]}
                      </span>
                    </div>
                    <p className="text-sm text-gray-500 mt-1">{ticket.equipment_name}</p>
                  </div>
                  <span className="text-xs text-gray-400">
                    {dayjs(ticket.reported_at).format('MM-DD HH:mm')}
                  </span>
                </div>
                <p className="text-sm text-gray-600 mb-3">{ticket.description}</p>
                <div className="flex items-center justify-between">
                  <span className="text-xs text-gray-500">报修人：{ticket.reporter_name}</span>
                  <div className="flex gap-2">
                    {ticket.status === 'open' && (
                      <button
                        onClick={() => handleUpdateStatus(ticket.id, 'in_progress')}
                        className="text-xs px-3 py-1 bg-blue-500 text-white rounded-lg hover:bg-blue-600"
                      >
                        开始处理
                      </button>
                    )}
                    {ticket.status === 'in_progress' && (
                      <button
                        onClick={() => handleUpdateStatus(ticket.id, 'resolved')}
                        className="text-xs px-3 py-1 bg-green-500 text-white rounded-lg hover:bg-green-600"
                      >
                        标记解决
                      </button>
                    )}
                  </div>
                </div>
              </div>
            ))}
            {openTickets.length === 0 && (
              <div className="card text-center py-8 text-gray-500">
                <p>暂无待处理工单 🎉</p>
              </div>
            )}
          </div>
        </div>

        <div className="space-y-4">
          <h2 className="font-semibold text-lg flex items-center gap-2">
            <span className="w-2 h-2 bg-green-500 rounded-full" />
            已完成工单 ({resolvedTickets.length})
          </h2>
          <div className="space-y-3 max-h-[600px] overflow-y-auto">
            {resolvedTickets.map(ticket => (
              <div key={ticket.id} className="card bg-gray-50 opacity-80">
                <div className="flex items-start justify-between mb-2">
                  <div>
                    <h3 className="font-medium text-gray-700">{ticket.title}</h3>
                    <p className="text-xs text-gray-500">{ticket.equipment_name}</p>
                  </div>
                  <span className="text-xs px-2 py-1 bg-green-100 text-green-700 rounded-full">
                    {statusLabels[ticket.status]}
                  </span>
                </div>
                <p className="text-xs text-gray-500">
                  完成于 {ticket.resolved_at ? dayjs(ticket.resolved_at).format('YYYY-MM-DD') : '-'}
                </p>
              </div>
            ))}
            {resolvedTickets.length === 0 && (
              <div className="card text-center py-8 text-gray-500">
                <p>暂无已完成工单</p>
              </div>
            )}
          </div>
        </div>
      </div>

      {showNewModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-2xl p-6 w-full max-w-lg">
            <h2 className="text-xl font-bold mb-4">新建维修工单</h2>
            <form onSubmit={handleCreateTicket} className="space-y-4">
              <div>
                <label className="label">选择设备 *</label>
                <select
                  value={newTicket.equipment_id}
                  onChange={(e) => setNewTicket({ ...newTicket, equipment_id: e.target.value })}
                  className="input-field"
                  required
                >
                  <option value="">请选择故障设备</option>
                  {equipment.map(item => (
                    <option key={item.id} value={item.id}>{item.name}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="label">故障标题 *</label>
                <input
                  type="text"
                  value={newTicket.title}
                  onChange={(e) => setNewTicket({ ...newTicket, title: e.target.value })}
                  placeholder="简要描述故障"
                  className="input-field"
                  required
                />
              </div>
              <div>
                <label className="label">优先级</label>
                <select
                  value={newTicket.priority}
                  onChange={(e) => setNewTicket({ ...newTicket, priority: e.target.value })}
                  className="input-field"
                >
                  <option value="low">低</option>
                  <option value="medium">中</option>
                  <option value="high">高</option>
                  <option value="critical">紧急</option>
                </select>
              </div>
              <div>
                <label className="label">详细描述</label>
                <textarea
                  value={newTicket.description}
                  onChange={(e) => setNewTicket({ ...newTicket, description: e.target.value })}
                  rows={3}
                  placeholder="详细描述故障现象..."
                  className="input-field resize-none"
                />
              </div>
              <div className="flex gap-3 pt-2">
                <button
                  type="button"
                  onClick={() => setShowNewModal(false)}
                  className="btn-secondary flex-1"
                >
                  取消
                </button>
                <button type="submit" className="btn-primary flex-1">
                  提交工单
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}

// frontend/src/routes/maintenance/index.tsx
import { component$, useStore, useTask$, $ } from "@builder.io/qwik";
import { useNavigate } from "@builder.io/qwik-city";
import Layout from "~/components/layout";
import apiClient from "~/utils/api";
import { useAuth } from "~/context/auth";
import dayjs from "dayjs";

interface MaintenanceTicket {
  id: string;
  equipment_id: string;
  equipment_name: string;
  reported_by: string;
  reporter_name: string;
  title: string;
  description: string;
  priority: 'low' | 'medium' | 'high' | 'critical';
  status: 'open' | 'in_progress' | 'resolved' | 'closed';
  cost: number;
  reported_at: string;
  resolved_at: string | null;
}

const priorityLabels: Record<string, string> = {
  low: '低',
  medium: '中',
  high: '高',
  critical: '紧急',
};

const priorityBadgeClass: Record<string, string> = {
  low: 'bg-gray-100 text-gray-800',
  medium: 'bg-blue-100 text-blue-800',
  high: 'bg-yellow-100 text-yellow-800',
  critical: 'bg-red-100 text-red-800',
};

const statusLabels: Record<string, string> = {
  open: '待处理',
  in_progress: '处理中',
  resolved: '已解决',
  closed: '已关闭',
};

export default component$(() => {
  const auth = useAuth();
  const nav = useNavigate();
  
  const state = useStore({
    tickets: [] as MaintenanceTicket[],
    equipments: [] as any[],
    loading: true,
    showCreateModal: false,
    newTicket: {
      equipment_id: '',
      title: '',
      description: '',
      priority: 'medium' as 'low' | 'medium' | 'high' | 'critical',
    },
  });

  const loadData = $(async () => {
    try {
      const [ticketRes, equipRes] = await Promise.all([
        apiClient.get('/maintenance'),
        apiClient.get('/equipment'),
      ]);
      state.tickets = ticketRes.data;
      state.equipments = equipRes.data;
      if (state.equipments.length > 0 && !state.newTicket.equipment_id) {
        state.newTicket.equipment_id = state.equipments[0].id;
      }
    } catch (e) {
      console.error('加载数据失败', e);
    } finally {
      state.loading = false;
    }
  });

  useTask$(async () => {
    if (!auth.isAuthenticated) {
      nav.navigate('/login');
      return;
    }
    await loadData();
  });

  const handleCreateTicket = $(async () => {
    try {
      await apiClient.post('/maintenance', state.newTicket);
      state.showCreateModal = false;
      state.newTicket = { equipment_id: state.equipments[0]?.id || '', title: '', description: '', priority: 'medium' };
      await loadData();
      alert('工单创建成功！高优先级工单将自动触发设备故障重排流程');
    } catch (e: any) {
      alert(e.response?.data?.error || '创建失败');
    }
  });

  return (
    <Layout title="维修工单">
      <div class="flex items-center justify-between mb-6">
        <div class="text-gray-500 text-sm">
          共 {state.tickets.length} 个工单
        </div>
        <button
          onClick$={() => state.showCreateModal = true}
          class="btn-primary flex items-center gap-2"
        >
          <span>+</span>
          新建工单
        </button>
      </div>

      {state.loading ? (
        <div class="card text-center text-gray-500">加载中...</div>
      ) : state.tickets.length === 0 ? (
        <div class="card text-center py-12">
          <div class="text-4xl mb-4">🔧</div>
          <p class="text-gray-500">暂无维修工单</p>
        </div>
      ) : (
        <div class="space-y-4">
          {state.tickets.map((ticket) => (
            <div key={ticket.id} class="card">
              <div class="flex items-start justify-between">
                <div class="flex-1">
                  <div class="flex items-center gap-3 mb-2">
                    <h3 class="font-bold text-gray-800">{ticket.title}</h3>
                    <span class={`badge ${priorityBadgeClass[ticket.priority]}`}>
                      {priorityLabels[ticket.priority]}
                    </span>
                    <span class="badge bg-gray-100 text-gray-600">
                      {statusLabels[ticket.status]}
                    </span>
                  </div>
                  
                  <p class="text-gray-600 text-sm mb-3">{ticket.description}</p>
                  
                  <div class="flex flex-wrap gap-4 text-xs text-gray-400">
                    <span>设备：{ticket.equipment_name}</span>
                    <span>上报人：{ticket.reporter_name}</span>
                    <span>上报时间：{dayjs(ticket.reported_at).format('YYYY-MM-DD HH:mm')}</span>
                    {ticket.cost > 0 && <span>费用：¥{ticket.cost}</span>}
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {state.showCreateModal && (
        <div class="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div class="bg-white rounded-xl p-6 w-full max-w-lg">
            <h3 class="text-lg font-bold text-gray-800 mb-6">新建维修工单</h3>
            
            <div class="space-y-4">
              <div>
                <label class="label">选择设备 *</label>
                <select
                  class="input-field"
                  value={state.newTicket.equipment_id}
                  onInput$={(e) => state.newTicket.equipment_id = (e.target as HTMLSelectElement).value}
                >
                  {state.equipments.map((eq) => (
                    <option key={eq.id} value={eq.id}>{eq.name}</option>
                  ))}
                </select>
              </div>

              <div>
                <label class="label">标题 *</label>
                <input
                  type="text"
                  class="input-field"
                  placeholder="简要描述故障"
                  value={state.newTicket.title}
                  onInput$={(e) => state.newTicket.title = (e.target as HTMLInputElement).value}
                />
              </div>

              <div>
                <label class="label">详细描述 *</label>
                <textarea
                  class="input-field"
                  rows={3}
                  placeholder="详细描述故障现象和情况"
                  value={state.newTicket.description}
                  onInput$={(e) => state.newTicket.description = (e.target as HTMLTextAreaElement).value}
                />
              </div>

              <div>
                <label class="label">优先级 *</label>
                <select
                  class="input-field"
                  value={state.newTicket.priority}
                  onInput$={(e) => state.newTicket.priority = (e.target as HTMLSelectElement).value as any}
                >
                  <option value="low">低</option>
                  <option value="medium">中</option>
                  <option value="high">高</option>
                  <option value="critical">紧急（将自动重排预约）</option>
                </select>
                <p class="text-xs text-yellow-600 mt-1">
                  选择"高"或"紧急"优先级时，系统将自动重排受影响的预约
                </p>
              </div>
            </div>

            <div class="flex gap-3 mt-6">
              <button
                onClick$={() => state.showCreateModal = false}
                class="flex-1 btn-secondary"
              >
                取消
              </button>
              <button
                onClick$={handleCreateTicket}
                class="flex-1 btn-primary"
              >
                创建工单
              </button>
            </div>
          </div>
        </div>
      )}
    </Layout>
  );
});
