// components/layout/Header.tsx
"use client";

import { Bell, Search, ChevronDown, Menu } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

interface HeaderProps {
  title: string;
  description?: string;
}

export function Header({ title, description }: HeaderProps) {
  return (
    <header className="h-16 border-b border-slate-200 bg-white/80 backdrop-blur-sm sticky top-0 z-40">
      <div className="flex h-full items-center justify-between px-6">
        <div className="flex items-center">
          <Button variant="ghost" size="icon" className="mr-4 md:hidden">
            <Menu className="h-5 w-5" />
          </Button>
          <div>
            <h1 className="text-xl font-semibold text-slate-800">{title}</h1>
            {description && (
              <p className="text-sm text-slate-500">{description}</p>
            )}
          </div>
        </div>

        <div className="flex items-center gap-4">
          <div className="relative w-80 hidden md:block">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
            <Input
              placeholder="全局搜索知识、工单..."
              className="pl-10 bg-slate-50 border-slate-200 focus:bg-white"
            />
          </div>

          <Button variant="ghost" size="icon" className="relative">
            <Bell className="h-5 w-5 text-slate-600" />
            <span className="absolute top-1.5 right-1.5 h-2 w-2 rounded-full bg-red-500" />
          </Button>

          <div className="flex items-center gap-2 pl-4 border-l border-slate-200">
            <div className="text-right hidden sm:block">
              <p className="text-sm font-medium text-slate-700">张经理</p>
              <p className="text-xs text-slate-500">MANAGER</p>
            </div>
            <div className="h-9 w-9 rounded-full bg-gradient-to-br from-[#1e3a5f] to-[#2d4a6f] flex items-center justify-center text-white text-sm font-semibold">
              张
            </div>
            <ChevronDown className="h-4 w-4 text-slate-400" />
          </div>
        </div>
      </div>
    </header>
  );
}

// src/components/layout/Header.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import { Bell, RefreshCw, User } from 'lucide-vue-next'
import { useEnergyStore } from '@/stores/energy'

const route = useRoute()
const energyStore = useEnergyStore()

const pageTitle = computed(() => route.meta?.title || '能耗分析平台')
const alertCount = computed(() => energyStore.openAlerts.length)

function refreshData() {
  energyStore.refreshData()
}
</script>

<template>
  <header class="h-16 bg-bg-secondary border-b border-slate-700/50 flex items-center justify-between px-6 sticky top-0 z-10">
    <div>
      <h2 class="font-display font-semibold text-xl text-white">{{ pageTitle }}</h2>
    </div>

    <div class="flex items-center gap-4">
      <button
        @click="refreshData"
        class="flex items-center gap-2 px-3 py-2 text-slate-400 hover:text-slate-200 hover:bg-bg-tertiary/50 rounded-lg transition-colors"
      >
        <RefreshCw class="w-4 h-4" />
        <span class="text-sm">刷新数据</span>
      </button>

      <button class="relative p-2 text-slate-400 hover:text-slate-200 hover:bg-bg-tertiary/50 rounded-lg transition-colors">
        <Bell class="w-5 h-5" />
        <span
          v-if="alertCount > 0"
          class="absolute -top-1 -right-1 w-5 h-5 bg-status-danger text-white text-xs font-bold rounded-full flex items-center justify-center"
        >
          {{ alertCount > 9 ? '9+' : alertCount }}
        </span>
      </button>

      <div class="flex items-center gap-3 pl-4 border-l border-slate-700/50">
        <div class="w-9 h-9 bg-brand-600 rounded-full flex items-center justify-center">
          <User class="w-5 h-5 text-white" />
        </div>
        <div class="hidden md:block">
          <p class="text-sm font-medium text-slate-200">能源管理员</p>
          <p class="text-xs text-slate-400">admin@building.com</p>
        </div>
      </div>
    </div>
  </header>
</template>
