// qc-dashboard/src/components/header.tsx
"use client"

import { usePathname } from "next/navigation"
import { Bell, Search } from "lucide-react"

const breadcrumbMap: Record<string, string> = {
  "/dashboard": "质检看板",
  "/sessions": "会话质检",
  "/knowledge": "知识库",
  "/issues": "问题追踪",
}

export default function Header() {
  const pathname = usePathname()

  const segments = pathname.split("/").filter(Boolean)
  const breadcrumbs = segments.map((seg, i) => {
    const path = "/" + segments.slice(0, i + 1).join("/")
    const label = breadcrumbMap[path] || seg
    return { path, label }
  })

  return (
    <header className="sticky top-0 z-30 flex h-14 items-center justify-between border-b border-slate-200 bg-white px-6">
      <div className="flex items-center gap-2 text-sm">
        <span className="text-slate-light">首页</span>
        {breadcrumbs.map((crumb, i) => (
          <span key={crumb.path} className="flex items-center gap-2">
            <span className="text-slate-light">/</span>
            <span className={i === breadcrumbs.length - 1 ? "font-medium text-navy" : "text-slate-light"}>
              {crumb.label}
            </span>
          </span>
        ))}
      </div>
      <div className="flex items-center gap-3">
        <button className="flex h-8 w-8 items-center justify-center rounded-md text-slate-light transition-colors hover:bg-surface hover:text-navy">
          <Search size={16} />
        </button>
        <button className="relative flex h-8 w-8 items-center justify-center rounded-md text-slate-light transition-colors hover:bg-surface hover:text-navy">
          <Bell size={16} />
          <span className="absolute right-1 top-1 h-2 w-2 rounded-full bg-danger" />
        </button>
      </div>
    </header>
  )
}

// src/components/Layout/Header.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { Bell, User, LogOut, ChevronRight } from 'lucide-vue-next'
import { useAuthStore } from '@/stores/auth'
import { ref } from 'vue'

const route = useRoute()
const router = useRouter()
const authStore = useAuthStore()
const showUserMenu = ref(false)

const breadcrumbs = computed(() => {
  const matched = route.matched.filter((r) => r.meta?.title)
  return matched.map((r) => ({ title: r.meta.title as string, path: r.path }))
})

function logout() {
  authStore.logout()
  router.push('/login')
}

const userName = computed(() => authStore.user?.name || authStore.user?.username || '用户')
</script>

<template>
  <header class="h-16 bg-white border-b border-slate-200 flex items-center justify-between px-6 sticky top-0 z-20">
    <div class="flex items-center gap-2 text-sm">
      <router-link to="/" class="text-slate-400 hover:text-slate-600">首页</router-link>
      <template v-for="(crumb, idx) in breadcrumbs" :key="idx">
        <ChevronRight class="w-4 h-4 text-slate-300" />
        <span
          :class="idx === breadcrumbs.length - 1 ? 'text-slate-700 font-medium' : 'text-slate-400'"
        >
          {{ crumb.title }}
        </span>
      </template>
    </div>

    <div class="flex items-center gap-4">
      <button class="relative p-2 rounded-md hover:bg-slate-100 transition-colors">
        <Bell class="w-5 h-5 text-slate-500" />
        <span class="absolute top-1 right-1 w-2 h-2 bg-red-500 rounded-full"></span>
      </button>

      <div class="relative">
        <button
          class="flex items-center gap-2 px-3 py-1.5 rounded-md hover:bg-slate-100 transition-colors"
          @click="showUserMenu = !showUserMenu"
        >
          <div class="w-7 h-7 rounded-full bg-slate-800 text-white flex items-center justify-center text-xs">
            {{ userName.charAt(0) }}
          </div>
          <span class="text-sm text-slate-700">{{ userName }}</span>
        </button>

        <div
          v-if="showUserMenu"
          class="absolute right-0 mt-2 w-48 bg-white rounded-md shadow-lg border border-slate-200 py-1 z-50"
          @mouseleave="showUserMenu = false"
        >
          <button
            class="w-full flex items-center gap-2 px-4 py-2 text-sm text-slate-700 hover:bg-slate-50"
            @click="showUserMenu = false"
          >
            <User class="w-4 h-4" />
            个人信息
          </button>
          <button
            class="w-full flex items-center gap-2 px-4 py-2 text-sm text-red-600 hover:bg-red-50"
            @click="logout"
          >
            <LogOut class="w-4 h-4" />
            退出登录
          </button>
        </div>
      </div>
    </div>
  </header>
</template>
