// src/components/sidebar.tsx
'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { cn } from '@/lib/utils';
import {
  LayoutDashboard,
  Briefcase,
  Clock,
  FileText,
  Receipt,
  DollarSign,
  BarChart3,
  Users,
  Settings,
  LogOut,
} from 'lucide-react';
import { useAuthStore } from '@/stores/useAuthStore';

const navigation = [
  { name: '仪表盘', href: '/dashboard', icon: LayoutDashboard },
  { name: '项目', href: '/projects', icon: Briefcase },
  { name: '工时记录', href: '/time-tracker', icon: Clock },
  { name: '报价单', href: '/quotes', icon: FileText },
  { name: '发票', href: '/invoices', icon: Receipt },
  { name: '收款', href: '/payments', icon: DollarSign },
  { name: '统计报表', href: '/reports', icon: BarChart3 },
  { name: '客户', href: '/clients', icon: Users },
];

export function Sidebar() {
  const pathname = usePathname();
  const user = useAuthStore((state) => state.user);
  const logout = useAuthStore((state) => state.logout);

  const handleLogout = () => {
    logout();
    window.location.href = '/login';
  };

  return (
    <div className="flex flex-col h-screen w-64 border-r bg-white">
      <div className="p-6 border-b">
        <Link href="/dashboard" className="flex items-center gap-2">
          <div className="w-10 h-10 rounded-xl bg-primary flex items-center justify-center">
            <Briefcase className="w-5 h-5 text-white" />
          </div>
          <span className="text-xl font-bold font-display text-slate-900">ProjectHub</span>
        </Link>
      </div>

      <nav className="flex-1 p-4 space-y-1 overflow-y-auto">
        {navigation.map((item) => {
          const isActive = pathname === item.href || pathname?.startsWith(item.href + '/');
          return (
            <Link
              key={item.href}
              href={item.href}
              className={cn(
                'flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm font-medium transition-all',
                isActive
                  ? 'bg-primary text-white shadow-sm'
                  : 'text-slate-600 hover:bg-slate-100 hover:text-slate-900'
              )}
            >
              <item.icon className="w-5 h-5" />
              {item.name}
            </Link>
          );
        })}
      </nav>

      <div className="p-4 border-t space-y-2">
        <Link
          href="/settings"
          className="flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm font-medium text-slate-600 hover:bg-slate-100 hover:text-slate-900 transition-all"
        >
          <Settings className="w-5 h-5" />
          系统设置
        </Link>

        <button
          onClick={handleLogout}
          className="w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm font-medium text-red-600 hover:bg-red-50 transition-all"
        >
          <LogOut className="w-5 h-5" />
          退出登录
        </button>

        {user && (
          <div className="px-3 py-3 mt-2">
            <p className="text-sm font-medium text-slate-900">{user.name}</p>
            <p className="text-xs text-slate-500">{user.email}</p>
          </div>
        )}
      </div>
    </div>
  );
}

// src/components/layout/Sidebar.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import {
  LayoutDashboard,
  BarChart3,
  Users,
  AlertTriangle,
  Settings,
  FileText,
  Building2
} from 'lucide-vue-next'

const route = useRoute()
const router = useRouter()

const menuItems = [
  { path: '/dashboard', name: '综合能耗看板', icon: LayoutDashboard },
  { path: '/peak-valley', name: '峰谷对比分析', icon: BarChart3 },
  { path: '/allocation', name: '租户分摊管理', icon: Users },
  { path: '/alerts', name: '异常告警中心', icon: AlertTriangle },
  { path: '/reports', name: '报告导出', icon: FileText },
  { path: '/config', name: '系统配置', icon: Settings }
]

const isActive = (path: string) => computed(() => route.path === path)

function navigateTo(path: string) {
  router.push(path)
}
</script>

<template>
  <aside class="w-64 bg-bg-secondary border-r border-slate-700/50 flex flex-col h-screen sticky top-0">
    <div class="p-6 border-b border-slate-700/50">
      <div class="flex items-center gap-3">
        <div class="w-10 h-10 bg-brand-600 rounded-xl flex items-center justify-center">
          <Building2 class="w-6 h-6 text-white" />
        </div>
        <div>
          <h1 class="font-display font-bold text-lg text-white">能源分析平台</h1>
          <p class="text-xs text-slate-400">Energy Management</p>
        </div>
      </div>
    </div>

    <nav class="flex-1 p-4 overflow-y-auto">
      <ul class="space-y-1">
        <li v-for="item in menuItems" :key="item.path">
          <button
            @click="navigateTo(item.path)"
            class="w-full flex items-center gap-3 px-4 py-3 rounded-lg transition-all duration-200"
            :class="isActive(item.path)
              ? 'bg-brand-600/20 text-brand-400 border border-brand-500/30'
              : 'text-slate-400 hover:text-slate-200 hover:bg-bg-tertiary/50'"
          >
            <component :is="item.icon" class="w-5 h-5" />
            <span class="font-medium">{{ item.name }}</span>
          </button>
        </li>
      </ul>
    </nav>

    <div class="p-4 border-t border-slate-700/50">
      <div class="bg-bg-tertiary/50 rounded-lg p-4">
        <p class="text-xs text-slate-400 mb-2">数据更新时间</p>
        <p class="font-mono text-sm text-slate-200">{{ new Date().toLocaleString('zh-CN') }}</p>
      </div>
    </div>
  </aside>
</template>
