// src/components/FilterPanel.svelte
<script lang="ts">
	import { departments, timeSlots, patientTypes, processNodes } from '$lib/dictionary';
	import { Filter, X, ChevronDown, ChevronUp } from 'lucide-svelte';
	import type { FilterParams, PatientType, ProcessNode } from '$types';

	export let filters: Partial<FilterParams> = {
		departments: [],
		doctors: [],
		timeSlots: [],
		patientTypes: [],
		processNodes: [],
		excludeAnomalies: true
	};

	export let onFilterChange: (filters: Partial<FilterParams>) => void = () => {};

	let expanded = true;
	let doctors = ['张医生', '李医生', '王医生', '刘医生', '陈医生', '杨医生', '赵医生', '黄医生'];

	function toggleDepartment(dept: string) {
		const current = filters.departments || [];
		const updated = current.includes(dept) ? current.filter((d) => d !== dept) : [...current, dept];
		filters = { ...filters, departments: updated };
		onFilterChange(filters);
	}

	function toggleDoctor(doc: string) {
		const current = filters.doctors || [];
		const updated = current.includes(doc) ? current.filter((d) => d !== doc) : [...current, doc];
		filters = { ...filters, doctors: updated };
		onFilterChange(filters);
	}

	function toggleTimeSlot(slot: string) {
		const current = filters.timeSlots || [];
		const updated = current.includes(slot) ? current.filter((s) => s !== slot) : [...current, slot];
		filters = { ...filters, timeSlots: updated };
		onFilterChange(filters);
	}

	function togglePatientType(type: PatientType) {
		const current = filters.patientTypes || [];
		const updated = current.includes(type) ? current.filter((t) => t !== type) : [...current, type];
		filters = { ...filters, patientTypes: updated };
		onFilterChange(filters);
	}

	function toggleProcessNode(node: ProcessNode) {
		const current = filters.processNodes || [];
		const updated = current.includes(node) ? current.filter((n) => n !== node) : [...current, node];
		filters = { ...filters, processNodes: updated };
		onFilterChange(filters);
	}

	function toggleExcludeAnomalies() {
		filters = { ...filters, excludeAnomalies: !filters.excludeAnomalies };
		onFilterChange(filters);
	}

	function clearAll() {
		filters = {
			departments: [],
			doctors: [],
			timeSlots: [],
			patientTypes: [],
			processNodes: [],
			excludeAnomalies: true
		};
		onFilterChange(filters);
	}

	function hasActiveFilters(): boolean {
		return (
			(filters.departments?.length || 0) > 0 ||
			(filters.doctors?.length || 0) > 0 ||
			(filters.timeSlots?.length || 0) > 0 ||
			(filters.patientTypes?.length || 0) > 0 ||
			(filters.processNodes?.length || 0) > 0 ||
			!filters.excludeAnomalies
		);
	}
</script>

<div class="card mb-6">
	<div class="flex items-center justify-between mb-4">
		<button
			class="flex items-center space-x-2 text-gray-700 font-medium"
			on:click={() => (expanded = !expanded)}
		>
			<Filter class="w-5 h-5 text-primary-500" />
			<span>筛选条件</span>
			{#if hasActiveFilters()}
				<span
					class="bg-primary-100 text-primary-600 text-xs px-2 py-0.5 rounded-full font-medium"
				>
					{#each [
						filters.departments?.length || 0,
						filters.doctors?.length || 0,
						filters.timeSlots?.length || 0,
						filters.patientTypes?.length || 0
					] as c}
						{#if c > 0}{c}{/if}
					{/each}
					已选
				</span>
			{/if}
			<svelte:component this={expanded ? ChevronUp : ChevronDown} class="w-4 h-4" />
		</button>
		{#if hasActiveFilters()}
			<button
				class="text-sm text-gray-500 hover:text-gray-700 flex items-center space-x-1"
				on:click={clearAll}
			>
				<X class="w-4 h-4" />
				<span>清除全部</span>
			</button>
		{/if}
	</div>

	{#if expanded}
		<div class="space-y-4">
			<div>
				<label class="text-sm font-medium text-gray-700 mb-2 block">科室</label>
				<div class="flex flex-wrap gap-2">
					{#each departments as dept}
						<button
							class="px-3 py-1.5 text-sm rounded-lg border transition-colors duration-150 {filters
								.departments?.includes(dept)
								? 'bg-primary-50 border-primary-300 text-primary-700'
								: 'bg-white border-gray-200 text-gray-600 hover:border-gray-300'}"
							on:click={() => toggleDepartment(dept)}
						>
							{dept}
						</button>
					{/each}
				</div>
			</div>

			<div>
				<label class="text-sm font-medium text-gray-700 mb-2 block">时段</label>
				<div class="flex flex-wrap gap-2">
					{#each timeSlots as slot}
						<button
							class="px-3 py-1.5 text-sm rounded-lg border transition-colors duration-150 {filters
								.timeSlots?.includes(slot)
								? 'bg-primary-50 border-primary-300 text-primary-700'
								: 'bg-white border-gray-200 text-gray-600 hover:border-gray-300'}"
							on:click={() => toggleTimeSlot(slot)}
						>
							{slot}
						</button>
					{/each}
				</div>
			</div>

			<div>
				<label class="text-sm font-medium text-gray-700 mb-2 block">患者类型</label>
				<div class="flex flex-wrap gap-2">
					{#each patientTypes as type}
						<button
							class="px-3 py-1.5 text-sm rounded-lg border transition-colors duration-150 {filters
								.patientTypes?.includes(type)
								? 'bg-primary-50 border-primary-300 text-primary-700'
								: 'bg-white border-gray-200 text-gray-600 hover:border-gray-300'}"
							on:click={() => togglePatientType(type)}
						>
							{type}
						</button>
					{/each}
				</div>
			</div>

			<div class="flex items-center justify-between pt-2 border-t border-gray-100">
				<label class="flex items-center space-x-2 cursor-pointer">
					<input
						type="checkbox"
						bind:checked={filters.excludeAnomalies}
						on:change={toggleExcludeAnomalies}
						class="w-4 h-4 text-primary-600 rounded border-gray-300 focus:ring-primary-500"
					/>
					<span class="text-sm text-gray-600">排除异常数据</span>
				</label>
			</div>
		</div>
	{/if}
</div>

// components/FilterPanel.tsx
'use client'

import { useState } from 'react'
import { Filter, X, ChevronDown, ChevronUp } from 'lucide-react'
import type { FilterParams } from '@/lib/types'

interface FilterPanelProps {
  masterData: {
    stations: { id: string; name: string }[]
    vehicles: { id: string; plateNumber: string }[]
    teams: { id: string; name: string }[]
    weatherConditions: { value: string; label: string }[]
    delayCategories: { value: string; label: string }[]
    severityLevels: { value: string; label: string }[]
  }
  filters: FilterParams
  onFilterChange: (filters: FilterParams) => void
  onExport: () => void
  canExport: boolean
}

export default function FilterPanel({
  masterData,
  filters,
  onFilterChange,
  onExport,
  canExport,
}: FilterPanelProps) {
  const [isExpanded, setIsExpanded] = useState(true)

  const handleMultiSelect = (field: keyof FilterParams, value: string) => {
    const current = (filters[field] as string[]) || []
    const updated = current.includes(value)
      ? current.filter(v => v !== value)
      : [...current, value]
    onFilterChange({ ...filters, [field]: updated.length > 0 ? updated : undefined })
  }

  const handleSingleChange = (field: keyof FilterParams, value: string | number | undefined) => {
    onFilterChange({ ...filters, [field]: value })
  }

  const clearFilters = () => {
    onFilterChange({})
  }

  const hasActiveFilters = Object.values(filters).some(v => 
    Array.isArray(v) ? v.length > 0 : v !== undefined
  )

  return (
    <div className="card">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <Filter className="w-5 h-5 text-primary-600" />
          <h3 className="font-semibold text-gray-800">筛选条件</h3>
          {hasActiveFilters && (
            <span className="bg-primary-100 text-primary-700 text-xs px-2 py-0.5 rounded-full">
              已筛选
            </span>
          )}
        </div>
        <div className="flex items-center gap-2">
          {hasActiveFilters && (
            <button
              onClick={clearFilters}
              className="text-sm text-gray-500 hover:text-gray-700 flex items-center gap-1"
            >
              <X className="w-4 h-4" />
              清除
            </button>
          )}
          <button
            onClick={() => setIsExpanded(!isExpanded)}
            className="text-gray-500 hover:text-gray-700"
          >
            {isExpanded ? <ChevronUp className="w-5 h-5" /> : <ChevronDown className="w-5 h-5" />}
          </button>
        </div>
      </div>

      {isExpanded && (
        <div className="space-y-4">
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">开始日期</label>
              <input
                type="date"
                className="input text-sm"
                value={filters.startDate || ''}
                onChange={(e) => handleSingleChange('startDate', e.target.value || undefined)}
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">结束日期</label>
              <input
                type="date"
                className="input text-sm"
                value={filters.endDate || ''}
                onChange={(e) => handleSingleChange('endDate', e.target.value || undefined)}
              />
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">中转站</label>
            <div className="flex flex-wrap gap-2 max-h-24 overflow-y-auto">
              {masterData.stations.map(stn => (
                <button
                  key={stn.id}
                  onClick={() => handleMultiSelect('stationIds', stn.id)}
                  className={`text-xs px-2 py-1 rounded-full border transition-colors ${
                    (filters.stationIds || []).includes(stn.id)
                      ? 'bg-primary-100 border-primary-300 text-primary-700'
                      : 'bg-gray-50 border-gray-200 text-gray-600 hover:bg-gray-100'
                  }`}
                >
                  {stn.name}
                </button>
              ))}
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">车辆</label>
            <div className="flex flex-wrap gap-2 max-h-20 overflow-y-auto">
              {masterData.vehicles.slice(0, 10).map(v => (
                <button
                  key={v.id}
                  onClick={() => handleMultiSelect('vehicleIds', v.id)}
                  className={`text-xs px-2 py-1 rounded-full border transition-colors ${
                    (filters.vehicleIds || []).includes(v.id)
                      ? 'bg-primary-100 border-primary-300 text-primary-700'
                      : 'bg-gray-50 border-gray-200 text-gray-600 hover:bg-gray-100'
                  }`}
                >
                  {v.plateNumber}
                </button>
              ))}
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">迟滞原因</label>
            <div className="flex flex-wrap gap-2">
              {masterData.delayCategories.map(cat => (
                <button
                  key={cat.value}
                  onClick={() => handleMultiSelect('delayCategories', cat.value)}
                  className={`text-xs px-2 py-1 rounded-full border transition-colors ${
                    (filters.delayCategories || []).includes(cat.value)
                      ? 'bg-orange-100 border-orange-300 text-orange-700'
                      : 'bg-gray-50 border-gray-200 text-gray-600 hover:bg-gray-100'
                  }`}
                >
                  {cat.label}
                </button>
              ))}
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              最小迟滞时长 (分钟)
            </label>
            <input
              type="number"
              className="input text-sm"
              placeholder="输入最小迟滞分钟数"
              value={filters.minDelayMinutes || ''}
              onChange={(e) => handleSingleChange('minDelayMinutes', e.target.value ? Number(e.target.value) : undefined)}
            />
          </div>

          {canExport && (
            <div className="pt-3 border-t border-gray-200">
              <button
                onClick={onExport}
                className="btn-primary w-full text-sm"
              >
                导出分析报告
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  )
}
