// src/components/filter-bar.tsx
"use client";

import { useState } from "react";
import { Search, Filter, X } from "lucide-react";
import { cn } from "@/lib/utils";

interface FilterOption {
  label: string;
  value: string;
}

interface FilterConfig {
  key: string;
  label: string;
  type: "select" | "date" | "search" | "text";
  options?: FilterOption[];
  placeholder?: string;
}

interface FilterBarProps {
  filters: FilterConfig[];
  values: Record<string, any>;
  onChange: (values: Record<string, any>) => void;
  onReset: () => void;
  className?: string;
}

export function FilterBar({ filters, values, onChange, onReset, className }: FilterBarProps) {
  const [isExpanded, setIsExpanded] = useState(false);

  const handleChange = (key: string, value: any) => {
    onChange({ ...values, [key]: value });
  };

  const hasActiveFilters = Object.values(values).some((v) => v !== undefined && v !== "" && v !== null);

  return (
    <div className={cn("bg-white rounded-xl border border-zinc-200 p-4", className)}>
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <Filter className="h-5 w-5 text-zinc-500" />
          <h3 className="font-semibold text-zinc-900">筛选条件</h3>
        </div>
        <div className="flex items-center gap-2">
          {hasActiveFilters && (
            <button
              onClick={onReset}
              className="flex items-center gap-1 text-sm text-zinc-500 hover:text-zinc-700"
            >
              <X className="h-4 w-4" />
              重置
            </button>
          )}
          <button
            onClick={() => setIsExpanded(!isExpanded)}
            className="text-sm text-zinc-600 hover:text-zinc-900"
          >
            {isExpanded ? "收起" : "展开"}
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {filters.slice(0, isExpanded ? filters.length : 4).map((filter) => (
          <div key={filter.key}>
            <label className="block text-sm font-medium text-zinc-700 mb-1">
              {filter.label}
            </label>
            {filter.type === "select" && (
              <select
                value={values[filter.key] || ""}
                onChange={(e) => handleChange(filter.key, e.target.value || undefined)}
                className="w-full rounded-lg border border-zinc-200 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-zinc-900"
              >
                <option value="">全部</option>
                {filter.options?.map((opt) => (
                  <option key={opt.value} value={opt.value}>
                    {opt.label}
                  </option>
                ))}
              </select>
            )}
            {filter.type === "date" && (
              <input
                type="date"
                value={values[filter.key] ? new Date(values[filter.key]).toISOString().split('T')[0] : ""}
                onChange={(e) => handleChange(filter.key, e.target.value ? new Date(e.target.value) : undefined)}
                className="w-full rounded-lg border border-zinc-200 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-zinc-900"
              />
            )}
            {filter.type === "text" && (
              <input
                type="text"
                value={values[filter.key] || ""}
                onChange={(e) => handleChange(filter.key, e.target.value || undefined)}
                placeholder={filter.placeholder}
                className="w-full rounded-lg border border-zinc-200 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-zinc-900"
              />
            )}
            {filter.type === "search" && (
              <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-zinc-400" />
                <input
                  type="text"
                  value={values[filter.key] || ""}
                  onChange={(e) => handleChange(filter.key, e.target.value || undefined)}
                  placeholder={filter.placeholder}
                  className="w-full rounded-lg border border-zinc-200 pl-9 pr-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-zinc-900"
                />
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}

// resources/js/Components/FilterBar.vue
<script setup>
import { ref, watch } from 'vue';

const props = defineProps({
    filters: {
        type: Array,
        required: true,
    },
    modelValue: {
        type: Object,
        default: () => ({}),
    },
});

const emit = defineEmits(['update:modelValue', 'filter', 'reset']);

const localFilters = ref({ ...props.modelValue });

watch(
    () => props.modelValue,
    (newVal) => {
        localFilters.value = { ...newVal };
    },
    { deep: true }
);

const handleFilter = () => {
    emit('update:modelValue', { ...localFilters.value });
    emit('filter', { ...localFilters.value });
};

const handleReset = () => {
    localFilters.value = {};
    emit('update:modelValue', {});
    emit('reset');
};
</script>

<template>
    <div class="bg-white rounded-lg shadow p-4 mb-4">
        <div class="flex flex-wrap gap-4 items-end">
            <template v-for="filter in filters" :key="filter.name">
                <div class="flex-1 min-w-[200px]">
                    <label class="block text-sm font-medium text-gray-700 mb-1">
                        {{ filter.label }}
                    </label>

                    <input
                        v-if="filter.type === 'text'"
                        v-model="localFilters[filter.name]"
                        :type="filter.inputType || 'text'"
                        :placeholder="filter.placeholder || ''"
                        class="w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm"
                    />

                    <select
                        v-else-if="filter.type === 'select'"
                        v-model="localFilters[filter.name]"
                        class="w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm"
                    >
                        <option value="">全部</option>
                        <option
                            v-for="option in filter.options"
                            :key="option.value"
                            :value="option.value"
                        >
                            {{ option.label }}
                        </option>
                    </select>

                    <input
                        v-else-if="filter.type === 'date'"
                        v-model="localFilters[filter.name]"
                        type="date"
                        class="w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm"
                    />

                    <input
                        v-else-if="filter.type === 'daterange'"
                        v-model="localFilters[filter.name]"
                        type="date"
                        class="w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm"
                    />
                </div>
            </template>

            <div class="flex gap-2">
                <button
                    type="button"
                    @click="handleFilter"
                    class="inline-flex items-center px-4 py-2 bg-primary-600 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-primary-700 focus:bg-primary-700 active:bg-primary-900 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2 transition ease-in-out duration-150"
                >
                    <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                    </svg>
                    筛选
                </button>
                <button
                    type="button"
                    @click="handleReset"
                    class="inline-flex items-center px-4 py-2 bg-white border border-gray-300 rounded-md font-semibold text-xs text-gray-700 uppercase tracking-widest shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2 disabled:opacity-25 transition ease-in-out duration-150"
                >
                    重置
                </button>
            </div>
        </div>
    </div>
</template>
