// src/components/ui/Pagination.tsx
"use client";

import { ChevronLeft, ChevronRight } from "lucide-react";
import { cn } from "@/lib/utils";

export interface PaginationProps {
  page: number;
  pageSize: number;
  total: number;
  totalPages: number;
  onChange: (page: number) => void;
  onPageSizeChange?: (size: number) => void;
  className?: string;
}

export function Pagination({
  page,
  pageSize,
  total,
  totalPages,
  onChange,
  onPageSizeChange,
  className,
}: PaginationProps) {
  const start = total === 0 ? 0 : (page - 1) * pageSize + 1;
  const end = Math.min(page * pageSize, total);

  return (
    <div className={cn("flex items-center justify-between gap-2 px-4 py-3 text-sm", className)}>
      <div className="text-slate-500">
        显示 <span className="font-medium text-slate-700">{start}</span> –{" "}
        <span className="font-medium text-slate-700">{end}</span> 条，共{" "}
        <span className="font-medium text-slate-700">{total}</span> 条
      </div>
      <div className="flex items-center gap-3">
        {onPageSizeChange && (
          <select
            className="h-8 w-auto"
            value={pageSize}
            onChange={(e) => onPageSizeChange(Number(e.target.value))}
          >
            {[10, 20, 50, 100].map((n) => (
              <option key={n} value={n}>
                {n} 条/页
              </option>
            ))}
          </select>
        )}
        <div className="flex items-center gap-1">
          <button
            type="button"
            className="btn-secondary h-8 w-8 !p-0"
            disabled={page <= 1}
            onClick={() => onChange(page - 1)}
            aria-label="上一页"
          >
            <ChevronLeft className="h-4 w-4" />
          </button>
          {buildPages(page, totalPages).map((p) =>
            p === "..." ? (
              <span key={`dot-${p}-${Math.random()}`} className="px-1 text-slate-400">
                …
              </span>
            ) : (
              <button
                key={p}
                type="button"
                className={cn("h-8 min-w-8 px-2 rounded-md text-sm", {
                  "bg-primary-600 text-white": p === page,
                  "text-slate-600 hover:bg-slate-100": p !== page,
                })}
                onClick={() => onChange(p as number)}
              >
                {p}
              </button>
            )
          )}
          <button
            type="button"
            className="btn-secondary h-8 w-8 !p-0"
            disabled={page >= totalPages}
            onClick={() => onChange(page + 1)}
            aria-label="下一页"
          >
            <ChevronRight className="h-4 w-4" />
          </button>
        </div>
      </div>
    </div>
  );
}

function buildPages(current: number, total: number): (number | "...")[] {
  const delta = 2;
  const range: number[] = [];
  for (let i = Math.max(2, current - delta); i <= Math.min(total - 1, current + delta); i++) {
    range.push(i);
  }
  const pages: (number | "...")[] = [1];
  if (range[0] > 2) pages.push("...");
  pages.push(...range);
  if (range[range.length - 1] < total - 1) pages.push("...");
  if (total > 1) pages.push(total);
  return pages;
}

// resources/js/Components/Pagination.vue
<script setup>
import { computed } from 'vue';

const props = defineProps({
    currentPage: {
        type: Number,
        required: true,
    },
    lastPage: {
        type: Number,
        required: true,
    },
    perPage: {
        type: Number,
        default: 15,
    },
    total: {
        type: Number,
        default: 0,
    },
    showPerPage: {
        type: Boolean,
        default: true,
    },
    showTotal: {
        type: Boolean,
        default: true,
    },
});

const emit = defineEmits(['update:currentPage', 'update:perPage', 'change']);

const pages = computed(() => {
    const pages = [];
    const start = Math.max(1, props.currentPage - 2);
    const end = Math.min(props.lastPage, props.currentPage + 2);

    if (start > 1) {
        pages.push(1);
        if (start > 2) pages.push('...');
    }

    for (let i = start; i <= end; i++) {
        pages.push(i);
    }

    if (end < props.lastPage) {
        if (end < props.lastPage - 1) pages.push('...');
        pages.push(props.lastPage);
    }

    return pages;
});

const perPageOptions = [10, 15, 25, 50, 100];

const goToPage = (page) => {
    if (page >= 1 && page <= props.lastPage && page !== props.currentPage) {
        emit('update:currentPage', page);
        emit('change', { page, perPage: props.perPage });
    }
};

const changePerPage = (e) => {
    const value = parseInt(e.target.value);
    emit('update:perPage', value);
    emit('change', { page: 1, perPage: value });
};
</script>

<template>
    <div class="flex items-center justify-between px-4 py-3 bg-white dark:bg-gray-800 border-t border-gray-200 dark:border-gray-700 sm:px-6">
        <div class="flex-1 flex items-center justify-between">
            <div v-if="showTotal" class="text-sm text-gray-700 dark:text-gray-300">
                显示
                <span class="font-medium">
                    {{ total > 0 ? (currentPage - 1) * perPage + 1 : 0 }}
                </span>
                到
                <span class="font-medium">
                    {{ Math.min(currentPage * perPage, total) }}
                </span>
                共
                <span class="font-medium">{{ total }}</span>
                条
            </div>
            <div v-else></div>

            <div class="flex items-center space-x-4">
                <div v-if="showPerPage" class="flex items-center">
                    <label class="mr-2 text-sm text-gray-700 dark:text-gray-300">每页</label>
                    <select
                        :value="perPage"
                        @change="changePerPage"
                        class="block w-20 rounded-md border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-white py-1.5 text-sm focus:ring-indigo-500 focus:border-indigo-500"
                    >
                        <option v-for="opt in perPageOptions" :key="opt" :value="opt">{{ opt }}</option>
                    </select>
                    <label class="ml-2 text-sm text-gray-700 dark:text-gray-300">条</label>
                </div>

                <nav class="flex items-center space-x-1" aria-label="Pagination">
                    <button
                        @click="goToPage(currentPage - 1)"
                        :disabled="currentPage <= 1"
                        class="relative inline-flex items-center px-2 py-2 rounded-md border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-sm font-medium text-gray-500 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-600 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        <span class="sr-only">上一页</span>
                        <svg class="h-5 w-5" fill="currentColor" viewBox="0 0 20 20">
                            <path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd" />
                        </svg>
                    </button>

                    <template v-for="page in pages" :key="page">
                        <span v-if="page === '...'" class="relative inline-flex items-center px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300">
                            ...
                        </span>
                        <button
                            v-else
                            @click="goToPage(page)"
                            :class="[
                                'relative inline-flex items-center px-4 py-2 text-sm font-medium rounded-md border',
                                page === currentPage
                                    ? 'z-10 bg-indigo-600 border-indigo-500 text-white'
                                    : 'bg-white dark:bg-gray-700 border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-600'
                            ]"
                        >
                            {{ page }}
                        </button>
                    </template>

                    <button
                        @click="goToPage(currentPage + 1)"
                        :disabled="currentPage >= lastPage"
                        class="relative inline-flex items-center px-2 py-2 rounded-md border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-sm font-medium text-gray-500 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-600 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        <span class="sr-only">下一页</span>
                        <svg class="h-5 w-5" fill="currentColor" viewBox="0 0 20 20">
                            <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
                        </svg>
                    </button>
                </nav>
            </div>
        </div>
    </div>
</template>
