// brand-video-platform/src/app/schedule/page.tsx
'use client'

import { useState, useMemo } from 'react'
import { useAppStore } from '@/lib/store'
import { SCHEDULE_STATUS_MAP, ScheduleStatus } from '@/lib/types'
import { formatDate, generateId } from '@/lib/utils'
import {
  Calendar,
  List,
  ChevronLeft,
  ChevronRight,
  Plus,
  X,
  Filter,
  Trash2,
} from 'lucide-react'

const PLATFORM_COLORS: Record<string, { bg: string; text: string; dot: string }> = {
  '抖音': { bg: 'bg-orange-100', text: 'text-orange-700', dot: 'bg-orange-400' },
  '小红书': { bg: 'bg-red-100', text: 'text-red-700', dot: 'bg-red-400' },
  'B站': { bg: 'bg-blue-100', text: 'text-blue-700', dot: 'bg-blue-400' },
  '视频号': { bg: 'bg-green-100', text: 'text-green-700', dot: 'bg-green-400' },
}

const PLATFORMS = ['抖音', '小红书', 'B站', '视频号']
const WEEKDAYS = ['一', '二', '三', '四', '五', '六', '日']

type ViewMode = 'calendar' | 'list'

function getDaysInMonth(year: number, month: number) {
  return new Date(year, month + 1, 0).getDate()
}

function getFirstDayOfWeek(year: number, month: number) {
  const day = new Date(year, month, 1).getDay()
  return day === 0 ? 6 : day - 1
}

export default function SchedulePage() {
  const { schedules, topics, profiles, addSchedule, updateScheduleStatus, currentUserId } = useAppStore()

  const [viewMode, setViewMode] = useState<ViewMode>('calendar')
  const [currentYear, setCurrentYear] = useState(2025)
  const [currentMonth, setCurrentMonth] = useState(6)

  const [statusFilter, setStatusFilter] = useState<ScheduleStatus | ''>('')
  const [dateFrom, setDateFrom] = useState('')
  const [dateTo, setDateTo] = useState('')
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set())

  const [showNewForm, setShowNewForm] = useState(false)
  const [newTopicId, setNewTopicId] = useState('')
  const [newPlatform, setNewPlatform] = useState('')
  const [newDate, setNewDate] = useState('')
  const [newTime, setNewTime] = useState('')

  const handlePrevMonth = () => {
    if (currentMonth === 0) {
      setCurrentMonth(11)
      setCurrentYear(currentYear - 1)
    } else {
      setCurrentMonth(currentMonth - 1)
    }
  }

  const handleNextMonth = () => {
    if (currentMonth === 11) {
      setCurrentMonth(0)
      setCurrentYear(currentYear + 1)
    } else {
      setCurrentMonth(currentMonth + 1)
    }
  }

  const calendarDays = useMemo(() => {
    const daysInMonth = getDaysInMonth(currentYear, currentMonth)
    const firstDay = getFirstDayOfWeek(currentYear, currentMonth)
    const days: (number | null)[] = []
    for (let i = 0; i < firstDay; i++) days.push(null)
    for (let d = 1; d <= daysInMonth; d++) days.push(d)
    return days
  }, [currentYear, currentMonth])

  const getSchedulesForDate = (day: number) => {
    const dateStr = `${currentYear}-${String(currentMonth + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`
    return schedules.filter((s) => s.publish_date === dateStr)
  }

  const filteredSchedules = useMemo(() => {
    let result = [...schedules]
    if (statusFilter) {
      result = result.filter((s) => s.status === statusFilter)
    }
    if (dateFrom) {
      result = result.filter((s) => s.publish_date >= dateFrom)
    }
    if (dateTo) {
      result = result.filter((s) => s.publish_date <= dateTo)
    }
    return result.sort((a, b) => a.publish_date.localeCompare(b.publish_date) || (a.publish_time || '').localeCompare(b.publish_time || ''))
  }, [schedules, statusFilter, dateFrom, dateTo])

  const toggleSelect = (id: string) => {
    const next = new Set(selectedIds)
    if (next.has(id)) next.delete(id)
    else next.add(id)
    setSelectedIds(next)
  }

  const handleBatchCancel = () => {
    selectedIds.forEach((id) => {
      updateScheduleStatus(id, 'cancelled')
    })
    setSelectedIds(new Set())
  }

  const handleCancel = (id: string) => {
    updateScheduleStatus(id, 'cancelled')
  }

  const handleCreate = () => {
    if (!newTopicId || !newPlatform || !newDate) return
    const topic = topics.find((t) => t.id === newTopicId)
    if (!topic) return
    const operator = profiles.find((p) => p.id === currentUserId)
    addSchedule({
      id: generateId(),
      topic_id: topic.id,
      topic_title: topic.title,
      platform: newPlatform,
      publish_date: newDate,
      publish_time: newTime || null,
      status: 'scheduled',
      operator_id: currentUserId,
      operator_name: operator?.display_name || '',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    })
    setNewTopicId('')
    setNewPlatform('')
    setNewDate('')
    setNewTime('')
    setShowNewForm(false)
  }

  const monthLabel = `${currentYear}年${currentMonth + 1}月`

  return (
    <div className="min-h-screen bg-[var(--background)] p-6">
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-bold text-brand-500">发布排期</h1>
        <div className="flex items-center gap-3">
          <div className="flex rounded-lg border border-surface-300 overflow-hidden">
            <button
              onClick={() => setViewMode('calendar')}
              className={`px-3 py-1.5 text-sm flex items-center gap-1.5 transition-colors ${
                viewMode === 'calendar' ? 'bg-accent-500 text-white' : 'bg-white text-brand-500 hover:bg-surface-100'
              }`}
            >
              <Calendar size={15} />
              日历
            </button>
            <button
              onClick={() => setViewMode('list')}
              className={`px-3 py-1.5 text-sm flex items-center gap-1.5 transition-colors ${
                viewMode === 'list' ? 'bg-accent-500 text-white' : 'bg-white text-brand-500 hover:bg-surface-100'
              }`}
            >
              <List size={15} />
              列表
            </button>
          </div>
          <button onClick={() => setShowNewForm(true)} className="btn-primary text-sm">
            <Plus size={16} />
            新建排期
          </button>
        </div>
      </div>

      {showNewForm && (
        <div className="card p-5 mb-6">
          <div className="flex items-center justify-between mb-4">
            <h3 className="section-title">新建排期</h3>
            <button onClick={() => setShowNewForm(false)} className="btn-ghost">
              <X size={16} />
            </button>
          </div>
          <div className="grid grid-cols-4 gap-4">
            <div>
              <label className="block text-xs text-surface-400 mb-1">选题</label>
              <select value={newTopicId} onChange={(e) => setNewTopicId(e.target.value)} className="select-field">
                <option value="">选择选题</option>
                {topics.map((t) => (
                  <option key={t.id} value={t.id}>{t.title}</option>
                ))}
              </select>
            </div>
            <div>
              <label className="block text-xs text-surface-400 mb-1">平台</label>
              <select value={newPlatform} onChange={(e) => setNewPlatform(e.target.value)} className="select-field">
                <option value="">选择平台</option>
                {PLATFORMS.map((p) => (
                  <option key={p} value={p}>{p}</option>
                ))}
              </select>
            </div>
            <div>
              <label className="block text-xs text-surface-400 mb-1">发布日期</label>
              <input type="date" value={newDate} onChange={(e) => setNewDate(e.target.value)} className="input-field" />
            </div>
            <div>
              <label className="block text-xs text-surface-400 mb-1">发布时间</label>
              <input type="time" value={newTime} onChange={(e) => setNewTime(e.target.value)} className="input-field" />
            </div>
          </div>
          <div className="flex justify-end mt-4">
            <button onClick={handleCreate} className="btn-primary text-sm">确认创建</button>
          </div>
        </div>
      )}

      {viewMode === 'calendar' ? (
        <div>
          <div className="flex items-center justify-between mb-4">
            <button onClick={handlePrevMonth} className="btn-ghost">
              <ChevronLeft size={18} />
            </button>
            <span className="text-lg font-semibold text-brand-500">{monthLabel}</span>
            <button onClick={handleNextMonth} className="btn-ghost">
              <ChevronRight size={18} />
            </button>
          </div>

          <div className="card overflow-hidden">
            <div className="grid grid-cols-7 border-b border-surface-200">
              {WEEKDAYS.map((d) => (
                <div key={d} className="py-2 text-center text-xs font-medium text-surface-400">
                  周{d}
                </div>
              ))}
            </div>
            <div className="grid grid-cols-7">
              {calendarDays.map((day, idx) => {
                if (day === null) {
                  return <div key={`empty-${idx}`} className="min-h-[100px] border-b border-r border-surface-200 bg-surface-50" />
                }
                const daySchedules = getSchedulesForDate(day)
                return (
                  <div key={day} className="min-h-[100px] border-b border-r border-surface-200 p-1.5">
                    <span className="text-xs text-surface-400 font-medium">{day}</span>
                    <div className="flex flex-col gap-0.5 mt-1">
                      {daySchedules.map((s) => {
                        const pc = PLATFORM_COLORS[s.platform] || { bg: 'bg-gray-100', text: 'text-gray-700', dot: 'bg-gray-400' }
                        return (
                          <div
                            key={s.id}
                            className={`${pc.bg} ${pc.text} text-xs px-1.5 py-0.5 rounded truncate`}
                          >
                            <span className={`inline-block w-1.5 h-1.5 rounded-full ${pc.dot} mr-1`} />
                            {s.topic_title}
                          </div>
                        )
                      })}
                    </div>
                  </div>
                )
              })}
            </div>
          </div>
        </div>
      ) : (
        <div>
          <div className="card p-4 mb-4">
            <div className="flex items-center gap-4 flex-wrap">
              <div className="flex items-center gap-2">
                <Filter size={14} className="text-surface-400" />
                <select
                  value={statusFilter}
                  onChange={(e) => setStatusFilter(e.target.value as ScheduleStatus | '')}
                  className="select-field w-32"
                >
                  <option value="">全部状态</option>
                  {Object.entries(SCHEDULE_STATUS_MAP).map(([key, val]) => (
                    <option key={key} value={key}>{val.label}</option>
                  ))}
                </select>
              </div>
              <div className="flex items-center gap-2">
                <input type="date" value={dateFrom} onChange={(e) => setDateFrom(e.target.value)} className="input-field w-36" />
                <span className="text-xs text-surface-400">至</span>
                <input type="date" value={dateTo} onChange={(e) => setDateTo(e.target.value)} className="input-field w-36" />
              </div>
              {selectedIds.size > 0 && (
                <button onClick={handleBatchCancel} className="btn-ghost text-red-500 hover:text-red-600 text-sm">
                  <Trash2 size={14} />
                  取消排期 ({selectedIds.size})
                </button>
              )}
            </div>
          </div>

          <div className="card overflow-hidden">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-surface-200 bg-surface-50">
                  <th className="py-3 px-4 text-left font-medium text-surface-400 w-10">
                    <input
                      type="checkbox"
                      checked={selectedIds.size === filteredSchedules.length && filteredSchedules.length > 0}
                      onChange={() => {
                        if (selectedIds.size === filteredSchedules.length) {
                          setSelectedIds(new Set())
                        } else {
                          setSelectedIds(new Set(filteredSchedules.map((s) => s.id)))
                        }
                      }}
                      className="rounded"
                    />
                  </th>
                  <th className="py-3 px-4 text-left font-medium text-surface-400">选题标题</th>
                  <th className="py-3 px-4 text-left font-medium text-surface-400">平台</th>
                  <th className="py-3 px-4 text-left font-medium text-surface-400">发布日期</th>
                  <th className="py-3 px-4 text-left font-medium text-surface-400">发布时间</th>
                  <th className="py-3 px-4 text-left font-medium text-surface-400">状态</th>
                  <th className="py-3 px-4 text-left font-medium text-surface-400">操作</th>
                </tr>
              </thead>
              <tbody>
                {filteredSchedules.map((s) => {
                  const pc = PLATFORM_COLORS[s.platform] || { bg: 'bg-gray-100', text: 'text-gray-700' }
                  return (
                    <tr key={s.id} className="border-b border-surface-200 hover:bg-surface-50 transition-colors">
                      <td className="py-3 px-4">
                        <input
                          type="checkbox"
                          checked={selectedIds.has(s.id)}
                          onChange={() => toggleSelect(s.id)}
                          className="rounded"
                        />
                      </td>
                      <td className="py-3 px-4 text-brand-500">{s.topic_title}</td>
                      <td className="py-3 px-4">
                        <span className={`status-badge text-xs ${pc.bg} ${pc.text}`}>
                          {s.platform}
                        </span>
                      </td>
                      <td className="py-3 px-4 text-surface-400">{formatDate(s.publish_date)}</td>
                      <td className="py-3 px-4 text-surface-400">{s.publish_time || '-'}</td>
                      <td className="py-3 px-4">
                        <span className={`status-badge text-xs ${SCHEDULE_STATUS_MAP[s.status].color}`}>
                          {SCHEDULE_STATUS_MAP[s.status].label}
                        </span>
                      </td>
                      <td className="py-3 px-4">
                        {s.status !== 'cancelled' && s.status !== 'published' && (
                          <button
                            onClick={() => handleCancel(s.id)}
                            className="btn-ghost text-xs text-red-500 hover:text-red-600"
                          >
                            取消排期
                          </button>
                        )}
                      </td>
                    </tr>
                  )
                })}
                {filteredSchedules.length === 0 && (
                  <tr>
                    <td colSpan={7} className="py-8 text-center text-sm text-surface-400">
                      暂无排期数据
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  )
}

// src/routes/schedule/+page.svelte
<script lang="ts">
	import { store } from '$lib/stores/mock-data.svelte';
	import {
		SCHEDULE_STATUS_LABELS,
		PLATFORM_COLORS
	} from '$lib/types';
	import type { ScheduleStatus } from '$lib/types';
	import {
		Plus,
		ChevronLeft,
		ChevronRight,
		X,
		List,
		CalendarDays,
		Clock
	} from 'lucide-svelte';

	let currentYear = $state(new Date().getFullYear());
	let currentMonth = $state(new Date().getMonth());
	let viewMode = $state<'calendar' | 'list'>('calendar');
	let showNewDialog = $state(false);

	let newTopicId = $state('');
	let newPlatform = $state('');
	let newAccountName = $state('');
	let newPublishDate = $state('');
	let newPublishTime = $state('');
	let newNotes = $state('');

	const weekdays = ['周一', '周二', '周三', '周四', '周五', '周六', '周日'];

	let calendarDays = $derived.by(() => {
		const firstDay = new Date(currentYear, currentMonth, 1);
		const lastDay = new Date(currentYear, currentMonth + 1, 0);
		let startDow = firstDay.getDay() - 1;
		if (startDow < 0) startDow = 6;
		const days: { date: Date; isCurrentMonth: boolean }[] = [];
		for (let i = startDow - 1; i >= 0; i--) {
			const d = new Date(currentYear, currentMonth, -i);
			days.push({ date: d, isCurrentMonth: false });
		}
		for (let i = 1; i <= lastDay.getDate(); i++) {
			days.push({ date: new Date(currentYear, currentMonth, i), isCurrentMonth: true });
		}
		const remaining = 7 - (days.length % 7);
		if (remaining < 7) {
			for (let i = 1; i <= remaining; i++) {
				days.push({ date: new Date(currentYear, currentMonth + 1, i), isCurrentMonth: false });
			}
		}
		return days;
	});

	let schedulesByDate = $derived.by(() => {
		const map = new Map<string, typeof store.schedules>();
		for (const s of store.schedules) {
			const key = s.publishDate;
			if (!map.has(key)) map.set(key, []);
			map.get(key)!.push(s);
		}
		return map;
	});

	let monthLabel = $derived(
		`${currentYear}年${currentMonth + 1}月`
	);

	function getTopicTitle(id: string) {
		return store.topics.find((t) => t.id === id)?.title ?? '未知选题';
	}

	function dateKey(d: Date) {
		return d.toISOString().slice(0, 10);
	}

	function isToday(d: Date) {
		const today = new Date();
		return d.getFullYear() === today.getFullYear() && d.getMonth() === today.getMonth() && d.getDate() === today.getDate();
	}

	function prevMonth() {
		if (currentMonth === 0) {
			currentMonth = 11;
			currentYear--;
		} else {
			currentMonth--;
		}
	}

	function nextMonth() {
		if (currentMonth === 11) {
			currentMonth = 0;
			currentYear++;
		} else {
			currentMonth++;
		}
	}

	function resetForm() {
		newTopicId = '';
		newPlatform = '';
		newAccountName = '';
		newPublishDate = '';
		newPublishTime = '';
		newNotes = '';
	}

	function handleCreate() {
		if (!newTopicId || !newPlatform || !newAccountName || !newPublishDate || !newPublishTime) return;
		store.addSchedule({
			topicId: newTopicId,
			platform: newPlatform,
			accountName: newAccountName,
			publishDate: newPublishDate,
			publishTime: newPublishTime,
			status: 'scheduled',
			supplementaryNotes: newNotes,
			createdBy: store.getCurrentUser().id
		});
		showNewDialog = false;
		resetForm();
	}

	function statusBadgeClass(status: ScheduleStatus) {
		const map: Record<ScheduleStatus, string> = {
			scheduled: 'bg-blue-100 text-blue-700',
			published: 'bg-success-light text-success',
			cancelled: 'bg-danger-light text-danger'
		};
		return map[status];
	}

	function platformColor(platform: string) {
		return PLATFORM_COLORS[platform] ?? '#e07a3a';
	}
</script>

<div class="min-h-screen bg-warm-gray">
	<div class="max-w-7xl mx-auto px-4 sm:px-6 py-6">
		<div class="flex flex-wrap items-center justify-between gap-4 mb-6">
			<h1 class="text-2xl font-bold text-ink">发布排期</h1>
			<div class="flex items-center gap-3">
				<div class="flex items-center bg-card rounded-lg shadow-sm">
					<button
						onclick={() => (viewMode = 'calendar')}
						class="p-2 rounded-l-lg {viewMode === 'calendar' ? 'bg-copper text-white' : 'text-ink/50 hover:text-ink'}"
					>
						<CalendarDays size={18} />
					</button>
					<button
						onclick={() => (viewMode = 'list')}
						class="p-2 rounded-r-lg {viewMode === 'list' ? 'bg-copper text-white' : 'text-ink/50 hover:text-ink'}"
					>
						<List size={18} />
					</button>
				</div>
				<button
					onclick={() => (showNewDialog = true)}
					class="flex items-center gap-2 bg-copper text-white px-4 py-2 rounded-lg hover:bg-copper-dark transition-colors"
				>
					<Plus size={18} />
					新建排期
				</button>
			</div>
		</div>

		{#if viewMode === 'calendar'}
			<div class="bg-card rounded-xl shadow-sm p-4 mb-6">
				<div class="flex items-center justify-between mb-4">
					<button onclick={prevMonth} class="p-2 hover:bg-warm-gray rounded-lg transition-colors">
						<ChevronLeft size={20} class="text-ink/50" />
					</button>
					<h2 class="text-lg font-bold text-ink">{monthLabel}</h2>
					<button onclick={nextMonth} class="p-2 hover:bg-warm-gray rounded-lg transition-colors">
						<ChevronRight size={20} class="text-ink/50" />
					</button>
				</div>

				<div class="grid grid-cols-7 gap-px bg-warm-gray-dark rounded-lg overflow-hidden">
					{#each weekdays as day}
						<div class="bg-card px-2 py-2 text-center text-xs font-semibold text-ink/50">
							{day}
						</div>
					{/each}
					{#each calendarDays as dayObj}
						{@const key = dateKey(dayObj.date)}
						{@const daySchedules = schedulesByDate.get(key) ?? []}
						<div
							class="bg-card min-h-[80px] sm:min-h-[100px] p-1.5 sm:p-2 transition-colors {dayObj.isCurrentMonth ? '' : 'opacity-40'}"
						>
							<div class="text-xs font-medium mb-1 {isToday(dayObj.date) ? 'w-6 h-6 rounded-full bg-copper text-white flex items-center justify-center' : 'text-ink/50'}">
								{dayObj.date.getDate()}
							</div>
							<div class="space-y-0.5">
								{#each daySchedules.slice(0, 3) as sch}
									<a
										href="/schedule/{sch.id}"
										class="block text-xs truncate rounded px-1 py-0.5 hover:bg-warm-gray transition-colors"
										style="border-left: 3px solid {platformColor(sch.platform)}"
									>
										<span class="font-medium text-ink/80">{getTopicTitle(sch.topicId).slice(0, 6)}</span>
										<span class="text-ink/40 ml-1">{sch.publishTime}</span>
									</a>
								{/each}
								{#if daySchedules.length > 3}
									<div class="text-xs text-ink/40 pl-1">+{daySchedules.length - 3} 更多</div>
								{/if}
							</div>
						</div>
					{/each}
				</div>
			</div>
		{:else}
			<div class="bg-card rounded-xl shadow-sm overflow-hidden">
				<div class="overflow-x-auto">
					<table class="w-full text-sm">
						<thead>
							<tr class="bg-warm-gray">
								<th class="text-left px-4 py-3 font-semibold text-ink/60">选题</th>
								<th class="text-left px-4 py-3 font-semibold text-ink/60">平台</th>
								<th class="text-left px-4 py-3 font-semibold text-ink/60">账号</th>
								<th class="text-left px-4 py-3 font-semibold text-ink/60">日期</th>
								<th class="text-left px-4 py-3 font-semibold text-ink/60">时间</th>
								<th class="text-left px-4 py-3 font-semibold text-ink/60">状态</th>
								<th class="text-left px-4 py-3 font-semibold text-ink/60">操作</th>
							</tr>
						</thead>
						<tbody>
							{#each store.schedules as sch}
								<tr class="border-t border-warm-gray-dark hover:bg-warm-gray/50 transition-colors">
									<td class="px-4 py-3">
										<span class="text-ink font-medium">{getTopicTitle(sch.topicId)}</span>
									</td>
									<td class="px-4 py-3">
										<span
											class="inline-flex items-center gap-1 text-xs px-2 py-0.5 rounded-full"
											style="background: {platformColor(sch.platform)}15; color: {platformColor(sch.platform)}"
										>
											<span class="w-1.5 h-1.5 rounded-full" style="background: {platformColor(sch.platform)}"></span>
											{sch.platform}
										</span>
									</td>
									<td class="px-4 py-3 text-ink/70">{sch.accountName}</td>
									<td class="px-4 py-3 text-ink/70">{sch.publishDate}</td>
									<td class="px-4 py-3 text-ink/70">{sch.publishTime}</td>
									<td class="px-4 py-3">
										<span class="text-xs px-2 py-0.5 rounded-full {statusBadgeClass(sch.status)}">
											{SCHEDULE_STATUS_LABELS[sch.status]}
										</span>
									</td>
									<td class="px-4 py-3">
										<a href="/schedule/{sch.id}" class="text-copper hover:underline text-sm">查看</a>
									</td>
								</tr>
							{/each}
						</tbody>
					</table>
				</div>
			</div>
		{/if}
	</div>
</div>

{#if showNewDialog}
	<div class="fixed inset-0 z-50 flex items-center justify-center bg-ink/40" onclick={() => (showNewDialog = false)}>
		<!-- svelte-ignore a11y_no_static_element_interactions -->
		<div class="bg-card rounded-2xl shadow-xl w-full max-w-lg mx-4 p-6" onclick={(e) => e.stopPropagation()}>
			<div class="flex items-center justify-between mb-5">
				<h2 class="text-lg font-bold text-ink">新建排期</h2>
				<button onclick={() => (showNewDialog = false)} class="text-ink/40 hover:text-ink">
					<X size={20} />
				</button>
			</div>
			<div class="space-y-4">
				<div>
					<label class="block text-sm font-medium text-ink/70 mb-1">关联选题</label>
					<select
						bind:value={newTopicId}
						class="w-full border border-warm-gray-dark rounded-lg px-3 py-2 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-copper/40"
					>
						<option value="">请选择选题</option>
						{#each store.topics as t}
							<option value={t.id}>{t.title}</option>
						{/each}
					</select>
				</div>
				<div>
					<label class="block text-sm font-medium text-ink/70 mb-1">发布平台</label>
					<input
						type="text"
						bind:value={newPlatform}
						class="w-full border border-warm-gray-dark rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-copper/40"
						placeholder="如：微信公众号、抖音"
					/>
				</div>
				<div>
					<label class="block text-sm font-medium text-ink/70 mb-1">账号名称</label>
					<input
						type="text"
						bind:value={newAccountName}
						class="w-full border border-warm-gray-dark rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-copper/40"
						placeholder="如：城市观察"
					/>
				</div>
				<div class="grid grid-cols-2 gap-3">
					<div>
						<label class="block text-sm font-medium text-ink/70 mb-1">发布日期</label>
						<input
							type="date"
							bind:value={newPublishDate}
							class="w-full border border-warm-gray-dark rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-copper/40"
						/>
					</div>
					<div>
						<label class="block text-sm font-medium text-ink/70 mb-1">发布时间</label>
						<input
							type="time"
							bind:value={newPublishTime}
							class="w-full border border-warm-gray-dark rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-copper/40"
						/>
					</div>
				</div>
				<div>
					<label class="block text-sm font-medium text-ink/70 mb-1">备注</label>
					<textarea
						bind:value={newNotes}
						rows="2"
						class="w-full border border-warm-gray-dark rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-copper/40"
						placeholder="补充说明"
					></textarea>
				</div>
			</div>
			<div class="flex justify-end gap-3 mt-6">
				<button
					onclick={() => (showNewDialog = false)}
					class="px-4 py-2 text-sm rounded-lg border border-warm-gray-dark text-ink/60 hover:bg-warm-gray transition-colors"
				>
					取消
				</button>
				<button
					onclick={handleCreate}
					disabled={!newTopicId || !newPlatform || !newAccountName || !newPublishDate || !newPublishTime}
					class="px-4 py-2 text-sm rounded-lg bg-copper text-white hover:bg-copper-dark transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
				>
					创建
				</button>
			</div>
		</div>
	</div>
{/if}
