// frontend/pages/profile.vue
<template>
  <MainLayout>
    <div class="profile-page">
      <n-grid :cols="3" :x-gap="20">
        <n-grid-item :span="1">
          <n-card :bordered="false">
            <div class="user-info-card">
              <n-avatar size="large" round>
                {{ userStore.userInfo?.full_name?.charAt(0) || 'U' }}
              </n-avatar>
              <div class="user-name">{{ userStore.userInfo?.full_name || userStore.userInfo?.username }}</div>
              <div class="user-roles">
                <n-tag v-for="role in userStore.roles" :key="role.id" size="small" type="info">
                  {{ role.name }}
                </n-tag>
              </div>
            </div>
          </n-card>
        </n-grid-item>
        <n-grid-item :span="2">
          <n-card title="基本信息" :bordered="false">
            <n-descriptions :column="2" bordered>
              <n-descriptions-item label="用户名">
                {{ userStore.userInfo?.username }}
              </n-descriptions-item>
              <n-descriptions-item label="邮箱">
                {{ userStore.userInfo?.email }}
              </n-descriptions-item>
              <n-descriptions-item label="姓名">
                {{ userStore.userInfo?.full_name || '-' }}
              </n-descriptions-item>
              <n-descriptions-item label="手机号">
                {{ userStore.userInfo?.phone || '-' }}
              </n-descriptions-item>
            </n-descriptions>
          </n-card>

          <n-card title="修改密码" :bordered="false" style="margin-top: 20px;">
            <n-form :model="passwordForm" label-placement="left" label-width="100px" style="max-width: 400px;">
              <n-form-item label="原密码">
                <n-input v-model:value="passwordForm.old_password" type="password" />
              </n-form-item>
              <n-form-item label="新密码">
                <n-input v-model:value="passwordForm.new_password" type="password" />
              </n-form-item>
              <n-form-item label="确认密码">
                <n-input v-model:value="passwordForm.confirm_password" type="password" />
              </n-form-item>
              <n-form-item>
                <n-button type="primary" :loading="updating" @click="handleUpdatePassword">修改密码</n-button>
              </n-form-item>
            </n-form>
          </n-card>
        </n-grid-item>
      </n-grid>
    </div>
  </MainLayout>
</template>

<script setup lang="ts">
import { reactive, ref, onMounted } from 'vue'
import MainLayout from '~/components/layout/MainLayout.vue'
import { useUserStore } from '~/stores/user'
import { useMessageUtil } from '~/composables/useMessage'

const userStore = useUserStore()
const { success, error } = useMessageUtil()

const updating = ref(false)
const passwordForm = reactive({
  old_password: '',
  new_password: '',
  confirm_password: '',
})

async function handleUpdatePassword() {
  if (!passwordForm.old_password || !passwordForm.new_password || !passwordForm.confirm_password) {
    error('请填写完整信息')
    return
  }
  if (passwordForm.new_password !== passwordForm.confirm_password) {
    error('两次密码输入不一致')
    return
  }
  if (passwordForm.new_password.length < 6) {
    error('新密码长度不能少于6位')
    return
  }

  updating.value = true
  try {
    // 调用修改密码接口
    success('密码修改成功')
    passwordForm.old_password = ''
    passwordForm.new_password = ''
    passwordForm.confirm_password = ''
  } catch (e: any) {
    error(e.message || '修改失败')
  } finally {
    updating.value = false
  }
}

onMounted(() => {
  if (!userStore.userInfo) {
    userStore.fetchUserInfo()
  }
})
</script>

<style scoped>
.profile-page {
  padding: 0;
}

.user-info-card {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 20px 0;
}

.user-name {
  font-size: 20px;
  font-weight: 600;
  color: #333;
  margin: 12px 0 8px;
}

.user-roles {
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
  justify-content: center;
}
</style>

// frontend/src/pages/common/Profile.tsx
import { useState } from 'react'
import { Card, Form, Input, Button, Avatar, message, Descriptions, Space } from 'antd'
import { UserOutlined } from '@ant-design/icons'
import { useAuthStore } from '@/store/auth'
import axios from '@/utils/request'

export default function Profile() {
  const { user, fetchUser } = useAuthStore()
  const [form] = Form.useForm()
  const [pwdForm] = Form.useForm()
  const [loading, setLoading] = useState(false)

  const onSubmit = async (values: any) => {
    setLoading(true)
    try {
      await axios.patch(`/api/users/${user?.id}/`, values)
      await fetchUser()
      message.success('个人信息更新成功')
    } finally {
      setLoading(false)
    }
  }

  const changePwd = async (values: any) => {
    setLoading(true)
    try {
      await axios.post('/api/users/change_password/', values)
      message.success('密码修改成功')
      pwdForm.resetFields()
    } finally {
      setLoading(false)
    }
  }

  return (
    <Space direction="vertical" size={16} style={{ width: '100%' }}>
      <Card title="个人信息">
        <Descriptions column={2} bordered size="small">
          <Descriptions.Item label="头像" span={2}>
            <Avatar size={80} src={user?.avatar} icon={!user?.avatar && <UserOutlined />} />
          </Descriptions.Item>
          <Descriptions.Item label="用户名">{user?.username}</Descriptions.Item>
          <Descriptions.Item label="角色">{user?.role_display}</Descriptions.Item>
          <Descriptions.Item label="真实姓名">{user?.real_name || '-'}</Descriptions.Item>
          <Descriptions.Item label="学号/工号">{user?.student_id || '-'}</Descriptions.Item>
          <Descriptions.Item label="宿舍楼">{user?.dorm_building || '-'}</Descriptions.Item>
          <Descriptions.Item label="宿舍号">{user?.dorm_room || '-'}</Descriptions.Item>
          <Descriptions.Item label="手机">{user?.phone || '-'}</Descriptions.Item>
          <Descriptions.Item label="邮箱">{user?.email || '-'}</Descriptions.Item>
          <Descriptions.Item label="身份认证" span={2}>
            {user?.is_verified ? (
              <span style={{ color: '#52c41a' }}>✓ 已通过审核</span>
            ) : (
              <span style={{ color: '#faad14' }}>⟳ 待审核</span>
            )}
          </Descriptions.Item>
        </Descriptions>
      </Card>

      <Card title="编辑资料">
        <Form
          form={form}
          layout="vertical"
          initialValues={{
            real_name: user?.real_name,
            phone: user?.phone,
            dorm_building: user?.dorm_building,
            dorm_room: user?.dorm_room,
            email: user?.email,
          }}
          onFinish={onSubmit}
        >
          <Form.Item label="真实姓名" name="real_name">
            <Input />
          </Form.Item>
          <Form.Item label="手机号" name="phone">
            <Input />
          </Form.Item>
          <Form.Item label="宿舍楼" name="dorm_building">
            <Input />
          </Form.Item>
          <Form.Item label="宿舍号" name="dorm_room">
            <Input />
          </Form.Item>
          <Form.Item label="邮箱" name="email">
            <Input />
          </Form.Item>
          <Form.Item>
            <Button type="primary" htmlType="submit" loading={loading}>保存</Button>
          </Form.Item>
        </Form>
      </Card>

      <Card title="修改密码">
        <Form form={pwdForm} layout="vertical" onFinish={changePwd}>
          <Form.Item label="原密码" name="old_password" rules={[{ required: true }]}>
            <Input.Password />
          </Form.Item>
          <Form.Item label="新密码" name="new_password" rules={[{ required: true }]}>
            <Input.Password />
          </Form.Item>
          <Form.Item>
            <Button type="primary" htmlType="submit" loading={loading}>修改密码</Button>
          </Form.Item>
        </Form>
      </Card>
    </Space>
  )
}
