// src/lib/components/charts/FunnelChart.svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import * as echarts from 'echarts';
	import type { FunnelDataPoint } from '@/lib/types';
	import { formatNumber, formatPercent } from '@/lib/utils/format';

	export let data: FunnelDataPoint[] = [];
	export let title = '转人工漏斗';

	let chartContainer: HTMLDivElement;
	let chart: echarts.ECharts | null = null;

	function initChart() {
		if (!chartContainer) return;

		chart = echarts.init(chartContainer);
		updateChart();
	}

	function updateChart() {
		if (!chart) return;

		const colors = ['#0c87f0', '#0ea5e9', '#06b6d4', '#14b8a6', '#10b981'];

		const option: echarts.EChartsOption = {
			title: {
				text: title,
				left: 'center',
				textStyle: {
					fontSize: 16,
					fontWeight: 600,
					color: '#0f172a'
				}
			},
			tooltip: {
				trigger: 'item',
				formatter: (params: any) => {
					const point = data[params.dataIndex];
					return `
                        <div style="font-weight: 600; margin-bottom: 4px;">${params.name}</div>
                        <div>会话量: <strong>${formatNumber(params.value)}</strong></div>
                        ${point.rate !== undefined ? `<div>转化率: <strong>${formatPercent(point.rate)}</strong></div>` : ''}
                    `;
				}
			},
			legend: {
				top: 30,
				data: data.map((d) => d.name)
			},
			series: [
				{
					name: '转化漏斗',
					type: 'funnel',
					left: '10%',
					top: 80,
					bottom: 20,
					width: '80%',
					min: 0,
					max: Math.max(...data.map((d) => d.value)),
					minSize: '20%',
					maxSize: '100%',
					sort: 'descending',
					gap: 2,
					label: {
						show: true,
						position: 'inside',
						formatter: (params: any) => {
							const point = data[params.dataIndex];
							return `${params.name}\n${formatNumber(params.value)}${point.rate !== undefined ? ` (${formatPercent(point.rate)})` : ''}`;
						},
						color: '#fff',
						fontSize: 12,
						fontWeight: 500
					},
					labelLine: {
						length: 10,
						lineStyle: {
							width: 1,
							type: 'solid'
						}
					},
					itemStyle: {
						borderColor: '#fff',
						borderWidth: 2
					},
					emphasis: {
						label: {
							fontSize: 14
						}
					},
					data: data.map((d, i) => ({
						value: d.value,
						name: d.name,
						itemStyle: {
							color: colors[i % colors.length]
						}
					}))
				}
			]
		};

		chart.setOption(option);
	}

	function handleResize() {
		chart?.resize();
	}

	$: if (chart && data) {
		updateChart();
	}

	onMount(() => {
		initChart();
		window.addEventListener('resize', handleResize);
	});

	onDestroy(() => {
		window.removeEventListener('resize', handleResize);
		chart?.dispose();
	});
</script>

<div bind:this={chartContainer} class="chart-container w-full h-[400px]" />

// app/components/charts/FunnelChart.tsx
import { useMemo, useState } from 'react';
import * as echarts from 'echarts';
import { ChartCard, BaseChart } from './BaseChart';
import type { FunnelResponse } from '@shared/types';
import { STAGE_DEFINITIONS } from '../../../scripts/metrics/definitions';
import { formatNumber } from '~/utils/format';

interface Props {
  data: FunnelResponse | null;
  loading: boolean;
}

export default function FunnelChart({ data, loading }: Props) {
  const [hoveredStage, setHoveredStage] = useState<string | null>(null);

  const option = useMemo((): echarts.EChartsOption => {
    if (!data) return {};

    const stageData = data.stages.map((s) => ({
      value: s.quantity,
      name: s.name,
      itemStyle: {
        color: new echarts.graphic.LinearGradient(0, 0, 1, 0, [
          { offset: 0, color: STAGE_DEFINITIONS[s.stage].color + 'CC' },
          { offset: 1, color: STAGE_DEFINITIONS[s.stage].color + '66' },
        ]),
      },
    }));

    return {
      tooltip: {
        trigger: 'item' as const,
        formatter: (params: any) => {
          const stage = data.stages.find((s) => s.name === params.name);
          if (!stage) return '';
          return `
            <div style="padding: 8px;">
              <div style="font-weight: 600; margin-bottom: 4px;">${stage.name}</div>
              <div>数量: ${formatNumber(stage.quantity, 0)}</div>
              <div>金额: ¥${formatNumber(stage.amount)}</div>
              <div>转化率: ${(stage.conversionRate * 100).toFixed(1)}%</div>
            </div>
          `;
        },
        backgroundColor: 'rgba(15, 23, 42, 0.95)',
        borderColor: 'rgba(71, 85, 105, 0.5)',
        textStyle: { color: '#E2E8F0' },
      },
      series: [
        {
          type: 'funnel',
          left: '10%',
          top: 20,
          bottom: 20,
          width: '80%',
          min: 0,
          max: Math.max(...data.stages.map((s) => s.quantity)),
          minSize: '30%',
          maxSize: '100%',
          sort: 'descending',
          gap: 3,
          label: {
            show: true,
            position: 'inside',
            formatter: '{b}\n{c}',
            color: '#fff',
            fontSize: 12,
          },
          labelLine: { show: false },
          itemStyle: {
            borderColor: 'rgba(15, 23, 42, 0.5)',
            borderWidth: 1,
          },
          emphasis: {
            label: { fontSize: 14, fontWeight: 'bold' },
          },
          data: stageData,
        },
      ],
    };
  }, [data]);

  return (
    <ChartCard title="临期漏斗" subtitle="入库→可售→临期→促销→报损/退货 全链路">
      {loading ? (
        <div className="h-[300px] flex items-center justify-center">
          <div className="w-8 h-8 border-2 border-slate-600 border-t-fresh-green rounded-full animate-spin" />
        </div>
      ) : (
        <BaseChart option={option} height={300} />
      )}
    </ChartCard>
  );
}
