// test-drive-dashboard/src/lib/components/FunnelChart.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import * as echarts from 'echarts';
  import type { FunnelData } from '$lib/types';

  interface Props {
    data: FunnelData | null;
  }

  let { data }: Props = $props();

  let chartEl: HTMLDivElement;
  let chart: echarts.ECharts;
  let activeTab: string = $state('overall');

  onMount(() => {
    chart = echarts.init(chartEl);
    const ro = new ResizeObserver(() => chart?.resize());
    ro.observe(chartEl);
    return () => ro.disconnect();
  });

  $effect(() => {
    if (!data || !chart) return;

    if (activeTab === 'overall') {
      renderOverallFunnel(data);
    } else {
      renderModelFunnel(data);
    }
  });

  function renderOverallFunnel(funnelData: FunnelData) {
    const maxVal = Math.max(...funnelData.stages.map(s => s.count), 1);
    chart.setOption({
      tooltip: {
        trigger: 'item',
        formatter: (params: Record<string, unknown>) => {
          const d = params.data as Record<string, unknown>;
          return `${d.name}<br/>数量: ${d.value}<br/>占比: ${((d.value as number) / maxVal * 100).toFixed(1)}%`;
        }
      },
      series: [{
        type: 'funnel',
        left: '10%',
        top: 30,
        bottom: 30,
        width: '80%',
        min: 0,
        max: maxVal,
        minSize: '0%',
        maxSize: '100%',
        sort: 'descending',
        gap: 4,
        label: {
          show: true,
          position: 'inside',
          formatter: (params: Record<string, unknown>) => {
            const d = params.data as Record<string, unknown>;
            return `${d.name}\n${d.value}`;
          },
          fontSize: 14,
          fontWeight: 'bold',
          color: '#fff'
        },
        itemStyle: {
          borderColor: '#fff',
          borderWidth: 1
        },
        data: funnelData.stages.map((s, i) => ({
          value: s.count,
          name: s.name,
          itemStyle: {
            color: ['#3b82f6', '#6366f1', '#8b5cf6', '#a855f7', '#ec4899'][i]
          }
        }))
      }]
    }, true);
  }

  function renderModelFunnel(funnelData: FunnelData) {
    const models = Object.keys(funnelData.by_model);
    const stageNames = ['预约提交', '确认到店', '实际到店', '完成试驾', '成交转化'];

    chart.setOption({
      tooltip: {
        trigger: 'axis',
        axisPointer: { type: 'shadow' }
      },
      legend: {
        data: stageNames,
        top: 0
      },
      grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
      },
      xAxis: {
        type: 'category',
        data: models,
        axisLabel: { rotate: 30, fontSize: 11 }
      },
      yAxis: {
        type: 'value'
      },
      series: stageNames.map((name, i) => ({
        name,
        type: 'bar',
        stack: 'total',
        data: models.map(m => {
          const stages = funnelData.by_model[m];
          return stages[i]?.count || 0;
        }),
        itemStyle: {
          color: ['#3b82f6', '#6366f1', '#8b5cf6', '#a855f7', '#ec4899'][i]
        }
      }))
    }, true);
  }
</script>

<div class="panel">
  <div class="panel-header">
    <h3>预约漏斗</h3>
    <div class="tab-group">
      <button class:active={activeTab === 'overall'} onclick={() => activeTab = 'overall'}>总览</button>
      <button class:active={activeTab === 'model'} onclick={() => activeTab = 'model'}>按车型</button>
    </div>
  </div>
  <div class="chart-container" bind:this={chartEl}></div>
</div>

<style>
  .panel {
    background: #fff;
    border-radius: 12px;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.08);
    padding: 20px;
    height: 420px;
    display: flex;
    flex-direction: column;
  }

  .panel-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 12px;
  }

  .panel-header h3 {
    font-size: 16px;
    font-weight: 600;
    color: #1f2937;
    margin: 0;
  }

  .tab-group {
    display: flex;
    gap: 4px;
    background: #f3f4f6;
    border-radius: 8px;
    padding: 2px;
  }

  .tab-group button {
    padding: 4px 14px;
    border: none;
    border-radius: 6px;
    font-size: 12px;
    cursor: pointer;
    background: transparent;
    color: #6b7280;
    transition: all 0.2s;
  }

  .tab-group button.active {
    background: #fff;
    color: #3b82f6;
    box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);
    font-weight: 500;
  }

  .chart-container {
    flex: 1;
    min-height: 0;
  }
</style>

// app/components/charts/FunnelChart.tsx
import { useMemo, useState } from 'react';
import * as echarts from 'echarts';
import { ChartCard, BaseChart } from './BaseChart';
import type { FunnelResponse } from '@shared/types';
import { STAGE_DEFINITIONS } from '../../../scripts/metrics/definitions';
import { formatNumber } from '~/utils/format';

interface Props {
  data: FunnelResponse | null;
  loading: boolean;
}

export default function FunnelChart({ data, loading }: Props) {
  const [hoveredStage, setHoveredStage] = useState<string | null>(null);

  const option = useMemo((): echarts.EChartsOption => {
    if (!data) return {};

    const stageData = data.stages.map((s) => ({
      value: s.quantity,
      name: s.name,
      itemStyle: {
        color: new echarts.graphic.LinearGradient(0, 0, 1, 0, [
          { offset: 0, color: STAGE_DEFINITIONS[s.stage].color + 'CC' },
          { offset: 1, color: STAGE_DEFINITIONS[s.stage].color + '66' },
        ]),
      },
    }));

    return {
      tooltip: {
        trigger: 'item' as const,
        formatter: (params: any) => {
          const stage = data.stages.find((s) => s.name === params.name);
          if (!stage) return '';
          return `
            <div style="padding: 8px;">
              <div style="font-weight: 600; margin-bottom: 4px;">${stage.name}</div>
              <div>数量: ${formatNumber(stage.quantity, 0)}</div>
              <div>金额: ¥${formatNumber(stage.amount)}</div>
              <div>转化率: ${(stage.conversionRate * 100).toFixed(1)}%</div>
            </div>
          `;
        },
        backgroundColor: 'rgba(15, 23, 42, 0.95)',
        borderColor: 'rgba(71, 85, 105, 0.5)',
        textStyle: { color: '#E2E8F0' },
      },
      series: [
        {
          type: 'funnel',
          left: '10%',
          top: 20,
          bottom: 20,
          width: '80%',
          min: 0,
          max: Math.max(...data.stages.map((s) => s.quantity)),
          minSize: '30%',
          maxSize: '100%',
          sort: 'descending',
          gap: 3,
          label: {
            show: true,
            position: 'inside',
            formatter: '{b}\n{c}',
            color: '#fff',
            fontSize: 12,
          },
          labelLine: { show: false },
          itemStyle: {
            borderColor: 'rgba(15, 23, 42, 0.5)',
            borderWidth: 1,
          },
          emphasis: {
            label: { fontSize: 14, fontWeight: 'bold' },
          },
          data: stageData,
        },
      ],
    };
  }, [data]);

  return (
    <ChartCard title="临期漏斗" subtitle="入库→可售→临期→促销→报损/退货 全链路">
      {loading ? (
        <div className="h-[300px] flex items-center justify-center">
          <div className="w-8 h-8 border-2 border-slate-600 border-t-fresh-green rounded-full animate-spin" />
        </div>
      ) : (
        <BaseChart option={option} height={300} />
      )}
    </ChartCard>
  );
}
