// src/lib/components/AnomalyCard.svelte
<script lang="ts">
  import { AlertTriangle, ChevronRight, Clock, User } from 'lucide-svelte';
  import { formatDate, formatPercent, severityLabel, statusLabel, formatNumber } from '$utils';
  import type { AnomalyRecord } from '$types';

  export let anomaly: AnomalyRecord;
  export let showDetails: boolean = true;

  $: severityClass = {
    low: 'bg-slate-100 text-slate-700',
    medium: 'bg-warning-100 text-warning-700',
    high: 'bg-orange-100 text-orange-700',
    critical: 'bg-danger-100 text-danger-700'
  }[anomaly.severity] || 'bg-slate-100 text-slate-700';

  $: statusClass = {
    open: 'bg-danger-100 text-danger-700',
    investigating: 'bg-warning-100 text-warning-700',
    resolved: 'bg-accent-100 text-accent-700',
    ignored: 'bg-slate-100 text-slate-700'
  }[anomaly.status] || 'bg-slate-100 text-slate-700';

  $: isNegative = anomaly.deviation < 0;
</script>

<a 
  href="/anomalies/{anomaly.id}"
  class="card card-hover p-4 block group"
>
  <div class="flex items-start justify-between gap-4">
    <div class="flex items-start gap-3 flex-1 min-w-0">
      <div class={`p-2 rounded-lg flex-shrink-0 ${severityClass}`}>
        <AlertTriangle class="w-5 h-5" />
      </div>
      
      <div class="flex-1 min-w-0">
        <div class="flex items-center gap-2 mb-1">
          <h4 class="font-medium text-slate-900 truncate">{anomaly.metricName}</h4>
          <span class={`badge ${severityClass}`}>{severityLabel(anomaly.severity)}</span>
        </div>
        
        {#if showDetails}
          <p class="text-sm text-slate-500 line-clamp-2 mb-2">{anomaly.description}</p>
          
          <div class="flex items-center gap-4 text-xs text-slate-500">
            <span class="flex items-center gap-1">
              <Clock class="w-3.5 h-3.5" />
              {formatDate(anomaly.date)}
            </span>
            <span>
              波动：<span class={isNegative ? 'text-danger-600' : 'text-accent-600'}>
                {formatPercent(anomaly.deviationPercent, 1)}
              </span>
            </span>
          </div>
        {/if}
      </div>
    </div>

    <div class="flex items-center gap-2 flex-shrink-0">
      <span class={`badge ${statusClass}`}>{statusLabel(anomaly.status)}</span>
      <ChevronRight class="w-4 h-4 text-slate-400 group-hover:text-primary-500 transition-colors" />
    </div>
  </div>
</a>

// src/components/AnomalyCard.tsx
import { Eye, UserPlus, Clock, User } from "lucide-react";
import { cn, formatRelativeTime, formatPercent } from "@/lib/utils";
import type { Anomaly } from "@/types";
import { StatusBadge } from "./StatusBadge";
import { Button } from "./Button";

interface AnomalyCardProps {
  anomaly: Anomaly;
  onView?: () => void;
  onAssign?: () => void;
  className?: string;
}

const severityMap: Record<string, "normal" | "warning" | "critical" | "info"> = {
  LOW: "info",
  MEDIUM: "warning",
  HIGH: "warning",
  CRITICAL: "critical",
};

const statusMap: Record<string, "pending" | "warning" | "success"> = {
  PENDING: "pending",
  PROCESSING: "warning",
  RESOLVED: "success",
};

const statusLabelMap: Record<string, string> = {
  PENDING: "待处理",
  PROCESSING: "处理中",
  RESOLVED: "已解决",
};

const severityLabelMap: Record<string, string> = {
  LOW: "低",
  MEDIUM: "中",
  HIGH: "高",
  CRITICAL: "严重",
};

export function AnomalyCard({ anomaly, onView, onAssign, className }: AnomalyCardProps) {
  const isCritical = anomaly.severity === "CRITICAL";
  const deviationColor = anomaly.deviationPercent > 0 ? "text-danger" : "text-success";

  return (
    <div
      className={cn(
        "bg-card rounded-xl border shadow-card transition-all duration-300 hover:shadow-card-hover hover:-translate-y-0.5 overflow-hidden",
        isCritical && "animate-breathe",
        className
      )}
    >
      <div
        className={cn(
          "h-1 w-full",
          anomaly.severity === "CRITICAL" && "bg-danger",
          anomaly.severity === "HIGH" && "bg-orange-500",
          anomaly.severity === "MEDIUM" && "bg-warning",
          anomaly.severity === "LOW" && "bg-blue-500"
        )}
      />
      <div className="p-5">
        <div className="flex items-start justify-between mb-3">
          <div className="flex-1 min-w-0">
            <h3 className="text-base font-semibold text-foreground mb-2 truncate">
              {anomaly.metricName}
            </h3>
            <div className="flex items-center gap-2 flex-wrap">
              <StatusBadge status={severityMap[anomaly.severity] || "info"} size="sm">
                {severityLabelMap[anomaly.severity] || "未知"}
              </StatusBadge>
              <StatusBadge status={statusMap[anomaly.status] || "pending"} size="sm">
                {statusLabelMap[anomaly.status] || "未知"}
              </StatusBadge>
            </div>
          </div>
        </div>

        <div className="space-y-2 mb-4">
          <div className="flex items-center justify-between text-sm">
            <span className="text-muted">异常值</span>
            <span className="font-semibold text-foreground font-display">
              {anomaly.actualValue.toLocaleString()}
            </span>
          </div>
          <div className="flex items-center justify-between text-sm">
            <span className="text-muted">偏离幅度</span>
            <span className={cn("font-semibold", deviationColor)}>
              {anomaly.deviationPercent > 0 ? "+" : ""}
              {formatPercent(anomaly.deviationPercent)}
            </span>
          </div>
          <div className="flex items-center justify-between text-sm">
            <span className="text-muted">检测时间</span>
            <span className="text-foreground flex items-center gap-1">
              <Clock className="w-3.5 h-3.5 text-muted" />
              {formatRelativeTime(anomaly.detectedAt)}
            </span>
          </div>
        </div>

        <div className="flex items-center justify-between pt-4 border-t border-card-border">
          {anomaly.assigneeName ? (
            <div className="flex items-center gap-2">
              <div className="w-7 h-7 rounded-full bg-primary/10 flex items-center justify-center">
                <User className="w-4 h-4 text-primary" />
              </div>
              <span className="text-sm text-foreground">{anomaly.assigneeName}</span>
            </div>
          ) : (
            <div className="flex items-center gap-2 text-muted">
              <User className="w-4 h-4" />
              <span className="text-sm">未分配</span>
            </div>
          )}
          <div className="flex items-center gap-2">
            {anomaly.status !== "RESOLVED" && !anomaly.assignee && (
              <Button
                variant="outline"
                size="sm"
                onClick={onAssign}
                leftIcon={<UserPlus className="w-4 h-4" />}
              >
                认领
              </Button>
            )}
            <Button
              variant="primary"
              size="sm"
              onClick={onView}
              leftIcon={<Eye className="w-4 h-4" />}
            >
              查看
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
