// src/lib/components/charts/BaseChart.svelte
<script lang="ts">
  import { onMount, onDestroy, beforeUpdate, browser } from 'svelte';
  import * as echarts from 'echarts';
  import type { EChartsOption, ECharts } from 'echarts';

  export let option: EChartsOption;
  export let theme: string | null = 'dark';
  export let height: string = '100%';
  export let width: string = '100%';

  let chartContainer: HTMLDivElement;
  let chart: ECharts | null = null;

  function initChart() {
    if (!browser || !chartContainer || chart) return;
    
    chart = echarts.init(chartContainer, theme);
    chart.setOption(option);
    
    if (typeof window !== 'undefined') {
      window.addEventListener('resize', handleResize);
    }
  }

  function handleResize() {
    if (chart) {
      chart.resize();
    }
  }

  onMount(() => {
    if (browser) {
      initChart();
    }
  });

  beforeUpdate(() => {
    if (chart && browser) {
      chart.setOption(option, { notMerge: true });
    }
  });

  onDestroy(() => {
    if (typeof window !== 'undefined') {
      window.removeEventListener('resize', handleResize);
    }
    if (chart) {
      chart.dispose();
      chart = null;
    }
  });

  export function getChartInstance() {
    return chart;
  }
</script>

<div bind:this={chartContainer} style="width: {width}; height: {height};"></div>

// src/components/BaseChart.vue
<template>
  <div ref="chartRef" :style="{ width, height }"></div>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount, watch } from 'vue'
import * as echarts from 'echarts'

const props = defineProps<{
  option: any
  width?: string
  height?: string
}>()

const emit = defineEmits<{
  (e: 'click', params: any): void
}>()

const chartRef = ref<HTMLDivElement>()
let chartInstance: echarts.ECharts | null = null

function initChart() {
  if (!chartRef.value) return
  chartInstance = echarts.init(chartRef.value)
  chartInstance.setOption(props.option)
  chartInstance.on('click', (params: any) => {
    emit('click', params)
  })
}

function resizeChart() {
  chartInstance?.resize()
}

onMounted(() => {
  initChart()
  window.addEventListener('resize', resizeChart)
})

onBeforeUnmount(() => {
  window.removeEventListener('resize', resizeChart)
  chartInstance?.dispose()
})

watch(
  () => props.option,
  (newOption) => {
    chartInstance?.setOption(newOption, true)
  },
  { deep: true }
)
</script>
