// components/ChartCard.tsx
"use client";

import { Download, MoreHorizontal, Info } from "lucide-react";
import SampleSizeIndicator from "./SampleSizeIndicator";
import { useState } from "react";

interface ChartCardProps {
  title: string;
  subtitle?: string;
  sampleSize?: number;
  onExport?: () => void;
  infoTooltip?: string;
  children: React.ReactNode;
}

export default function ChartCard({
  title,
  subtitle,
  sampleSize,
  onExport,
  infoTooltip,
  children,
}: ChartCardProps) {
  const [showInfo, setShowInfo] = useState(false);

  return (
    <div className="bg-white rounded-xl border border-slate-200 overflow-hidden hover:shadow-md transition-all duration-300">
      <div className="px-5 py-4 border-b border-slate-100">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <h3 className="font-display text-lg font-semibold text-slate-800">{title}</h3>
            {infoTooltip && (
              <div className="relative">
                <button
                  onMouseEnter={() => setShowInfo(true)}
                  onMouseLeave={() => setShowInfo(false)}
                  className="text-slate-400 hover:text-slate-600 transition-colors"
                >
                  <Info className="w-4 h-4" />
                </button>
                {showInfo && (
                  <div className="absolute left-0 top-full mt-1 w-64 p-3 bg-slate-800 text-white text-xs rounded-lg z-10 animate-fade-in">
                    {infoTooltip}
                  </div>
                )}
              </div>
            )}
          </div>
          <div className="flex items-center gap-2">
            {sampleSize !== undefined && <SampleSizeIndicator sampleSize={sampleSize} showLabel={false} />}
            {onExport && (
              <button
                onClick={onExport}
                className="p-1.5 rounded-md text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition-colors"
              >
                <Download className="w-4 h-4" />
              </button>
            )}
          </div>
        </div>
        {subtitle && <p className="text-xs text-slate-500 mt-1">{subtitle}</p>}
      </div>
      <div className="p-4">{children}</div>
    </div>
  );
}

// src/components/ChartCard.vue
<script setup lang="ts">
import { Download, Loader2, AlertCircle, Database } from 'lucide-vue-next';

interface Props {
  title: string;
  sampleSize?: number;
  loading?: boolean;
  error?: string | null;
  showExport?: boolean;
  large?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  showExport: false,
  large: false
});

const emit = defineEmits<{
  (e: 'export'): void;
}>();
</script>

<template>
  <div
    :class="[
      'bg-white rounded-xl border border-slate-200 shadow-sm flex flex-col overflow-hidden',
      large ? 'col-span-2 row-span-2' : ''
    ]"
  >
    <div class="flex items-center justify-between px-5 py-4 border-b border-slate-100">
      <div class="flex items-center gap-3">
        <h3 class="font-semibold text-slate-800">{{ title }}</h3>
        <div v-if="sampleSize !== undefined" class="flex items-center gap-1 text-xs text-slate-400">
          <Database class="w-3 h-3" />
          <span>样本量: {{ sampleSize.toLocaleString() }}</span>
        </div>
      </div>
      <div class="flex items-center gap-2">
        <div v-if="loading" class="flex items-center gap-2 text-sm text-slate-400">
          <Loader2 class="w-4 h-4 animate-spin" />
          <span>加载中</span>
        </div>
        <div v-else-if="error" class="flex items-center gap-1 text-sm text-rose-500">
          <AlertCircle class="w-4 h-4" />
          <span>数据异常</span>
        </div>
        <button
          v-if="showExport && !loading"
          class="p-2 text-slate-400 hover:text-slate-600 hover:bg-slate-100 rounded-lg transition-colors"
          @click="emit('export')"
          title="导出数据"
        >
          <Download class="w-4 h-4" />
        </button>
      </div>
    </div>
    <div class="flex-1 p-4 min-h-0 relative">
      <slot />
      <div v-if="loading" class="absolute inset-0 bg-white/60 flex items-center justify-center z-10">
        <Loader2 class="w-8 h-8 animate-spin text-teal-600" />
      </div>
    </div>
  </div>
</template>
