// src/components/common/FilterBar.vue
<script setup lang="ts">
import { Search, X } from 'lucide-vue-next'

interface FilterOption {
  label: string
  value: string | number
}

interface FilterField {
  key: string
  label: string
  type: 'select' | 'dateRange'
  options?: FilterOption[]
}

const props = defineProps<{
  fields: FilterField[]
  modelValue: Record<string, unknown>
}>()

const emit = defineEmits<{
  (e: 'update:modelValue', value: Record<string, unknown>): void
  (e: 'search'): void
  (e: 'reset'): void
}>()

function updateField(key: string, value: unknown) {
  emit('update:modelValue', { ...props.modelValue, [key]: value })
}

function reset() {
  const cleared: Record<string, unknown> = {}
  props.fields.forEach((f) => {
    cleared[f.key] = f.type === 'dateRange' ? [] : ''
  })
  emit('update:modelValue', cleared)
  emit('reset')
}
</script>

<template>
  <div class="bg-white rounded-lg border border-slate-200 p-4 mb-4">
    <div class="flex flex-wrap items-end gap-4">
      <template v-for="field in fields" :key="field.key">
        <div v-if="field.type === 'select'" class="flex flex-col gap-1">
          <label class="text-xs text-slate-500">{{ field.label }}</label>
          <select
            class="h-9 px-3 rounded-md border border-slate-300 text-sm text-slate-700 bg-white focus:outline-none focus:ring-1 focus:ring-amber-500 focus:border-amber-500"
            :value="modelValue[field.key] || ''"
            @change="updateField(field.key, ($event.target as HTMLSelectElement).value)"
          >
            <option value="">全部</option>
            <option v-for="opt in field.options" :key="opt.value" :value="opt.value">
              {{ opt.label }}
            </option>
          </select>
        </div>

        <div v-else-if="field.type === 'dateRange'" class="flex flex-col gap-1">
          <label class="text-xs text-slate-500">{{ field.label }}</label>
          <div class="flex items-center gap-2">
            <input
              type="date"
              class="h-9 px-3 rounded-md border border-slate-300 text-sm text-slate-700 focus:outline-none focus:ring-1 focus:ring-amber-500 focus:border-amber-500"
              :value="(modelValue[field.key] as string[])?.[0] || ''"
              @input="updateField(field.key, [($event.target as HTMLInputElement).value, (modelValue[field.key] as string[])?.[1] || ''])"
            />
            <span class="text-slate-400 text-sm">至</span>
            <input
              type="date"
              class="h-9 px-3 rounded-md border border-slate-300 text-sm text-slate-700 focus:outline-none focus:ring-1 focus:ring-amber-500 focus:border-amber-500"
              :value="(modelValue[field.key] as string[])?.[1] || ''"
              @input="updateField(field.key, [(modelValue[field.key] as string[])?.[0] || '', ($event.target as HTMLInputElement).value])"
            />
          </div>
        </div>
      </template>

      <div class="flex items-center gap-2">
        <button
          class="h-9 px-4 bg-amber-500 text-white text-sm rounded-md hover:bg-amber-600 transition-colors flex items-center gap-1"
          @click="emit('search')"
        >
          <Search class="w-4 h-4" />
          查询
        </button>
        <button
          class="h-9 px-4 bg-white text-slate-600 text-sm rounded-md border border-slate-300 hover:bg-slate-50 transition-colors flex items-center gap-1"
          @click="reset"
        >
          <X class="w-4 h-4" />
          重置
        </button>
      </div>
    </div>
  </div>
</template>

// src/components/filter-bar.tsx
"use client";

import { useState } from "react";
import { Search, Filter, X } from "lucide-react";
import { cn } from "@/lib/utils";

interface FilterOption {
  label: string;
  value: string;
}

interface FilterConfig {
  key: string;
  label: string;
  type: "select" | "date" | "search" | "text";
  options?: FilterOption[];
  placeholder?: string;
}

interface FilterBarProps {
  filters: FilterConfig[];
  values: Record<string, any>;
  onChange: (values: Record<string, any>) => void;
  onReset: () => void;
  className?: string;
}

export function FilterBar({ filters, values, onChange, onReset, className }: FilterBarProps) {
  const [isExpanded, setIsExpanded] = useState(false);

  const handleChange = (key: string, value: any) => {
    onChange({ ...values, [key]: value });
  };

  const hasActiveFilters = Object.values(values).some((v) => v !== undefined && v !== "" && v !== null);

  return (
    <div className={cn("bg-white rounded-xl border border-zinc-200 p-4", className)}>
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <Filter className="h-5 w-5 text-zinc-500" />
          <h3 className="font-semibold text-zinc-900">筛选条件</h3>
        </div>
        <div className="flex items-center gap-2">
          {hasActiveFilters && (
            <button
              onClick={onReset}
              className="flex items-center gap-1 text-sm text-zinc-500 hover:text-zinc-700"
            >
              <X className="h-4 w-4" />
              重置
            </button>
          )}
          <button
            onClick={() => setIsExpanded(!isExpanded)}
            className="text-sm text-zinc-600 hover:text-zinc-900"
          >
            {isExpanded ? "收起" : "展开"}
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {filters.slice(0, isExpanded ? filters.length : 4).map((filter) => (
          <div key={filter.key}>
            <label className="block text-sm font-medium text-zinc-700 mb-1">
              {filter.label}
            </label>
            {filter.type === "select" && (
              <select
                value={values[filter.key] || ""}
                onChange={(e) => handleChange(filter.key, e.target.value || undefined)}
                className="w-full rounded-lg border border-zinc-200 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-zinc-900"
              >
                <option value="">全部</option>
                {filter.options?.map((opt) => (
                  <option key={opt.value} value={opt.value}>
                    {opt.label}
                  </option>
                ))}
              </select>
            )}
            {filter.type === "date" && (
              <input
                type="date"
                value={values[filter.key] ? new Date(values[filter.key]).toISOString().split('T')[0] : ""}
                onChange={(e) => handleChange(filter.key, e.target.value ? new Date(e.target.value) : undefined)}
                className="w-full rounded-lg border border-zinc-200 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-zinc-900"
              />
            )}
            {filter.type === "text" && (
              <input
                type="text"
                value={values[filter.key] || ""}
                onChange={(e) => handleChange(filter.key, e.target.value || undefined)}
                placeholder={filter.placeholder}
                className="w-full rounded-lg border border-zinc-200 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-zinc-900"
              />
            )}
            {filter.type === "search" && (
              <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-zinc-400" />
                <input
                  type="text"
                  value={values[filter.key] || ""}
                  onChange={(e) => handleChange(filter.key, e.target.value || undefined)}
                  placeholder={filter.placeholder}
                  className="w-full rounded-lg border border-zinc-200 pl-9 pr-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-zinc-900"
                />
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
