// src/components/Cards/KPICard.tsx
import React from 'react';
import { TrendingUp, TrendingDown, Users, AlertTriangle } from 'lucide-react';
import { KPICardData } from '../../data/types';

interface KPICardProps {
  data: KPICardData;
  delay?: number;
}

export const KPICard: React.FC<KPICardProps> = ({ data, delay = 0 }) => {
  const isPositive = data.trend >= 0;
  
  return (
    <div
      className="bg-white rounded-xl shadow-sm border border-gray-100 p-5 hover:shadow-md transition-all duration-300"
      style={{
        animation: `fadeInUp 0.5s ease-out ${delay}ms both`,
      }}
    >
      <div className="flex items-start justify-between mb-3">
        <span className="text-sm font-medium text-gray-500">{data.title}</span>
        {data.isLowSample && (
          <div className="flex items-center gap-1 text-xs text-amber-600 bg-amber-50 px-2 py-0.5 rounded-full">
            <AlertTriangle size={12} />
            <span>样本量小</span>
          </div>
        )}
      </div>
      
      <div className="flex items-end gap-3">
        <div className="text-3xl font-bold text-gray-800">
          {data.value.toFixed(1)}
          <span className="text-lg font-normal text-gray-500 ml-1">{data.unit}</span>
        </div>
        
        <div className={`flex items-center gap-1 text-sm font-medium ${
          isPositive ? 'text-green-600' : 'text-red-500'
        }`}>
          {isPositive ? <TrendingUp size={16} /> : <TrendingDown size={16} />}
          <span>{Math.abs(data.trend).toFixed(1)}%</span>
        </div>
      </div>
      
      <div className="mt-3 flex items-center gap-1.5 text-xs text-gray-400">
        <Users size={12} />
        <span>样本量: {data.sampleSize}</span>
      </div>
    </div>
  );
};

// src/components/KPICard.vue
<script setup lang="ts">
import { TrendingUp, TrendingDown, Users, Clock, TicketCheck, DollarSign } from 'lucide-vue-next';
import { computed } from 'vue';
import { formatNumber } from '@/data/cleaner';

interface Props {
  title: string;
  value: number | string;
  change?: number;
  icon: 'users' | 'clock' | 'ticket' | 'dollar';
  suffix?: string;
  decimals?: number;
}

const props = withDefaults(defineProps<Props>(), {
  suffix: '',
  decimals: 0
});

const iconComponent = computed(() => {
  const icons = { users: Users, clock: Clock, ticket: TicketCheck, dollar: DollarSign };
  return icons[props.icon];
});

const isPositive = computed(() => props.change !== undefined && props.change >= 0);
const displayValue = computed(() => {
  if (typeof props.value === 'string') return props.value;
  return formatNumber(props.value, props.decimals);
});
</script>

<template>
  <div class="bg-white rounded-xl border border-slate-200 p-5 shadow-sm hover:shadow-md transition-shadow duration-200">
    <div class="flex items-start justify-between">
      <div class="flex-1">
        <p class="text-sm font-medium text-slate-500 mb-1">{{ title }}</p>
        <p class="text-2xl font-bold text-slate-800 tracking-tight">
          {{ displayValue }}{{ suffix }}
        </p>
        <div v-if="change !== undefined" class="flex items-center mt-2">
          <component
            :is="isPositive ? TrendingUp : TrendingDown"
            :class="isPositive ? 'text-emerald-600' : 'text-rose-600'"
            class="w-4 h-4 mr-1"
          />
          <span
            :class="isPositive ? 'text-emerald-600' : 'text-rose-600'"
            class="text-sm font-medium"
          >
            {{ Math.abs(change).toFixed(1) }}%
          </span>
          <span class="text-slate-400 text-sm ml-1">较昨日</span>
        </div>
      </div>
      <div class="w-11 h-11 rounded-lg bg-teal-50 flex items-center justify-center">
        <component :is="iconComponent" class="w-6 h-6 text-teal-700" />
      </div>
    </div>
  </div>
</template>
