// src/layouts/MainLayout.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import {
  Home,
  ListTodo,
  BarChart3,
  Settings,
  Users,
  LogOut,
  ChevronRight,
} from 'lucide-vue-next'
import { cn } from '@/lib/utils'

export type UserRole = 'pm' | 'admin'

export interface CurrentUser {
  id: string
  name: string
  role: UserRole
}

const route = useRoute()
const router = useRouter()

const currentUser = ref<CurrentUser | null>(null)

const userInfo = computed(() => {
  const stored = localStorage.getItem('user')
  if (stored) {
    try {
      currentUser.value = JSON.parse(stored)
      return currentUser.value
    } catch {
      return null
    }
  }
  return null
})

const isAdmin = computed(() => userInfo.value?.role === 'admin')

const menuItems = computed(() => {
  const items = [
    { path: '/', label: '首页', icon: Home, roles: ['pm', 'admin'] as UserRole[] },
    { path: '/items', label: '事项管理', icon: ListTodo, roles: ['pm', 'admin'] as UserRole[] },
  ]
  
  if (isAdmin.value) {
    items.push(
      { path: '/operations', label: '运营后台', icon: BarChart3, roles: ['admin'] as UserRole[] },
      { path: '/settings', label: '配置页', icon: Settings, roles: ['admin'] as UserRole[] },
      { path: '/users', label: '用户管理', icon: Users, roles: ['admin'] as UserRole[] },
    )
  }
  
  return items
})

const breadcrumbItems = computed(() => {
  const matched = route.matched.filter(item => item.meta?.title)
  return matched.map(item => ({
    title: item.meta?.title as string,
    path: item.path,
  }))
})

function isActive(path: string) {
  if (path === '/') {
    return route.path === '/'
  }
  return route.path.startsWith(path)
}

function handleLogout() {
  localStorage.removeItem('token')
  localStorage.removeItem('user')
  router.push('/login')
}

function navigateTo(path: string) {
  router.push(path)
}
</script>

<template>
  <div class="flex h-screen bg-surface">
    <aside class="w-[240px] bg-primary flex-shrink-0 flex flex-col shadow-lg">
      <div class="h-16 flex items-center px-6 border-b border-white/10">
        <span class="text-white font-bold text-lg">事项管理系统</span>
      </div>
      
      <nav class="flex-1 py-4 overflow-y-auto">
        <ul class="space-y-1 px-3">
          <li v-for="item in menuItems" :key="item.path">
            <button
              @click="navigateTo(item.path)"
              class="w-full flex items-center gap-3 px-4 py-3 rounded-lg transition-all duration-200"
              :class="[
                isActive(item.path)
                  ? 'bg-accent text-primary font-medium'
                  : 'text-white/80 hover:bg-white/10 hover:text-white'
              ]"
            >
              <component :is="item.icon" class="w-5 h-5" />
              <span>{{ item.label }}</span>
            </button>
          </li>
        </ul>
      </nav>
      
      <div class="p-4 border-t border-white/10">
        <button
          @click="handleLogout"
          class="w-full flex items-center gap-3 px-4 py-3 rounded-lg text-white/60 hover:bg-white/10 hover:text-white transition-all duration-200"
        >
          <LogOut class="w-5 h-5" />
          <span>退出登录</span>
        </button>
      </div>
    </aside>
    
    <div class="flex-1 flex flex-col overflow-hidden">
      <header class="h-16 bg-white border-b border-gray-200 flex items-center justify-between px-6 shadow-sm">
        <div class="flex items-center gap-2 text-sm">
          <template v-for="(item, index) in breadcrumbItems" :key="item.path">
            <span
              v-if="index === breadcrumbItems.length - 1"
              class="text-gray-900 font-medium"
            >
              {{ item.title }}
            </span>
            <router-link
              v-else
              :to="item.path"
              class="text-gray-500 hover:text-primary transition-colors"
            >
              {{ item.title }}
            </router-link>
            <ChevronRight
              v-if="index < breadcrumbItems.length - 1"
              class="w-4 h-4 text-gray-400"
            />
          </template>
        </div>
        
        <div class="flex items-center gap-4">
          <div class="flex items-center gap-3">
            <div class="w-8 h-8 rounded-full bg-primary flex items-center justify-center">
              <span class="text-white text-sm font-medium">
                {{ userInfo?.name?.charAt(0) || 'U' }}
              </span>
            </div>
            <div class="text-right">
              <div class="text-sm font-medium text-gray-900">{{ userInfo?.name || '用户' }}</div>
              <div class="text-xs text-gray-500">
                {{ userInfo?.role === 'admin' ? '管理员' : '项目经理' }}
              </div>
            </div>
          </div>
        </div>
      </header>
      
      <main class="flex-1 overflow-y-auto p-6">
        <div class="max-w-7xl mx-auto">
          <router-view />
        </div>
      </main>
    </div>
  </div>
</template>

// src/components/MainLayout.tsx
import { Outlet, useNavigate, useLocation } from 'react-router-dom';
import { Activity, BarChart3, TrendingUp, Users, FileText, Settings, LogOut, Menu, X, ChevronRight } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { useAuthStore, useUIStore } from '../store';
import { DataQualityBanner } from '../components/DataQualityBanner';
import { useDataQuality, useRefreshData } from '../hooks/useData';
import { useFilterStore } from '../store';

const NAV_ITEMS = [
  { path: '/dashboard', label: '仪表盘', icon: BarChart3 },
  { path: '/workload', label: '负荷分析', icon: TrendingUp },
  { path: '/compare', label: '对比分析', icon: Users },
  { path: '/recovery', label: '恢复监测', icon: Activity },
  { path: '/reports', label: '报告中心', icon: FileText },
];

const COACH_NAV_ITEMS = [
  { path: '/injury', label: '伤病管理', icon: Activity },
];

export function MainLayout() {
  const navigate = useNavigate();
  const location = useLocation();
  const user = useAuthStore((s) => s.user);
  const logout = useAuthStore((s) => s.logout);
  const isCoach = useAuthStore((s) => s.isCoach());
  const { sidebarOpen, setSidebarOpen } = useUIStore();
  const filters = useFilterStore((s) => s.filters);
  const { data: dataQuality } = useDataQuality();
  const refreshData = useRefreshData();

  const allNavItems = isCoach ? [...NAV_ITEMS, ...COACH_NAV_ITEMS] : NAV_ITEMS;

  const handleLogout = () => {
    logout();
    navigate('/login');
  };

  return (
    <div className="min-h-screen flex">
      <AnimatePresence mode="wait">
        {sidebarOpen && (
          <motion.div
            className="fixed inset-0 bg-black/50 z-40 lg:hidden"
            onClick={() => setSidebarOpen(false)}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
          />
        )}
      </AnimatePresence>

      <motion.aside
        initial={false}
        animate={{
          x: sidebarOpen ? 0 : -280,
          width: 280,
        }}
        className={`fixed lg:static z-50 h-screen bg-surface-lighter/95 backdrop-blur-xl border-r border-white/10 flex flex-col`}
      >
        <div className="p-5 border-b border-white/10">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-brand-400 to-brand-600 flex items-center justify-center">
              <Activity className="w-5 h-5 text-white" />
            </div>
            <div>
              <h1 className="font-display font-bold text-white">训练负荷平台</h1>
              <p className="text-xs text-slate-500">Training Load Analytics</p>
            </div>
          </div>
        </div>

        <nav className="flex-1 p-4 space-y-1 overflow-y-auto scrollbar-thin">
          {allNavItems.map((item) => {
            const Icon = item.icon;
            const isActive = location.pathname === item.path;
            return (
              <button
                key={item.path}
                onClick={() => {
                  navigate(item.path);
                  setSidebarOpen(false);
                }}
                className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-lg transition-all ${
                  isActive
                    ? 'bg-brand-500/20 text-brand-300 border border-brand-400/20'
                    : 'text-slate-400 hover:text-white hover:bg-white/5'
                }`}
              >
                <Icon className="w-5 h-5" />
                <span className="text-sm font-medium">{item.label}</span>
                {isActive && <ChevronRight className="w-4 h-4 ml-auto" />}
              </button>
            );
          })}
        </nav>

        <div className="p-4 border-t border-white/10">
          <div className="flex items-center gap-3 mb-3">
            <div className="w-9 h-9 rounded-full bg-gradient-to-br from-brand-400 to-brand-600 flex items-center justify-center text-white font-medium text-sm">
              {user?.name?.charAt(0)}
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-sm font-medium text-white truncate">{user?.name}</p>
              <p className="text-xs text-slate-500">
                {isCoach ? '教练组' : '队员'}
              </p>
            </div>
          </div>
          <button
            onClick={handleLogout}
            className="w-full flex items-center gap-2 px-3 py-2 rounded-lg text-slate-400 hover:text-white hover:bg-white/5 transition-all text-sm"
          >
            <LogOut className="w-4 h-4" />
            退出登录
          </button>
        </div>
      </motion.aside>

      <div className="flex-1 flex flex-col min-w-0">
        <header className="sticky top-0 z-30 bg-surface/80 backdrop-blur-xl border-b border-white/10">
          <div className="flex items-center justify-between px-4 lg:px-6 py-3">
            <div className="flex items-center gap-3">
            <button
              onClick={() => setSidebarOpen(!sidebarOpen)}
              className="p-2 rounded-lg hover:bg-white/5 lg:hidden"
            >
              {sidebarOpen ? <X className="w-5 h-5" /> : <Menu className="w-5 h-5" />}
            </button>
            <h2 className="font-display text-lg font-semibold text-white">
              {allNavItems.find((i) => i.path === location.pathname)?.label || '仪表盘'}
            </h2>
          </div>
          <div className="flex items-center gap-2">
            <span className="text-xs text-slate-500 hidden sm:block">
              {new Date().toLocaleDateString('zh-CN', { year: 'numeric', month: 'long', day: 'numeric', weekday: 'long' })}
            </span>
          </div>
          </div>

          {dataQuality && (
            <DataQualityBanner
              status={dataQuality}
              onRefresh={refreshData}
            />
          )}
        </header>

        <main className="flex-1 p-4 lg:p-6 overflow-y-auto">
          <Outlet />
        </main>
      </div>
    </div>
  );
}
