// src/components/MetricCard.svelte
<script lang="ts">
	import { ArrowUp, ArrowDown, Minus } from 'lucide-svelte';
	import MetricDefinition from './MetricDefinition.svelte';

	export let label: string;
	export let value: string | number;
	export let unit = '';
	export let trend: number | undefined = undefined;
	export let metricKey: string | undefined = undefined;
	export let color: 'default' | 'success' | 'warning' | 'danger' = 'default';

	const colorClasses = {
		default: 'text-gray-900',
		success: 'text-success',
		warning: 'text-warning',
		danger: 'text-danger'
	};
</script>

<div class="metric-card">
	<div class="flex items-start justify-between">
		<div>
			<p class="text-sm text-gray-500">{label}</p>
			<p class="text-2xl font-bold mt-1 {colorClasses[color]}">
				{value}
				{#if unit}
					<span class="text-sm font-normal text-gray-500 ml-1">{unit}</span>
				{/if}
			</p>
			{#if trend !== undefined}
				<div class="flex items-center mt-2 text-sm">
					{#if trend > 0}
						<ArrowUp class="w-4 h-4 text-danger" />
						<span class="text-danger">+{trend.toFixed(1)}%</span>
					{:else if trend < 0}
						<ArrowDown class="w-4 h-4 text-success" />
						<span class="text-success">{trend.toFixed(1)}%</span>
					{:else}
						<Minus class="w-4 h-4 text-gray-400" />
						<span class="text-gray-500">持平</span>
					{/if}
					<span class="text-gray-400 ml-1">较上周</span>
				</div>
			{/if}
		</div>
		{#if metricKey}
			<MetricDefinition {metricKey} compact />
		{/if}
	</div>
</div>

// src/components/MetricCard.tsx
import { motion } from 'framer-motion';
import { TrendingUp, TrendingDown, Minus } from 'lucide-react';
import type { ReactNode } from 'react';

interface MetricCardProps {
  title: string;
  value: string | number;
  unit?: string;
  icon: ReactNode;
  trend?: number;
  trendLabel?: string;
  sampleSize?: number;
  delay?: number;
}

export function MetricCard({
  title,
  value,
  unit,
  icon,
  trend,
  trendLabel,
  sampleSize,
  delay = 0,
}: MetricCardProps) {
  const trendColor = trend !== undefined
    ? trend > 0
      ? 'text-success'
      : trend < 0
        ? 'text-danger'
        : 'text-slate-400'
    : '';

  const TrendIcon = trend !== undefined
    ? trend > 0
      ? TrendingUp
      : trend < 0
        ? TrendingDown
        : Minus
    : null;

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: delay * 0.1, duration: 0.4 }}
      className="glass-card card-hover p-5"
    >
      <div className="flex items-start justify-between mb-3">
        <div className="w-10 h-10 rounded-lg bg-brand-400/15 flex items-center justify-center text-brand-300">
          {icon}
        </div>
        {trend !== undefined && TrendIcon && (
          <div className={`flex items-center gap-1 text-xs ${trendColor}`}>
            <TrendIcon className="w-3.5 h-3.5" />
            <span>{Math.abs(trend).toFixed(1)}%</span>
            {trendLabel && <span className="text-slate-500 ml-1">{trendLabel}</span>}
          </div>
        )}
      </div>
      <div className="metric-value mb-1">
        {value}
        {unit && <span className="text-sm text-slate-400 ml-1 font-normal">{unit}</span>}
      </div>
      <div className="flex items-center justify-between">
        <p className="metric-label">{title}</p>
        {sampleSize !== undefined && (
          <span className="text-xs text-slate-500">
            样本量: {sampleSize}
          </span>
        )}
      </div>
    </motion.div>
  );
}
