// src/lib/components/Modal.svelte
<script lang="ts">
  export let open: boolean;
  export let title: string;
  export let description = '';
  export let size: 'sm' | 'md' | 'lg' = 'md';
  export let onClose: () => void = () => {};
  export let footer = false;

  import { X } from 'lucide-svelte';

  const sizeClasses: Record<string, string> = {
    sm: 'max-w-md',
    md: 'max-w-lg',
    lg: 'max-w-2xl'
  };
</script>

{#if open}
  <div
    class="fixed inset-0 z-50 flex items-center justify-center p-4 animate-fade-in"
    role="dialog"
    aria-modal="true"
  >
    <div
      class="absolute inset-0 bg-navy-900/50 backdrop-blur-sm"
      on:click={onClose}
    />
    <div
      class="relative bg-white rounded-2xl shadow-2xl w-full {sizeClasses[size]} animate-fade-in-up"
    >
      <div class="flex items-start justify-between p-6 border-b border-navy-100">
        <div>
          <h3 class="font-display text-lg text-navy-900">{title}</h3>
          {#if description}
            <p class="text-sm text-navy-500 mt-1">{description}</p>
          {/if}
        </div>
        <button
          on:click={onClose}
          class="w-8 h-8 rounded-lg flex items-center justify-center text-navy-400 hover:bg-navy-50 hover:text-navy-700 transition"
          aria-label="关闭"
        >
          <X class="w-4 h-4" stroke-width={1.8} />
        </button>
      </div>
      <div class="p-6">
        <slot />
      </div>
      {#if footer}
        <div class="flex items-center justify-end gap-2 p-6 pt-0">
          <slot name="footer" />
        </div>
      {/if}
    </div>
  </div>
{/if}

// src/components/Modal.tsx
import { useEffect } from 'react';
import { X } from 'lucide-react';

interface ModalProps {
  open: boolean;
  onClose: () => void;
  title: string;
  children: React.ReactNode;
  width?: string;
}

export default function Modal({ open, onClose, title, children, width = 'max-w-lg' }: ModalProps) {
  useEffect(() => {
    if (open) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }
    return () => {
      document.body.style.overflow = '';
    };
  }, [open]);

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      <div className="absolute inset-0 bg-black/60" onClick={onClose} />
      <div
        className={`relative ${width} w-full mx-4 bg-[#1E293B] rounded-lg border border-[#334155] shadow-2xl animate-fade-in-up`}
      >
        <div className="flex items-center justify-between px-6 py-4 border-b border-[#334155]">
          <h3 className="text-lg font-medium text-[#F1F5F9]">{title}</h3>
          <button
            onClick={onClose}
            className="p-1 rounded hover:bg-[#334155] text-[#94A3B8] hover:text-white transition-colors"
          >
            <X size={18} />
          </button>
        </div>
        <div className="px-6 py-4 max-h-[70vh] overflow-y-auto">{children}</div>
      </div>
    </div>
  );
}
