// src/lib/components/Navbar.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import { currentUser, isAdmin, toggleUserRole } from '$stores/user';
  import {
    Home,
    FileText,
    Archive,
    Shield,
    Settings,
    User,
    ChevronDown,
    Menu,
    X,
    BarChart3,
    AlertTriangle,
    FlaskConical
  } from 'lucide-svelte';

  let mobileMenuOpen = $state(false);

  let user = $derived($currentUser);
  let admin = $derived($isAdmin);
  let path = $derived($page.url.pathname);

  const navItems = [
    { href: '/', label: '首页', icon: Home },
    { href: '/requisition', label: '领用申请', icon: FlaskConical },
    { href: '/archive', label: '数据归档', icon: Archive },
    { href: '/compliance', label: '安全合规', icon: Shield }
  ];

  const adminItems = [
    { href: '/admin/experiments', label: '实验管理', icon: FileText },
    { href: '/admin/compliance-dashboard', label: '合规看板', icon: BarChart3 },
    { href: '/admin/risk-management', label: '风险管理', icon: AlertTriangle }
  ];

  function isActive(href: string) {
    if (href === '/') return path === '/';
    return path.startsWith(href);
  }
</script>

<nav class="bg-white border-b border-gray-200 sticky top-0 z-50 backdrop-blur-lg bg-white/95">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">
      <div class="flex items-center gap-8">
        <a href="/" class="flex items-center gap-2">
          <div class="w-8 h-8 bg-gradient-to-br from-primary-500 to-primary-700 rounded-lg flex items-center justify-center">
            <FlaskConical class="w-5 h-5 text-white" />
          </div>
          <span class="font-display font-bold text-lg text-primary-950 hidden sm:block">
            试剂库存登记站
          </span>
        </a>

        <div class="hidden md:flex items-center gap-1">
          {#each navItems as item}
            <a
              href={item.href}
              class="inline-flex items-center gap-1.5 px-3 py-2 text-sm font-medium rounded-lg transition-colors"
              class:bg-primary-50={isActive(item.href)}
              class:text-primary-700={isActive(item.href)}
              class:text-gray-600 hover:text-primary-600 hover:bg-gray-50={!isActive(item.href)}
            >
              <item.icon class="w-4 h-4" />
              {item.label}
            </a>
          {/each}

          {#if admin}
            <div class="w-px h-6 bg-gray-200 mx-2" />
            {#each adminItems as item}
              <a
                href={item.href}
                class="inline-flex items-center gap-1.5 px-3 py-2 text-sm font-medium rounded-lg transition-colors"
                class:bg-primary-50={isActive(item.href)}
                class:text-primary-700={isActive(item.href)}
                class:text-gray-600 hover:text-primary-600 hover:bg-gray-50={!isActive(item.href)}
              >
                <item.icon class="w-4 h-4" />
                {item.label}
              </a>
            {/each}
          {/if}
        </div>
      </div>

      <div class="flex items-center gap-3">
        <button
          on:click={toggleUserRole}
          class="hidden sm:inline-flex items-center gap-1.5 px-2.5 py-1.5 text-xs font-medium text-gray-600 bg-gray-100 hover:bg-gray-200 rounded-lg transition-colors"
          title="切换角色"
        >
          <Settings class="w-3.5 h-3.5" />
          {admin ? '管理员' : '科研人员'}
        </button>

        <div class="flex items-center gap-2">
          <div class="w-8 h-8 bg-gradient-to-br from-primary-400 to-primary-600 rounded-full flex items-center justify-center">
            <User class="w-4 h-4 text-white" />
          </div>
          <div class="hidden sm:block">
            <p class="text-sm font-medium text-gray-900">{user.name}</p>
            <p class="text-xs text-gray-500">{admin ? '实验室管理员' : '研究生'}</p>
          </div>
        </div>

        <button
          on:click={() => mobileMenuOpen = !mobileMenuOpen}
          class="md:hidden p-2 text-gray-500 hover:text-gray-700 hover:bg-gray-100 rounded-lg"
        >
          {#if mobileMenuOpen}
            <X class="w-5 h-5" />
          {:else}
            <Menu class="w-5 h-5" />
          {/if}
        </button>
      </div>
    </div>
  </div>

  {#if mobileMenuOpen}
    <div class="md:hidden border-t border-gray-200 bg-white">
      <div class="px-4 py-3 space-y-1">
        {#each navItems as item}
          <a
            href={item.href}
            on:click={() => mobileMenuOpen = false}
            class="flex items-center gap-2 px-3 py-2.5 text-sm font-medium rounded-lg transition-colors"
            class:bg-primary-50 text-primary-700={isActive(item.href)}
            class:text-gray-700 hover:bg-gray-50={!isActive(item.href)}
          >
            <item.icon class="w-4 h-4" />
            {item.label}
          </a>
        {/each}

        {#if admin}
          <div class="border-t border-gray-100 my-2 pt-2">
            <p class="px-3 py-1 text-xs font-medium text-gray-500">后台管理</p>
            {#each adminItems as item}
              <a
                href={item.href}
                on:click={() => mobileMenuOpen = false}
                class="flex items-center gap-2 px-3 py-2.5 text-sm font-medium rounded-lg transition-colors"
                class:bg-primary-50 text-primary-700={isActive(item.href)}
                class:text-gray-700 hover:bg-gray-50={!isActive(item.href)}
              >
                <item.icon class="w-4 h-4" />
                {item.label}
              </a>
            {/each}
          </div>
        {/if}

        <div class="border-t border-gray-100 pt-3">
          <button
            on:click={toggleUserRole}
            class="w-full flex items-center gap-2 px-3 py-2.5 text-sm font-medium text-gray-700 hover:bg-gray-50 rounded-lg"
          >
            <Settings class="w-4 h-4" />
            切换为{admin ? '科研人员' : '管理员'}
          </button>
        </div>
      </div>
    </div>
  {/if}
</nav>

// src/components/NavBar.vue
<script setup lang="ts">
import { ref } from 'vue'
import { RouterLink as Link, useRouter, useRoute } from 'vue-router'
import {
  Map,
  BarChart3,
  Image,
  Eye,
  Settings,
  User,
  LogOut,
  ChevronDown,
  Menu,
  X
} from 'lucide-vue-next'
import { useUserStore } from '@/stores/user'

const userStore = useUserStore()
const router = useRouter()
const route = useRoute()
const showUserMenu = ref(false)
const showMobileMenu = ref(false)

function handleLogout() {
  userStore.logout()
  router.push('/')
  showUserMenu.value = false
}

const navItems = [
  { name: '桶点地图', path: '/', icon: Map, public: true },
  { name: '工作台', path: '/manager', icon: BarChart3, role: 'manager' },
  { name: '照片审核', path: '/audit', icon: Image, roles: ['manager', 'auditor'] },
  { name: '公开看板', path: '/public', icon: Eye, public: true },
  { name: '系统设置', path: '/settings', icon: Settings, role: 'manager' }
]

function isVisible(item: any) {
  if (item.public) return true
  if (!userStore.isLoggedIn) return false
  if (item.role) return userStore.role === item.role
  if (item.roles) return item.roles.includes(userStore.role)
  return false
}

function isActive(path: string) {
  if (path === '/') return route.path === '/'
  return route.path.startsWith(path)
}
</script>

<template>
  <header class="bg-white border-b border-gray-100 sticky top-0 z-50">
    <div class="max-w-7xl mx-auto px-4 sm:px-6">
      <div class="flex items-center justify-between h-16">
        <div class="flex items-center gap-3">
          <div class="w-9 h-9 rounded-xl bg-gradient-to-br from-teal-500 to-emerald-600 flex items-center justify-center">
            <Map class="w-5 h-5 text-white" />
          </div>
          <div>
            <h1 class="text-base font-bold text-gray-900 leading-tight">垃圾分类投放分析</h1>
            <p class="text-xs text-gray-500 leading-tight">城市智慧环卫平台</p>
          </div>
        </div>

        <nav class="hidden md:flex items-center gap-1">
          <template v-for="item in navItems" :key="item.path">
            <Link
              v-if="isVisible(item)"
              :to="item.path"
              :class="[
                'flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium transition-colors',
                isActive(item.path)
                  ? 'bg-teal-50 text-teal-700'
                  : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900'
              ]"
            >
              <component :is="item.icon" class="w-4 h-4" />
              {{ item.name }}
            </Link>
          </template>
        </nav>

        <div class="flex items-center gap-3">
          <div v-if="userStore.isLoggedIn" class="relative hidden sm:block">
            <button
              class="flex items-center gap-2 px-2 py-1.5 rounded-lg hover:bg-gray-50 transition-colors"
              @click="showUserMenu = !showUserMenu"
            >
              <div class="w-8 h-8 rounded-full bg-gradient-to-br from-teal-400 to-emerald-500 flex items-center justify-center text-white text-sm font-medium">
                {{ userStore.currentUser?.name.charAt(0) }}
              </div>
              <div class="text-left">
                <p class="text-sm font-medium text-gray-900">{{ userStore.currentUser?.name }}</p>
                <p class="text-xs text-gray-500">
                  {{ userStore.role === 'manager' ? '项目经理' : userStore.role === 'auditor' ? '审核员' : '' }}
                </p>
              </div>
              <ChevronDown class="w-4 h-4 text-gray-400" />
            </button>

            <Transition name="slide-up">
              <div
                v-if="showUserMenu"
                class="absolute right-0 top-full mt-2 w-48 bg-white rounded-xl shadow-lg border border-gray-100 py-2"
              >
                <div class="px-4 py-2 border-b border-gray-50">
                  <p class="text-sm font-medium text-gray-900">{{ userStore.currentUser?.name }}</p>
                  <p class="text-xs text-gray-500">{{ userStore.currentUser?.role }}</p>
                </div>
                <button
                  class="w-full flex items-center gap-2 px-4 py-2 text-sm text-gray-700 hover:bg-gray-50"
                  @click="handleLogout"
                >
                  <LogOut class="w-4 h-4" />
                  退出登录
                </button>
              </div>
            </Transition>
          </div>

          <Link
            v-else
            to="/login"
            class="btn-primary text-sm hidden sm:flex"
          >
            <User class="w-4 h-4 mr-1" />
            登录
          </Link>

          <button
            class="md:hidden p-2 rounded-lg hover:bg-gray-100"
            @click="showMobileMenu = !showMobileMenu"
          >
            <Menu v-if="!showMobileMenu" class="w-5 h-5 text-gray-600" />
            <X v-else class="w-5 h-5 text-gray-600" />
          </button>
        </div>
      </div>

      <Transition name="slide-up">
        <div v-if="showMobileMenu" class="md:hidden py-3 border-t border-gray-100">
          <nav class="flex flex-col gap-1">
            <template v-for="item in navItems" :key="item.path">
              <Link
                v-if="isVisible(item)"
                :to="item.path"
                :class="[
                  'flex items-center gap-2 px-3 py-2.5 rounded-lg text-sm font-medium transition-colors',
                  isActive(item.path)
                    ? 'bg-teal-50 text-teal-700'
                    : 'text-gray-600 hover:bg-gray-50'
                ]"
                @click="showMobileMenu = false"
              >
                <component :is="item.icon" class="w-4 h-4" />
                {{ item.name }}
              </Link>
            </template>
            <div v-if="userStore.isLoggedIn" class="pt-2 mt-2 border-t border-gray-100">
              <div class="flex items-center gap-2 px-3 py-2">
                <div class="w-8 h-8 rounded-full bg-teal-500 flex items-center justify-center text-white text-sm font-medium">
                  {{ userStore.currentUser?.name.charAt(0) }}
                </div>
                <div>
                  <p class="text-sm font-medium text-gray-900">{{ userStore.currentUser?.name }}</p>
                  <p class="text-xs text-gray-500">{{ userStore.role === 'manager' ? '项目经理' : '审核员' }}</p>
                </div>
              </div>
              <button
                class="w-full flex items-center gap-2 px-3 py-2.5 rounded-lg text-sm text-red-600 hover:bg-red-50"
                @click="handleLogout"
              >
                <LogOut class="w-4 h-4" />
                退出登录
              </button>
            </div>
          </nav>
        </div>
      </Transition>
    </div>
  </header>
</template>
