// frontend/src/routes/reservations/index.tsx
import { component$, useStore, useTask$, $ } from "@builder.io/qwik";
import { useNavigate, Link } from "@builder.io/qwik-city";
import Layout from "~/components/layout";
import apiClient from "~/utils/api";
import { useAuth } from "~/context/auth";
import dayjs from "dayjs";

interface Reservation {
  id: string;
  member_id: string;
  member_name: string;
  equipment_id: string;
  equipment_name: string;
  field_id: string;
  field_name: string;
  crop: string;
  start_time: string;
  end_time: string;
  status: 'pending' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled' | 'waitlisted';
  price_type: 'member' | 'subsidy' | 'commercial';
  estimated_price: number;
  queue_position: number | null;
  cancel_reason: string | null;
  notes: string | null;
  operator_name: string | null;
  created_at: string;
}

const statusLabels: Record<string, string> = {
  pending: '待确认',
  confirmed: '已确认',
  in_progress: '作业中',
  completed: '已完成',
  cancelled: '已取消',
  waitlisted: '候补中',
};

const statusBadgeClass: Record<string, string> = {
  pending: 'badge-pending',
  confirmed: 'badge-confirmed',
  in_progress: 'badge-blue',
  completed: 'badge-completed',
  cancelled: 'badge-cancelled',
  waitlisted: 'badge-waitlisted',
};

const priceTypeLabels: Record<string, string> = {
  member: '社员自用 (×0.7)',
  subsidy: '合作社补贴 (×0.5)',
  commercial: '跨村租赁 (×1.3)',
};

export default component$(() => {
  const auth = useAuth();
  const nav = useNavigate();
  
  const state = useStore({
    reservations: [] as Reservation[],
    loading: true,
    filter: 'all',
    showCancelModal: false,
    selectedReservation: null as Reservation | null,
    cancelReason: '',
  });

  const loadReservations = $(async () => {
    try {
      const params: any = {};
      if (state.filter !== 'all') {
        params.status = state.filter;
      }
      const response = await apiClient.get('/reservations', { params });
      state.reservations = response.data;
    } catch (e) {
      console.error('加载预约失败', e);
    } finally {
      state.loading = false;
    }
  });

  useTask$(async () => {
    if (!auth.isAuthenticated) {
      nav.navigate('/login');
      return;
    }
    await loadReservations();
  });

  const handleCancel = $(async () => {
    if (!state.selectedReservation) return;
    
    try {
      await apiClient.post(`/reservations/${state.selectedReservation.id}/cancel`, {
        reason: state.cancelReason || '用户取消',
      });
      state.showCancelModal = false;
      state.selectedReservation = null;
      state.cancelReason = '';
      await loadReservations();
    } catch (e: any) {
      alert(e.response?.data?.error || '取消失败');
    }
  });

  const handleResubmit = $((reservation: Reservation) => {
    nav.navigate(`/reservations/new?original=${reservation.id}`);
  });

  const handleConfirm = $(async (reservation: Reservation) => {
    try {
      await apiClient.post(`/reservations/${reservation.id}/confirm`);
      await loadReservations();
    } catch (e: any) {
      alert(e.response?.data?.error || '确认失败');
    }
  });

  const filteredReservations = state.reservations.filter(r => {
    if (state.filter === 'all') return true;
    return r.status === state.filter;
  });

  return (
    <Layout title="预约管理">
      <div class="flex items-center justify-between mb-6">
        <div class="flex gap-2">
          {['all', 'pending', 'confirmed', 'waitlisted', 'cancelled', 'completed'].map((f) => (
            <button
              key={f}
              onClick$={() => { state.filter = f; loadReservations(); }}
              class={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
                state.filter === f
                  ? 'bg-primary-500 text-white'
                  : 'bg-white text-gray-600 hover:bg-gray-50 border border-gray-200'
              }`}
            >
              {f === 'all' ? '全部' : statusLabels[f]}
            </button>
          ))}
        </div>
        
        {auth.user?.role !== 'operator' && (
          <button
            onClick$={() => nav.navigate('/reservations/new')}
            class="btn-primary flex items-center gap-2"
          >
            <span>+</span>
            新建预约
          </button>
        )}
      </div>

      {state.loading ? (
        <div class="card text-center text-gray-500">加载中...</div>
      ) : (
        <div class="card overflow-x-auto">
          <table class="w-full">
            <thead>
              <tr class="border-b border-gray-100">
                <th class="text-left py-3 px-4 text-sm font-medium text-gray-500">设备</th>
                <th class="text-left py-3 px-4 text-sm font-medium text-gray-500">地块</th>
                <th class="text-left py-3 px-4 text-sm font-medium text-gray-500">作物</th>
                <th class="text-left py-3 px-4 text-sm font-medium text-gray-500">预约时间</th>
                <th class="text-left py-3 px-4 text-sm font-medium text-gray-500">社员</th>
                <th class="text-left py-3 px-4 text-sm font-medium text-gray-500">价格</th>
                <th class="text-left py-3 px-4 text-sm font-medium text-gray-500">状态</th>
                <th class="text-left py-3 px-4 text-sm font-medium text-gray-500">操作</th>
              </tr>
            </thead>
            <tbody>
              {filteredReservations.length === 0 ? (
                <tr>
                  <td colspan="8" class="text-center py-8 text-gray-500">暂无预约记录</td>
                </tr>
              ) : (
                filteredReservations.map((r) => (
                  <tr key={r.id} class="border-b border-gray-50 hover:bg-gray-50">
                    <td class="py-3 px-4">
                      <div class="font-medium text-gray-800">{r.equipment_name}</div>
                    </td>
                    <td class="py-3 px-4 text-gray-600">{r.field_name}</td>
                    <td class="py-3 px-4 text-gray-600">{r.crop}</td>
                    <td class="py-3 px-4">
                      <div class="text-sm text-gray-800">
                        {dayjs(r.start_time).format('MM-DD HH:mm')} - {dayjs(r.end_time).format('HH:mm')}
                      </div>
                      <div class="text-xs text-gray-400">
                        {dayjs(r.start_time).fromNow()}
                      </div>
                    </td>
                    <td class="py-3 px-4 text-gray-600">{r.member_name}</td>
                    <td class="py-3 px-4">
                      <div class="text-sm font-medium text-gray-800">¥{r.estimated_price}</div>
                      <div class="text-xs text-gray-400">{priceTypeLabels[r.price_type]}</div>
                    </td>
                    <td class="py-3 px-4">
                      <span class={`badge ${statusBadgeClass[r.status]}`}>
                        {statusLabels[r.status]}
                        {r.status === 'waitlisted' && r.queue_position && ` #${r.queue_position}`}
                      </span>
                    </td>
                    <td class="py-3 px-4">
                      <div class="flex gap-2">
                        {r.status === 'pending' && auth.user?.role !== 'member' && (
                          <button
                            onClick$={() => handleConfirm(r)}
                            class="text-sm text-primary-600 hover:text-primary-700"
                          >
                            确认
                          </button>
                        )}
                        {(r.status === 'pending' || r.status === 'waitlisted') && (
                          <button
                            onClick$={() => { state.selectedReservation = r; state.showCancelModal = true; }}
                            class="text-sm text-red-600 hover:text-red-700"
                          >
                            取消
                          </button>
                        )}
                        {r.status === 'cancelled' && (
                          <button
                            onClick$={() => handleResubmit(r)}
                            class="text-sm text-primary-600 hover:text-primary-700"
                          >
                            重新提交
                          </button>
                        )}
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      )}

      {state.showCancelModal && state.selectedReservation && (
        <div class="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div class="bg-white rounded-xl p-6 w-full max-w-md">
            <h3 class="text-lg font-bold text-gray-800 mb-4">取消预约</h3>
            <p class="text-gray-600 mb-4">
              确定要取消 {state.selectedReservation.equipment_name} 的预约吗？
              {!state.selectedReservation.status.includes('wait') && (
                <span class="text-red-500 block mt-1 text-sm">注意：取消将扣除10积分</span>
              )}
            </p>
            <div class="mb-4">
              <label class="label">取消原因</label>
              <textarea
                class="input-field"
                rows={3}
                placeholder="请输入取消原因"
                value={state.cancelReason}
                onInput$={(e) => state.cancelReason = (e.target as HTMLTextAreaElement).value}
              />
            </div>
            <div class="flex gap-3 justify-end">
              <button
                onClick$={() => { state.showCancelModal = false; state.selectedReservation = null; }}
                class="btn-secondary"
              >
                取消
              </button>
              <button
                onClick$={handleCancel}
                class="btn-danger"
              >
                确认取消
              </button>
            </div>
          </div>
        </div>
      )}
    </Layout>
  );
});

// frontend/src/pages/Reservations.tsx
import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { Link } from 'react-router-dom';
import dayjs from 'dayjs';
import { useAuthStore } from '../store/authStore';

interface Reservation {
  id: string;
  member_name: string;
  equipment_name: string;
  field_name: string;
  crop: string;
  start_time: string;
  end_time: string;
  status: 'pending' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled' | 'waitlisted' | 'conflict';
  price_type: 'member' | 'subsidy' | 'commercial';
  is_conflict?: boolean;
}

const statusLabels: Record<string, string> = {
  pending: '待确认',
  confirmed: '已确认',
  in_progress: '作业中',
  completed: '已完成',
  cancelled: '已取消',
  waitlisted: '候补中',
  conflict: '时间冲突'
};

const statusColors: Record<string, string> = {
  pending: 'bg-yellow-100 text-yellow-700',
  confirmed: 'bg-blue-100 text-blue-700',
  in_progress: 'bg-green-100 text-green-700',
  completed: 'bg-gray-100 text-gray-700',
  cancelled: 'bg-red-100 text-red-700',
  waitlisted: 'bg-purple-100 text-purple-700',
  conflict: 'bg-orange-100 text-orange-700'
};

const priceTypeLabels: Record<string, string> = {
  member: '社员自用',
  subsidy: '合作社补贴',
  commercial: '跨村租赁'
};

export default function Reservations() {
  const [reservations, setReservations] = useState<Reservation[]>([]);
  const [loading, setLoading] = useState(true);
  const [filters, setFilters] = useState({
    status: '',
    date: ''
  });
  const user = useAuthStore(state => state.user);

  useEffect(() => {
    fetchReservations();
  }, [filters]);

  const fetchReservations = async () => {
    try {
      const params = new URLSearchParams();
      if (filters.status) params.append('status', filters.status);
      if (filters.date) params.append('date', filters.date);

      const response = await axios.get(`/api/reservations?${params.toString()}`);
      setReservations(response.data);
    } catch (error) {
      console.error('获取预约列表失败:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleCancel = async (id: string) => {
    if (!confirm('确定要取消这个预约吗？')) return;
    try {
      await axios.post(`/api/reservations/${id}/cancel`);
      fetchReservations();
    } catch (error) {
      console.error('取消预约失败:', error);
      alert('取消失败，请重试');
    }
  };

  const handleConfirm = async (id: string) => {
    try {
      await axios.post(`/api/reservations/${id}/confirm`);
      fetchReservations();
    } catch (error) {
      console.error('确认预约失败:', error);
      alert('确认失败，请重试');
    }
  };

  if (loading) {
    return <div className="text-gray-500">加载中...</div>;
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-800">预约管理</h1>
          <p className="text-gray-500 mt-1">管理所有农机预约申请</p>
        </div>
        {user?.role === 'member' && (
          <Link to="/reservations/new" className="btn-primary">
            + 新建预约
          </Link>
        )}
      </div>

      <div className="card">
        <div className="flex flex-wrap gap-4 mb-6">
          <div>
            <label className="label">状态</label>
            <select
              value={filters.status}
              onChange={(e) => setFilters({ ...filters, status: e.target.value })}
              className="input-field min-w-[150px]"
            >
              <option value="">全部状态</option>
              <option value="pending">待确认</option>
              <option value="confirmed">已确认</option>
              <option value="in_progress">作业中</option>
              <option value="completed">已完成</option>
              <option value="cancelled">已取消</option>
              <option value="waitlisted">候补中</option>
              <option value="conflict">时间冲突</option>
            </select>
          </div>
          <div>
            <label className="label">日期</label>
            <input
              type="date"
              value={filters.date}
              onChange={(e) => setFilters({ ...filters, date: e.target.value })}
              className="input-field"
            />
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full">
            <thead>
              <tr className="border-b border-gray-100">
                <th className="text-left py-3 px-4 text-sm font-medium text-gray-500">预约信息</th>
                <th className="text-left py-3 px-4 text-sm font-medium text-gray-500">设备/地块</th>
                <th className="text-left py-3 px-4 text-sm font-medium text-gray-500">作业时间</th>
                <th className="text-left py-3 px-4 text-sm font-medium text-gray-500">价格类型</th>
                <th className="text-left py-3 px-4 text-sm font-medium text-gray-500">状态</th>
                <th className="text-right py-3 px-4 text-sm font-medium text-gray-500">操作</th>
              </tr>
            </thead>
            <tbody>
              {reservations.map((item) => (
                <tr key={item.id} className="border-b border-gray-50 hover:bg-gray-50">
                  <td className="py-4 px-4">
                    <p className="font-medium">{item.member_name}</p>
                    <p className="text-xs text-gray-500">作物：{item.crop}</p>
                  </td>
                  <td className="py-4 px-4">
                    <p className="text-sm">{item.equipment_name}</p>
                    <p className="text-xs text-gray-500">{item.field_name}</p>
                  </td>
                  <td className="py-4 px-4">
                    <p className="text-sm">{dayjs(item.start_time).format('MM-DD HH:mm')}</p>
                    <p className="text-xs text-gray-500">至 {dayjs(item.end_time).format('HH:mm')}</p>
                  </td>
                  <td className="py-4 px-4">
                    <span className="text-sm">{priceTypeLabels[item.price_type]}</span>
                  </td>
                  <td className="py-4 px-4">
                    <div className="flex items-center gap-2">
                      <span className={`px-2 py-1 rounded-full text-xs font-medium ${statusColors[item.status]}`}>
                        {statusLabels[item.status]}
                      </span>
                      {item.is_conflict && (
                        <span className="text-xs text-red-500 font-medium">⚠️ 冲突</span>
                      )}
                    </div>
                  </td>
                  <td className="py-4 px-4 text-right">
                    <div className="flex justify-end gap-2">
                      {item.status === 'pending' && user?.role !== 'member' && (
                        <button
                          onClick={() => handleConfirm(item.id)}
                          className="text-xs px-3 py-1 bg-green-500 text-white rounded-lg hover:bg-green-600"
                        >
                          确认
                        </button>
                      )}
                      {['pending', 'confirmed', 'waitlisted'].includes(item.status) && (
                        <button
                          onClick={() => handleCancel(item.id)}
                          className="text-xs px-3 py-1 bg-red-50 text-red-600 rounded-lg hover:bg-red-100"
                        >
                          取消
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {reservations.length === 0 && (
          <div className="text-center py-12 text-gray-500">
            <div className="text-4xl mb-3">📅</div>
            <p>暂无预约记录</p>
          </div>
        )}
      </div>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div className="card text-center">
          <p className="text-3xl font-bold text-yellow-600">
            {reservations.filter(r => r.status === 'pending').length}
          </p>
          <p className="text-sm text-gray-500 mt-1">待确认</p>
        </div>
        <div className="card text-center">
          <p className="text-3xl font-bold text-blue-600">
            {reservations.filter(r => r.status === 'confirmed').length}
          </p>
          <p className="text-sm text-gray-500 mt-1">已确认</p>
        </div>
        <div className="card text-center">
          <p className="text-3xl font-bold text-green-600">
            {reservations.filter(r => r.status === 'in_progress').length}
          </p>
          <p className="text-sm text-gray-500 mt-1">作业中</p>
        </div>
        <div className="card text-center">
          <p className="text-3xl font-bold text-purple-600">
            {reservations.filter(r => r.status === 'waitlisted').length}
          </p>
          <p className="text-sm text-gray-500 mt-1">候补中</p>
        </div>
      </div>
    </div>
  );
}
