// app/admin/users/page.tsx
'use client';

import { useState } from 'react';
import AppLayout from '@/components/AppLayout';
import { useStore } from '@/store/useStore';
import { UserRole } from '@/types';
import { formatDate } from '@/lib/utils';
import Avatar from '@/components/Avatar';
import {
  Users,
  Plus,
  Edit2,
  Trash2,
  Shield,
  UserCog,
  User,
  Building2,
  Mail,
  Save,
  X,
} from 'lucide-react';

const roleLabels: Record<UserRole, string> = {
  admin: '系统管理员',
  manager: '部门主管',
  user: '普通用户',
};

const roleIcons: Record<UserRole, any> = {
  admin: Shield,
  manager: UserCog,
  user: User,
};

const roleColors: Record<UserRole, string> = {
  admin: 'bg-danger-100 text-danger-700',
  manager: 'bg-primary-100 text-primary-700',
  user: 'bg-gray-100 text-gray-700',
};

export default function UserManagementPage() {
  const users = useStore((state) => state.users);
  const departments = useStore((state) => state.departments);
  const updateUser = useStore((state) => state.updateUser);
  const createUser = useStore((state) => state.createUser);
  const [editingUserId, setEditingUserId] = useState<string | null>(null);
  const [isCreating, setIsCreating] = useState(false);
  const [isSaving, setIsSaving] = useState(false);

  const [editForm, setEditForm] = useState({
    name: '',
    email: '',
    role: 'user' as UserRole,
    department_id: '',
  });

  const [newUserForm, setNewUserForm] = useState({
    name: '',
    email: '',
    role: 'user' as UserRole,
    department_id: '',
  });

  const handleEdit = (user: typeof users[0]) => {
    setEditingUserId(user.id);
    setEditForm({
      name: user.name,
      email: user.email,
      role: user.role,
      department_id: user.department_id,
    });
    setIsCreating(false);
  };

  const handleCancelEdit = () => {
    setEditingUserId(null);
  };

  const handleSaveEdit = async () => {
    if (!editingUserId) return;
    setIsSaving(true);
    try {
      await updateUser(editingUserId, editForm);
      setEditingUserId(null);
    } finally {
      setIsSaving(false);
    }
  };

  const handleCreate = async () => {
    if (!newUserForm.name || !newUserForm.email || !newUserForm.department_id) return;
    setIsSaving(true);
    try {
      await createUser(newUserForm);
      setNewUserForm({ name: '', email: '', role: 'user', department_id: '' });
      setIsCreating(false);
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <AppLayout>
      <div className="mb-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold text-gray-900 mb-1 flex items-center gap-2">
              <Users className="w-7 h-7 text-primary-900" />
              用户管理
            </h1>
            <p className="text-gray-500">管理系统用户、角色和部门归属</p>
          </div>
          <button
            onClick={() => setIsCreating(true)}
            className="btn-primary"
          >
            <Plus className="w-4 h-4 mr-2" />
            添加用户
          </button>
        </div>
      </div>

      {isCreating && (
        <div className="card p-5 mb-6 animate-slide-down">
          <div className="flex items-center justify-between mb-4">
            <h3 className="font-semibold text-gray-900 flex items-center gap-2">
              <Plus className="w-5 h-5 text-primary-900" />
              添加新用户
            </h3>
            <button
              onClick={() => setIsCreating(false)}
              className="p-2 hover:bg-gray-100 rounded-lg"
            >
              <X className="w-5 h-5 text-gray-500" />
            </button>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">姓名 *</label>
              <input
                type="text"
                value={newUserForm.name}
                onChange={(e) => setNewUserForm({ ...newUserForm, name: e.target.value })}
                className="input"
                placeholder="请输入用户姓名"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">邮箱 *</label>
              <input
                type="email"
                value={newUserForm.email}
                onChange={(e) => setNewUserForm({ ...newUserForm, email: e.target.value })}
                className="input"
                placeholder="请输入用户邮箱"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">角色 *</label>
              <select
                value={newUserForm.role}
                onChange={(e) => setNewUserForm({ ...newUserForm, role: e.target.value as UserRole })}
                className="select"
              >
                <option value="user">普通用户</option>
                <option value="manager">部门主管</option>
                <option value="admin">系统管理员</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">部门 *</label>
              <select
                value={newUserForm.department_id}
                onChange={(e) => setNewUserForm({ ...newUserForm, department_id: e.target.value })}
                className="select"
              >
                <option value="">请选择部门</option>
                {departments.map((dept) => (
                  <option key={dept.id} value={dept.id}>{dept.name}</option>
                ))}
              </select>
            </div>
          </div>

          <div className="flex justify-end gap-3">
            <button onClick={() => setIsCreating(false)} className="btn-secondary">
              取消
            </button>
            <button
              onClick={handleCreate}
              disabled={isSaving || !newUserForm.name || !newUserForm.email || !newUserForm.department_id}
              className="btn-primary"
            >
              {isSaving ? '创建中...' : '创建用户'}
            </button>
          </div>
        </div>
      )}

      <div className="card overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="bg-gray-50 border-b border-gray-200">
              <tr>
                <th className="text-left py-3 px-4 text-sm font-medium text-gray-500">用户</th>
                <th className="text-left py-3 px-4 text-sm font-medium text-gray-500">邮箱</th>
                <th className="text-left py-3 px-4 text-sm font-medium text-gray-500">角色</th>
                <th className="text-left py-3 px-4 text-sm font-medium text-gray-500">部门</th>
                <th className="text-left py-3 px-4 text-sm font-medium text-gray-500">创建时间</th>
                <th className="text-right py-3 px-4 text-sm font-medium text-gray-500">操作</th>
              </tr>
            </thead>
            <tbody>
              {users.map((user) => {
                const RoleIcon = roleIcons[user.role];
                const isEditing = editingUserId === user.id;
                const department = departments.find(d => d.id === user.department_id);

                if (isEditing) {
                  return (
                    <tr key={user.id} className="border-b border-gray-100 bg-primary-50/30">
                      <td className="py-3 px-4">
                        <input
                          type="text"
                          value={editForm.name}
                          onChange={(e) => setEditForm({ ...editForm, name: e.target.value })}
                          className="input"
                        />
                      </td>
                      <td className="py-3 px-4">
                        <input
                          type="email"
                          value={editForm.email}
                          onChange={(e) => setEditForm({ ...editForm, email: e.target.value })}
                          className="input"
                        />
                      </td>
                      <td className="py-3 px-4">
                        <select
                          value={editForm.role}
                          onChange={(e) => setEditForm({ ...editForm, role: e.target.value as UserRole })}
                          className="select"
                        >
                          <option value="user">普通用户</option>
                          <option value="manager">部门主管</option>
                          <option value="admin">系统管理员</option>
                        </select>
                      </td>
                      <td className="py-3 px-4">
                        <select
                          value={editForm.department_id}
                          onChange={(e) => setEditForm({ ...editForm, department_id: e.target.value })}
                          className="select"
                        >
                          {departments.map((dept) => (
                            <option key={dept.id} value={dept.id}>{dept.name}</option>
                          ))}
                        </select>
                      </td>
                      <td className="py-3 px-4 text-sm text-gray-500">
                        {formatDate(user.created_at)}
                      </td>
                      <td className="py-3 px-4 text-right">
                        <div className="flex justify-end gap-2">
                          <button
                            onClick={handleCancelEdit}
                            className="p-2 hover:bg-gray-100 rounded-lg text-gray-500"
                          >
                            <X className="w-4 h-4" />
                          </button>
                          <button
                            onClick={handleSaveEdit}
                            disabled={isSaving}
                            className="p-2 hover:bg-success-50 rounded-lg text-success-600"
                          >
                            <Save className="w-4 h-4" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                }

                return (
                  <tr key={user.id} className="border-b border-gray-100 hover:bg-gray-50 transition-colors">
                    <td className="py-3 px-4">
                      <div className="flex items-center gap-3">
                        <Avatar name={user.name} size="sm" />
                        <span className="font-medium text-gray-900">{user.name}</span>
                      </div>
                    </td>
                    <td className="py-3 px-4">
                      <div className="flex items-center gap-2 text-gray-600">
                        <Mail className="w-4 h-4 text-gray-400" />
                        {user.email}
                      </div>
                    </td>
                    <td className="py-3 px-4">
                      <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium ${roleColors[user.role]}`}>
                        <RoleIcon className="w-3.5 h-3.5" />
                        {roleLabels[user.role]}
                      </span>
                    </td>
                    <td className="py-3 px-4">
                      <div className="flex items-center gap-2 text-gray-600">
                        <Building2 className="w-4 h-4 text-gray-400" />
                        {department?.name || '未分配'}
                      </div>
                    </td>
                    <td className="py-3 px-4 text-sm text-gray-500">
                      {formatDate(user.created_at)}
                    </td>
                    <td className="py-3 px-4">
                      <div className="flex justify-end gap-2">
                        <button
                          onClick={() => handleEdit(user)}
                          className="p-2 hover:bg-primary-50 rounded-lg text-primary-600 transition-colors"
                          title="编辑"
                        >
                          <Edit2 className="w-4 h-4" />
                        </button>
                        <button
                          className="p-2 hover:bg-danger-50 rounded-lg text-danger-600 transition-colors"
                          title="删除"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>
    </AppLayout>
  );
}

// pages/users.vue
<template>
  <div>
    <div class="flex items-center justify-between mb-4">
      <h2 class="text-xl font-bold">用户管理</h2>
      <button class="btn btn-primary" @click="showCreateModal = true">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" style="width:16px;height:16px">
          <line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/>
        </svg>
        新增用户
      </button>
    </div>

    <div class="card">
      <div class="card-body" style="padding:0">
        <div class="overflow-x-auto">
          <table class="table">
            <thead>
              <tr>
                <th>用户</th>
                <th>用户名</th>
                <th>邮箱</th>
                <th>角色</th>
                <th>部门</th>
                <th>电话</th>
                <th>状态</th>
                <th>创建时间</th>
                <th>操作</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="u in users" :key="u.id">
                <td>
                  <div class="flex items-center gap-3">
                    <div class="user-avatar" style="width:36px;height:36px;font-size:14px">
                      {{ u.name?.charAt(0) }}
                    </div>
                    <span class="font-semibold">{{ u.name }}</span>
                  </div>
                </td>
                <td>{{ u.username }}</td>
                <td>{{ u.email }}</td>
                <td>
                  <span class="badge" :class="getRoleBadgeClass(u.role)">{{ getRoleLabel(u.role) }}</span>
                </td>
                <td class="text-gray-600">{{ u.department || '-' }}</td>
                <td class="text-gray-600">{{ u.phone || '-' }}</td>
                <td>
                  <span class="badge" :class="u.isActive ? 'badge-completed' : 'badge-error'">
                    {{ u.isActive ? '启用' : '禁用' }}
                  </span>
                </td>
                <td style="white-space:nowrap">{{ formatDate(u.createdAt, false) }}</td>
                <td>
                  <div class="flex items-center gap-2">
                    <button class="btn btn-secondary btn-sm" @click="editUser(u)">编辑</button>
                    <button class="btn btn-secondary btn-sm" :class="u.isActive ? '' : 'btn-success'" @click="toggleActive(u)">
                      {{ u.isActive ? '禁用' : '启用' }}
                    </button>
                  </div>
                </td>
              </tr>
              <tr v-if="users.length === 0">
                <td colspan="9" class="text-center text-gray-400 py-12">暂无用户</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <!-- 新增/编辑用户弹窗 -->
    <Teleport to="body">
      <Transition name="fade">
        <div v-if="showCreateModal || showEditModal" class="modal-mask" @click.self="closeModal">
          <div class="modal">
            <div class="modal-header">
              <div class="modal-title">{{ showCreateModal ? '新增用户' : '编辑用户' }}</div>
              <button class="modal-close" @click="closeModal">×</button>
            </div>
            <div class="modal-body">
              <div class="grid-2 mb-4">
                <div>
                  <label class="form-label"><span class="text-danger">*</span> 姓名</label>
                  <input v-model="form.name" class="form-input" placeholder="真实姓名" />
                </div>
                <div>
                  <label class="form-label"><span class="text-danger">*</span> 用户名</label>
                  <input v-model="form.username" class="form-input" :disabled="showEditModal" placeholder="登录用户名" />
                </div>
                <div>
                  <label class="form-label"><span class="text-danger">*</span> 角色</label>
                  <select v-model="form.role" class="form-select">
                    <option value="LEGAL_MANAGER">法务负责人</option>
                    <option value="LAWYER">律师</option>
                    <option value="REVIEWER">复核人</option>
                    <option value="ADMIN">系统管理员</option>
                  </select>
                </div>
                <div>
                  <label class="form-label"><span class="text-danger">*</span> 邮箱</label>
                  <input v-model="form.email" type="email" class="form-input" placeholder="name@example.com" />
                </div>
                <div v-if="showCreateModal">
                  <label class="form-label"><span class="text-danger">*</span> 初始密码</label>
                  <input v-model="form.password" type="text" class="form-input" placeholder="至少6位" />
                </div>
                <div>
                  <label class="form-label">部门</label>
                  <input v-model="form.department" class="form-input" placeholder="如：法务部" />
                </div>
                <div>
                  <label class="form-label">电话</label>
                  <input v-model="form.phone" class="form-input" placeholder="联系电话" />
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <button class="btn btn-secondary" @click="closeModal">取消</button>
              <button class="btn btn-primary" @click="saveUser">{{ showCreateModal ? '创建用户' : '保存修改' }}</button>
            </div>
          </div>
        </div>
      </Transition>
    </Teleport>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'

const ui = useUiStore()

const users = ref<any[]>([])
const showCreateModal = ref(false)
const showEditModal = ref(false)
const editingUserId = ref<string | null>(null)

const form = reactive({
  name: '',
  username: '',
  email: '',
  role: 'LAWYER',
  password: '',
  department: '',
  phone: ''
})

function resetForm() {
  Object.assign(form, {
    name: '', username: '', email: '', role: 'LAWYER',
    password: '', department: '', phone: ''
  })
  editingUserId.value = null
}

function closeModal() {
  showCreateModal.value = false
  showEditModal.value = false
  resetForm()
}

function editUser(u: any) {
  Object.assign(form, {
    name: u.name, username: u.username, email: u.email, role: u.role,
    department: u.department || '', phone: u.phone || ''
  })
  editingUserId.value = u.id
  showEditModal.value = true
}

async function fetchUsers() {
  ui.showLoading()
  try {
    const res: any = await $fetch('/api/users', { params: { pageSize: 200 } })
    users.value = res.data || []
  } finally {
    ui.hideLoading()
  }
}

async function saveUser() {
  if (!form.name || !form.username || !form.email || !form.role) {
    alert('请填写必填字段')
    return
  }
  if (showCreateModal.value && !form.password) {
    alert('请设置初始密码')
    return
  }
  ui.showLoading()
  try {
    if (showCreateModal.value) {
      await $fetch('/api/users', {
        method: 'POST',
        body: { ...form }
      })
    } else {
      await $fetch(`/api/users/${editingUserId.value}`, {
        method: 'PUT',
        body: { ...form }
      })
    }
    closeModal()
    alert('保存成功！')
    fetchUsers()
  } catch (e: any) {
    alert(e?.data?.message || e?.message || '操作失败')
  } finally {
    ui.hideLoading()
  }
}

async function toggleActive(u: any) {
  if (!confirm(`确定${u.isActive ? '禁用' : '启用'}用户 ${u.name}？`)) return
  try {
    await $fetch(`/api/users/${u.id}`, {
      method: 'PATCH',
      body: { isActive: !u.isActive }
    })
    fetchUsers()
  } catch (e: any) {
    alert(e?.data?.message || '操作失败')
  }
}

onMounted(() => {
  ui.setPageTitle('用户管理')
  ui.setActiveNav('users')
  fetchUsers()
})
</script>
