// client/src/routes/users.tsx
import { createFileRoute } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import { apiClient } from '@/api/client';
import DataTable from '@/components/DataTable';
import Modal from '@/components/Modal';
import dayjs from 'dayjs';

interface User {
  id: number;
  username: string;
  name: string;
  phone: string;
  email: string;
  role: string;
  status: string;
  createdAt: string;
  lastLogin: string;
}

export const Route = createFileRoute('/users')({
  component: UsersPage,
});

function UsersPage() {
  const [users, setUsers] = useState<User[]>([]);
  const [loading, setLoading] = useState(false);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(20);
  const [total, setTotal] = useState(0);
  const [modalOpen, setModalOpen] = useState(false);
  const [editingUser, setEditingUser] = useState<User | null>(null);
  const [formData, setFormData] = useState({
    username: '',
    name: '',
    phone: '',
    email: '',
    role: 'consultant' as 'admin' | 'consultant',
    password: '',
  });

  const fetchUsers = () => {
    setLoading(true);
    apiClient
      .get('/users', { params: { page, pageSize } })
      .then((res) => {
        setUsers(res.data.list || res.data);
        setTotal(res.data.total || (res.data.list ? res.data.list.length : res.data.length));
      })
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    fetchUsers();
  }, [page, pageSize]);

  const handleSubmit = () => {
    const data = { ...formData };
    if (!editingUser && !data.password) {
      alert('请输入密码');
      return;
    }
    if (editingUser && !data.password) {
      delete (data as { password?: string }).password;
    }
    
    const promise = editingUser
      ? apiClient.put(`/users/${editingUser.id}`, data)
      : apiClient.post('/users', data);
    
    promise.then(() => {
      setModalOpen(false);
      fetchUsers();
    });
  };

  const handleToggleStatus = (user: User) => {
    const newStatus = user.status === 'active' ? 'inactive' : 'active';
    if (confirm(`确定要${newStatus === 'active' ? '启用' : '禁用'}用户 "${user.name}" 吗？`)) {
      apiClient.patch(`/users/${user.id}/status`, { status: newStatus }).then(fetchUsers);
    }
  };

  const handleResetPassword = (user: User) => {
    const newPassword = prompt('请输入新密码：');
    if (newPassword && newPassword.length >= 6) {
      apiClient.patch(`/users/${user.id}/password`, { password: newPassword }).then(() => {
        alert('密码重置成功');
      });
    } else if (newPassword) {
      alert('密码长度至少6位');
    }
  };

  const openEditModal = (user: User) => {
    setEditingUser(user);
    setFormData({
      username: user.username,
      name: user.name,
      phone: user.phone,
      email: user.email,
      role: user.role as 'admin' | 'consultant',
      password: '',
    });
    setModalOpen(true);
  };

  const openCreateModal = () => {
    setEditingUser(null);
    setFormData({
      username: '',
      name: '',
      phone: '',
      email: '',
      role: 'consultant',
      password: '',
    });
    setModalOpen(true);
  };

  const columns = [
    {
      key: 'name',
      title: '姓名',
      render: (r: User) => (
        <div className="flex items-center">
          <div className="w-8 h-8 bg-blue-500 rounded-full flex items-center justify-center text-white text-sm font-semibold mr-3">
            {r.name?.charAt(0)}
          </div>
          <div>
            <div className="font-medium text-gray-800">{r.name}</div>
            <div className="text-xs text-gray-500">@{r.username}</div>
          </div>
        </div>
      ),
    },
    {
      key: 'phone',
      title: '联系电话',
      render: (r: User) => r.phone || '-',
    },
    {
      key: 'email',
      title: '邮箱',
      render: (r: User) => r.email || '-',
    },
    {
      key: 'role',
      title: '角色',
      render: (r: User) => (
        <span className={`px-2 py-1 rounded text-xs ${r.role === 'admin' ? 'bg-purple-100 text-purple-800' : 'bg-blue-100 text-blue-800'}`}>
          {r.role === 'admin' ? '管理员' : '顾问'}
        </span>
      ),
    },
    {
      key: 'status',
      title: '状态',
      render: (r: User) => (
        <span className={`px-2 py-1 rounded text-xs ${r.status === 'active' ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800'}`}>
          {r.status === 'active' ? '正常' : '禁用'}
        </span>
      ),
    },
    {
      key: 'lastLogin',
      title: '最后登录',
      render: (r: User) => r.lastLogin ? dayjs(r.lastLogin).format('YYYY-MM-DD HH:mm') : '-',
    },
    {
      key: 'createdAt',
      title: '创建时间',
      render: (r: User) => dayjs(r.createdAt).format('YYYY-MM-DD'),
    },
  ];

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-gray-800">用户管理</h1>
        <button
          onClick={openCreateModal}
          className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
        >
          + 新增用户
        </button>
      </div>

      <DataTable
        columns={columns}
        data={users}
        loading={loading}
        total={total}
        page={page}
        pageSize={pageSize}
        onPageChange={setPage}
        onPageSizeChange={setPageSize}
        rowKey={(r) => r.id}
        actions={(r) => (
          <>
            <button
              onClick={() => openEditModal(r)}
              className="text-blue-600 hover:text-blue-800"
            >
              编辑
            </button>
            <button
              onClick={() => handleResetPassword(r)}
              className="text-yellow-600 hover:text-yellow-800"
            >
              重置密码
            </button>
            <button
              onClick={() => handleToggleStatus(r)}
              className={r.status === 'active' ? 'text-red-600 hover:text-red-800' : 'text-green-600 hover:text-green-800'}
            >
              {r.status === 'active' ? '禁用' : '启用'}
            </button>
          </>
        )}
      />

      <Modal
        open={modalOpen}
        title={editingUser ? '编辑用户' : '新增用户'}
        onClose={() => setModalOpen(false)}
        width="max-w-2xl"
        footer={
          <>
            <button
              onClick={() => setModalOpen(false)}
              className="px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50"
            >
              取消
            </button>
            <button
              onClick={handleSubmit}
              className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
            >
              保存
            </button>
          </>
        }
      >
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">用户名 *</label>
            <input
              type="text"
              value={formData.username}
              onChange={(e) => setFormData({ ...formData, username: e.target.value })}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg"
              placeholder="登录账号"
              required
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">姓名 *</label>
            <input
              type="text"
              value={formData.name}
              onChange={(e) => setFormData({ ...formData, name: e.target.value })}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg"
              placeholder="真实姓名"
              required
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">角色 *</label>
            <select
              value={formData.role}
              onChange={(e) => setFormData({ ...formData, role: e.target.value as 'admin' | 'consultant' })}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg"
              required
            >
              <option value="consultant">顾问</option>
              <option value="admin">管理员</option>
            </select>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              密码 {!editingUser && <span className="text-red-500">*</span>}
            </label>
            <input
              type="password"
              value={formData.password}
              onChange={(e) => setFormData({ ...formData, password: e.target.value })}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg"
              placeholder={editingUser ? '不修改请留空' : '至少6位'}
            />
            {editingUser && (
              <p className="mt-1 text-xs text-gray-500">不修改密码请留空</p>
            )}
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">电话</label>
            <input
              type="tel"
              value={formData.phone}
              onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg"
              placeholder="手机号码"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">邮箱</label>
            <input
              type="email"
              value={formData.email}
              onChange={(e) => setFormData({ ...formData, email: e.target.value })}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg"
              placeholder="电子邮箱"
            />
          </div>
        </div>
      </Modal>
    </div>
  );
}

// pages/users.vue
<template>
  <div>
    <div class="flex items-center justify-between mb-4">
      <h2 class="text-xl font-bold">用户管理</h2>
      <button class="btn btn-primary" @click="showCreateModal = true">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" style="width:16px;height:16px">
          <line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/>
        </svg>
        新增用户
      </button>
    </div>

    <div class="card">
      <div class="card-body" style="padding:0">
        <div class="overflow-x-auto">
          <table class="table">
            <thead>
              <tr>
                <th>用户</th>
                <th>用户名</th>
                <th>邮箱</th>
                <th>角色</th>
                <th>部门</th>
                <th>电话</th>
                <th>状态</th>
                <th>创建时间</th>
                <th>操作</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="u in users" :key="u.id">
                <td>
                  <div class="flex items-center gap-3">
                    <div class="user-avatar" style="width:36px;height:36px;font-size:14px">
                      {{ u.name?.charAt(0) }}
                    </div>
                    <span class="font-semibold">{{ u.name }}</span>
                  </div>
                </td>
                <td>{{ u.username }}</td>
                <td>{{ u.email }}</td>
                <td>
                  <span class="badge" :class="getRoleBadgeClass(u.role)">{{ getRoleLabel(u.role) }}</span>
                </td>
                <td class="text-gray-600">{{ u.department || '-' }}</td>
                <td class="text-gray-600">{{ u.phone || '-' }}</td>
                <td>
                  <span class="badge" :class="u.isActive ? 'badge-completed' : 'badge-error'">
                    {{ u.isActive ? '启用' : '禁用' }}
                  </span>
                </td>
                <td style="white-space:nowrap">{{ formatDate(u.createdAt, false) }}</td>
                <td>
                  <div class="flex items-center gap-2">
                    <button class="btn btn-secondary btn-sm" @click="editUser(u)">编辑</button>
                    <button class="btn btn-secondary btn-sm" :class="u.isActive ? '' : 'btn-success'" @click="toggleActive(u)">
                      {{ u.isActive ? '禁用' : '启用' }}
                    </button>
                  </div>
                </td>
              </tr>
              <tr v-if="users.length === 0">
                <td colspan="9" class="text-center text-gray-400 py-12">暂无用户</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <!-- 新增/编辑用户弹窗 -->
    <Teleport to="body">
      <Transition name="fade">
        <div v-if="showCreateModal || showEditModal" class="modal-mask" @click.self="closeModal">
          <div class="modal">
            <div class="modal-header">
              <div class="modal-title">{{ showCreateModal ? '新增用户' : '编辑用户' }}</div>
              <button class="modal-close" @click="closeModal">×</button>
            </div>
            <div class="modal-body">
              <div class="grid-2 mb-4">
                <div>
                  <label class="form-label"><span class="text-danger">*</span> 姓名</label>
                  <input v-model="form.name" class="form-input" placeholder="真实姓名" />
                </div>
                <div>
                  <label class="form-label"><span class="text-danger">*</span> 用户名</label>
                  <input v-model="form.username" class="form-input" :disabled="showEditModal" placeholder="登录用户名" />
                </div>
                <div>
                  <label class="form-label"><span class="text-danger">*</span> 角色</label>
                  <select v-model="form.role" class="form-select">
                    <option value="LEGAL_MANAGER">法务负责人</option>
                    <option value="LAWYER">律师</option>
                    <option value="REVIEWER">复核人</option>
                    <option value="ADMIN">系统管理员</option>
                  </select>
                </div>
                <div>
                  <label class="form-label"><span class="text-danger">*</span> 邮箱</label>
                  <input v-model="form.email" type="email" class="form-input" placeholder="name@example.com" />
                </div>
                <div v-if="showCreateModal">
                  <label class="form-label"><span class="text-danger">*</span> 初始密码</label>
                  <input v-model="form.password" type="text" class="form-input" placeholder="至少6位" />
                </div>
                <div>
                  <label class="form-label">部门</label>
                  <input v-model="form.department" class="form-input" placeholder="如：法务部" />
                </div>
                <div>
                  <label class="form-label">电话</label>
                  <input v-model="form.phone" class="form-input" placeholder="联系电话" />
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <button class="btn btn-secondary" @click="closeModal">取消</button>
              <button class="btn btn-primary" @click="saveUser">{{ showCreateModal ? '创建用户' : '保存修改' }}</button>
            </div>
          </div>
        </div>
      </Transition>
    </Teleport>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'

const ui = useUiStore()

const users = ref<any[]>([])
const showCreateModal = ref(false)
const showEditModal = ref(false)
const editingUserId = ref<string | null>(null)

const form = reactive({
  name: '',
  username: '',
  email: '',
  role: 'LAWYER',
  password: '',
  department: '',
  phone: ''
})

function resetForm() {
  Object.assign(form, {
    name: '', username: '', email: '', role: 'LAWYER',
    password: '', department: '', phone: ''
  })
  editingUserId.value = null
}

function closeModal() {
  showCreateModal.value = false
  showEditModal.value = false
  resetForm()
}

function editUser(u: any) {
  Object.assign(form, {
    name: u.name, username: u.username, email: u.email, role: u.role,
    department: u.department || '', phone: u.phone || ''
  })
  editingUserId.value = u.id
  showEditModal.value = true
}

async function fetchUsers() {
  ui.showLoading()
  try {
    const res: any = await $fetch('/api/users', { params: { pageSize: 200 } })
    users.value = res.data || []
  } finally {
    ui.hideLoading()
  }
}

async function saveUser() {
  if (!form.name || !form.username || !form.email || !form.role) {
    alert('请填写必填字段')
    return
  }
  if (showCreateModal.value && !form.password) {
    alert('请设置初始密码')
    return
  }
  ui.showLoading()
  try {
    if (showCreateModal.value) {
      await $fetch('/api/users', {
        method: 'POST',
        body: { ...form }
      })
    } else {
      await $fetch(`/api/users/${editingUserId.value}`, {
        method: 'PUT',
        body: { ...form }
      })
    }
    closeModal()
    alert('保存成功！')
    fetchUsers()
  } catch (e: any) {
    alert(e?.data?.message || e?.message || '操作失败')
  } finally {
    ui.hideLoading()
  }
}

async function toggleActive(u: any) {
  if (!confirm(`确定${u.isActive ? '禁用' : '启用'}用户 ${u.name}？`)) return
  try {
    await $fetch(`/api/users/${u.id}`, {
      method: 'PATCH',
      body: { isActive: !u.isActive }
    })
    fetchUsers()
  } catch (e: any) {
    alert(e?.data?.message || '操作失败')
  }
}

onMounted(() => {
  ui.setPageTitle('用户管理')
  ui.setActiveNav('users')
  fetchUsers()
})
</script>
