// test-drive-dashboard/src/lib/components/FunnelChart.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import * as echarts from 'echarts';
  import type { FunnelData } from '$lib/types';

  interface Props {
    data: FunnelData | null;
  }

  let { data }: Props = $props();

  let chartEl: HTMLDivElement;
  let chart: echarts.ECharts;
  let activeTab: string = $state('overall');

  onMount(() => {
    chart = echarts.init(chartEl);
    const ro = new ResizeObserver(() => chart?.resize());
    ro.observe(chartEl);
    return () => ro.disconnect();
  });

  $effect(() => {
    if (!data || !chart) return;

    if (activeTab === 'overall') {
      renderOverallFunnel(data);
    } else {
      renderModelFunnel(data);
    }
  });

  function renderOverallFunnel(funnelData: FunnelData) {
    const maxVal = Math.max(...funnelData.stages.map(s => s.count), 1);
    chart.setOption({
      tooltip: {
        trigger: 'item',
        formatter: (params: Record<string, unknown>) => {
          const d = params.data as Record<string, unknown>;
          return `${d.name}<br/>数量: ${d.value}<br/>占比: ${((d.value as number) / maxVal * 100).toFixed(1)}%`;
        }
      },
      series: [{
        type: 'funnel',
        left: '10%',
        top: 30,
        bottom: 30,
        width: '80%',
        min: 0,
        max: maxVal,
        minSize: '0%',
        maxSize: '100%',
        sort: 'descending',
        gap: 4,
        label: {
          show: true,
          position: 'inside',
          formatter: (params: Record<string, unknown>) => {
            const d = params.data as Record<string, unknown>;
            return `${d.name}\n${d.value}`;
          },
          fontSize: 14,
          fontWeight: 'bold',
          color: '#fff'
        },
        itemStyle: {
          borderColor: '#fff',
          borderWidth: 1
        },
        data: funnelData.stages.map((s, i) => ({
          value: s.count,
          name: s.name,
          itemStyle: {
            color: ['#3b82f6', '#6366f1', '#8b5cf6', '#a855f7', '#ec4899'][i]
          }
        }))
      }]
    }, true);
  }

  function renderModelFunnel(funnelData: FunnelData) {
    const models = Object.keys(funnelData.by_model);
    const stageNames = ['预约提交', '确认到店', '实际到店', '完成试驾', '成交转化'];

    chart.setOption({
      tooltip: {
        trigger: 'axis',
        axisPointer: { type: 'shadow' }
      },
      legend: {
        data: stageNames,
        top: 0
      },
      grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
      },
      xAxis: {
        type: 'category',
        data: models,
        axisLabel: { rotate: 30, fontSize: 11 }
      },
      yAxis: {
        type: 'value'
      },
      series: stageNames.map((name, i) => ({
        name,
        type: 'bar',
        stack: 'total',
        data: models.map(m => {
          const stages = funnelData.by_model[m];
          return stages[i]?.count || 0;
        }),
        itemStyle: {
          color: ['#3b82f6', '#6366f1', '#8b5cf6', '#a855f7', '#ec4899'][i]
        }
      }))
    }, true);
  }
</script>

<div class="panel">
  <div class="panel-header">
    <h3>预约漏斗</h3>
    <div class="tab-group">
      <button class:active={activeTab === 'overall'} onclick={() => activeTab = 'overall'}>总览</button>
      <button class:active={activeTab === 'model'} onclick={() => activeTab = 'model'}>按车型</button>
    </div>
  </div>
  <div class="chart-container" bind:this={chartEl}></div>
</div>

<style>
  .panel {
    background: #fff;
    border-radius: 12px;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.08);
    padding: 20px;
    height: 420px;
    display: flex;
    flex-direction: column;
  }

  .panel-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 12px;
  }

  .panel-header h3 {
    font-size: 16px;
    font-weight: 600;
    color: #1f2937;
    margin: 0;
  }

  .tab-group {
    display: flex;
    gap: 4px;
    background: #f3f4f6;
    border-radius: 8px;
    padding: 2px;
  }

  .tab-group button {
    padding: 4px 14px;
    border: none;
    border-radius: 6px;
    font-size: 12px;
    cursor: pointer;
    background: transparent;
    color: #6b7280;
    transition: all 0.2s;
  }

  .tab-group button.active {
    background: #fff;
    color: #3b82f6;
    box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);
    font-weight: 500;
  }

  .chart-container {
    flex: 1;
    min-height: 0;
  }
</style>

// src/components/dashboard/funnel-chart.tsx
"use client";

import { useState, useMemo } from "react";
import { useQuery } from "@tanstack/react-query";
import { trpc } from "@/hooks/use-trpc";
import type { FunnelFilter } from "@/lib/types";
import { isLowSample } from "@/lib/utils";
import ReactECharts from "echarts-for-react";
import { AlertTriangle } from "lucide-react";

type FunnelChartProps = {
  filters: FunnelFilter;
};

const FUNNEL_COLORS = [
  "#1E3A5F",
  "#2D5A8E",
  "#4A7FB5",
  "#6BA3D6",
  "#8EC0EA",
  "#B5D8F5",
];

const DRILLDOWN_TABS = [
  { key: "campus" as const, label: "校区" },
  { key: "course" as const, label: "课程" },
  { key: "ageGroup" as const, label: "年龄段" },
  { key: "channel" as const, label: "渠道" },
] as const;

type DrilldownDimension = (typeof DRILLDOWN_TABS)[number]["key"];

export function FunnelChart({ filters }: FunnelChartProps) {
  const [activeDimension, setActiveDimension] = useState<DrilldownDimension>("campus");

  const { data, isLoading } = useQuery({
    queryKey: ["funnel", filters],
    queryFn: () => trpc.funnel.getFunnel.query(filters),
  });

  const funnelOption = useMemo(() => {
    if (!data) return {};
    return {
      tooltip: {
        trigger: "item" as const,
        formatter: (params: { name: string; value: number; percent: number }) =>
          `${params.name}<br/>数量: ${params.value}<br/>占比: ${params.percent}%`,
      },
      series: [
        {
          type: "funnel" as const,
          left: "10%",
          top: 20,
          bottom: 20,
          width: "80%",
          height: "70%",
          sort: "descending" as const,
          gap: 4,
          label: {
            show: true,
            position: "inside" as const,
            formatter: (params: { name: string; value: number }) =>
              `${params.name}: ${params.value}`,
            fontSize: 13,
            color: "#fff",
          },
          itemStyle: {
            borderColor: "#fff",
            borderWidth: 1,
          },
          data: data.data.map((item, i) => ({
            name: item.label,
            value: item.count,
            itemStyle: { color: FUNNEL_COLORS[i] ?? FUNNEL_COLORS[FUNNEL_COLORS.length - 1] },
          })),
        },
      ],
    };
  }, [data]);

  const drilldownData = useMemo(() => {
    if (!data) return null;
    return data.drilldown.find((d) => d.dimension === activeDimension) ?? null;
  }, [data, activeDimension]);

  const drilldownOption = useMemo(() => {
    if (!drilldownData) return {};
    return {
      tooltip: { trigger: "axis" as const, axisPointer: { type: "shadow" as const } },
      grid: { left: 120, right: 40, top: 10, bottom: 20 },
      xAxis: { type: "value" as const },
      yAxis: {
        type: "category" as const,
        data: drilldownData.items.map((item) => item.label),
        axisLabel: { fontSize: 12 },
      },
      series: [
        {
          type: "bar" as const,
          data: drilldownData.items.map((item) => {
            const waitlistItem = item.data.find((d) => d.stage === "waitlist");
            return waitlistItem?.count ?? 0;
          }),
          itemStyle: {
            color: "#4A7FB5",
            borderRadius: [0, 4, 4, 0],
          },
          barWidth: 20,
          label: {
            show: true,
            position: "right" as const,
            fontSize: 12,
            color: "#6B7B8D",
          },
        },
      ],
    };
  }, [drilldownData]);

  const hasLowSample = useMemo(() => {
    if (!drilldownData) return false;
    return drilldownData.items.some((item) => {
      const waitlistItem = item.data.find((d) => d.stage === "waitlist");
      return isLowSample(waitlistItem?.count ?? 0);
    });
  }, [drilldownData]);

  if (isLoading) {
    return (
      <div className="bg-white rounded-xl p-5 shadow-sm border border-border">
        <div className="h-[420px] bg-bg rounded-lg animate-pulse" />
      </div>
    );
  }

  return (
    <div className="bg-white rounded-xl p-5 shadow-sm border border-border">
      <ReactECharts option={funnelOption} style={{ height: 420 }} />

      <div className="mt-4 pt-4 border-t border-border">
        <div className="flex items-center gap-2 mb-3">
          <span className="text-sm font-medium text-text-secondary">下钻维度</span>
          {hasLowSample && (
            <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded text-xs bg-warning/10 text-warning font-medium">
              <AlertTriangle size={12} />
              低样本量
            </span>
          )}
        </div>
        <div className="flex gap-2 mb-4">
          {DRILLDOWN_TABS.map((tab) => (
            <button
              key={tab.key}
              onClick={() => setActiveDimension(tab.key)}
              className={`px-3 py-1.5 rounded-lg text-sm font-medium transition-colors ${
                activeDimension === tab.key
                  ? "bg-primary text-white"
                  : "bg-bg text-text-secondary hover:bg-primary/5"
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>
        <ReactECharts option={drilldownOption} style={{ height: 240 }} />
      </div>
    </div>
  );
}
