// frontend/components/TrendChart.vue
<template>
  <div ref="chartRef" style="width: 100%; height: 320px;"></div>
</template>

<script setup lang="ts">
import { ref, onMounted, watch } from 'vue'
import * as echarts from 'echarts'

const props = defineProps<{ data?: any }>()
const chartRef = ref<HTMLElement | null>(null)
let instance: any = null

function render() {
  if (!chartRef.value) return
  if (!instance) instance = echarts.init(chartRef.value)
  const list = props.data?.last_14_days || []
  const dates = list.map((x: any) => x.date.slice(5))
  const option = {
    tooltip: { trigger: 'axis' },
    legend: { data: ['新提交', '新缺口', '完成数'], right: 0, top: 0, textStyle: { fontSize: 12 } },
    grid: { left: 36, right: 16, top: 40, bottom: 30 },
    xAxis: { type: 'category', data: dates, axisLine: { lineStyle: { color: '#e5e7eb' } }, axisLabel: { fontSize: 11, color: '#6b7280' } },
    yAxis: { type: 'value', splitLine: { lineStyle: { color: '#f3f4f6' } }, axisLabel: { fontSize: 11, color: '#6b7280' } },
    series: [
      { name: '新提交', type: 'line', smooth: true, data: list.map((x: any) => x.submission_count), itemStyle: { color: '#2d8a5e' }, lineStyle: { width: 2.5 }, areaStyle: { color: 'rgba(45,138,94,0.1)' } },
      { name: '新缺口', type: 'line', smooth: true, data: list.map((x: any) => x.gap_count), itemStyle: { color: '#d03050' }, lineStyle: { width: 2.5 }, areaStyle: { color: 'rgba(208,48,80,0.08)' } },
      { name: '完成数', type: 'bar', data: list.map((x: any) => x.completed_count), itemStyle: { color: '#1d6ff2', borderRadius: [4,4,0,0] }, barWidth: 10 },
    ],
  }
  instance.setOption(option)
}

onMounted(render)
watch(() => props.data, render, { deep: true })
</script>

// src/components/dashboard/trend-chart.tsx
"use client";

import { useMemo } from "react";
import { useQuery } from "@tanstack/react-query";
import { trpc } from "@/hooks/use-trpc";
import type { FunnelFilter } from "@/lib/types";
import ReactECharts from "echarts-for-react";

type TrendChartProps = {
  filters: FunnelFilter;
};

export function TrendChart({ filters }: TrendChartProps) {
  const { data, isLoading } = useQuery({
    queryKey: ["trend", filters],
    queryFn: () =>
      trpc.funnel.getTrend.query({ ...filters, granularity: "month" }),
  });

  const option = useMemo(() => {
    if (!data) return {};

    return {
      tooltip: {
        trigger: "axis" as const,
        axisPointer: { type: "cross" as const },
      },
      legend: {
        data: ["候补量", "转正率"],
        bottom: 0,
        textStyle: { fontSize: 12, color: "#6B7B8D" },
      },
      grid: {
        containLabel: true,
        left: 50,
        right: 60,
        top: 20,
        bottom: 40,
      },
      xAxis: {
        type: "category" as const,
        data: data.map((d) => d.period),
        axisLabel: { fontSize: 12, color: "#6B7B8D" },
        axisTick: { show: false },
        axisLine: { lineStyle: { color: "#E2E8F0" } },
      },
      yAxis: [
        {
          type: "value" as const,
          name: "候补量",
          nameTextStyle: { fontSize: 12, color: "#6B7B8D" },
          axisLabel: { fontSize: 12, color: "#6B7B8D" },
          splitLine: { lineStyle: { color: "#F0F0F0" } },
        },
        {
          type: "value" as const,
          name: "转正率",
          nameTextStyle: { fontSize: 12, color: "#6B7B8D" },
          axisLabel: {
            fontSize: 12,
            color: "#6B7B8D",
            formatter: (v: number) => `${(v * 100).toFixed(0)}%`,
          },
          splitLine: { show: false },
        },
      ],
      series: [
        {
          name: "候补量",
          type: "bar" as const,
          yAxisIndex: 0,
          data: data.map((d) => d.waitlistCount),
          itemStyle: {
            color: "rgba(30, 58, 95, 0.6)",
            borderRadius: [4, 4, 0, 0],
          },
          barWidth: 28,
        },
        {
          name: "转正率",
          type: "line" as const,
          yAxisIndex: 1,
          data: data.map((d) => d.conversionRate),
          itemStyle: { color: "#E8A838" },
          lineStyle: { width: 2, color: "#E8A838" },
          smooth: true,
          showSymbol: true,
          symbolSize: 6,
          symbol: "circle",
        },
      ],
    };
  }, [data]);

  if (isLoading) {
    return (
      <div className="bg-white rounded-xl p-5 shadow-sm border border-border">
        <div className="h-[350px] bg-bg rounded-lg animate-pulse" />
      </div>
    );
  }

  return (
    <div className="bg-white rounded-xl p-5 shadow-sm border border-border">
      <ReactECharts option={option} style={{ height: 350 }} />
    </div>
  );
}
