// src/routes/todos/+page.svelte
<script lang="ts">
	let { data } = $props();

	let todos = $state<any[]>(data.todos);
	let statusFilter = $state('');
	let urgencyFilter = $state('');
	let panelOpen = $state(false);
	let selectedTodo: any = $state(null);
	let errorMessage = $state('');
	let submitLoading = $state(false);

	let formStatus = $state('in_progress');
	let formResult = $state('');
	let formEvidence = $state('');

	const statusTabs = [
		{ key: '', label: '全部' },
		{ key: 'pending', label: '待处理' },
		{ key: 'in_progress', label: '处理中' },
		{ key: 'completed', label: '已完成' }
	];

	const urgencyTabs = [
		{ key: '', label: '全部' },
		{ key: 'high', label: '紧急' },
		{ key: 'medium', label: '中等' },
		{ key: 'low', label: '一般' }
	];

	const filteredTodos = $derived(() => {
		let result = [...todos];
		if (statusFilter) {
			result = result.filter((t: any) => t.status === statusFilter);
		}
		if (urgencyFilter) {
			result = result.filter((t: any) => t.urgency === urgencyFilter);
		}
		result.sort((a: any, b: any) => {
			const urgencyOrder: Record<string, number> = { high: 0, medium: 1, low: 2 };
			const ua = urgencyOrder[a.urgency] ?? 3;
			const ub = urgencyOrder[b.urgency] ?? 3;
			if (ua !== ub) return ua - ub;
			return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
		});
		return result;
	});

	function urgencyBadge(urgency: string): { label: string; cls: string } {
		switch (urgency) {
			case 'high': return { label: '紧急', cls: 'bg-danger/15 text-danger' };
			case 'medium': return { label: '中等', cls: 'bg-warning/15 text-warning' };
			case 'low': return { label: '一般', cls: 'bg-blue-500/15 text-blue-600' };
			default: return { label: urgency, cls: 'bg-gray-400/15 text-gray-500' };
		}
	}

	function statusBadge(status: string): { label: string; cls: string } {
		switch (status) {
			case 'pending': return { label: '待处理', cls: 'bg-warning/15 text-warning' };
			case 'in_progress': return { label: '处理中', cls: 'bg-blue-500/15 text-blue-600' };
			case 'completed': return { label: '已完成', cls: 'bg-success/15 text-success' };
			default: return { label: status, cls: 'bg-gray-400/15 text-gray-500' };
		}
	}

	function sourceLabel(source: string): string {
		switch (source) {
			case 'escalation': return '催办升级';
			case 'manual': return '手动创建';
			default: return source;
		}
	}

	function sourceBadgeClass(source: string): string {
		switch (source) {
			case 'escalation': return 'bg-accent/15 text-accent';
			case 'manual': return 'bg-purple-500/15 text-purple-600';
			default: return 'bg-gray-400/15 text-gray-500';
		}
	}

	function formatTime(ts: string): string {
		if (!ts) return '-';
		return new Date(ts).toLocaleString('zh-CN', {
			year: 'numeric', month: '2-digit', day: '2-digit',
			hour: '2-digit', minute: '2-digit'
		});
	}

	function relativeTime(ts: string): string {
		if (!ts) return '-';
		const now = Date.now();
		const then = new Date(ts).getTime();
		const diff = now - then;
		const minutes = Math.floor(diff / 60000);
		if (minutes < 1) return '刚刚';
		if (minutes < 60) return `${minutes}分钟前`;
		const hours = Math.floor(minutes / 60);
		if (hours < 24) return `${hours}小时前`;
		const days = Math.floor(hours / 24);
		if (days < 30) return `${days}天前`;
		return formatTime(ts);
	}

	function openProcessPanel(todo: any) {
		selectedTodo = todo;
		formStatus = todo.status === 'completed' ? 'completed' : 'in_progress';
		formResult = todo.result || '';
		formEvidence = todo.evidence || '';
		errorMessage = '';
		panelOpen = true;
	}

	function closePanel() {
		panelOpen = false;
		selectedTodo = null;
	}

	async function submitProcess() {
		if (!selectedTodo) return;
		if (formStatus === 'completed' && !formEvidence.trim()) {
			errorMessage = '完成待办时处理依据为必填';
			return;
		}

		submitLoading = true;
		errorMessage = '';
		try {
			const res = await fetch(`/api/todos/${selectedTodo.id}`, {
				method: 'PATCH',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({
					status: formStatus,
					result: formResult.trim() || undefined,
					evidence: formEvidence.trim() || undefined,
					operatorId: 'admin',
					operatorName: '管理员'
				})
			});
			if (!res.ok) {
				const err = await res.json();
				throw new Error(err.error || '处理失败');
			}
			closePanel();
			await refreshData();
		} catch (e: any) {
			errorMessage = e.message || '处理失败';
		} finally {
			submitLoading = false;
		}
	}

	async function refreshData() {
		try {
			const res = await fetch('/api/todos');
			const d = await res.json();
			todos = d.todos || [];
		} catch (e) {
			console.error('刷新数据失败', e);
		}
	}
</script>

<svelte:head>
	<title>待办中心 - 导览协作</title>
</svelte:head>

<div class="flex flex-1 flex-col overflow-auto">
	<header class="flex items-center justify-between border-b border-gray-200 bg-white px-8 py-4">
		<h1 class="font-serif text-2xl font-bold text-text">待办中心</h1>
		<span class="text-sm text-text-muted">共 {filteredTodos().length} 条待办</span>
	</header>

	<main class="flex-1 p-8">
		<div class="mb-6 flex flex-wrap gap-3">
			<div class="flex rounded-lg bg-white border border-gray-100 overflow-hidden shadow-sm">
				{#each statusTabs as tab}
					<button
						type="button"
						onclick={() => { statusFilter = tab.key; }}
						class="px-4 py-2 text-sm font-medium transition-colors {statusFilter === tab.key
							? 'bg-primary text-white'
							: 'text-text-muted hover:text-text hover:bg-surface'}"
					>
						{tab.label}
					</button>
				{/each}
			</div>
			<div class="flex rounded-lg bg-white border border-gray-100 overflow-hidden shadow-sm">
				{#each urgencyTabs as tab}
					<button
						type="button"
						onclick={() => { urgencyFilter = tab.key; }}
						class="px-4 py-2 text-sm font-medium transition-colors {urgencyFilter === tab.key
							? 'bg-accent text-white'
							: 'text-text-muted hover:text-text hover:bg-surface'}"
					>
						{tab.label}
					</button>
				{/each}
			</div>
		</div>

		{#if filteredTodos().length === 0}
			<div class="flex flex-col items-center justify-center py-24 text-text-muted">
				<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="mb-4 opacity-30"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/></svg>
				<p class="text-lg font-serif">暂无匹配的待办</p>
				<p class="mt-1 text-sm">当前筛选条件下没有待办事项</p>
			</div>
		{:else}
			<div class="space-y-3">
				{#each filteredTodos() as todo (todo.id)}
					{@const ub = urgencyBadge(todo.urgency)}
					{@const sb = statusBadge(todo.status)}
					<div class="rounded-xl bg-white shadow-sm border border-gray-100 p-5 transition-all duration-200 hover:shadow-md">
						<div class="flex items-start justify-between gap-4">
							<div class="flex-1 min-w-0">
								<div class="flex items-center gap-2 mb-2 flex-wrap">
									<span class="inline-flex rounded-full px-2.5 py-0.5 text-xs font-medium {ub.cls}">
										{ub.label}
									</span>
									<span class="inline-flex rounded-full px-2.5 py-0.5 text-xs font-medium {sb.cls}">
										{sb.label}
									</span>
									<span class="inline-flex rounded-full px-2.5 py-0.5 text-xs font-medium {sourceBadgeClass(todo.source)}">
										{sourceLabel(todo.source)}
									</span>
								</div>

								<p class="text-sm text-text leading-relaxed mb-2">{todo.description}</p>

								{#if todo.routeName || todo.itineraryId}
									<div class="flex items-center gap-3 text-xs text-text-muted mb-1">
										{#if todo.routeName}
											<span>路线: {todo.routeName}</span>
										{/if}
										{#if todo.itineraryId}
											<span>行程: {todo.itineraryId.slice(0, 8)}...</span>
										{/if}
									</div>
								{/if}

								{#if todo.status === 'completed'}
									<div class="mt-3 rounded-lg bg-success/5 border border-success/10 p-3 space-y-1">
										{#if todo.result}
											<div class="text-xs"><span class="font-medium text-text">处理结果:</span> <span class="text-text-muted">{todo.result}</span></div>
										{/if}
										{#if todo.evidence}
											<div class="text-xs"><span class="font-medium text-text">处理依据:</span> <span class="text-text-muted">{todo.evidence}</span></div>
										{/if}
										<div class="text-xs text-text-muted">
											处理人: {todo.operatorName || '-'} · 完成时间: {formatTime(todo.completedAt)}
										</div>
									</div>
								{:else}
									<div class="mt-2 text-xs text-text-muted">
										创建时间: {relativeTime(todo.createdAt)}
									</div>
								{/if}
							</div>

							{#if todo.status !== 'completed'}
								<button
									type="button"
									onclick={() => openProcessPanel(todo)}
									class="flex-shrink-0 rounded-lg bg-primary px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-primary-light"
								>
									处理
								</button>
							{/if}
						</div>
					</div>
				{/each}
			</div>
		{/if}
	</main>
</div>

{#if panelOpen && selectedTodo}
	<div class="fixed inset-0 z-40 flex justify-end">
		<div class="absolute inset-0 bg-black/30" onclick={closePanel} role="presentation"></div>
		<div class="relative z-50 w-full max-w-md bg-white shadow-2xl flex flex-col transition-transform">
			<div class="flex items-center justify-between border-b border-gray-200 px-6 py-4">
				<h2 class="font-serif text-lg font-semibold text-text">处理待办</h2>
				<button type="button" onclick={closePanel} class="rounded-lg p-1.5 text-text-muted hover:bg-surface hover:text-text transition-colors">
					<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>
				</button>
			</div>

			<div class="flex-1 overflow-y-auto p-6 space-y-5">
				<div class="rounded-lg bg-surface p-4 space-y-2">
					<div class="flex items-center gap-2 mb-1">
						<span class="inline-flex rounded-full px-2.5 py-0.5 text-xs font-medium {urgencyBadge(selectedTodo.urgency).cls}">
							{urgencyBadge(selectedTodo.urgency).label}
						</span>
						<span class="inline-flex rounded-full px-2.5 py-0.5 text-xs font-medium {sourceBadgeClass(selectedTodo.source)}">
							{sourceLabel(selectedTodo.source)}
						</span>
					</div>
					<p class="text-sm text-text">{selectedTodo.description}</p>
				</div>

				{#if errorMessage}
					<div class="rounded-lg bg-danger/10 border border-danger/20 px-4 py-3 text-sm text-danger">
						{errorMessage}
					</div>
				{/if}

				<div>
					<label class="mb-1.5 block text-sm font-medium text-text">状态</label>
					<select
						bind:value={formStatus}
						class="w-full rounded-lg border border-gray-200 bg-white px-4 py-2.5 text-sm outline-none focus:border-primary focus:ring-1 focus:ring-primary/30 transition-colors"
					>
						<option value="in_progress">处理中</option>
						<option value="completed">已完成</option>
					</select>
				</div>

				<div>
					<label class="mb-1.5 block text-sm font-medium text-text">处理结果</label>
					<textarea
						bind:value={formResult}
						rows={3}
						class="w-full rounded-lg border border-gray-200 bg-white px-4 py-2.5 text-sm outline-none focus:border-primary focus:ring-1 focus:ring-primary/30 transition-colors resize-none"
						placeholder="输入处理结果..."
					></textarea>
				</div>

				<div>
					<label class="mb-1.5 block text-sm font-medium text-text">处理依据 {#if formStatus === 'completed'}<span class="text-danger">*</span>{/if}</label>
					<textarea
						bind:value={formEvidence}
						rows={3}
						class="w-full rounded-lg border border-gray-200 bg-white px-4 py-2.5 text-sm outline-none focus:border-primary focus:ring-1 focus:ring-primary/30 transition-colors resize-none"
						placeholder="输入处理依据..."
					></textarea>
				</div>

				<div>
					<label class="mb-1.5 block text-sm font-medium text-text">操作人</label>
					<div class="flex gap-3">
						<input
							type="text"
							value="admin"
							disabled
							class="flex-1 rounded-lg border border-gray-200 bg-surface px-4 py-2.5 text-sm text-text-muted cursor-not-allowed"
						/>
						<input
							type="text"
							value="管理员"
							disabled
							class="flex-1 rounded-lg border border-gray-200 bg-surface px-4 py-2.5 text-sm text-text-muted cursor-not-allowed"
						/>
					</div>
				</div>
			</div>

			<div class="border-t border-gray-200 px-6 py-4">
				<button
					type="button"
					onclick={submitProcess}
					disabled={submitLoading}
					class="w-full rounded-lg bg-primary py-2.5 text-sm font-medium text-white transition-colors hover:bg-primary-light disabled:opacity-50 disabled:cursor-not-allowed"
				>
					{submitLoading ? '提交中...' : '提交处理'}
				</button>
			</div>
		</div>
	</div>
{/if}

// beiqiao-inn/pages/admin/todos/index.vue
<script setup lang="ts">
definePageMeta({ layout: 'admin' })

const todos = ref<any[]>([])
const reminders = ref<any[]>([])
const loading = ref(false)
const activePriority = ref('ALL')
const activeStatus = ref('PENDING')
const successMessage = ref('')
const showSuccess = ref(false)
const vacancyUpdated = ref(false)

const priorityTabs = [
  { label: '全部', value: 'ALL' },
  { label: 'P0紧急', value: 'P0', badge: 'badge-p0' },
  { label: 'P1重要', value: 'P1', badge: 'badge-p1' },
  { label: 'P2一般', value: 'P2', badge: 'badge-p2' },
]

const statusTabs = [
  { label: '待处理', value: 'PENDING' },
  { label: '处理中', value: 'IN_PROGRESS' },
  { label: '已办结', value: 'COMPLETED' },
]

const typeLabel: Record<string, string> = {
  REFUND_APPROVAL: '退款审批',
  CLEANING: '清洁任务',
  REVIEW_REPLY: '评价回复',
}

const typeBadgeClass: Record<string, string> = {
  REFUND_APPROVAL: 'bg-brick/10 text-brick',
  CLEANING: 'bg-info/10 text-info',
  REVIEW_REPLY: 'bg-amber/15 text-amber',
}

const priorityBarClass: Record<string, string> = {
  P0: 'priority-bar-p0',
  P1: 'priority-bar-p1',
  P2: 'priority-bar-p2',
}

const statusLabel: Record<string, string> = {
  PENDING: '待处理',
  IN_PROGRESS: '处理中',
  COMPLETED: '已办结',
}

async function loadTodos() {
  loading.value = true
  try {
    const query: Record<string, string> = {}
    if (activePriority.value !== 'ALL') query.priority = activePriority.value
    if (activeStatus.value) query.status = activeStatus.value
    todos.value = await $fetch('/api/todos', { query })
  } finally {
    loading.value = false
  }
}

async function loadReminders() {
  try {
    reminders.value = await $fetch('/api/reminders', { query: { isRead: 'false' } })
  } catch {}
}

async function handleStart(id: number) {
  try {
    await $fetch(`/api/todos/${id}/start`, { method: 'PUT' })
    await loadTodos()
  } catch (e: any) {
    console.error('Failed to start todo:', e)
  }
}

async function handleComplete(id: number) {
  try {
    const result: any = await $fetch(`/api/todos/${id}/complete`, { method: 'PUT' })
    await loadTodos()
    await loadReminders()

    if (result.vacancyUpdated) {
      successMessage.value = '待办已办结，空置率已更新'
      vacancyUpdated.value = true
    } else {
      successMessage.value = '待办已办结'
      vacancyUpdated.value = false
    }
    showSuccess.value = true
    setTimeout(() => {
      showSuccess.value = false
    }, 3000)
  } catch (e: any) {
    console.error('Failed to complete todo:', e)
  }
}

async function markReminderRead(id: number) {
  try {
    await $fetch(`/api/reminders/${id}/read`, { method: 'PUT' })
    await loadReminders()
  } catch (e: any) {
    console.error('Failed to mark reminder read:', e)
  }
}

function formatDate(dateStr: string | null) {
  if (!dateStr) return '-'
  return new Date(dateStr).toLocaleDateString('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' })
}

function isOverdue(dueAt: string | null) {
  if (!dueAt) return false
  return new Date(dueAt) < new Date()
}

onMounted(() => {
  loadTodos()
  loadReminders()
})

watch([activePriority, activeStatus], () => {
  loadTodos()
})
</script>

<template>
  <div>
    <div class="flex items-center justify-between mb-6">
      <h1 class="font-serif text-2xl font-bold text-pine">待办中心</h1>
      <button
        @click="loadTodos(); loadReminders()"
        class="btn-secondary text-sm py-1.5 px-3 flex items-center gap-1.5"
      >
        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 0115.357-2m-2H4v.582z" />
        </svg>
        刷新
      </button>
    </div>

    <Teleport to="body">
      <Transition name="fade">
        <div
          v-if="showSuccess"
          class="fixed top-4 right-4 z-50 bg-pine text-cream px-5 py-3 rounded-lg shadow-lg flex items-center gap-2"
        >
          <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
          </svg>
          <span>{{ successMessage }}</span>
          <span v-if="vacancyUpdated" class="text-amber text-xs ml-1">(空置率 ↓)</span>
        </div>
      </Transition>
    </Teleport>

    <section v-if="reminders.length > 0" class="mb-6">
      <div class="bg-brick/5 border border-brick/20 rounded-xl p-4">
        <div class="flex items-center gap-2 mb-3">
          <svg class="w-5 h-5 text-brick" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
          </svg>
          <span class="font-serif font-semibold text-brick">未读提醒 ({{ reminders.length }})</span>
        </div>
        <div class="space-y-2">
          <div
            v-for="reminder in reminders"
            :key="reminder.id"
            class="flex items-center justify-between bg-white rounded-lg px-4 py-2.5 border border-cream-dark/50 transition-all hover:shadow-sm"
          >
            <div class="flex items-center gap-3 min-w-0">
              <span
                class="px-2 py-0.5 rounded-full text-xs font-semibold flex-shrink-0"
                :class="reminder.priority === 'P0' ? 'badge-p0' : reminder.priority === 'P1' ? 'badge-p1' : 'badge-p2'"
              >
                {{ reminder.priority }}
              </span>
              <span class="text-sm text-pine truncate">{{ reminder.title }}</span>
            </div>
            <button
              class="text-xs text-brick hover:text-brick-light font-medium flex-shrink-0 ml-3 transition-colors"
              @click="markReminderRead(reminder.id)"
            >
              标记已读
            </button>
          </div>
        </div>
      </div>
    </section>

    <section class="mb-4">
      <div class="flex gap-2 overflow-x-auto pb-2">
        <button
          v-for="tab in priorityTabs"
          :key="tab.value"
          class="px-4 py-2 rounded-full text-sm font-medium whitespace-nowrap transition-all duration-200 flex items-center gap-1.5"
          :class="activePriority === tab.value
            ? 'bg-pine text-cream shadow-md'
            : 'bg-white text-pine border border-cream-dark hover:bg-cream-dark'"
          @click="activePriority = tab.value"
        >
          {{ tab.label }}
          <span v-if="tab.badge" class="w-2 h-2 rounded-full" :class="tab.value === 'P0' ? 'bg-brick' : tab.value === 'P1' ? 'bg-amber' : 'bg-info'" />
        </button>
      </div>
    </section>

    <section class="mb-6">
      <div class="flex gap-2">
        <button
          v-for="tab in statusTabs"
          :key="tab.value"
          class="px-3 py-1.5 rounded-lg text-xs font-medium transition-all duration-200"
          :class="activeStatus === tab.value
            ? 'bg-pine-light text-cream'
            : 'bg-cream-dark text-pine/70 hover:text-pine'"
          @click="activeStatus = tab.value"
        >
          {{ tab.label }}
        </button>
      </div>
    </section>

    <section>
      <div v-if="loading" class="text-center py-16 text-slate">
        <div class="inline-block w-8 h-8 border-2 border-pine/20 border-t-pine rounded-full animate-spin mb-3" />
        <p>加载中...</p>
      </div>

      <div v-else-if="todos.length === 0" class="text-center py-20">
        <div class="w-20 h-20 rounded-full bg-cream-dark mx-auto flex items-center justify-center mb-4">
          <svg class="w-10 h-10 text-slate/30" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
          </svg>
        </div>
        <p class="text-slate text-lg mb-1">暂无待办</p>
        <p class="text-slate/60 text-sm">当前筛选条件下没有待办事项</p>
      </div>

      <div v-else class="space-y-3">
        <div
          v-for="todo in todos"
          :key="todo.id"
          class="card transition-all duration-300"
          :class="[
            priorityBarClass[todo.priority],
            todo.status === 'COMPLETED' ? 'opacity-60' : '',
          ]"
        >
          <div class="flex items-start justify-between mb-2">
            <div class="flex items-center gap-2 flex-wrap">
              <span
                class="px-2.5 py-0.5 rounded-full text-xs font-semibold"
                :class="typeBadgeClass[todo.type]"
              >
                {{ typeLabel[todo.type] || todo.type }}
              </span>
              <span
                class="px-2 py-0.5 rounded-full text-xs font-semibold"
                :class="todo.priority === 'P0' ? 'badge-p0' : todo.priority === 'P1' ? 'badge-p1' : 'badge-p2'"
              >
                {{ todo.priority }}
              </span>
              <span
                class="px-2 py-0.5 rounded-full text-xs font-medium"
                :class="todo.status === 'COMPLETED' ? 'bg-pine/10 text-pine' : todo.status === 'IN_PROGRESS' ? 'bg-amber/15 text-amber' : 'bg-slate/10 text-slate'"
              >
                {{ statusLabel[todo.status] }}
              </span>
            </div>
            <span
              v-if="todo.dueAt && isOverdue(todo.dueAt) && todo.status !== 'COMPLETED'"
              class="text-xs text-brick font-medium flex-shrink-0 ml-2"
            >
              已逾期
            </span>
          </div>

          <h3 class="font-serif text-base font-semibold text-pine mb-1" :class="{ 'line-through': todo.status === 'COMPLETED' }">
            {{ todo.title }}
          </h3>
          <p v-if="todo.description" class="text-sm text-pine/60 mb-3 line-clamp-2">
            {{ todo.description }}
          </p>

          <div class="flex items-center justify-between pt-3 border-t border-cream-dark/50">
            <div class="flex items-center gap-4 text-xs text-pine/60">
              <span class="flex items-center gap-1">
                <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                </svg>
                {{ todo.assignee?.name || '未分配' }}
              </span>
              <span v-if="todo.dueAt" class="flex items-center gap-1">
                <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                </svg>
                {{ formatDate(todo.dueAt) }}
              </span>
              <span v-if="todo.completedAt" class="flex items-center gap-1 text-pine/70">
                <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                </svg>
                {{ formatDate(todo.completedAt) }} 办结
              </span>
            </div>

            <div class="flex gap-2">
              <button
                v-if="todo.status === 'PENDING'"
                class="btn-primary text-xs px-3 py-1.5"
                @click="handleStart(todo.id)"
              >
                开始处理
              </button>
              <button
                v-if="todo.status === 'IN_PROGRESS'"
                class="btn-secondary text-xs px-3 py-1.5"
                @click="handleComplete(todo.id)"
              >
                办结
              </button>
              <span
                v-if="todo.status === 'COMPLETED'"
                class="text-xs text-pine/50 font-medium"
              >
                已完成
              </span>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.3s ease, transform 0.3s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
  transform: translateY(-10px);
}
</style>
