// apps/web/app/routes/audit.tsx
import { useEffect, useState } from 'react';
import { useNavigate } from '@remix-run/react';
import { useAuth } from '~/contexts/AuthContext';
import { api } from '~/lib/api';
import Layout from '~/components/Layout';

export default function Audit() {
  const { token, isAuthenticated, user } = useAuth();
  const navigate = useNavigate();
  const [logs, setLogs] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [filterEntityType, setFilterEntityType] = useState('');

  useEffect(() => {
    if (!isAuthenticated) {
      navigate('/login');
      return;
    }
    loadLogs();
  }, [token, isAuthenticated, navigate, filterEntityType]);

  const loadLogs = async () => {
    if (!token) return;
    setLoading(true);
    try {
      const params: any = {};
      if (filterEntityType) params.entityType = filterEntityType;
      const data: any = await api.audit.logs(token, params);
      setLogs(Array.isArray(data) ? data : []);
    } catch (error) {
      console.error('加载审计日志失败:', error);
    } finally {
      setLoading(false);
    }
  };

  const actionText: Record<string, string> = {
    login: '登录',
    logout: '登出',
    create_material: '创建物资',
    update_material: '更新物资',
    create_category: '创建分类',
    create_activity: '创建活动',
    update_activity: '更新活动',
    update_activity_status: '更新活动状态',
    create_application: '创建申请',
    approve_application: '批准申请',
    reject_application: '拒绝申请',
    cancel_application: '取消申请',
    borrow_material: '借出物资',
    return_material: '归还物资',
    create_compensation: '创建赔付单',
    handle_compensation_paid: '确认赔付收款',
    handle_compensation_waived: '豁免赔付',
    manual_entry_borrow: '借用补录',
    manual_entry_return: '归还补录',
    manual_entry_material: '物资补录',
    manual_entry_compensation: '赔付补录',
  };

  const entityTypeText: Record<string, string> = {
    user: '用户',
    material: '物资',
    material_category: '物资分类',
    activity: '活动',
    borrow_application: '借用申请',
    borrow_item: '借用明细',
    compensation_order: '赔付单',
    manual_entry: '人工补录',
  };

  if (!isAuthenticated || (user?.role !== 'warehouse_manager' && user?.role !== 'admin')) {
    return null;
  }

  return (
    <Layout>
      <div>
        <div className="flex justify-between items-center mb-6">
          <h1 className="text-2xl font-bold text-gray-800">审计日志</h1>
          <select
            value={filterEntityType}
            onChange={(e) => setFilterEntityType(e.target.value)}
            className="px-3 py-2 border rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-primary-500 outline-none"
          >
            <option value="">全部类型</option>
            <option value="user">用户</option>
            <option value="material">物资</option>
            <option value="activity">活动</option>
            <option value="borrow_application">借用申请</option>
            <option value="compensation_order">赔付单</option>
          </select>
        </div>

        <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
          {loading ? (
            <div className="p-8 text-center text-gray-500">加载中...</div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">时间</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">操作人</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">操作</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">对象类型</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">IP地址</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {logs.length === 0 ? (
                    <tr>
                      <td colSpan={5} className="px-6 py-8 text-center text-gray-500">
                        暂无审计日志
                      </td>
                    </tr>
                  ) : (
                    logs.map((log: any) => (
                      <tr key={log.id} className="hover:bg-gray-50">
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                          {new Date(log.created_at).toLocaleString()}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                          {log.real_name || log.username || '系统'}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <span className="px-2 py-1 text-xs rounded-full bg-primary-100 text-primary-800">
                            {actionText[log.action] || log.action}
                          </span>
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                          {entityTypeText[log.entity_type] || log.entity_type}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 font-mono">
                          {log.ip_address || '-'}
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>
    </Layout>
  );
}

// frontend/src/routes/audit/index.tsx
import { component$, useStore, useTask$, $ } from "@builder.io/qwik";
import { useNavigate } from "@builder.io/qwik-city";
import Layout from "~/components/layout";
import apiClient from "~/utils/api";
import { useAuth } from "~/context/auth";
import dayjs from "dayjs";

interface AuditLog {
  id: string;
  user_id: string;
  user_name: string;
  action: string;
  module: string;
  target_type: string;
  target_id: string;
  description: string;
  ip_address: string;
  user_agent: string;
  created_at: string;
}

const actionLabels: Record<string, string> = {
  create: '创建',
  create_waitlisted: '创建（候补）',
  cancel: '取消',
  rain_cancel: '雨天取消',
  confirm: '确认',
  resubmit: '重新提交',
  breakdown_reschedule: '故障重排',
  login: '登录',
  logout: '登出',
};

const moduleLabels: Record<string, string> = {
  reservation: '预约',
  auth: '认证',
  equipment: '设备',
  maintenance: '维修',
  settlement: '结算',
};

export default component$(() => {
  const auth = useAuth();
  const nav = useNavigate();
  
  const state = useStore({
    logs: [] as AuditLog[],
    loading: true,
  });

  useTask$(async () => {
    if (!auth.isAuthenticated) {
      nav.navigate('/login');
      return;
    }
    
    if (auth.user?.role !== 'admin') {
      nav.navigate('/dashboard');
      return;
    }
    
    try {
      const response = await apiClient.get('/audit-logs');
      state.logs = response.data;
    } catch (e) {
      console.error('加载审计日志失败', e);
    } finally {
      state.loading = false;
    }
  });

  return (
    <Layout title="审计日志">
      {state.loading ? (
        <div class="card text-center text-gray-500">加载中...</div>
      ) : state.logs.length === 0 ? (
        <div class="card text-center py-12">
          <div class="text-4xl mb-4">📋</div>
          <p class="text-gray-500">暂无审计日志</p>
        </div>
      ) : (
        <div class="card overflow-x-auto">
          <table class="w-full">
            <thead>
              <tr class="border-b border-gray-100">
                <th class="text-left py-3 px-4 text-sm font-medium text-gray-500">时间</th>
                <th class="text-left py-3 px-4 text-sm font-medium text-gray-500">用户</th>
                <th class="text-left py-3 px-4 text-sm font-medium text-gray-500">模块</th>
                <th class="text-left py-3 px-4 text-sm font-medium text-gray-500">操作</th>
                <th class="text-left py-3 px-4 text-sm font-medium text-gray-500">描述</th>
                <th class="text-left py-3 px-4 text-sm font-medium text-gray-500">IP</th>
              </tr>
            </thead>
            <tbody>
              {state.logs.map((log) => (
                <tr key={log.id} class="border-b border-gray-50 hover:bg-gray-50">
                  <td class="py-3 px-4 text-sm text-gray-500 whitespace-nowrap">
                    {dayjs(log.created_at).format('MM-DD HH:mm:ss')}
                  </td>
                  <td class="py-3 px-4 text-sm text-gray-800">{log.user_name}</td>
                  <td class="py-3 px-4">
                    <span class="badge bg-gray-100 text-gray-600">
                      {moduleLabels[log.module] || log.module}
                    </span>
                  </td>
                  <td class="py-3 px-4 text-sm text-gray-600">
                    {actionLabels[log.action] || log.action}
                  </td>
                  <td class="py-3 px-4 text-sm text-gray-600 max-w-xs truncate">
                    {log.description}
                  </td>
                  <td class="py-3 px-4 text-sm text-gray-400">{log.ip_address}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </Layout>
  );
});
