// app/components/ExportButton.tsx
import { useState } from "react";
import type { Filters } from "~/types";

interface ExportButtonProps {
  filters: Filters;
}

export function ExportButton({ filters }: ExportButtonProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<{ success: boolean; files?: string[] } | null>(null);

  const handleExport = async (type: string, format: string) => {
    setLoading(true);
    try {
      const res = await fetch("/api/export", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ type, format, filters }),
      });
      const data = await res.json();
      setResult(data);
      setTimeout(() => setResult(null), 5000);
    } catch (err) {
      setResult({ success: false });
    } finally {
      setLoading(false);
      setIsOpen(false);
    }
  };

  return (
    <div className="relative">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="inline-flex items-center gap-2 px-4 py-2 bg-primary-600 text-white text-sm font-medium rounded-md hover:bg-primary-700 transition-colors"
      >
        <span>📥</span>
        导出数据
      </button>

      {result && (
        <div
          className={`absolute right-0 top-full mt-2 px-3 py-2 rounded-md text-sm z-50 ${
            result.success
              ? "bg-green-50 text-green-800 border border-green-200"
              : "bg-red-50 text-red-800 border border-red-200"
          }`}
        >
          {result.success ? "导出成功！" : "导出失败"}
        </div>
      )}

      {isOpen && (
        <div className="absolute right-0 top-full mt-2 bg-white border border-gray-200 rounded-md shadow-lg z-50 min-w-48">
          <div className="p-2 border-b border-gray-100">
            <p className="text-xs text-gray-500 px-2 py-1">选择导出类型</p>
            {loading && <p className="text-xs text-gray-400 px-2 py-1">导出中...</p>}
          </div>
          <div className="p-2 space-y-1">
            {[
              { type: "full", label: "完整数据" },
              { type: "funnel", label: "漏斗数据" },
              { type: "quiz", label: "测验数据" },
              { type: "department", label: "部门对比" },
              { type: "certificate", label: "证书数据" },
            ].map(item => (
              <div key={item.type} className="flex items-center justify-between px-2 py-1.5 hover:bg-gray-50 rounded">
                <span className="text-sm text-gray-700">{item.label}</span>
                <div className="flex gap-1">
                  <button
                    onClick={() => handleExport(item.type, "csv")}
                    className="text-xs px-2 py-0.5 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded"
                  >
                    CSV
                  </button>
                  <button
                    onClick={() => handleExport(item.type, "json")}
                    className="text-xs px-2 py-0.5 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded"
                  >
                    JSON
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// src/components/common/ExportButton.vue
<script setup lang="ts">
import { ref } from 'vue';
import { Download, ChevronDown, FileSpreadsheet, FileJson } from 'lucide-vue-next';
import { exportToCSV, exportToJSON } from '@/utils/export';

const props = defineProps<{
  data: any[];
  filename: string;
}>();

const showMenu = ref(false);

function handleExport(format: 'csv' | 'json') {
  if (format === 'csv') {
    exportToCSV(props.data, props.filename);
  } else {
    exportToJSON(props.data, props.filename);
  }
  showMenu.value = false;
}
</script>

<template>
  <div class="relative">
    <button 
      class="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors text-sm font-medium"
      @click="showMenu = !showMenu"
    >
      <Download class="w-4 h-4" />
      导出
      <ChevronDown class="w-4 h-4" :class="{ 'rotate-180': showMenu }" />
    </button>
    
    <div 
      v-if="showMenu"
      class="absolute right-0 top-full mt-1 bg-white border border-slate-200 rounded-lg shadow-xl overflow-hidden z-50 min-w-[140px]"
    >
      <button 
        class="w-full flex items-center gap-2 px-4 py-2.5 text-sm text-slate-700 hover:bg-slate-50 transition-colors text-left"
        @click="handleExport('csv')"
      >
        <FileSpreadsheet class="w-4 h-4 text-green-600" />
        导出 CSV
      </button>
      <button 
        class="w-full flex items-center gap-2 px-4 py-2.5 text-sm text-slate-700 hover:bg-slate-50 transition-colors text-left"
        @click="handleExport('json')"
      >
        <FileJson class="w-4 h-4 text-blue-600" />
        导出 JSON
      </button>
    </div>
  </div>
</template>
