// src/components/ui/KPICard.tsx
"use client";

import { cn, formatMinutes, formatNumber } from "@/utils";
import { ArrowUp, ArrowDown, Minus } from "lucide-react";

interface KPICardProps {
  title: string;
  value: number | string;
  unit?: string;
  trend?: number;
  icon?: React.ReactNode;
  color?: "primary" | "success" | "warning" | "danger";
  isTime?: boolean;
}

export function KPICard({
  title,
  value,
  unit,
  trend,
  icon,
  color = "primary",
  isTime = false,
}: KPICardProps) {
  const colorClasses = {
    primary: "bg-primary-50 text-primary-600",
    success: "bg-success-50 text-success-600",
    warning: "bg-warning-50 text-warning-600",
    danger: "bg-danger-50 text-danger-600",
  };

  const displayValue = isTime && typeof value === "number"
    ? formatMinutes(value)
    : formatNumber(value as number);

  return (
    <div className="bg-white rounded-lg shadow-card p-4 hover:shadow-card-hover transition-shadow">
      <div className="flex items-start justify-between">
        <div>
          <p className="text-sm text-neutral-500 mb-1">{title}</p>
          <p className="text-2xl font-bold text-neutral-800 font-mono">
            {displayValue}
            {unit && <span className="text-sm font-normal text-neutral-500 ml-1">{unit}</span>}
          </p>
        </div>
        {icon && (
          <div className={cn("p-2.5 rounded-lg", colorClasses[color])}>
            {icon}
          </div>
        )}
      </div>
      {trend !== undefined && (
        <div className="mt-3 flex items-center gap-1">
          {trend > 0 ? (
            <ArrowUp className="w-3.5 h-3.5 text-danger-500" />
          ) : trend < 0 ? (
            <ArrowDown className="w-3.5 h-3.5 text-success-500" />
          ) : (
            <Minus className="w-3.5 h-3.5 text-neutral-400" />
          )}
          <span
            className={cn(
              "text-xs font-medium",
              trend > 0
                ? "text-danger-500"
                : trend < 0
                ? "text-success-500"
                : "text-neutral-400"
            )}
          >
            {Math.abs(trend)}分钟
          </span>
          <span className="text-xs text-neutral-400">较上一周期</span>
        </div>
      )}
    </div>
  );
}

// src/components/common/KpiCard.vue
<script setup lang="ts">
import { computed, type Component } from 'vue'
import { TrendingUp, TrendingDown, Minus } from 'lucide-vue-next'

const props = defineProps<{
  title: string
  value: string | number
  unit?: string
  trend?: 'up' | 'down' | 'flat'
  trendValue?: string
  icon?: Component
  color?: 'primary' | 'success' | 'warning' | 'danger' | 'secondary'
  isPercentage?: boolean
}>()

const colorClasses = computed(() => {
  const colorMap: Record<string, string> = {
    primary: 'text-survey-primary',
    success: 'text-survey-success',
    warning: 'text-survey-warning',
    danger: 'text-survey-danger',
    secondary: 'text-survey-secondary',
  }
  return colorMap[props.color || 'primary']
})

const trendIcon = computed(() => {
  if (props.trend === 'up') return TrendingUp
  if (props.trend === 'down') return TrendingDown
  return Minus
})

const trendColorClass = computed(() => {
  if (props.trend === 'up') return 'text-survey-success'
  if (props.trend === 'down') return 'text-survey-danger'
  return 'text-survey-text-muted'
})
</script>

<template>
  <div class="bg-survey-surface border border-survey-border rounded-lg p-5 card-hover">
    <div class="flex items-start justify-between">
      <div>
        <p class="text-sm text-survey-text-muted mb-2">{{ title }}</p>
        <div class="flex items-baseline gap-1">
          <span class="font-mono text-3xl font-bold" :class="colorClasses">{{ value }}</span>
          <span v-if="unit" class="text-sm text-survey-text-muted">{{ unit }}</span>
        </div>
      </div>
      <div v-if="icon" class="w-10 h-10 rounded-lg bg-survey-bg flex items-center justify-center" :class="colorClasses">
        <component :is="icon" class="w-5 h-5" />
      </div>
    </div>
    <div v-if="trendValue" class="mt-3 flex items-center gap-1">
      <component :is="trendIcon" class="w-4 h-4" :class="trendColorClass" />
      <span class="text-xs" :class="trendColorClass">{{ trendValue }}</span>
      <span class="text-xs text-survey-text-muted ml-1">较上周</span>
    </div>
  </div>
</template>
