// src/components/common/KpiCard.vue
<script setup lang="ts">
import { computed, type Component } from 'vue'
import { TrendingUp, TrendingDown, Minus } from 'lucide-vue-next'

const props = defineProps<{
  title: string
  value: string | number
  unit?: string
  trend?: 'up' | 'down' | 'flat'
  trendValue?: string
  icon?: Component
  color?: 'primary' | 'success' | 'warning' | 'danger' | 'secondary'
  isPercentage?: boolean
}>()

const colorClasses = computed(() => {
  const colorMap: Record<string, string> = {
    primary: 'text-survey-primary',
    success: 'text-survey-success',
    warning: 'text-survey-warning',
    danger: 'text-survey-danger',
    secondary: 'text-survey-secondary',
  }
  return colorMap[props.color || 'primary']
})

const trendIcon = computed(() => {
  if (props.trend === 'up') return TrendingUp
  if (props.trend === 'down') return TrendingDown
  return Minus
})

const trendColorClass = computed(() => {
  if (props.trend === 'up') return 'text-survey-success'
  if (props.trend === 'down') return 'text-survey-danger'
  return 'text-survey-text-muted'
})
</script>

<template>
  <div class="bg-survey-surface border border-survey-border rounded-lg p-5 card-hover">
    <div class="flex items-start justify-between">
      <div>
        <p class="text-sm text-survey-text-muted mb-2">{{ title }}</p>
        <div class="flex items-baseline gap-1">
          <span class="font-mono text-3xl font-bold" :class="colorClasses">{{ value }}</span>
          <span v-if="unit" class="text-sm text-survey-text-muted">{{ unit }}</span>
        </div>
      </div>
      <div v-if="icon" class="w-10 h-10 rounded-lg bg-survey-bg flex items-center justify-center" :class="colorClasses">
        <component :is="icon" class="w-5 h-5" />
      </div>
    </div>
    <div v-if="trendValue" class="mt-3 flex items-center gap-1">
      <component :is="trendIcon" class="w-4 h-4" :class="trendColorClass" />
      <span class="text-xs" :class="trendColorClass">{{ trendValue }}</span>
      <span class="text-xs text-survey-text-muted ml-1">较上周</span>
    </div>
  </div>
</template>

// src/components/common/KPICard.tsx
'use client';

import { TrendingUp, TrendingDown, Minus } from 'lucide-react';
import { cn } from '@/utils/formatters';

interface KPICardProps {
  title: string;
  value: string | number;
  unit?: string;
  trend?: number;
  trendLabel?: string;
  icon?: React.ReactNode;
  color?: 'blue' | 'orange' | 'green' | 'red';
  warning?: boolean;
  onClick?: () => void;
}

const colorMap = {
  blue: 'from-blue-500 to-blue-600',
  orange: 'from-orange-500 to-orange-600',
  green: 'from-green-500 to-green-600',
  red: 'from-red-500 to-red-600',
};

export default function KPICard({
  title,
  value,
  unit,
  trend,
  trendLabel,
  icon,
  color = 'blue',
  warning = false,
  onClick,
}: KPICardProps) {
  const TrendIcon = trend && trend > 0 ? TrendingUp : trend && trend < 0 ? TrendingDown : Minus;
  const trendColor = trend && trend > 0 ? 'text-red-500' : trend && trend < 0 ? 'text-green-500' : 'text-gray-500';

  return (
    <div
      className={cn(
        'bg-white rounded-xl p-5 shadow-card hover:shadow-card-hover transition-all cursor-pointer',
        warning && 'ring-2 ring-warning-400 ring-offset-2'
      )}
      onClick={onClick}
    >
      <div className="flex items-start justify-between">
        <div>
          <p className="text-sm text-gray-500 mb-1">{title}</p>
          <div className="flex items-baseline gap-1">
            <span className="text-2xl font-bold text-gray-900 font-mono">{value}</span>
            {unit && <span className="text-sm text-gray-500">{unit}</span>}
          </div>
        </div>
        {icon && (
          <div
            className={cn(
              'w-10 h-10 rounded-lg flex items-center justify-center bg-gradient-to-br text-white',
              colorMap[color]
            )}
          >
            {icon}
          </div>
        )}
      </div>
      {trend !== undefined && (
        <div className="mt-3 flex items-center gap-1">
          <TrendIcon className={cn('w-4 h-4', trendColor)} />
          <span className={cn('text-sm', trendColor)}>
            {Math.abs(trend).toFixed(1)}%
          </span>
          <span className="text-xs text-gray-400 ml-1">{trendLabel || '较上周'}</span>
        </div>
      )}
    </div>
  );
}
