// src/lib/components/MetricCard.svelte
<script lang="ts">
	import { TrendingUp, TrendingDown, Minus } from 'lucide-svelte';

	let { label, value, unit = '', trend, trendValue, color = '#1B4332' }: {
		label: string;
		value: number | string;
		unit?: string;
		trend?: 'up' | 'down' | 'flat';
		trendValue?: number;
		color?: string;
	} = $props();

	const trendColor = $derived(
		trend === 'up' ? 'text-red-500' : trend === 'down' ? 'text-green-500' : 'text-gray-400'
	);
</script>

<div class="bg-white rounded-lg p-4 border border-gray-100 shadow-sm hover:shadow-md transition-shadow">
	<div class="text-xs text-gray-500 mb-1">{label}</div>
	<div class="flex items-end gap-2">
		<span class="text-2xl font-bold" style="color: {color}">{value}</span>
		{#if unit}
			<span class="text-xs text-gray-400 mb-1">{unit}</span>
		{/if}
	</div>
	{#if trend && trendValue !== undefined}
		<div class="flex items-center gap-1 mt-1 {trendColor}">
			{#if trend === 'up'}
				<TrendingUp size={12} />
			{:else if trend === 'down'}
				<TrendingDown size={12} />
			{:else}
				<Minus size={12} />
			{/if}
			<span class="text-[10px]">{trendValue}%</span>
		</div>
	{/if}
</div>

// src/components/common/MetricCard.vue
<script setup lang="ts">
import { computed } from 'vue'
import { TrendingUp, TrendingDown } from 'lucide-vue-next'
import SampleSizeBadge from './SampleSizeBadge.vue'
import { obfuscateLowSampleValue } from '@/utils/privacy'

const props = defineProps<{
  name: string
  value: number
  unit: string
  trend: number
  sampleSize: number
  lowSample: boolean
}>()

const displayValue = computed(() => {
  if (props.lowSample) {
    return '样本不足'
  }
  return obfuscateLowSampleValue(props.value, props.sampleSize, 10, props.unit)
})

const trendPositive = computed(() => props.trend >= 0)
</script>

<template>
  <div class="bg-white rounded-lg shadow-sm border border-gray-100 p-5 hover:shadow-md transition-shadow">
    <div class="flex items-start justify-between mb-3">
      <h3 class="text-sm font-medium text-gray-600">{{ name }}</h3>
      <SampleSizeBadge :sample-size="sampleSize" />
    </div>
    <div class="flex items-end justify-between">
      <div>
        <p class="text-2xl font-bold text-gray-900" :class="{ 'text-gray-400': lowSample }">
          {{ displayValue }}
        </p>
      </div>
      <div
        class="flex items-center gap-1 text-sm font-medium"
        :class="trendPositive ? 'text-green-600' : 'text-red-600'"
      >
        <TrendingUp v-if="trendPositive" class="w-4 h-4" />
        <TrendingDown v-else class="w-4 h-4" />
        <span>{{ Math.abs(trend) }}%</span>
      </div>
    </div>
  </div>
</template>
