// src/components/common/MetricCard.vue
<script setup lang="ts">
import { computed } from 'vue'
import { TrendingUp, TrendingDown } from 'lucide-vue-next'
import SampleSizeBadge from './SampleSizeBadge.vue'
import { obfuscateLowSampleValue } from '@/utils/privacy'

const props = defineProps<{
  name: string
  value: number
  unit: string
  trend: number
  sampleSize: number
  lowSample: boolean
}>()

const displayValue = computed(() => {
  if (props.lowSample) {
    return '样本不足'
  }
  return obfuscateLowSampleValue(props.value, props.sampleSize, 10, props.unit)
})

const trendPositive = computed(() => props.trend >= 0)
</script>

<template>
  <div class="bg-white rounded-lg shadow-sm border border-gray-100 p-5 hover:shadow-md transition-shadow">
    <div class="flex items-start justify-between mb-3">
      <h3 class="text-sm font-medium text-gray-600">{{ name }}</h3>
      <SampleSizeBadge :sample-size="sampleSize" />
    </div>
    <div class="flex items-end justify-between">
      <div>
        <p class="text-2xl font-bold text-gray-900" :class="{ 'text-gray-400': lowSample }">
          {{ displayValue }}
        </p>
      </div>
      <div
        class="flex items-center gap-1 text-sm font-medium"
        :class="trendPositive ? 'text-green-600' : 'text-red-600'"
      >
        <TrendingUp v-if="trendPositive" class="w-4 h-4" />
        <TrendingDown v-else class="w-4 h-4" />
        <span>{{ Math.abs(trend) }}%</span>
      </div>
    </div>
  </div>
</template>

// src/components/common/MetricCard.tsx
"use client";

import { TrendingUp, TrendingDown } from "lucide-react";
import { cn } from "@/lib/utils";

interface MetricCardProps {
  title: string;
  value: string | number;
  unit?: string;
  trend?: number;
  trendLabel?: string;
  icon?: React.ReactNode;
  color?: "primary" | "success" | "warning" | "danger";
  className?: string;
}

const colorConfig = {
  primary: {
    bg: "from-primary-50 to-primary-100/50",
    border: "border-primary-100",
    icon: "bg-primary-500 text-white",
  },
  success: {
    bg: "from-success-50 to-success-100/50",
    border: "border-success-100",
    icon: "bg-success-500 text-white",
  },
  warning: {
    bg: "from-warning-50 to-warning-100/50",
    border: "border-warning-100",
    icon: "bg-warning-500 text-white",
  },
  danger: {
    bg: "from-danger-50 to-danger-100/50",
    border: "border-danger-100",
    icon: "bg-danger-500 text-white",
  },
};

export function MetricCard({
  title,
  value,
  unit,
  trend,
  trendLabel,
  icon,
  color = "primary",
  className,
}: MetricCardProps) {
  const colors = colorConfig[color];
  const isPositive = trend && trend >= 0;

  return (
    <div
      className={cn(
        "rounded-2xl p-5 bg-gradient-to-br border transition-all duration-300 hover:shadow-card-hover",
        colors.bg,
        colors.border,
        className
      )}
    >
      <div className="flex items-start justify-between mb-4">
        <div className="p-2.5 rounded-xl bg-white shadow-sm">
          {icon || (
            <div className={cn("w-6 h-6 rounded-lg", colors.icon)} />
          )}
        </div>
        {trend !== undefined && (
          <div
            className={cn(
              "flex items-center gap-1 px-2 py-1 rounded-full text-xs font-medium",
              isPositive
                ? "bg-success-100 text-success-700"
                : "bg-danger-100 text-danger-700"
            )}
          >
            {isPositive ? (
              <TrendingUp className="w-3 h-3" />
            ) : (
              <TrendingDown className="w-3 h-3" />
            )}
            {Math.abs(trend)}%
          </div>
        )}
      </div>

      <div>
        <p className="text-sm text-neutral-500 mb-1">{title}</p>
        <div className="flex items-baseline gap-1">
          <span className="text-3xl font-bold text-neutral-800 font-mono">
            {value}
          </span>
          {unit && <span className="text-sm text-neutral-500">{unit}</span>}
        </div>
        {trendLabel && (
          <p className="text-xs text-neutral-400 mt-1">{trendLabel}</p>
        )}
      </div>
    </div>
  );
}
