// src/components/common/KpiCard.vue
<script setup lang="ts">
import { computed, type Component } from 'vue'
import { TrendingUp, TrendingDown, Minus } from 'lucide-vue-next'

const props = defineProps<{
  title: string
  value: string | number
  unit?: string
  trend?: 'up' | 'down' | 'flat'
  trendValue?: string
  icon?: Component
  color?: 'primary' | 'success' | 'warning' | 'danger' | 'secondary'
  isPercentage?: boolean
}>()

const colorClasses = computed(() => {
  const colorMap: Record<string, string> = {
    primary: 'text-survey-primary',
    success: 'text-survey-success',
    warning: 'text-survey-warning',
    danger: 'text-survey-danger',
    secondary: 'text-survey-secondary',
  }
  return colorMap[props.color || 'primary']
})

const trendIcon = computed(() => {
  if (props.trend === 'up') return TrendingUp
  if (props.trend === 'down') return TrendingDown
  return Minus
})

const trendColorClass = computed(() => {
  if (props.trend === 'up') return 'text-survey-success'
  if (props.trend === 'down') return 'text-survey-danger'
  return 'text-survey-text-muted'
})
</script>

<template>
  <div class="bg-survey-surface border border-survey-border rounded-lg p-5 card-hover">
    <div class="flex items-start justify-between">
      <div>
        <p class="text-sm text-survey-text-muted mb-2">{{ title }}</p>
        <div class="flex items-baseline gap-1">
          <span class="font-mono text-3xl font-bold" :class="colorClasses">{{ value }}</span>
          <span v-if="unit" class="text-sm text-survey-text-muted">{{ unit }}</span>
        </div>
      </div>
      <div v-if="icon" class="w-10 h-10 rounded-lg bg-survey-bg flex items-center justify-center" :class="colorClasses">
        <component :is="icon" class="w-5 h-5" />
      </div>
    </div>
    <div v-if="trendValue" class="mt-3 flex items-center gap-1">
      <component :is="trendIcon" class="w-4 h-4" :class="trendColorClass" />
      <span class="text-xs" :class="trendColorClass">{{ trendValue }}</span>
      <span class="text-xs text-survey-text-muted ml-1">较上周</span>
    </div>
  </div>
</template>

// src/lib/components/KPICard.svelte
<script lang="ts">
	import { TrendingUp, TrendingDown } from 'lucide-svelte';

	export let title: string;
	export let value: string | number;
	export let icon: any;
	export let trend: number | undefined = undefined;
	export let trendLabel: string | undefined = undefined;
	export let color: string = 'primary';
	export let subtitle: string | undefined = undefined;

	const colorClasses: Record<string, string> = {
		primary: 'bg-primary-50 text-primary-600',
		green: 'bg-green-50 text-green-600',
		red: 'bg-red-50 text-red-600',
		yellow: 'bg-yellow-50 text-yellow-600',
		purple: 'bg-purple-50 text-purple-600',
		cyan: 'bg-cyan-50 text-cyan-600'
	};
</script>

<div class="card p-6">
	<div class="flex items-start justify-between">
		<div class="flex-1">
			<p class="text-sm font-medium text-slate-500">{title}</p>
			<p class="text-3xl font-bold text-slate-800 mt-2 font-mono">{value}</p>
			{#if subtitle}
				<p class="text-xs text-slate-400 mt-1">{subtitle}</p>
			{/if}
			{#if trend !== undefined}
				<div class="flex items-center gap-1 mt-3">
					{#if trend >= 0}
						<TrendingUp class="w-4 h-4 text-green-500" />
						<span class="text-sm font-medium text-green-600">+{trend.toFixed(1)}%</span>
					{:else}
						<TrendingDown class="w-4 h-4 text-red-500" />
						<span class="text-sm font-medium text-red-600">{trend.toFixed(1)}%</span>
					{/if}
					{#if trendLabel}
						<span class="text-xs text-slate-400 ml-1">{trendLabel}</span>
					{/if}
				</div>
			{/if}
		</div>
		<div class="w-12 h-12 rounded-xl {colorClasses[color] || colorClasses.primary} flex items-center justify-center flex-shrink-0">
			<svelte:component this={icon} class="w-6 h-6" />
		</div>
	</div>
</div>
