// src/components/dashboard/MetricCard.tsx
"use client";

import { TrendingUp, TrendingDown, Minus } from "lucide-react";
import { formatNumber, formatPercent } from "@/utils/format";

interface MetricCardProps {
  title: string;
  value: number | null | undefined;
  unit?: string;
  change?: number;
  changeLabel?: string;
  trend?: "up" | "down" | "flat";
  isPositive?: boolean;
  onClick?: () => void;
}

export function MetricCard({
  title,
  value,
  unit = "",
  change,
  changeLabel = "环比",
  trend,
  isPositive = true,
  onClick,
}: MetricCardProps) {
  const getTrendIcon = () => {
    if (trend === "up") return <TrendingUp className="w-4 h-4" />;
    if (trend === "down") return <TrendingDown className="w-4 h-4" />;
    return <Minus className="w-4 h-4" />;
  };

  const getTrendColor = () => {
    if (trend === "flat") return "text-neutral-500";
    const goodColor = isPositive ? "text-emerald-600" : "text-red-600";
    const badColor = isPositive ? "text-red-600" : "text-emerald-600";
    return trend === "up" ? goodColor : badColor;
  };

  const getTrendBg = () => {
    if (trend === "flat") return "bg-neutral-100";
    const goodBg = isPositive ? "bg-emerald-50" : "bg-red-50";
    const badBg = isPositive ? "bg-red-50" : "bg-emerald-50";
    return trend === "up" ? goodBg : badBg;
  };

  const hasValue = value != null;

  return (
    <div
      className={`card p-5 transition-all duration-200 ${
        onClick ? "cursor-pointer hover:shadow-card-hover hover:-translate-y-0.5" : ""
      }`}
      onClick={onClick}
    >
      <div className="flex items-start justify-between mb-3">
        <h3 className="text-sm font-medium text-neutral-600">{title}</h3>
      </div>

      <div className="flex items-end gap-2 mb-3">
        <span className="text-2xl lg:text-3xl font-bold text-neutral-900 font-mono tracking-tight">
          {hasValue
            ? (unit === "%" ? value!.toFixed(1) : formatNumber(value!))
            : "—"}
          <span className="text-lg font-normal text-neutral-500 ml-1">{unit}</span>
        </span>
      </div>

      {hasValue && change !== undefined ? (
        <div className="flex items-center gap-2">
          <div
            className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-md text-xs font-medium ${getTrendBg()} ${getTrendColor()}`}
          >
            {getTrendIcon()}
            <span>{change > 0 ? "+" : ""}{formatPercent(change / 100)}</span>
          </div>
          <span className="text-xs text-neutral-500">{changeLabel}</span>
        </div>
      ) : (
        <span className="text-xs text-primary-600 font-medium">查看口径 →</span>
      )}
    </div>
  );
}

// src/lib/components/MetricCard.svelte
<script lang="ts">
  import { TrendingUp, TrendingDown, Minus } from 'lucide-svelte';
  import { formatNumber, formatPercent, formatSignedPercent } from '$utils';

  export let name: string;
  export let value: number;
  export let unit: string = '';
  export let change: number = 0;
  export let changeLabel: string = '环比';
  export let trendData: number[] = [];
  export let delay: number = 0;

  $: isPositive = change > 0;
  $: isNegative = change < 0;
  $: isNeutral = change === 0;

  $: formattedValue = unit === '%' 
    ? formatPercent(value, 2) 
    : formatNumber(value, value >= 1000 ? 0 : 2);
</script>

<div 
  class="card card-hover p-5 animate-fade-in-up"
  style="animation-delay: {delay}ms; opacity: 0;"
>
  <div class="flex items-start justify-between mb-3">
    <div>
      <p class="text-sm font-medium text-slate-500">{name}</p>
      <p class="mt-1 text-2xl font-bold text-slate-900 font-mono tracking-tight">
        {formattedValue}
        {#if unit && unit !== '%'}
          <span class="text-base font-normal text-slate-500 ml-1">{unit}</span>
        {/if}
      </p>
    </div>
    <div 
      class="inline-flex items-center gap-1 px-2 py-1 rounded-md text-xs font-medium"
      class:bg-accent-50={isPositive}
      class:text-accent-700={isPositive}
      class:bg-danger-50={isNegative}
      class:text-danger-700={isNegative}
      class:bg-slate-100={isNeutral}
      class:text-slate-600={isNeutral}
    >
      {#if isPositive}
        <TrendingUp class="w-3.5 h-3.5" />
      {:else if isNegative}
        <TrendingDown class="w-3.5 h-3.5" />
      {:else}
        <Minus class="w-3.5 h-3.5" />
      {/if}
      {formatSignedPercent(change, 2)}
    </div>
  </div>

  {#if trendData.length > 0}
    <div class="h-12 flex items-end gap-0.5">
      {#each trendData as v, i}
        <div 
          class="flex-1 rounded-sm transition-all duration-300"
          class:bg-primary-200={i < trendData.length - 1}
          class:bg-primary-500={i === trendData.length - 1}
          style="height: {Math.max(v * 100, 8)}%"
        ></div>
      {/each}
    </div>
    <p class="mt-2 text-xs text-slate-400">{changeLabel}</p>
  {/if}
</div>
