// src/components/common/StatusBadge.vue
<script setup lang="ts">
import { computed } from 'vue'
import { cn } from '@/lib/utils'

export type ItemStatus = 'pending' | 'in_progress' | 'completed' | 'overdue' | 'archived'

interface Props {
  status: ItemStatus
}

const props = defineProps<Props>()

const statusConfig = computed(() => {
  const configs: Record<ItemStatus, { label: string; className: string }> = {
    pending: {
      label: '待认领',
      className: 'bg-gray-100 text-gray-600 border-gray-200',
    },
    in_progress: {
      label: '进行中',
      className: 'bg-blue-50 text-blue-600 border-blue-200',
    },
    completed: {
      label: '已完成',
      className: 'bg-green-50 text-green-600 border-green-200',
    },
    overdue: {
      label: '已逾期',
      className: 'bg-red-50 text-red-600 border-red-200',
    },
    archived: {
      label: '已归档',
      className: 'bg-gray-100 text-gray-500 border-gray-200',
    },
  }
  return configs[props.status]
})
</script>

<template>
  <span
    :class="[
      'inline-flex items-center px-2.5 py-0.5 rounded-lg text-xs font-medium border',
      cn(statusConfig.className),
    ]"
  >
    {{ statusConfig.label }}
  </span>
</template>

// src/lib/components/StatusBadge.svelte
<script lang="ts">
	let { status }: { status: 'draft' | 'pending' | 'reviewed' | 'sent' | 'archived' } = $props();

	const styles: Record<string, string> = {
		draft: 'bg-slate-100 text-slate-700 border-slate-200',
		pending: 'bg-amber-50 text-amber-700 border-amber-200',
		reviewed: 'bg-blue-50 text-blue-700 border-blue-200',
		sent: 'bg-emerald-50 text-emerald-700 border-emerald-200',
		archived: 'bg-gray-100 text-gray-500 border-gray-200'
	};

	const labels: Record<string, string> = {
		draft: '草稿',
		pending: '待复核',
		reviewed: '已复核',
		sent: '已发送',
		archived: '已归档'
	};
</script>

<span
	class="inline-flex items-center px-2.5 py-0.5 text-xs font-medium rounded-md border {styles[status] || styles.draft}"
>
	{labels[status] || status}
</span>
