// src/components/status-badge.tsx
"use client";

import { cn } from "@/lib/utils";
import { repairStatusConfig, complaintStatusConfig, refundStatusConfig, tradeStatusConfig, notificationStatusConfig, exportStatusConfig } from "@/lib/status-config";

type StatusType = "repair" | "complaint" | "refund" | "trade" | "notification" | "export";

interface StatusBadgeProps {
  status: string;
  type: StatusType;
  className?: string;
}

export function StatusBadge({ status, type, className }: StatusBadgeProps) {
  const configMap: Record<StatusType, Record<string, { label: string; color: string; bgColor: string }>> = {
    repair: repairStatusConfig,
    complaint: complaintStatusConfig,
    refund: refundStatusConfig,
    trade: tradeStatusConfig,
    notification: notificationStatusConfig,
    export: exportStatusConfig,
  };

  const config = configMap[type][status] || {
    label: status,
    color: "text-gray-700",
    bgColor: "bg-gray-50 border-gray-200",
  };

  return (
    <span
      className={cn(
        "inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-medium",
        config.bgColor,
        config.color,
        className
      )}
    >
      {config.label}
    </span>
  );
}

// src/lib/components/StatusBadge.svelte
<script lang="ts">
  import { statusMap, priorityMap, hazardLevelMap } from '$utils/format';
  import type { Status, Priority, HazardLevel } from '$types';

  type BadgeType = 'status' | 'priority' | 'hazard';

  const { type = 'status', value, size = 'md' } = $props<{
    type?: BadgeType;
    value: Status | Priority | HazardLevel | string;
    size?: 'sm' | 'md';
  }>();

  let badgeConfig = $derived<{ label: string; color: string }>(
    (() => {
      const v = value as string;
      if (type === 'status') {
        return statusMap[v as Status] || { label: v, color: 'bg-gray-100 text-gray-700 border-gray-300' };
      }
      if (type === 'priority') {
        return priorityMap[v as Priority] || { label: v, color: 'bg-gray-100 text-gray-700' };
      }
      return hazardLevelMap[v as HazardLevel] || { label: v, color: 'bg-gray-100 text-gray-700' };
    })()
  );

  let sizeClasses = $derived(size === 'sm' ? 'px-2 py-0.5 text-xs' : 'px-2.5 py-1 text-xs');
</script>

<span
  class="inline-flex items-center font-medium rounded-full border transition-all duration-200 {sizeClasses} {badgeConfig?.color}"
>
  {badgeConfig?.label}
</span>
