// components/StatCard.vue
<template>
  <div class="card-hover">
    <div class="flex items-start justify-between">
      <div class="flex-1 min-w-0">
        <p class="text-sm font-medium text-gray-500">{{ title }}</p>
        <p class="mt-1 text-2xl font-bold text-gray-900">{{ value }}</p>
        <div v-if="trend && trendValue" class="mt-2 flex items-center gap-1 text-sm">
          <TrendingUp v-if="trend === 'up'" class="w-4 h-4 text-success" />
          <TrendingDown v-else class="w-4 h-4 text-danger" />
          <span :class="trend === 'up' ? 'text-success' : 'text-danger'">{{ trendValue }}</span>
        </div>
      </div>
      <div
        :class="[
          'w-12 h-12 rounded-lg flex items-center justify-center shrink-0',
          colorClasses[color ?? 'primary']
        ]"
      >
        <component :is="icon" class="w-6 h-6" />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { TrendingUp, TrendingDown } from 'lucide-vue-next'

defineProps<{
  title: string
  value: string | number
  icon: any
  trend?: 'up' | 'down'
  trendValue?: string
  color?: 'primary' | 'success' | 'warning' | 'danger'
}>()

const colorClasses: Record<string, string> = {
  primary: 'bg-primary-100 text-primary-500',
  success: 'bg-green-100 text-success',
  warning: 'bg-amber-100 text-warning',
  danger: 'bg-red-100 text-danger',
}
</script>

// src/lib/components/StatCard.svelte
<script lang="ts">
  export let title: string;
  export let value: string | number;
  export let icon: any;
  export let trend: 'up' | 'down' | 'neutral' | undefined = undefined;
  export let trendValue: string | undefined = undefined;
  export let color: 'blue' | 'green' | 'orange' | 'purple' | 'red' | 'indigo' = 'blue';

  const colorClasses = {
    blue: {
      bg: 'bg-primary-50',
      icon: 'text-primary-600 bg-primary-100',
      text: 'text-primary-600'
    },
    green: {
      bg: 'bg-success-50',
      icon: 'text-success-600 bg-success-100',
      text: 'text-success-600'
    },
    orange: {
      bg: 'bg-warning-50',
      icon: 'text-warning-600 bg-warning-100',
      text: 'text-warning-600'
    },
    purple: {
      bg: 'bg-purple-50',
      icon: 'text-purple-600 bg-purple-100',
      text: 'text-purple-600'
    },
    red: {
      bg: 'bg-danger-50',
      icon: 'text-danger-600 bg-danger-100',
      text: 'text-danger-600'
    },
    indigo: {
      bg: 'bg-indigo-50',
      icon: 'text-indigo-600 bg-indigo-100',
      text: 'text-indigo-600'
    }
  };

  let classes = $derived(colorClasses[color]);
</script>

<div class="bg-white rounded-xl border border-gray-200 p-5 hover:shadow-md transition-shadow duration-300 animate-fade-in">
  <div class="flex items-start justify-between">
    <div>
      <p class="text-sm font-medium text-gray-500 mb-1">{title}</p>
      <p class="text-3xl font-bold text-gray-900 font-mono">{value}</p>
      {#if trend && trendValue}
        <p class="text-xs mt-1 {trend === 'up' ? 'text-success-600' : trend === 'down' ? 'text-danger-600' : 'text-gray-500'}">
          {trend === 'up' ? '↑' : trend === 'down' ? '↓' : '→'} {trendValue}
        </p>
      {/if}
    </div>
    <div class="w-12 h-12 rounded-xl flex items-center justify-center {classes.icon}">
      <svelte:component this={icon} class="w-6 h-6" />
    </div>
  </div>
</div>
