// components/Toast.vue
<template>
  <div
    v-if="message"
    class="fixed top-4 right-4 z-50 px-4 py-3 rounded-lg shadow-lg flex items-center gap-3 animate-slide-in"
    :class="typeClasses"
  >
    <span class="text-lg">{{ icon }}</span>
    <span class="text-sm font-medium">{{ message }}</span>
  </div>
</template>

<script setup lang="ts">
const props = withDefaults(defineProps<{
  message: string
  type?: 'success' | 'error' | 'info' | 'warning'
}>(), {
  type: 'info'
})
const typeMap = {
  success: { classes: 'bg-green-100 text-green-800 border border-green-200', icon: '✅' },
  error: { classes: 'bg-red-100 text-red-800 border border-red-200', icon: '❌' },
  info: { classes: 'bg-blue-100 text-blue-800 border border-blue-200', icon: 'ℹ️' },
  warning: { classes: 'bg-yellow-100 text-yellow-800 border border-yellow-200', icon: '⚠️' }
}
const typeClasses = computed(() => typeMap[props.type].classes)
const icon = computed(() => typeMap[props.type].icon)
</script>

<style scoped>
.animate-slide-in {
  animation: slideIn 0.3s ease-out;
}
@keyframes slideIn {
  from { transform: translateX(100%); opacity: 0; }
  to { transform: translateX(0); opacity: 1; }
}
</style>

// src/lib/components/Toast.svelte
<script lang="ts">
	import { toastStore } from '$lib/stores';
	import { CheckCircle, XCircle, AlertCircle, Info, X } from 'lucide-svelte';

	const iconMap = {
		success: CheckCircle,
		error: XCircle,
		warning: AlertCircle,
		info: Info
	};

	const colorMap = {
		success: 'bg-green-50 text-green-800 border-green-200',
		error: 'bg-red-50 text-red-800 border-red-200',
		warning: 'bg-yellow-50 text-yellow-800 border-yellow-200',
		info: 'bg-blue-50 text-blue-800 border-blue-200'
	};

	const iconColorMap = {
		success: 'text-green-500',
		error: 'text-red-500',
		warning: 'text-yellow-500',
		info: 'text-blue-500'
	};
</script>

{#if $toastStore}
	<div class="fixed top-4 right-4 z-50 animate-pulse">
		<div class="flex items-center gap-3 px-4 py-3 rounded-lg border shadow-lg {colorMap[$toastStore.type]}">
			<svelte:component
				this={iconMap[$toastStore.type]}
				class="w-5 h-5 flex-shrink-0 {iconColorMap[$toastStore.type]}"
			/>
			<p class="text-sm font-medium">{$toastStore.message}</p>
			<button on:click={() => ($toastStore = null)} class="ml-2">
				<X class="w-4 h-4" />
			</button>
		</div>
	</div>
{/if}
