// frontend/src/components/PageHeader.vue
<template>
  <div class="page-header">
    <div class="header-left">
      <el-icon v-if="showBack" class="back-btn" @click="handleBack">
        <ArrowLeft />
      </el-icon>
      <h2 class="title">{{ title }}</h2>
      <span v-if="showDemo && isDemoMode" class="demo-tag">演示数据</span>
    </div>
    <div class="header-right">
      <slot name="extra"></slot>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useRouter } from 'vue-router'
import { ArrowLeft } from '@element-plus/icons-vue'
import { useAppStore } from '@/stores/app'

const props = defineProps<{
  title: string
  showBack?: boolean
  showDemo?: boolean
}>()

const router = useRouter()
const appStore = useAppStore()

const isDemoMode = computed(() => appStore.isDemoMode)

function handleBack() {
  router.back()
}
</script>

<style lang="scss" scoped>
.page-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 16px 20px;
  background: #fff;
  border-radius: 8px;
  margin-bottom: 16px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);

  .header-left {
    display: flex;
    align-items: center;

    .back-btn {
      font-size: 20px;
      cursor: pointer;
      margin-right: 12px;
      color: #606266;
      transition: color 0.3s;

      &:hover {
        color: #409eff;
      }
    }

    .title {
      font-size: 18px;
      font-weight: 600;
      color: #303133;
      margin: 0;
    }
  }
}
</style>

// frontend/src/app/shared/page-header.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';

@Component({
  selector: 'app-page-header',
  standalone: true,
  imports: [CommonModule, MatButtonModule, MatIconModule],
  template: `
    <div class="page-header">
      <div class="title-section">
        <h2 class="page-title">{{ title }}</h2>
        <p *ngIf="subtitle" class="page-subtitle">{{ subtitle }}</p>
      </div>
      <div class="actions-section">
        <ng-content></ng-content>
      </div>
    </div>
  `,
  styles: [`
    .page-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 16px 24px;
      background: #fff;
      border-bottom: 1px solid #e0e0e0;
      margin-bottom: 16px;
    }
    .title-section {
      flex: 1;
    }
    .page-title {
      margin: 0;
      font-size: 20px;
      font-weight: 600;
      color: #1a1a1a;
    }
    .page-subtitle {
      margin: 4px 0 0 0;
      font-size: 14px;
      color: #666;
    }
    .actions-section {
      display: flex;
      gap: 8px;
    }
    @media (max-width: 768px) {
      .page-header {
        flex-direction: column;
        align-items: flex-start;
        gap: 12px;
      }
      .actions-section {
        width: 100%;
        flex-wrap: wrap;
      }
    }
  `]
})
export class PageHeaderComponent {
  @Input() title: string = '';
  @Input() subtitle?: string;
}
