// src/components/AppLayout.tsx
'use client'

import { useState } from 'react'
import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { UserButton, useUser } from '@clerk/nextjs'
import {
  LayoutDashboard,
  Package,
  FileText,
  HandshakeIcon,
  AlertTriangle,
  ClipboardList,
  Wallet,
  Bell,
  Users,
  Settings,
  Menu,
  X,
  ChevronRight,
} from 'lucide-react'
import { userRoleConfig } from '@/lib/config'

const navItems = [
  { name: '工作台', href: '/dashboard', icon: LayoutDashboard, roles: ['EMPLOYEE', 'PROCUREMENT_MANAGER', 'SUPPLIER_COORDINATOR', 'APPROVER', 'ADMIN'] },
  { name: '耗材登记', href: '/supply', icon: Package, roles: ['EMPLOYEE', 'PROCUREMENT_MANAGER', 'ADMIN'] },
  { name: '月度用量', href: '/supply/monthly', icon: ClipboardList, roles: ['EMPLOYEE', 'PROCUREMENT_MANAGER', 'ADMIN'] },
  { name: '采购需求', href: '/procurement/requirements', icon: FileText, roles: ['EMPLOYEE', 'PROCUREMENT_MANAGER', 'ADMIN'] },
  { name: '框架协议', href: '/procurement/agreements', icon: HandshakeIcon, roles: ['PROCUREMENT_MANAGER', 'ADMIN'] },
  { name: '供应商报价', href: '/procurement/quotes', icon: FileText, roles: ['PROCUREMENT_MANAGER', 'ADMIN'] },
  { name: '交付管理', href: '/procurement/deliveries', icon: Package, roles: ['PROCUREMENT_MANAGER', 'SUPPLIER_COORDINATOR', 'ADMIN'] },
  { name: '对账处理', href: '/reconciliation', icon: ClipboardList, roles: ['PROCUREMENT_MANAGER', 'ADMIN'] },
  { name: '付款建议', href: '/reconciliation/payments', icon: Wallet, roles: ['PROCUREMENT_MANAGER', 'APPROVER', 'ADMIN'] },
  { name: '付款差异', href: '/reconciliation/payment-discrepancies', icon: AlertTriangle, roles: ['SUPPLIER_COORDINATOR', 'APPROVER', 'ADMIN'] },
  { name: '供应商风险', href: '/risk', icon: AlertTriangle, roles: ['PROCUREMENT_MANAGER', 'SUPPLIER_COORDINATOR', 'APPROVER', 'ADMIN'] },
  { name: '风险看板', href: '/risk/board', icon: AlertTriangle, roles: ['PROCUREMENT_MANAGER', 'APPROVER', 'ADMIN'] },
  { name: '提醒规则', href: '/risk/alerts', icon: Bell, roles: ['ADMIN'] },
  { name: '用户管理', href: '/admin/users', icon: Users, roles: ['ADMIN'] },
  { name: '供应商管理', href: '/admin/suppliers', icon: HandshakeIcon, roles: ['PROCUREMENT_MANAGER', 'ADMIN'] },
]

export default function AppLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname()
  const { user } = useUser()
  const [sidebarOpen, setSidebarOpen] = useState(false)

  const userRole = (user?.publicMetadata?.role as string) || 'EMPLOYEE'
  const visibleItems = navItems.filter(item => item.roles.includes(userRole))

  return (
    <div className="min-h-screen flex">
      <div
        className={`fixed inset-0 z-40 bg-black/50 lg:hidden transition-opacity ${
          sidebarOpen ? 'opacity-100' : 'opacity-0 pointer-events-none'
        }`}
        onClick={() => setSidebarOpen(false)}
      />

      <aside
        className={`fixed inset-y-0 left-0 z-50 w-64 transform bg-white dark:bg-slate-900 border-r border-slate-200 dark:border-slate-800 transition-transform duration-200 ease-in-out lg:translate-x-0 lg:static ${
          sidebarOpen ? 'translate-x-0' : '-translate-x-full'
        }`}
      >
        <div className="flex h-16 items-center justify-between px-4 border-b border-slate-200 dark:border-slate-800">
          <Link href="/dashboard" className="flex items-center gap-2 font-bold text-lg text-primary">
            <HandshakeIcon className="w-6 h-6" />
            <span>耗材对账系统</span>
          </Link>
          <button
            onClick={() => setSidebarOpen(false)}
            className="lg:hidden p-1 rounded hover:bg-slate-100 dark:hover:bg-slate-800"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <nav className="p-3 space-y-1 overflow-y-auto max-h-[calc(100vh-4rem)]">
          {visibleItems.map((item) => {
            const isActive = pathname === item.href || pathname.startsWith(item.href + '/')
            return (
              <Link
                key={item.href}
                href={item.href}
                onClick={() => setSidebarOpen(false)}
                className={`flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm font-medium transition-colors ${
                  isActive
                    ? 'bg-primary text-white'
                    : 'text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800'
                }`}
              >
                <item.icon className="w-5 h-5 shrink-0" />
                <span className="flex-1 truncate">{item.name}</span>
                {isActive && <ChevronRight className="w-4 h-4 shrink-0" />}
              </Link>
            )
          })}
        </nav>
      </aside>

      <div className="flex-1 flex flex-col min-w-0">
        <header className="h-16 flex items-center justify-between px-4 lg:px-6 border-b border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 sticky top-0 z-30">
          <div className="flex items-center gap-3">
            <button
              onClick={() => setSidebarOpen(true)}
              className="lg:hidden p-2 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800"
            >
              <Menu className="w-5 h-5" />
            </button>
            <div className="text-sm text-slate-500 dark:text-slate-400 hidden sm:block">
              {(user?.publicMetadata?.role && (
                <span className={`badge ${(userRoleConfig as any)[userRole as keyof typeof userRoleConfig]?.className || ''}`}>
                  {(userRoleConfig as any)[userRole as keyof typeof userRoleConfig]?.label || userRole}
                </span>
              )) as React.ReactNode}
            </div>
          </div>
          <div className="flex items-center gap-2 sm:gap-4">
            <button className="p-2 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800 relative">
              <Bell className="w-5 h-5" />
              <span className="absolute top-1.5 right-1.5 w-2 h-2 bg-red-500 rounded-full" />
            </button>
            <UserButton
              showName={true}
              appearance={{
                elements: {
                  userButtonBox: 'flex-row-reverse',
                  userButtonOuterIdentifier: 'text-sm font-medium',
                },
              }}
            />
          </div>
        </header>

        <main className="flex-1 p-4 lg:p-6 overflow-x-hidden">
          {children}
        </main>
      </div>
    </div>
  )
}

// resources/js/Layouts/AppLayout.vue
<script setup>
import { ref, computed } from 'vue'
import { Link, usePage } from '@inertiajs/vue3'
import {
    HomeIcon,
    ChartBarIcon,
    ShoppingCartIcon,
    ClipboardDocumentListIcon,
    TruckIcon,
    ReceiptRefundIcon,
    WrenchIcon,
    Cog6ToothIcon,
    BellIcon,
    UserCircleIcon,
    ArrowRightOnRectangleIcon,
    Bars3Icon,
    XMarkIcon,
} from '@heroicons/vue/24/outline'

const page = usePage()
const sidebarOpen = ref(true)
const userMenuOpen = ref(false)

const user = computed(() => page.props.auth?.user)

const navigation = [
    { name: 'Dashboard', href: route('dashboard.index'), icon: HomeIcon },
    { name: '环境监控', href: route('environment-data.index'), icon: ChartBarIcon },
    { name: '订单管理', href: route('orders.index'), icon: ShoppingCartIcon },
    { name: '分拣管理', href: route('sorting-tasks.index'), icon: ClipboardDocumentListIcon },
    { name: '发货管理', href: route('shipments.index'), icon: TruckIcon },
    { name: '补贴凭证', href: route('subsidy-vouchers.index'), icon: ReceiptRefundIcon },
    { name: '农机预约', href: route('machinery-appointments.index'), icon: WrenchIcon },
    { name: '系统设置', href: route('users.index'), icon: Cog6ToothIcon },
]

const isActive = (href) => {
    return page.url === href || page.url.startsWith(href + '/')
}

const toggleSidebar = () => {
    sidebarOpen.value = !sidebarOpen.value
}

const toggleUserMenu = () => {
    userMenuOpen.value = !userMenuOpen.value
}

const logout = () => {
    window.location.href = route('logout')
}
</script>

<template>
    <div class="min-h-screen bg-gray-50 flex">
        <aside
            :class="[
                'fixed inset-y-0 left-0 z-30 w-64 bg-white border-r border-gray-200 transition-transform duration-300 ease-in-out lg:translate-x-0 lg:static',
                sidebarOpen ? 'translate-x-0' : '-translate-x-full',
            ]"
        >
            <div class="flex items-center justify-between h-16 px-6 border-b border-gray-200">
                <Link href="/dashboard" class="text-xl font-bold text-primary">
                    农事溯源台
                </Link>
                <button
                    @click="toggleSidebar"
                    class="lg:hidden p-1 rounded-md text-gray-500 hover:text-gray-700 hover:bg-gray-100"
                >
                    <XMarkIcon class="w-5 h-5" />
                </button>
            </div>
            <nav class="p-4 space-y-1">
                <Link
                    v-for="item in navigation"
                    :key="item.name"
                    :href="item.href"
                    :class="[
                        'flex items-center px-4 py-2.5 rounded-lg text-sm font-medium transition-colors',
                        isActive(item.href)
                            ? 'bg-primary/10 text-primary'
                            : 'text-gray-700 hover:bg-gray-100 hover:text-gray-900',
                    ]"
                >
                    <component :is="item.icon" class="w-5 h-5 mr-3 flex-shrink-0" />
                    {{ item.name }}
                </Link>
            </nav>
        </aside>

        <div
            v-if="sidebarOpen"
            class="fixed inset-0 bg-black/50 z-20 lg:hidden"
            @click="toggleSidebar"
        ></div>

        <div class="flex-1 flex flex-col min-w-0">
            <header class="h-16 bg-white border-b border-gray-200 flex items-center justify-between px-4 lg:px-6 sticky top-0 z-10">
                <div class="flex items-center">
                    <button
                        @click="toggleSidebar"
                        class="lg:hidden p-2 -ml-2 rounded-md text-gray-500 hover:text-gray-700 hover:bg-gray-100 mr-2"
                    >
                        <Bars3Icon class="w-5 h-5" />
                    </button>
                    <h1 class="text-lg font-semibold text-gray-900">
                        {{ page.props.title || 'Dashboard' }}
                    </h1>
                </div>

                <div class="flex items-center space-x-3">
                    <button class="relative p-2 text-gray-500 hover:text-gray-700 hover:bg-gray-100 rounded-lg">
                        <BellIcon class="w-5 h-5" />
                        <span class="absolute top-1.5 right-1.5 w-2 h-2 bg-danger rounded-full"></span>
                    </button>

                    <div class="relative">
                        <button
                            @click="toggleUserMenu"
                            class="flex items-center space-x-2 p-1.5 rounded-lg hover:bg-gray-100"
                        >
                            <div class="w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center">
                                <UserCircleIcon class="w-6 h-6 text-primary" />
                            </div>
                            <div class="hidden md:block text-left">
                                <p class="text-sm font-medium text-gray-900">
                                    {{ user?.name || '管理员' }}
                                </p>
                                <p class="text-xs text-gray-500">
                                    {{ user?.email || 'admin@example.com' }}
                                </p>
                            </div>
                        </button>

                        <div
                            v-if="userMenuOpen"
                            class="absolute right-0 mt-2 w-48 bg-white rounded-lg shadow-lg border border-gray-200 py-1"
                        >
                            <button
                                @click="logout"
                                class="flex items-center w-full px-4 py-2 text-sm text-gray-700 hover:bg-gray-50"
                            >
                                <ArrowRightOnRectangleIcon class="w-4 h-4 mr-2" />
                                退出登录
                            </button>
                        </div>
                    </div>
                </div>
            </header>

            <main class="flex-1 p-4 lg:p-6">
                <slot />
            </main>
        </div>
    </div>
</template>
