// src/lib/components/Modal.svelte
<script lang="ts">
  export let open: boolean;
  export let title: string;
  export let description = '';
  export let size: 'sm' | 'md' | 'lg' = 'md';
  export let onClose: () => void = () => {};
  export let footer = false;

  import { X } from 'lucide-svelte';

  const sizeClasses: Record<string, string> = {
    sm: 'max-w-md',
    md: 'max-w-lg',
    lg: 'max-w-2xl'
  };
</script>

{#if open}
  <div
    class="fixed inset-0 z-50 flex items-center justify-center p-4 animate-fade-in"
    role="dialog"
    aria-modal="true"
  >
    <div
      class="absolute inset-0 bg-navy-900/50 backdrop-blur-sm"
      on:click={onClose}
    />
    <div
      class="relative bg-white rounded-2xl shadow-2xl w-full {sizeClasses[size]} animate-fade-in-up"
    >
      <div class="flex items-start justify-between p-6 border-b border-navy-100">
        <div>
          <h3 class="font-display text-lg text-navy-900">{title}</h3>
          {#if description}
            <p class="text-sm text-navy-500 mt-1">{description}</p>
          {/if}
        </div>
        <button
          on:click={onClose}
          class="w-8 h-8 rounded-lg flex items-center justify-center text-navy-400 hover:bg-navy-50 hover:text-navy-700 transition"
          aria-label="关闭"
        >
          <X class="w-4 h-4" stroke-width={1.8} />
        </button>
      </div>
      <div class="p-6">
        <slot />
      </div>
      {#if footer}
        <div class="flex items-center justify-end gap-2 p-6 pt-0">
          <slot name="footer" />
        </div>
      {/if}
    </div>
  </div>
{/if}

// src/components/ui/Modal.tsx
'use client';

import * as React from 'react';
import { X } from 'lucide-react';
import { cn } from '@/lib/utils';

interface ModalProps {
  open: boolean;
  onClose: () => void;
  title?: string;
  children: React.ReactNode;
  footer?: React.ReactNode;
  size?: 'sm' | 'md' | 'lg' | 'xl';
  className?: string;
}

const sizeClasses = {
  sm: 'max-w-md',
  md: 'max-w-lg',
  lg: 'max-w-2xl',
  xl: 'max-w-4xl',
};

export const Modal: React.FC<ModalProps> = ({
  open,
  onClose,
  title,
  children,
  footer,
  size = 'md',
  className,
}) => {
  React.useEffect(() => {
    if (open) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }
    return () => {
      document.body.style.overflow = '';
    };
  }, [open]);

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center animate-fade-in">
      <div
        className="absolute inset-0 bg-gray-900/40 backdrop-blur-sm"
        onClick={onClose}
      />
      <div
        className={cn(
          'relative z-10 w-full mx-4 bg-white rounded-2xl shadow-card-hover flex flex-col max-h-[90vh] animate-slide-up',
          sizeClasses[size],
          className
        )}
      >
        {(title || onClose) && (
          <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100 shrink-0">
            {title && <h3 className="text-lg font-semibold text-gray-900">{title}</h3>}
            {onClose && (
              <button
                onClick={onClose}
                className="p-1.5 rounded-lg text-gray-400 hover:text-gray-600 hover:bg-gray-100 transition-colors"
              >
                <X className="h-5 w-5" />
              </button>
            )}
          </div>
        )}
        <div className="flex-1 overflow-y-auto scrollbar-thin p-6">{children}</div>
        {footer && (
          <div className="flex items-center justify-end gap-3 px-6 py-4 border-t border-gray-100 bg-gray-50 rounded-b-2xl shrink-0">
            {footer}
          </div>
        )}
      </div>
    </div>
  );
};
